### ISSUE TITLE
SMCBatteryManager : percentage "hangs" after some time

### ISSUE THREAD

**Issue by thymidin** [acidanthera/bugtracker#2196] opened 2023-01-10 12:58 UTC
Hi,
I am currently using a rebranded Clevo NL51CU and I have some problems with SMCBatteryManager. It detects the battery correctly but the percentage is stuck (stops updating after some time) especially when discharging and it's sometimes not detecting or taking a lot of time to detect when I plug the power adapter. Then, after plugging the power adapter, the percentage increases for some seconds/minutes and hangs again.

I do not experience this strange behavior with ACPIBatteryManager from Rehabman. I tried some ACPI patching methods, using ECEnabler, renaming the ACPI variable to the direct offset (not sure if clear) of the data, but it didn't work. I think there might be a problem with VirtualSMC (I have seen that some other Clevo laptops user still use ACPIBatteryManager, maybe because of this behavior ?). It seems strange that the Battery Manager can work for a limited amount of time before it stops updating. Also when it does the CPU temps goes straight to the 80°C (unlike ACPIBatteryManager which keeps the temperature quite stable at about 45-50°C)

The specs of my laptop are :
Computer model Machenike Machcreator-A = Clevo NL4x_5xCU
Processor Intel Core i3-10110U
Memory 16 Gb DDR4 2667 MHz
Hard Disk Samsung 980 NVMe 1 Tb
Integrated Graphics Intel UHD Graphics 620
Monitor FHD 1920x1080 (15.6 inch)
Sound Card Realtek ALC293 (layout-id: 28)
Wireless Card Intel Wireless-AC 9462
Ethernet Card Realtek

I am currently using macOS Ventura 13.1 with OC 0.8.8 and already had the same problem on Monterey and Big Sur.

You can find attached to this post the DSDT since it may helps to determine if it is an ACPI issue or a KEXT issue. 
The OC log and Lilu log are also attached. I also attached the "log show --last boot | grep -i SMC >> boot-log.log" result and the IOReg in case it may help. The EFI folder attached doesn't have the AirportItlwm kexts since it was taking too much space it is otherwise the same I am using right now (minus the ressources folder).

I hope those files can help debug this strange behavior !
Thanks

[boot-log.log](https://github.com/acidanthera/bugtracker/files/10382842/boot-log.log)
[opencore-2023-01-10-122508.txt](https://github.com/acidanthera/bugtracker/files/10382854/opencore-2023-01-10-122508.txt)
[Lilu_1.6.3_22.2.txt](https://github.com/acidanthera/bugtracker/files/10382859/Lilu_1.6.3_22.2.txt)
[EFI 2.zip](https://github.com/acidanthera/bugtracker/files/10382875/EFI.2.zip)
[DSDT.aml.zip](https://github.com/acidanthera/bugtracker/files/10382897/DSDT.aml.zip)
[IOReg.zip](https://github.com/acidanthera/bugtracker/files/10382905/IOReg.zip)

**Comment by thymidin** [comment] 2023-05-16 08:45
Update : on latest OC + Lilu + VirtualSMC, it now always work during charge. It freezes only when the AC adapter isn't plugged in.

**Comment by vit9696** [comment] 2024-01-02 17:51
Likely duplicate of #2002 or #1841, if not, should be ACPI-related.

**Closed by vit9696** 2024-01-02 17:51 UTC
Labels: help wanted, project:vsmc
