### ISSUE TITLE
Mac OS 12, OC 0.7.0 kernel panic with _orgVaddrPresubmitTrampoline

### ISSUE THREAD

**Issue by g3d** [acidanthera/bugtracker#1672] opened 2021-06-08 08:51 UTC
On new macosx there is kernel panic at some time after boot. I've used the same config which was running seamlessly without problems on Big Sur with `-lilubetaall`. 

Crash dump: https://gist.github.com/g3d/4d657db6a2201a3a6e2b54ce028f346f
EFI: https://github.com/g3d/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/tree/macos-12

P.S. I would update this issue with Lilu & opencore logs, don't have much time after boot before kernel crash

**Comment by zhigang1992** [comment] 2021-06-08 09:13
https://gist.github.com/zhigang1992/91d50f48f4ae228489f8686d695184b2 here are mine crash log, I'll try to see if I can get the boot logs as well.

**Comment by zhigang1992** [comment] 2021-06-08 09:23
[opencore-2021-06-08-091850.txt](https://github.com/acidanthera/bugtracker/files/6615224/opencore-2021-06-08-091850.txt)

Here are my boot log, not sure if it include anything helpful.

**Comment by zhigang1992** [comment] 2021-06-08 10:18
[opencore-2021-06-08-091850.txt](https://github.com/acidanthera/bugtracker/files/6615671/opencore-2021-06-08-091850.txt)

Not sure if this is correct

**Comment by vit9696** [comment] 2021-06-08 13:13
RELEASE builds or non-symbolicated panics. Not helpful. Closing as invalid.

**Closed by vit9696** 2021-06-08 13:13 UTC
Labels: project:lilu

**Comment by Naituw** [comment] 2021-06-09 03:13
I have the exact same kernel crash with @g3d

> On new macosx there is kernel panic at some time after boot. I've used the same config which was running seamlessly without problems on Big Sur with `-lilubetaall`.
> 
> Crash dump: https://gist.github.com/g3d/4d657db6a2201a3a6e2b54ce028f346f
> EFI: https://github.com/g3d/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/tree/macos-12
> 
> P.S. I would update this issue with Lilu & opencore logs, don't have much time after boot before kernel crash

**Comment by g3d** [comment] 2021-06-09 23:46
Attaching detailed debugger logs. Hope that would help
[debug_27704.zip](https://github.com/acidanthera/bugtracker/files/6627453/debug_27704.zip)

**Comment by notjosh** [comment] 2021-06-13 22:36
I've been trying to narrow this down, and have a reliable repro. I'm wondering if it's consistent for anyone else. I've got: 10900K, Z490, 5700XT. Everything was stable on Big Sur.

We can see in the logs above that `powermetrics` is the process to blame, so we can try poking it directly.

My repro is:

- Boot to log in screen, but _don't log in_ yet. As long as I'm here, the system won't crash for a long time.
- From another machine, ssh in, and run `sudo powermetrics --samplers interrupts`, and get KP. If you don't have SSH access, then perhaps you can log in, open Terminal.app, and run it directly there if you're quick enough.

Specifically, `interrupts` seems to be the problem. I can run `sudo powermetrics --samplers tasks,battery,network,disk,int_sources,cpu_power,thermal,sfi,gpu_power,gpu_agpm_stats,smc,gpu_dcc_stats,nvme_ssd,io_throttle_ssd` (i.e. everything, except `interrupts`), and it runs fine.

(In my case, I suspect Intel Power Gadget and/or iStat Menus are trying to update a display, and causing the KP. Eventually macOS seems to probe it (even at log in screen) and it panics)

It seems like the 5700XT is a common thread here, can anyone else confirm their hardware, and we can try to narrow it down?

**Comment by zhigang1992** [comment] 2021-06-14 00:22
@notjosh  Mines is Vega 56, and I do have iStat Menus installed. My reproduce case was whenever you hit restart on the menu bar. (When it pops up the confirm dialog) it will freeze with this KP.

**Comment by notjosh** [comment] 2021-06-14 11:25
I took out my 5700XT (and used only iGPU), and still had the same KP, so what other common thread is there between us? It seems many other people have Monterey running flawlessly, so there must be something.

I've got ASUS PRIME Z490-A, 10900K, Fenvi T919. Using iMac19,1 SMBIOS.

**Comment by notjosh** [comment] 2021-06-14 12:01
Ok, maybe this helps others. I was looking around for other Z490 users on Monterey, and found [this commit](https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/blob/6450e05e16c9e60f7ef84996c0a0eb087e36cb46/README.md) had a note in the README. I'd also been using `FakePCIID` for the onboard NIC. Setting the two related kexts to "enabled: false" in my `config.plist` seems to have fixed it. (Downside: no onboard NIC, but wifi is fine for me as long as it's stable!).

For completeness, I can restart/shutdown via the menu bar too, it's working fine too.

I'll report back if I see the problem again.

Can anyone else in this thread confirm that a) they use `FakePCIID` for the NIC, and b) removing it fixes the KP?

**Comment by zhigang1992** [comment] 2021-06-14 14:16
I'm using Z490 and I do use FakePCIID for the audio fix.

But I've reverted back to BigSur for the moment, I can reinstall it in a few day. In the mean time, ping @g3d

**Comment by g3d** [comment] 2021-06-14 15:52
I'm using FakePCIID, would check if disabling kext fixes the problem.

**Comment by g3d** [comment] 2021-06-14 16:50
Tested - disabling FakePCIID fixes the problem, I am able to reboot now and there is no kernel panics anymore. @notjosh good job!
