### ISSUE TITLE
AppleALC Output non working if windows booted before OS X

### ISSUE THREAD

**Issue by iNDi** [acidanthera/bugtracker#547] opened 2019-11-02 11:55 UTC
AppleHDA loads and shows correct inputs and outputs, mic works fine but internal speakers produce no output.

**Non Working**
kernel[0]: (Lilu) Lilu:     api @ (DBG) got load request from AppleALC (142)
kernel[0]: (Lilu) AppleALC:    init @ (DBG) AppleALC bootstrap DBG-142-2019-10-08
kernel[0]: (Lilu) AppleALC:   iokit @ (DBG) getOSData vendor-id has 8086 value
kernel[0]: (Lilu) AppleALC:   iokit @ (DBG) getOSData device-id has A170 value
kernel[0]: (Lilu) AppleALC:   iokit @ (DBG) getOSData revision-id has 31 value
kernel[0]: (Lilu) AppleALC:   iokit @ (DBG) getOSData alc-layout-id has 3 value
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) found 2 audio controllers
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) validating 0 controller 10DE:FBB:A1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 0 mod 1002:AAC8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 1 mod 1002:AAE8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 2 mod 1002:AB08
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 3 mod 1022:1457
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 4 mod 1022:1487
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 5 mod 1022:15E3
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 6 mod 8086:C0C
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 7 mod 8086:F04
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 8 mod 8086:8CA0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 9 mod 8086:8D20
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 10 mod 8086:8D21
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 11 mod 8086:9DC8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 12 mod 8086:A171
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 13 mod 8086:A2F0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 14 mod 8086:A348
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 15 mod 10DE:E0F
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 16 mod 10DE:FB0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 17 mod 10DE:FB8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 18 mod 10DE:FB9
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 19 mod 10DE:FBA
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 20 mod 10DE:FBB
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) found mod for 0 controller
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) validating 1 controller 8086:A170:31
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 0 mod 1002:AAC8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 1 mod 1002:AAE8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 2 mod 1002:AB08
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 3 mod 1022:1457
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 4 mod 1022:1487
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 5 mod 1022:15E3
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 6 mod 8086:C0C
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 7 mod 8086:F04
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 8 mod 8086:8CA0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 9 mod 8086:8D20
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 10 mod 8086:8D21
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 11 mod 8086:9DC8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 12 mod 8086:A171
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 13 mod 8086:A2F0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 14 mod 8086:A348
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 15 mod 10DE:E0F
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 16 mod 10DE:FB0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 17 mod 10DE:FB8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 18 mod 10DE:FB9
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 19 mod 10DE:FBA
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 20 mod 10DE:FBB
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 21 mod 10DE:FBC
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 22 mod 10DE:10EF
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 23 mod 10DE:10F0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 24 mod 10DE:10F1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) handling 0 controller 10DE:FBB with 1 patches
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) finding 0FBB10DE repl at 0 curr 0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) assigned 0E0A10DE find 0FBB10DE repl at 0 curr 0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking patch 0 for 5 kext (com.apple.driver.AppleHDAController)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) applying patch 0  for 5 kext (com.apple.driver.AppleHDAController)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) missing ControllerModInfo for 1 controller
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) found analog codec IOHDACodecDevice
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) storing codec info for 10EC:255:100002
kernel[0]: (Lilu) AppleALC:     alc @ failed to find IOHDACodecVendorID, retrying 0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) found supported Realtek ALC255 codec revision 0x100002
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) handling 0 controller 10DE:FBB with 1 patches
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) missing ControllerModInfo for 1 controller
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) will route resource loading callbacks
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking patch 0 for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking patch 1 for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking patch 2 for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) applying patch 2  for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking patch 3 for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) applying patch 3  for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking patch 4 for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) applying patch 4  for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking patch 5 for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) applying patch 5  for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking patch 6 for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) applying patch 6  for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking patch 7 for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) applying patch 7  for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking patch 8 for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) applying patch 8  for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking patch 9 for 6 kext (com.apple.driver.AppleHDA)
kernel[0]: (Lilu) AppleALC:   iokit @ (DBG) getOSData layout-id has 7 value
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) initializePinConfig AppleHDACodecGeneric received hda 0xFFFFFF805C5FBAF0, config 0xFFFFFF805C454680 config name AppleHDAHardwareConfigDriver apple layout 7 codec 10EC0255 layout 3
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) discovered HDAConfigDefault with 419 entries
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) current config entry has boot 1, wake 1, reinit 1
kernel[0]: (Lilu) AppleALC:   iokit @ (DBG) getOSData layout-id has 7 value
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) initializePinConfig AppleHDACodecGeneric received hda 0xFFFFFF805C755810, config 0xFFFFFF805C5465A0 config name AppleHDAHardwareConfigDriver apple layout 7 codec 10EC0255 layout 3
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) discovered HDAConfigDefault with 419 entries
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) current config entry has boot 1, wake 1, reinit 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) layoutLoadCallback 1 0 1 15073 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) resource-request arrived layout
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking codec 10EC:255:100002
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) selecting from 13 files
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing 0 layout 3/3
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) found layout at 0 index
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) layoutLoadCallback done 1 0 1 1635 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) layoutLoadCallback 2 0 1 15073 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) resource-request arrived layout
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking codec 10EC:255:100002
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) selecting from 13 files
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing 0 layout 3/3
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) found layout at 0 index
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) layoutLoadCallback done 2 0 1 1635 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) platformLoadCallback 3 0 1 17735 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) resource-request arrived platform
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking codec 10EC:255:100002
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) selecting from 13 files
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing 0 layout 3/3
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) found platform at 0 index
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) platformLoadCallback done 3 0 1 434 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) power change AppleHDAHDMI_DPDriver at AppleHDACodecGeneric from 1 to 2 in from pin 1 sleep 0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) platformLoadCallback 4 0 1 17735 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) resource-request arrived platform
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking codec 10EC:255:100002
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) selecting from 13 files
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing 0 layout 3/3
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) found platform at 0 index
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) platformLoadCallback done 4 0 1 434 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) power change AppleHDADriver at AppleHDACodecGeneric from 1 to 2 in from pin 1 sleep 0

**Working**
kernel[0]: (Lilu) Lilu:     api @ (DBG) got load request from AppleALC (142)
kernel[0]: (Lilu) AppleALC:    init @ (DBG) AppleALC bootstrap DBG-142-2019-10-08
kernel[0]: (Lilu) AppleALC:   iokit @ (DBG) getOSData vendor-id has 8086 value
kernel[0]: (Lilu) AppleALC:   iokit @ (DBG) getOSData device-id has A170 value
kernel[0]: (Lilu) AppleALC:   iokit @ (DBG) getOSData revision-id has 31 value
kernel[0]: (Lilu) AppleALC:   iokit @ (DBG) getOSData alc-layout-id has 3 value
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) found 2 audio controllers
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) validating 0 controller 10DE:FBB:A1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 0 mod 1002:AAC8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 1 mod 1002:AAE8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 2 mod 1002:AB08
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 3 mod 1022:1457
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 4 mod 1022:1487
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 5 mod 1022:15E3
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 6 mod 8086:C0C
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 7 mod 8086:F04
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 8 mod 8086:8CA0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 9 mod 8086:8D20
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 10 mod 8086:8D21
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 11 mod 8086:9DC8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 12 mod 8086:A171
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 13 mod 8086:A2F0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 14 mod 8086:A348
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 15 mod 10DE:E0F
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 16 mod 10DE:FB0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 17 mod 10DE:FB8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 18 mod 10DE:FB9
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 19 mod 10DE:FBA
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 20 mod 10DE:FBB
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) found mod for 0 controller
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) validating 1 controller 8086:A170:31
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 0 mod 1002:AAC8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 1 mod 1002:AAE8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 2 mod 1002:AB08
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 3 mod 1022:1457
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 4 mod 1022:1487
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 5 mod 1022:15E3
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 6 mod 8086:C0C
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 7 mod 8086:F04
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 8 mod 8086:8CA0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 9 mod 8086:8D20
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 10 mod 8086:8D21
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 11 mod 8086:9DC8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 12 mod 8086:A171
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 13 mod 8086:A2F0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 14 mod 8086:A348
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 15 mod 10DE:E0F
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 16 mod 10DE:FB0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 17 mod 10DE:FB8
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 18 mod 10DE:FB9
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 19 mod 10DE:FBA
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 20 mod 10DE:FBB
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 21 mod 10DE:FBC
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 22 mod 10DE:10EF
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 23 mod 10DE:10F0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing to 24 mod 10DE:10F1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) handling 0 controller 10DE:FBB with 1 patches
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) finding 0FBB10DE repl at 0 curr 0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) assigned 0E0A10DE find 0FBB10DE repl at 0 curr 0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking patch 0 for 5 kext (com.apple.driver.AppleHDAController)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) applying patch 0  for 5 kext (com.apple.driver.AppleHDAController)
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) missing ControllerModInfo for 1 controller
kernel[0]: (Lilu) AppleALC:     alc @ failed to find IOHDACodecVendorID, retrying 0
....
kernel[0]: (Lilu) AppleALC:     alc @ failed to find IOHDACodecVendorID, retrying 2479
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) layoutLoadCallback 1 0 1 15073 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) resource-request arrived layout
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking codec 10EC:255:100002
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) selecting from 13 files
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing 0 layout 3/3
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) found layout at 0 index
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) layoutLoadCallback done 1 0 1 1635 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) layoutLoadCallback 2 0 1 15073 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) resource-request arrived layout
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking codec 10EC:255:100002
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) selecting from 13 files
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing 0 layout 3/3
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) found layout at 0 index
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) layoutLoadCallback done 2 0 1 1635 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) platformLoadCallback 3 0 1 17735 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) resource-request arrived platform
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking codec 10EC:255:100002
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) selecting from 13 files
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing 0 layout 3/3
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) found platform at 0 index
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) platformLoadCallback done 3 0 1 434 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) power change AppleHDAHDMI_DPDriver at AppleHDACodecGeneric from 1 to 2 in from pin 1 sleep 0
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) platformLoadCallback 4 0 1 17735 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) resource-request arrived platform
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) checking codec 10EC:255:100002
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) selecting from 13 files
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) comparing 0 layout 3/3
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) found platform at 0 index
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) platformLoadCallback done 4 0 1 434 1
kernel[0]: (Lilu) AppleALC:     alc @ (DBG) power change AppleHDADriver at AppleHDACodecGeneric from 1 to 2 in from pin 1 sleep 0

Checked ACPI as much as i can, nothing glaring to me.

**Comment by vit9696** [comment] 2019-11-02 12:16
That seems to be like ResetHDA thing in Clover. To resolve this you basically need to add some verbs to PinConfigs to reset your HDA codec during macOS boot.

**Comment by roddy20** [comment] 2019-12-22 20:49
windows sets verbs COEF_INDEX and PROC_COEF for Vendor Widget to zero to avoid noise at shudown. Vendor Widget is not used in macOS, and it is not described completely in HDA specs, so it is not initialized again at startup.
You may try to add 02050007 02047cb0 to ConfigData string for some ALC Realtek's codecs, or use another version of Windows audio drivers

**Comment by iNDi** [comment] 2020-05-24 16:02
> windows sets verbs COEF_INDEX and PROC_COEF for Vendor Widget to zero to avoid noise at shudown. Vendor Widget is not used in macOS, and it is not described completely in HDA specs, so it is not initialized again at startup.
> You may try to add 02050007 02047cb0 to ConfigData string for some ALC Realtek's codecs, or use another version of Windows audio drivers

sorry for raising this again, have tried all the available Realtek drivers i could find for ALC 255 same for each one.

a side not this also affects AudioDxe.efi

**Comment by vit9696** [comment] 2020-05-24 17:39
Well, does it help to update PinConfigs with the suggested verbs? As for AudioDxe I am CC'ing @Goldfish64.

**Comment by vit9696** [comment] 2020-06-06 04:26
Hmm, in fact, I have just remembered that modern AppleALC has a boot argument and device property named `alctcsel`, which effectively implements ResetHDA algorithm commonly found in Clover. Have you tried that?

**Comment by SukkaW** [comment] 2020-10-14 15:42
> Hmm, in fact, I have just remembered that modern AppleALC has a boot argument and device property named `alctcsel`, which effectively implements ResetHDA algorithm commonly found in Clover. Have you tried that?

@vit9696 Tested, no luck. Reboot from windows to macOS results in audio device missing.

**Comment by marianopela** [comment] 2020-10-14 16:05
> @vit9696 Tested, no luck. Reboot from windows to macOS results in audio device missing.

Am I wrong or this is not happening with a full shutdown from Windows and a boot to macOS?

**Comment by llooz** [comment] 2020-11-15 12:12
@vit9696 
I've got stung by this exact same issue, I've an MSI Z490 Tomahawk with ALC1200 and I was going crazy with trying all sorts of config.

This should work with layout-id=11 or layout-id=7 (for me this gives no devices), with layout-id=11 I always see devices but it only works if I do a shutdown and boot directly to macOS.

I have also tried `alctcsel` and `alctsel` (this is written on the Changelog of AppleALC, probably a typo).

**Comment by meetesh06** [comment] 2021-01-30 08:39
Hello, even i'm facing this issue using ALC 256 layout-id=23. Interesting part is headphones always work, only the internal speaker seems to be affected. using laptop with a i5 10210u processor.

**Comment by mjs520** [comment] 2021-02-26 01:17
Alc-269，声卡ID注入33，有时启动声卡会无法驱动，双系统，Clover引导，引导参数添加alc=33并在config里勾选了HDA重置按钮。

**Comment by gunners81** [comment] 2021-07-24 13:39
In my case it caused by Realtek HD audio driver, maybe it not release the audio resources properly when windows restarted. Solution is shutdown instead of restart the laptop/pc or uninstall Realtek HD audio driver then just use windows 10 default audio driver.

**Comment by mikebeaton** [comment] 2022-02-02 17:28
Successful method for discovering fix for this being (re?!)developed: https://github.com/acidanthera/AppleALC/pull/758

**Comment by mikebeaton** [comment] 2022-03-06 09:11
Script to help work out which processing caps need setting now at available https://github.com/mikebeaton/dump-coeff . Used successfully to get sound in https://github.com/acidanthera/AppleALC/pull/758 and https://github.com/acidanthera/AppleALC/pull/759 .

**Closed** 2022-03-06 09:14 UTC
Labels: project:alc

**Comment by PMheart** [comment] 2022-03-06 10:12
> Script to help work out which processing caps need setting now at available https://github.com/mikebeaton/dump-coeff . Used successfully to get sound in [acidanthera/AppleALC#758](https://github.com/acidanthera/AppleALC/pull/758) and [acidanthera/AppleALC#759](https://github.com/acidanthera/AppleALC/pull/759) .

Thanks! It would be better if we include this script in AppleALC. @vit9696

**Comment by mikebeaton** [comment] 2022-03-06 10:41
@PMheart Yes, I was wondering about this, too.

I will PM you and Vit, but the issues are: a) this script needs some more work https://github.com/mikebeaton/dump-coeff/issues/1 , and b) it only deals with the last 5% (or less!) of the work needed to get sound via AppleALC, and isn't even needed at all on many systems.

**Comment by PMheart** [comment] 2022-03-06 10:43
> @PMheart Yes, I was wondering about this, too.
> 
> I will PM you and Vit, but the issues are: a) this script needs some more work [mikebeaton/dump-coeff#1](https://github.com/mikebeaton/dump-coeff/issues/1) , and b) it only deals with the last 5% (or less!) of the work needed to get sound via AppleALC, and isn't even needed at all on many systems.

a) I could take a look at this, if time permits.
b) It does not really harm. Just mention this somewhere (e.g. in README).

**Comment by mikebeaton** [comment] 2022-03-06 13:48
`dump_coeff.sh` now part of AppleALC https://github.com/acidanthera/AppleALC/commit/02983ded485f3259b42f866de5140ae56e0d34b3 with write-up at https://github.com/acidanthera/AppleALC/wiki/Dumping-processing-coefficients .

**Comment by justinkb** [comment] 2022-11-05 21:08
wow, incredible job with this. I'm assuming there is no real way to check if any of the layouts already created for my codec match exactly in terms of coefficients? just a matter of a lot of rebooting? (and then going to work with your guide if none of them currently in the repo produce proper results?)

**Comment by mikebeaton** [comment] 2022-11-08 10:34
Yes, or research into doing your own layout - links off AppleALC page or various others (e.g. [this](https://github.com/F0x1c/AppleALC_Instructions), or Google!).
