### ISSUE TITLE
Threadripper 3960x / TRX40 motherboard - memory allocate failure, for a range which shows avaiable

### ISSUE THREAD

**Issue by InSanniti** [acidanthera/bugtracker#602] opened 2019-12-05 23:59 UTC
I've been testing with Pavo on discord, and was directed here to report the issue.

with a 3960X threadripper and a TRX40 motherboard, Opencore and Clover both give an error allocating memory before getting to the Mac installer. The memory address listed as errored is actually shown as available in an EFI memmap.

Attached is a memmap and error example using a 0.5.3 OC EFI folder provided by Pavo. I did a BIOS load defaults with no changes (CSM disabled by default). Then rebooted a few times, while the memmap learned and settled. Then captured the EFI memmap and error failure photo in the same boot.

System details:
MB: Asus Zenith II Extreme
CPU: Threadripper 3960x
RAM: 
Gskill Ripjaws 3200 DDR4
SSD: Sabrent M.2 NVME (PCIE 4.0)
GPU: Vega 64

[memmap.txt](https://github.com/acidanthera/bugtracker/files/3929643/memmap.txt)
![Error message](https://user-images.githubusercontent.com/24437359/70284156-0f0f1480-17fe-11ea-9d31-1ac74896854a.jpg)

Let me know if you need anything else

Thanks

**Comment by vit9696** [comment] 2019-12-06 01:40
The address you posted may get allocated during OpenCore loading or by boot.efi itself, so memory map is not too helpful here. Normally this issue is resolved by enabling `ProvideCustomSlide` Quirk and related options in `Booter` section on Intel computers. Could you check whether it is enabled? Also, it may help to upload your bootloader configuration files.

If that's enabled and changing other options still does not work, it might be that you will have to research and develop mitigations on your own.

**Comment by InSanniti** [comment] 2019-12-06 06:42
Hi, Yes ProvideCustomSlide is enabled, and I have also test most of the  quirks in the Booter section. Attached is the current config, and I can test any other options easily if needed.


[config.zip](https://github.com/acidanthera/bugtracker/files/3930749/config.zip)

**Comment by InSanniti** [comment] 2019-12-06 07:01
Attached is my full EFI folder used with 0.5.3 OC (debug version). I have also tested on 0.5.2 with same results

[EFI.zip](https://github.com/acidanthera/bugtracker/files/3930787/EFI.zip)

**Comment by vit9696** [comment] 2019-12-06 07:35
Yes, I see now. Well, it is AMD, you are alone with this stuff I am afraid. I have a suspect that page allocator allocates in more pages than requested, but this is a slim theory, and I don't know how it behaves really.

**Comment by Download-Fritz** [comment] 2019-12-11 08:38
You might succeed better with DevirtualiseMmio, but I also believe something is borked/unexpected... but it will not be something looked into (any time soon at least)

**Comment by InSanniti** [comment] 2019-12-11 11:24
Thanks -  I did try it previously, and it did seem to get past memory allocation errors, but would restart the PC immediately after. Looked into IRQ conflicts, but it didn't help. Any idea’s appreciated !

**Comment by Download-Fritz** [comment] 2019-12-11 16:49
There is a most minimal chance that this is caused by accesses to the devirtualised areas, however that usually happens much later. For now I will close this as it is not believed to be an OC issue.

**Closed by Download-Fritz** 2019-12-11 16:49 UTC
Labels: enhancement, priority:low, project:oc

**Comment by appleguy** [comment] 2019-12-23 04:37
Hey all — I'm having this exact same issue with a Threadripper 3960x and OpenCore 0.5.3-RELEASE. I also tried the experimental branch patches.plist just in case, in addition to modifying address slide parameters.

I'm pretty excited about the OpenCore project and have a fair amount of iOS / macOS platform experience (including at low levels). Though this may be officially unsupported, I'd greatly appreciate any tips or direction and would be happy to try out speculative ideas and report back. Perhaps I was too ambitious making this build with the assumption that the Ryzen 3000 platform support would apply to Threadripper, but I'm glad to tweak and hack as necessary.
