### ISSUE TITLE
Voodoops2 doesn’t work very well on Dell Inspiron 14z 5423

### ISSUE THREAD

**Issue by Rohan200220** [acidanthera/bugtracker#1010] opened 2020-06-28 04:17 UTC
So i am trying your voodoops2 kext and it works well but i have some problems. First i have physical click buttons on my laptop and they dont work with this kext. 
Second i am experiencing some lags with this one and didn’t feel them with the rehabman’s voodoops2 kext.

**Comment by vit9696** [comment] 2020-07-03 10:04
Duplicate of https://github.com/acidanthera/bugtracker/issues/890

**Closed by vit9696** 2020-07-03 10:04 UTC
Labels: project:ps2
