### ISSUE TITLE
Black screen on DRM videos in macOS Catalina with IQSV

### ISSUE THREAD

**Issue by vandroiy2013** [acidanthera/bugtracker#519] opened 2019-10-15 15:58 UTC
On macOS Mojave DRM video works well.

**Comment by cattyhouse** [comment] 2019-10-15 16:26
for me, i'm using iMac19,2, need to disable `forceOfflineRenderer` with `shikigva=1`, in this case i am able to play Tv.app video, if not, there is only sound, no video.

**Comment by vandroiy2013** [comment] 2019-10-15 16:45
Try to play this video. 
https://drive.google.com/file/d/12pQ5FFpdHdGOVV6jvbqEq2wmkpMKxsOF/view

**Comment by cattyhouse** [comment] 2019-10-15 17:05
confirmed, shikigva=1 bootargs, playable with quicktime player. but can't make screenshot, it will be blank picture.

**Comment by Andrey1970AppleLife** [comment] 2019-10-15 19:34
This bad decision. It breaks the hardware decoder. Research is necessary.

**Comment by cattyhouse** [comment] 2019-10-16 03:22
> This bad decision. It breaks the hardware decoder.
> Research is necessary.

It is too bad, so i decided to remove the shikigva=1 args, hardware decoder is more useful to me than playing DRM video. 

I've also tried models which has no forceOfflineRenderer option according to  /System/Library/PrivateFrameworks/AppleGVA.framework/Resources/Info.plist, e.g. use MacBookPro15,1 (without shikigva=1 boot arg)  instead of iMac19,2 for my hardware (i5-8400+ RX470), this model also breaks hardware decoder by default

**Comment by cattyhouse** [comment] 2019-10-16 13:20
update: 

defaults write com.apple.AppleGVA  gvaForceAMDAVCDecode -boolean yes

fixed VDADecoderChecker error

**Comment by Andrey1970AppleLife** [comment] 2019-10-16 17:55
You switched the decoder to AMD. This decision so-so, to us Intel the decoder is necessary because it is better.

**Comment by vit9696** [comment] 2019-11-17 00:48
Resolved in master.

**Closed by vit9696** 2019-11-17 00:48 UTC
Labels: bug, priority:low, project:green

**Comment by cattyhouse** [comment] 2019-11-17 10:01
@vit9696 just tried the new version of weg: 
The video provided by @vandroiy2013 is playable with sound and image now. 
But `/Application/Video.app` does not play, a new window flashes swiftly and then disappear. 

````
 nvram boot-args
boot-args	darkwake=0
````
````
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.1
BuildVersion:	19B88
````
````
macserial | grep Model
         Model: iMac19,2
         Model: JWDW - iMac19,2
   SystemModel: iMac (Retina 4K, 21.5-inch, 2019)
````

````
defaults read com.apple.AppleGVA
2019-11-17 18:00:49.153 defaults[809:14132]
Domain com.apple.AppleGVA does not exist
````

````
 defaults read com.apple.coremedia
2019-11-17 18:01:06.228 defaults[813:14275]
Domain com.apple.coremedia does not exist
````
I've tried Reset NVRAM and below commands, same result.
````
sudo kextcache -i /
sudo update_dyld_shared_cache -force
sudo rm -rf ~/Library/Caches/*
sudo rm -rf /Library/Caches/*
sudo rm -rf /System/Library/Caches/*
````

**Comment by cattyhouse** [comment] 2019-11-17 10:06
logs from Console. What else can i do to debug this issue?

[tv.log](https://github.com/acidanthera/bugtracker/files/3855454/tv.log)

**Comment by cattyhouse** [comment] 2019-11-17 10:40
sorry, it looks like a network error, Apple Tv is not playable in China now? 
<img width="1191" alt="Screen Shot 2019-11-17 at 18 40 02" src="https://user-images.githubusercontent.com/3365320/69006395-ad2f5d80-0969-11ea-9341-6ce4bbdf126f.png">

**Comment by ngc598** [comment] 2019-11-17 11:36
> sorry, it looks like a network error, Apple Tv is not playable in China now?
> <img alt="Screen Shot 2019-11-17 at 18 40 02" width="1191" src="https://user-images.githubusercontent.com/3365320/69006395-ad2f5d80-0969-11ea-9341-6ce4bbdf126f.png">

Same error code in Australia. This might not be a regional issue.

**Comment by vit9696** [comment] 2019-11-17 13:07
Apple TV requires hardware decoding, it will not work.

**Comment by cattyhouse** [comment] 2019-11-17 13:09
> Apple TV requires hardware decoding, it will not work.

But Hardware decoding already works,  i’m on UHD630+ RX 470

**Comment by Andrey1970AppleLife** [comment] 2019-11-17 13:57
You confuse service TV+ and movies shop in TV.app(as in iTunes).
Movies from shop it is solved in the master.
But service TV+ has problems with IQSV.

**Comment by cattyhouse** [comment] 2019-11-17 14:30
> You confuse service TV+ and movies shop in TV.app(as in iTunes).
> Movies from shop it is solved in the master.
> But service TV+ has problems with IQSV.

wow, thanks for the info, checked again, Apple's product name is confusing me, but i'm gonna make it clear, on `/Application/Video.app` there are 5 tabs, only films in `Movies` are playable. 

@vit9696  thanks for the update and patch.

**Comment by ngc598** [comment] 2019-11-17 14:35
> You confuse service TV+ and movies shop in TV.app(as in iTunes).
> Movies from shop it is solved in the master.
> But service TV+ has problems with IQSV.

Dose IQSV means Intel Quick Sync Video? Any plan to solve this IQSV issue? 
Thank you.
