### ISSUE TITLE
[VoodooPS2Trackpad] Touchpad Problem on HP EliteBook series. 

### ISSUE THREAD

**Issue by aleksyXI** [acidanthera/bugtracker#1015] opened 2020-07-02 12:40 UTC
Keyboard and functional keys working, but touchpad physical keys doesn't work, and touchpad have very big sensitive.
In logs I can see, that EW mode disableed, buy enabling this mode in Info.plist make touchpad not working.
[debug_16162.zip](https://github.com/acidanthera/bugtracker/files/4864244/debug_16162.zip)

**Comment by vit9696** [comment] 2020-07-03 10:04
Duplicate of https://github.com/acidanthera/bugtracker/issues/890

**Closed by vit9696** 2020-07-03 10:04 UTC
Labels: duplicate, project:ps2
