### ISSUE TITLE
Latest AppleALC.kext (v1.4.7) broke sound on Dell g5 5587

### ISSUE THREAD

**Issue by tikscr** [acidanthera/bugtracker#746] opened 2020-03-02 12:27 UTC
After latest kext update sound is missing from my system. layout-id is 14. here is my ioreg.
[broken_sound.ioreg.zip](https://github.com/acidanthera/bugtracker/files/4275340/broken_sound.ioreg.zip)

**Comment by vit9696** [comment] 2020-03-02 12:30
No layout 14 was updated in the latest ALC, the issue is elsewhere, closing as invalid.

**Closed by vit9696** 2020-03-02 12:30 UTC
Labels: invalid, project:alc

**Comment by tikscr** [comment] 2020-03-02 12:32
@vit9696 but on 1.4.6 sound works without issues.

**Comment by Andrey1970AppleLife** [comment] 2020-03-02 16:08
You have no AppleALC.

**Comment by Andrey1970AppleLife** [comment] 2020-03-02 16:10
> After latest kext update sound is missing from my system. layout-id is 14. here is my ioreg.
> [broken_sound.ioreg.zip](https://github.com/acidanthera/bugtracker/files/4275340/broken_sound.ioreg.zip)

You have no AppleALC.
