### ISSUE TITLE
Set custom Connectors for AMD GPU (RX 580)

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#578] opened 2019-11-16 06:38 UTC
Specifications :
1. GPU : MSI RX 580 4GB Armor Edition
2. Port : HDMI, HDMI, DP, DP and DVI-D
3. Monitor Asus VN248H

Conditions :
1. With default RadeonFramebuffer, my HDMI Port is in con3 / Framebuffer3.
2. With Orinoco injection, my HDMI Port is in Con3 too,

Problem 
I want to set my HDMI Port (with display) in con0 like real mac ones (just personal reason). So with orinoco i need to replace 
**00040000 04030000 00010101 00000000 12040601 00000000 
00040000 04030000 00010201 00000000 22050403 00000000 
00080000 04020000 00010300 00000000 11020102 00000000 
00080000 04020000 00010400 00000000 21030504 00000000 
04000000 04000000 00010500 00000000 00000306 00000000** 

with

**00040000 04030000 00010400 00000000 12040601 00000000 
00040000 04030000 00010200 00000000 22050403 00000000 
00080000 04020000 00010300 00000000 11020102 00000000 
00080000 04020000 00010100 00000000 21030504 00000000 
00080000 14020000 00010500 00000000 10000306 00000000** 

And i successed with it.

But i want do it with RadeonFramebuffer without inject orinoco, there are feature with WEG use "connectors"

i have set "connectors" in DSDT with custom bytes (i have attached the pictures), but it's not success. HDMI Display still in con3. Did i miss some step??

![Screen Shot 2019-11-16 at 13 21 56](https://user-images.githubusercontent.com/9614101/68989259-66ad0680-0876-11ea-8afa-e51a74afee96.png)
![Screen Shot 2019-11-16 at 13 22 32](https://user-images.githubusercontent.com/9614101/68989260-67459d00-0876-11ea-8467-60851d1b8218.png)
![Screen Shot 2019-11-16 at 13 29 28](https://user-images.githubusercontent.com/9614101/68989261-67459d00-0876-11ea-8021-4d6e1bb8bdd4.png)
![Screen Shot 2019-11-16 at 13 30 17](https://user-images.githubusercontent.com/9614101/68989262-67459d00-0876-11ea-8e1e-5b82443fc801.png)
![Screen Shot 2019-11-16 at 13 30 42](https://user-images.githubusercontent.com/9614101/68989292-ee931080-0876-11ea-8e41-c2796d56bbe2.png)

**Comment by andreszerocross** [comment] 2019-11-16 07:05
Tried with

```
"connectors", 
                            Buffer ()
                            {
                                0x00, 0x04, 0x00, 0x00, 0x04, 0x03, 0x00, 0x00, 0x00, 0x01, 0x04, 0x00, 0x12, 0x04, 0x06, 0x01,
                                0x00, 0x04, 0x00, 0x00, 0x04, 0x03, 0x00, 0x00, 0x00, 0x01, 0x02, 0x00, 0x22, 0x05, 0x04, 0x03,
                                0x00, 0x08, 0x00, 0x00, 0x04, 0x02, 0x00, 0x00, 0x00, 0x01, 0x03, 0x00, 0x11, 0x02, 0x01, 0x02,
                                0x00, 0x08, 0x00, 0x00, 0x04, 0x02, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x21, 0x03, 0x05, 0x04,
                                0x00, 0x08, 0x00, 0x00, 0x14, 0x02, 0x00, 0x00, 0x00, 0x01, 0x05, 0x00, 0x10, 0x00, 0x03, 0x06 
                            }
```

and 

```
"connectors", 
                            Buffer ()
                            {
                                0x00, 0x04, 0x00, 0x00, 0x04, 0x03, 0x00, 0x00, 0x00, 0x01, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x12, 0x04, 0x06, 0x01, 0x00, 0x00, 0x00, 0x00,
                                0x00, 0x04, 0x00, 0x00, 0x04, 0x03, 0x00, 0x00, 0x00, 0x01, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x22, 0x05, 0x04, 0x03, 0x00, 0x00, 0x00, 0x00,
                                0x00, 0x08, 0x00, 0x00, 0x04, 0x02, 0x00, 0x00, 0x00, 0x01, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x11, 0x02, 0x01, 0x02, 0x00, 0x00, 0x00, 0x00,
                                0x00, 0x08, 0x00, 0x00, 0x04, 0x02, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x21, 0x03, 0x05, 0x04, 0x00, 0x00, 0x00, 0x00,
                                0x00, 0x08, 0x00, 0x00, 0x14, 0x02, 0x00, 0x00, 0x00, 0x01, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x03, 0x06, 0x00, 0x00, 0x00, 0x00 
                            }
```

But without no success

**Comment by vit9696** [comment] 2019-11-16 10:17
Well, um, log? Make one with liludump=60 -liludbgall and upload /var/log/Lilu_x.y.z.txt here.

**Comment by andreszerocross** [comment] 2019-11-16 12:33
> Well, um, log? Make one with liludump=60 -liludbgall and upload /var/log/Lilu_x.y.z.txt here. Also, what OS is this?

 Here is the log,, 
I am using macOS Catalina 10.15.2 Beta Build 19C39d and Mojave 10.14.6 Build 18G112. Same result in both OS, 
[Lilu_1.3.9_19.2.txt](https://github.com/acidanthera/bugtracker/files/3854172/Lilu_1.3.9_19.2.txt)

**Comment by vit9696** [comment] 2019-11-16 13:11
Right, now I see the point. In newer macOS versions firstly the driver creates the list of framebuffers, then WhateverGreen updates their data after matching with sense id. For this reason it is currently not possible to change the connector order with WhateverGreen, as connector patching happens after connector generation.

We can rework this, but this is purely cosmetics, and framebuffer order has nothing to do with the real connector priority. It happens based on pri field:

```
WhateverGreen:     con @ (DBG) 0 is type 00000400 (DP  ) flags 00000304 feat 0100 pri 0004 txmit 12 enc 04 hotplug 06 sense 01
WhateverGreen:     con @ (DBG) 1 is type 00000400 (DP  ) flags 00000304 feat 0100 pri 0002 txmit 22 enc 05 hotplug 04 sense 03
WhateverGreen:     con @ (DBG) 2 is type 00000800 (HDMI) flags 00000204 feat 0100 pri 0003 txmit 11 enc 02 hotplug 01 sense 02
WhateverGreen:     con @ (DBG) 3 is type 00000800 (HDMI) flags 00000204 feat 0100 pri 0001 txmit 21 enc 03 hotplug 05 sense 04
WhateverGreen:     con @ (DBG) 4 is type 00000800 (HDMI) flags 00000214 feat 0100 pri 0005 txmit 10 enc 00 hotplug 03 sense 06
```

And to choose boot display you can always inject `@3,AAPL,boot-display` = `<00 00 00 00>`. I am closing this, as presently it will require effort for no benefit. Feel free to reopen if you find actual bugs caused by being unable to reorder the connectors.

**Closed by vit9696** 2019-11-16 13:11 UTC
Labels: project:green

**Comment by andreszerocross** [comment] 2019-11-16 13:24
> Right, now I see the point. In newer macOS versions firstly the driver creates the list of framebuffers, then WhateverGreen updates their data after matching with sense id. For this reason it is currently not possible to change the connector order with WhateverGreen, as connector patching happens after connector generation.
> 
> We can rework this, but this is purely cosmetics, and framebuffer order has nothing to do with the real connector priority. It happens based on pri field:
> 
> ```
> WhateverGreen:     con @ (DBG) 0 is type 00000400 (DP  ) flags 00000304 feat 0100 pri 0004 txmit 12 enc 04 hotplug 06 sense 01
> WhateverGreen:     con @ (DBG) 1 is type 00000400 (DP  ) flags 00000304 feat 0100 pri 0002 txmit 22 enc 05 hotplug 04 sense 03
> WhateverGreen:     con @ (DBG) 2 is type 00000800 (HDMI) flags 00000204 feat 0100 pri 0003 txmit 11 enc 02 hotplug 01 sense 02
> WhateverGreen:     con @ (DBG) 3 is type 00000800 (HDMI) flags 00000204 feat 0100 pri 0001 txmit 21 enc 03 hotplug 05 sense 04
> WhateverGreen:     con @ (DBG) 4 is type 00000800 (HDMI) flags 00000214 feat 0100 pri 0005 txmit 10 enc 00 hotplug 03 sense 06
> ```
> 
> And to choose boot display you can always inject `@3,AAPL,boot-display` = `<00 00 00 00>`. I am closing this, as presently it will require effort for no benefit. Feel free to reopen if you find actual bugs caused by being unable to reorder the connectors.

Sorry just need confirmation
Default pri should be,

0001
0002
0003
0004 (con3)
0005

Log show, pri connector has change but no effect, but if i change pri field of Orinoco then it gives effect (Hdmi with display become con0)

**Comment by vit9696** [comment] 2019-11-16 13:29
Internal priority and the order of framebuffer devices displayed in I/O Registry are different things:
- Internal priority affects AppleGraphicsDevicePolicy logic and bandwidth selection stuff. It is controlled by that pri field.
- Framebuffer device order depends on the VBIOS. You can indeed patch it by ignoring your VBIOS and using e.g. Orinoco framebuffer, yet it is irrelevant for macOS functioning. In my opinion, it in fact makes more sense to stick with what your GPU vendor did. Usually this order matches the physical order of ports on the GPU.
