### ISSUE TITLE
WhateverGreen / shikigva with radeon breaks iGPU hw encoding in 10.15.x

### ISSUE THREAD

**Issue by f00b4r0** [acidanthera/bugtracker#1444] opened 2021-01-19 10:58 UTC
Software:
- 10.15.7 (19H114)
- OC 0.6.5
- WhateverGreen 1.4.6
- Lilu 1.5.0

Hardware:
- i3-8350K
- RX560 2GB
- Asus Z370 Prime-A

I recently noticed that exporting a video in QuickTime player (with default 480p h264 setting) with `shikigva=80` or `shikigva=16` set produced garbled output (clobbered frames, blocky artifacts, see 1s [video attachment](https://user-images.githubusercontent.com/23039782/105024734-becc3380-5a4c-11eb-9137-c968478d57b6.mov)).

Not setting `shikigva` "fixes" the issue entirely.

In all cases, the hardware-accelerated encoder is used (confirmed with Intel Power Gadget).

I'm not really sure how to debug this so I apologise already if this bugreport isn't sufficiently thorough; I'm happy to provide further data if needed.

I've attached my OC folder (serials removed), please note the DSDT is included to work around the (unrelated to this issue) GPE6F ACPI interrupt bug which pegged `kernel_task` to 100% CPU. The only edit there is the removal of Method `_L6F` to address this problem, no other change.

[OC.zip](https://github.com/acidanthera/bugtracker/files/5835386/OC.zip)

I hope this helps.

**Comment by vit9696** [comment] 2021-01-19 15:31
This is the intended behaviour (unfortunately). It is not WEG/shikigva that do it, but rather AMD GPU decoder that is broken on your hardware/software. shikigva is no longer supported as of macOS 11 as well. Closing as "will not fix".

**Closed by vit9696** 2021-01-19 15:31 UTC
Labels: project:green
