### ISSUE TITLE
Duplicate Boot Entries

### ISSUE THREAD

**Issue by icedterminal** [acidanthera/bugtracker#784] opened 2020-03-25 15:18 UTC
OpenCore: v0.5.6
Board: GA-Z270X-UG (F9d)

System boots in UEFI only mode. When using OpenCore to boot Windows, each time a duplicate entry is created in the UEFI boot list. I am unsure which component is at fault for this bug. Windows, OpenCore or the board firmware. Unlike issue #425, OpenCore is not duplicated, Windows is.

F12 Boot selection screen:
* `UEFI OS` <--- Open Core
* `Windows Boot Manager`

Use OpenCore to boot Windows. Reboot computer and press F12.
* `UEFI OS` <--- Open Core
* `Windows Boot Manager`
* `Windows Boot Manager`

Repeat reboot cycle.
* `UEFI OS` <--- Open Core
* `Windows Boot Manager`
* `Windows Boot Manager`
* `Windows Boot Manager`

Duplicate entries can be rectified by [recreating Windows EFI partition](https://gist.github.com/icedterminal/0809ae8ece84fcc86e1747a3e053aa7e#recreate-boot-files-with-dism) with a USB installer.

**Comment by ZISQO** [comment] 2020-03-25 23:22
how about the clear CMOS BIOS first?

**Comment by icedterminal** [comment] 2020-03-26 00:01
@ZISQO Has no effect. If there are multiple entries prior to reset, it will get picked up again after reset. The entries are being wrote out to disk. Which the firmware then finds. As an extra measure, I removed both the macOS and Ubuntu boot drives. Leaving only Windows. Still multiple.

**Comment by vit9696** [comment] 2020-03-27 01:02
If anything, there is absolutely no way to prove this. No debug log, no EFI folder, etc. Closing as invalid.

**Closed by vit9696** 2020-03-27 01:02 UTC
Labels: invalid, project:oc

**Comment by icedterminal** [comment] 2020-03-27 01:16
> If anything, there is absolutely no way to prove this
I can provide photos or a clip of the boot screen if that helps.

> No debug log
No idea where I would find the debug log for opencore.

> no EFI folder
I can upload that.

**Comment by vit9696** [comment] 2020-03-27 01:26
Please refer to the manual on how to obtain the debug log, file logging should do. And yes, please do upload the EFI folder in addition to the debug log.

**Comment by icedterminal** [comment] 2020-04-08 02:15
Sorry for the long delay in response.

I updated everything to latest today. Enabled logging, cleared NVRAM, recreated both EFI partitions for each OS. At the boot selection screen I had one of each. After booting Windows through OpenCore, the boot selection had [two Windows entries](https://i.imgur.com/YTY1QNk.jpg). It did not create any more after the two with v.0.5.7. I recreated the Windows EFI partition to remove the duplicate entry.

As requested, here is the EFI and logs for macOS: https://github.com/icedterminal/ga-z270x-ug/tree/10.15.x/SSD_EFI/OC_EFI

**Comment by ZISQO** [comment] 2020-04-09 08:34
> Sorry for the long delay in response.
> 
> I updated everything to latest today. Enabled logging, cleared NVRAM, recreated both EFI partitions for each OS. At the boot selection screen I had one of each. After booting Windows through OpenCore, the boot selection had [two Windows entries](https://i.imgur.com/YTY1QNk.jpg). It did not create any more after the two with v.0.5.7. I recreated the Windows EFI partition to remove the duplicate entry.
> 
> As requested, here is the EFI and logs for macOS: https://github.com/icedterminal/ga-z270x-ug/tree/10.15.x/SSD_EFI/OC_EFI
> 
> Further information
> 
> It appears Windows is what has some issues with being loaded from OC. Selected from OC, it boots as normal but briefly shows _"Preparing devices..."_. Device Manager shows nothing out of the ordinary. I shutdown the computer and rebuilt the EFI once more to remove the duplicate. Once booted into Windows, Device Manager now shows an "Unknown Device" at `ACPI\UIA00000\2&DABA3FF&0`. I removed this device and rebooted. It did not reappear. Rebooted Windows from OC, then rebooted _again_ from the default entry. "Unknown Device" returned. Using `bcdedit /enum`, I was able to see there is indeed duplicate entries for Windows. Instead of rebuilding, I deleted one of the duplicates. I could have just done that in the first place. Didn't think about it though.

the duplicate boot disk list up was occur sometimes but easy to fix it up with re-flash CMOS bios even same version. and recently OC-Devbuild 0.5.8 or Officially 0.5.7 Release version was no error occur error found when booting up a wind10 RS5 via OpenCore bootloader. this is my exprience with ASUS x299 firmware. ty,.

**Comment by icedterminal** [comment] 2020-04-09 14:32
> but easy to fix it up with re-flash CMOS bios even same version

I did try that with latest version (F9d). But again, just like clearing CMOS (not reflashing), both entries are picked up as they are being wrote out to disk. The only way I have been able to remove the duplicate entry is by either recreating the EFI partition or, just recently, using `bcdedit` to reset it within Windows.

I must insist, resetting or reflashing BIOS in any way does not solve the problem. If there is no solution, I can live with pressing F12 to choose. Out of convenience, letting it default to OC where I can select is preferred. I'll poke around with it later and enable Windows verbose boot logging to see if there is anything happening after OC.

**Comment by vit9696** [comment] 2020-04-09 16:32
I checked your configuration, and it appears to be a bug in your motherboard BIOS automatic boot entry discovery. I suggest you to report that to the vendor support. Unfortunately we cannot do much, as this happens before OpenCore even starts.

**Comment by icedterminal** [comment] 2020-04-09 17:44
Thank you @vit9696. I'll just use F12. I doubt Gigabyte will fix this bug on such an older board, though I'll report it.

**Comment by vit9696** [comment] 2020-04-09 23:37
Are you sure that **disabling** `RequestBootVarFallback` and performing NVRAM reset afterwards does not solve it though?

**Comment by icedterminal** [comment] 2020-04-10 16:15
Within Windows I deleted the bcd. Edited the config and disabled `RequestBootVarFallback`. Rebooted and noticed there were now ghost entries in F12. Two in fact. Since the firmware wasn't able to actually find Windows bootloader, it left empty options. Selecting either one resulted in a "Insert boot media" screen. I let it default to OC and cleared NVRAM. Ghost entries are now gone. Plugged in Windows USB and recreated the Windows EFI partition. Rebooted letting it default to OC then Windows. After that I performed multiple reboot cycles to see if the bug would trigger again. The only thing to appear again was a ghost entry when the USB was plugged in as a test and then removed. It then disappeared later.

I realise flashing BIOS versions is inherently risky, however, I wanted to determine if there was a version that did not have this issue. Unfortunately, all versions down to F6 present the same thing. Duplicate and ghost entries. I could go no lower than F6 due to a [firmware restriction.](https://www.gigabyte.com/Motherboard/GA-Z270X-Ultra-Gaming-rev-10/support#support-dl-bios)

I will submit findings to Gigabyte in hopes they *might* fix it. Makes me wonder if there are other boards from their lineup that do this too.

**Comment by alextrieutuan** [comment] 2020-05-11 01:13
@icedterminal Have you solved this issue. I got exactly your issue yesterday with OC 0.5.8.

**Comment by icedterminal** [comment] 2020-05-11 02:11
@alextrieutuan I have not. Doesn't matter which one I select as they both appear to have the same function. On 0.5.8 resetting NVRAM clears it out. Where as 0.5.7 it was being written out.

If your firmware bugs out preventing entering settings, you'll need boot into OC. If OC is not your default, I hope you can manually enter it. Reset NVRAM. Otherwise, CMOS reset is your option.

---

Further gremlins have arrived though!

1. From a complete power off, I press the power button. Press F12 to enter the boot menu. At this time, there are only three boot entries. Ubuntu via GRUB, macOS via OC, and Windows via WBL. I select OpenCore to boot macOS. Once the OS is loaded, I let a few minutes pass then click the Apple menu to click Restart. Upon reboot if I press F12, the screen turns black. The system will continue to function as normal and boot into Windows via WBL, since this is default setting. I can reconnect the HDMI cable all I want, but no picture will display. It is at this time I am certain there are now two WBL options.
2. Once the above happens, I have no choice but to force shutdown by hand. From a complete power off, I press the power button. Press F12 to enter boot menu. Select either one of the Windows via WBL.
3. Once the OS is loaded I let a few minutes pass and click Restart. This time I don't press F12. The post screen hangs around until the I see the Windows login. So I do not see the Windows boot screen at all.

I have disabled BGRT in firmware settings in case that was a conflict with post screen hanging around. But it isn't. It's indeed a board firmware bug with the use of OpenCore. I can reset NVRAM, clear CMOS or complete flash the firmware and it all goes away. There is something screwy going on with board firmware that doesn't like something OC is doing. Which results in the behavior we see.

I still see *Other devices* > *Unknown device* in Device Manager if I boot Windows via OC.

**Comment by vit9696** [comment] 2020-05-11 02:16
Will not promise but you might have more luck with 0.5.9 and the following settings after NVRAM reset:

- RequestBootVarRouting - yes
- RequestBootVarFallback - no
- BootProtect - Bootstrap

**Comment by icedterminal** [comment] 2020-05-11 02:32
I'll wait patiently for it. Thanks for the heads up.

In the mean time I just complete power off to bypass any of the quirks I have came across. It's not a huge deal.

**Comment by alextrieutuan** [comment] 2020-05-15 04:03
Thanks for all of your response. But it is still seem no luck to me, I still need to reset NVRAM to clear extra boot options. Already try with :

- RequestBootVarRouting - yes
- RequestBootVarFallback - no
- BootProtect - Bootstrap

But it is not a big deal. Thanks for your great bootloader and also looking for some good news soon.

Sorry for my bad english too.

**Comment by icedterminal** [comment] 2020-05-17 09:19
@alextrieutuan He said after 0.5.9 releases. You're making these changes on 0.5.8. Which is likely why it has no effect for you.

@vit9696 

> Will not promise but you might have more luck with 0.5.9 and the following settings after NVRAM reset

It worked. I built from source because why the hell not. Whatever magic fixed it. At least for me. I read over the differences doc and sample to make changes to my config. I rebooted over and over trying to make it trigger. It did not.

**Comment by alextrieutuan** [comment] 2020-05-17 09:28
@icedterminal Oh sorry, my mistake. I'm just follow on these config but not the version.

I will give a try, thanks bro.

**Comment by alextrieutuan** [comment] 2020-06-06 07:52
@icedterminal Sorry for bothering you but How could you managed to work?. I have updated 0.5.9 version and try above config but I still got duplicated entry.

**Comment by Tahiry25** [comment] 2020-06-15 23:23
@icedterminal  Have you managed to fix the "unknown device" ACPI\UIA00000\2&DABA3FF&0 in windows? I have a gigabyte MB and I also have the this issue in windows.

As far as the duplicated entry, I usually clear NVRAM, always work when I need to get rid of unwanted boot entries

**Comment by icedterminal** [comment] 2020-06-17 21:40
@Tahiry25 It's a side effect of OpenCore. It's harmless. Used for macOS. The developers have already stated Windows gets little to no support other than passing the command to boot it. You should instead use WBL from the BIOS boot screen.

@alextrieutuan When it comes to duplicated entries, this was resolved with 0.5.9. The developers corrected this. At least for me. If you still have this issue, I suggest you communicate with them.

**Comment by vit9696** [comment] 2020-06-17 23:33
The unknown device should be caused by your ACPI edits, it has nothing to directly do with OpenCore. Just check your ACPI changes and make sure to properly guard the additions with `_OSI` method.

**Comment by Tahiry25** [comment] 2020-06-18 00:20
@vit9696 the thing is even when I remove all the ssdts under acpi. I still get the unknown device. If my config.plist is what’s causing it, It’s got to be one of quirks being enabled.

**Comment by vit9696** [comment] 2020-06-18 00:23
Hmm, should be patches or dropped tables. There are no ACPI quirks that can cause this. Feel free to post your config though.

**Comment by Tahiry25** [comment] 2020-06-18 05:06
Thanks @vit9696 this is my config.plist. 
quick note: 
ACPI path:  PCI0.LPCB 
cfglock disabled.

[config.plist](https://drive.google.com/file/d/1f1clHqhxMEHFE9cdftG2RsWIw_mXZ0Ta/view?usp=sharing)

**Comment by vit9696** [comment] 2020-06-18 09:08
I don't know what `SSDT-UIAC-ALL.aml` is. Probably it is related to `USBInjectAll.kext` from its name, and the use of this kext is strongly discouraged. You should map the USBs via a custom plist-only kext. There is a more or less decent guide [here](https://dortania.github.io/USB-Map-Guide/).

**Comment by dreamwhite** [comment] 2020-06-18 13:26
> the use of this kext is strongly discouraged

Dear @vit9696, why is the use of this kext discouraged? I heard about power management issues and RAM consumption. Is this the main reason of discouraging or what? Many thanks :)

**Comment by vit9696** [comment] 2020-06-18 13:32
Because it reimplements what macOS already has in a confusing manner.

**Comment by dreamwhite** [comment] 2020-06-18 13:36
> Because it reimplements what macOS already has in a confusing manner.

Uhm so something about USB ports injection okay. And what's the preferred method to map USB ports? Enable `XHCIPortLimit` quirk and discovering the active ports without need to inject USBInjectAll?

**Comment by vit9696** [comment] 2020-06-18 13:37
This is not your favourite support forum. See the link I posted right above.
