### ISSUE TITLE
No boot entries from NVMe drives on Z390 and select Z370

### ISSUE THREAD

**Issue by MacFriedIntel** [acidanthera/bugtracker#309] opened 2019-05-01 23:55 UTC
After using new updated files for AptioMemory and adding the new Quirk under UEFI, NVME is still not being detected on the OpenCore Menu as an option to boot from with Z390 Gigabyte and Z370 Prime -P. Have used the forum to request support and not receiving an update. Certain UEFI's are not picking up the boot option where is clover is.

**Comment by martineastwood82** [comment] 2019-05-02 00:02
This issue is being listed on many Forums that are testing OC

**Comment by NCC-Lykos** [comment] 2019-05-02 00:19
I am also having this on my Z390 Aorus Ultra Gigabyte board. I have attached a log. One thing to note is that it detected the Clover EFI on the NVME when it was still there, so I moved it off to a USB stick and moved OC to the NVME drive. It appears it cannot detect macOS on APFS on NVME. Not sure about HFS+

[opencorebootlog-latest.txt](https://github.com/acidanthera/bugtracker/files/3136400/opencorebootlog-latest.txt)

**Comment by errorexists** [comment] 2019-05-02 00:23
same issue with me here? https://github.com/acidanthera/bugtracker/issues/306

**Comment by NCC-Lykos** [comment] 2019-05-02 00:31
Yes, except I am using vanilla, not olarila

**Comment by vit9696** [comment] 2019-05-02 12:06
Morning, so we finally have a log, which is good, even though it does not tell us much. Thank you for that.

It will take some time to come up with a conclusion for the issue, so please patiently execute the steps we ask (asking about them on forums when something is unclear) and do not post not technical information.

We will later provide a new debug binary of OC, as Fritz mentioned on insanely, yet for now I need careful answers of the following questions:

1. How was macOS installed on these drives? Was it an upgrade, a normal installation from a drive created with `createinstallmedia` tool, or something else? Please be as specific as possible.
2. What does `diskutil list` show for these drives in macOS? Are Preboot and Recovery partitions available? (Use other bootloaders to load into OS)
3. If you mount the Preboot volume (use `diskutil mount /dev/diskNsM`), what files does it have? It is supposed to have directors named with your volume UUID and have boot.efi inside.
If you are uncertain what we need, you can simply provide the output of `ls -la` command in Preboot root and each top level subdirectory. Another way could be using `tree -a /Volumes/Preboot` command, but it will have to be installed with MacPorts or HomeBrew.
4. If you put EFI\BOOT\BOOTx64.efi file onto the EFI partition of your NVMe volume, is it visible from your BIOS menu (commonly there is a boot selection menu accessible with F8 key or something like that)? If it is, is it visible from OpenCore menu?
5. Since you use an APFS filesystem, do both Clover and OpenCore use the same filesystem drivers? For instance, do you use the same binary versions of ApfsDriverLoader.efi or not, and do you use apfs.efi directly with e.g. Clover?
6. Can you browse your filesystem from UEFI Shell loaded from OpenCore? For that take UEFI Shell (e.g. https://github.com/acidanthera/OpenCoreShell/releases), and save it under the name of EFI\BOOT\BOOTx64.efi on some USB stick. Then choose this Shell in OpenCore menu, and try to find your NVMe partitions by typing fsX: and checking dir output.
7. Does your OpenCore binary (and all the drivers) work on some other system? There is always a possibility that for some reason the compilation failed to create a working binary (or binaries), so it is best to ensure that there exists a system that boots fine with exactly the same set of binaries.

Thanks and take your time.

**Comment by NCC-Lykos** [comment] 2019-05-02 16:53
> Morning, so we finally have a log, which is good, even though it does not tell us much. Thank you for that.
> 
> It will take some time to come up with a conclusion for the issue, so please patiently execute the steps we ask (asking about them on forums when something is unclear) and do not post not technical information.
> 
> We will later provide a new debug binary of OC, as Fritz mentioned on insanely, yet for now I need careful answers of the following questions:
> 
> 1. How was macOS installed on these drives? Was it an upgrade, a normal installation from a drive created with `createinstallmedia` tool, or something else? Please be as specific as possible.
> 2. What does `diskutil list` show for these drives in macOS? Are Preboot and Recovery partitions available? (Use other bootloaders to load into OS)
> 3. If you mount the Preboot volume (use `diskutil mount /dev/diskNsM`), what files does it have? It is supposed to have directors named with your volume UUID and have boot.efi inside.
>    If you are uncertain what we need, you can simply provide the output of `ls -la` command in Preboot root and each top level subdirectory. Another way could be using `tree -a /Volumes/Preboot` command, but it will have to be installed with MacPorts or HomeBrew.
> 4. If you put EFI\BOOT\BOOTx64.efi file onto the EFI partition of your NVMe volume, is it visible from your BIOS menu (commonly there is a boot selection menu accessible with F8 key or something like that)? If it is, is it visible from OpenCore menu?
> 5. Since you use an APFS filesystem, do both Clover and OpenCore use the same filesystem drivers? For instance, do you use the same binary versions of ApfsDriverLoader.efi or not, and do you use apfs.efi directly with e.g. Clover?
> 6. Can you browse your filesystem from UEFI Shell loaded from OpenCore? For that take UEFI Shell (e.g. https://github.com/acidanthera/OpenCoreShell/releases), and save it under the name of EFI\BOOT\BOOTx64.efi on some USB stick. Then choose this Shell in OpenCore menu, and try to find your NVMe partitions by typing fsX: and checking dir output.
> 7. Does your OpenCore binary (and all the drivers) work on some other system? There is always a possibility that for some reason the compilation failed to create a working binary (or binaries), so it is best to ensure that there exists a system that boots fine with exactly the same set of binaries.
> 
> Thanks and take your time.

1. macOS was installed by creating an installer USB with createinstallmedia and then installing Clover to the USB Drive. Installation was straight forward and Clover was moved to the EFI of the installation drive upon completion.

2. I have provided this in a txt file by executing `diskutil list > diskutillist.txt` - Yes, preboot and recovery are available in the diskutil list but not in the OC Boot menu. An entry for MacData is available on OC and is pointing to an .efi file for booting into a Time Machine recovery at `/dev/disk3s2`

3. I have provided a tree view of Preboot via `tree /Volumes/Preboot/ > preboottree.txt`

4. This one has two outcomes, when I install OpenCore on a USB and boot from it, it will see Clover EFI on the NVME drive and boot to it, however Clover will return no macOS options to boot from when boot with OC. The second, when I install OpenCore to the NVME drive and boot from that, it will again see Clover EFI on the USB Drive if I have it plugged in, but does not see its self as a boot option, or macOS as a boot option. I hope this was a clear answer and if not please tell me how to clarify. 

5. I use the same drivers with both bootloaders, I have provided a tree view of my EFI folder for OpenCore and for Clover. Clover is installed to a USB currently and OpenCore is installed to the NVME drive.

6. Yes, both the HFS+ drive and the APFS drive I can find and browse the directory structure, I can even view text files successfully. I did this by booting the UEFI Shell you provided via OC installed on the NVME, with Clover completely removed from the system at the time.

7. Yes, we have an active discussion on Discord and I have been getting working builds and binaries from other members to try each time there is an update or when somebody has come up with a new config.plist


If you need anything else please don't hesitate to ask, I am available all day.

[cloverefitree.txt](https://github.com/acidanthera/bugtracker/files/3139058/cloverefitree.txt)
[opencoreefitree.txt](https://github.com/acidanthera/bugtracker/files/3139059/opencoreefitree.txt)
[preboottree.txt](https://github.com/acidanthera/bugtracker/files/3139060/preboottree.txt)
[diskutillist.txt](https://github.com/acidanthera/bugtracker/files/3139061/diskutillist.txt)

**Comment by vit9696** [comment] 2019-05-02 17:59
Thanks for the information, this is very useful.

1. Regarding NvmExpressDxe.efi, I guess that was added for testing purposes. Please remove it, it should not be needed, and may potentially meddle with our code.
2. I see 4263DF0B-77EF-4DFC-A152-78C3614D24EB UUID on your Preboot volume, which is good, but does it actually match your partition ID? Please run `diskutil info /Volumes/Macintosh` and compare them.
3. I added initial logging to some of the boot entry lookup code, please recompile OpenCore and redo the log. Hopefully it will give us a hint on where to continue looking in the first place.

At present I believe that the issue is in our bless protocol implementation, which replicates 1:1 what Apple does on Macs and relies quite a lot on Apple's APFS driver. For this reason the most likely cause is that your firmware behaves differently from what we and Apple expect.

It will take some time and effort to investigate what exactly happens there, which will require several log dumps as we progress. Do not expect it to be quick.

**Comment by NCC-Lykos** [comment] 2019-05-02 20:27
> Thanks for the information, this is very useful.
> 
> 1. Regarding NvmExpressDxe.efi, I guess that was added for testing purposes. Please remove it, it should not be needed, and may potentially meddle with our code.
> 2. I see 4263DF0B-77EF-4DFC-A152-78C3614D24EB UUID on your Preboot volume, which is good, but does it actually match your partition ID? Please run `diskutil info /Volumes/Macintosh` and compare them.
> 3. I added initial logging to some of the boot entry lookup code, please recompile OpenCore and redo the log. Hopefully it will give us a hint on where to continue looking in the first place.
> 
> At present I believe that the issue is in our bless protocol implementation, which replicates 1:1 what Apple does on Macs and relies quite a lot on Apple's APFS driver. For this reason the most likely cause is that your firmware behaves differently from what we and Apple expect.
> 
> It will take some time and effort to investigate what exactly happens there, which will require several log dumps as we progress. Do not expect it to be quick.


1. I have removed NvmExpressDxe.efi, it was added for testing purposes. My new structure is reflected in attachment below and an attached config.plist

2. Yes, it does match. See output attached below.

3. I have attached a new log file using the latest debug build.

I am very patient :) I've handled bug reports on my own projects and I know these can be hard to track down. Anything I can provide I will do so.

[opencoreefitree-522019-1.txt](https://github.com/acidanthera/bugtracker/files/3139839/opencoreefitree-522019-1.txt)
[opencoreboot-522019.txt](https://github.com/acidanthera/bugtracker/files/3139840/opencoreboot-522019.txt)
[macintoshdiskutilinfo.txt](https://github.com/acidanthera/bugtracker/files/3139841/macintoshdiskutilinfo.txt)

**Comment by vit9696** [comment] 2019-05-02 21:41
So, the issue is visible. These lines should not abort with not found:

```
00:000 00:000 OCB: Bless result for load (0) - Not Found
00:000 00:000 OCB: Filesystem 6 (33BDB298) named Preboot (Success) has 0 entries
```

Also, while unrelated, your configuration has several issues, including `XMPDetection` or `CPU` (we do not support that), `ReinstallProtocol` (that got removed) and several other minor stuff that got changed, etc. However, I do not expect it to be able to cause the issue we have (regardless of documentation forbidding broken configs), so best fix it later accordingly to the manual.

I added logging to OcAppleBootPolicyLib, let's hope it sheds some light on the matter. Redo the log with master please.

**Comment by NCC-Lykos** [comment] 2019-05-02 23:33
> So, the issue is visible. These lines should not abort with not found:
> 
> ```
> 00:000 00:000 OCB: Bless result for load (0) - Not Found
> 00:000 00:000 OCB: Filesystem 6 (33BDB298) named Preboot (Success) has 0 entries
> ```
> 
> Also, while unrelated, your configuration has several issues, including `XMPDetection` or `CPU` (we do not support that), `ReinstallProtocol` (that got removed) and several other minor stuff that got changed, etc. However, I do not expect it to be able to cause the issue we have (regardless of documentation forbidding broken configs), so best fix it later accordingly to the manual.
> 
> I added logging to OcAppleBootPolicyLib, let's hope it sheds some light on the matter. Redo the log with master please.

I am having an issue now with boot-log being empty.

`nvram: Error getting variable - '4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:boot-log': (iokit/common) data was not found`

 I have not changed my configuration. I will have to attempt again tomorrow as I have to go to work now. I will report back tomorrow with my findings. Thank you!

**Comment by vit9696** [comment] 2019-05-03 01:22
It seems that very bad things happen when NVRAM log exceeds 32 kilobytes. It silently dies and often does not even report failure.

To circumvent this I had to limit log size to 32 kilobytes and avoid sending extra verbose data to NVRAM to ensure reliable booting on most systems. This means that we cannot easily log bless data to NVRAM, and it is best to use some other target.

For this reason I added file logging. It is very slow, expect minutes on HDD or USB flash, but reliable, as every line is immediately saved on the disk. Please note, that you will likely need `DisableWatchDog`, which got moved to Misc → Debug section.

**Comment by NCC-Lykos** [comment] 2019-05-03 16:42
> It seems that very bad things happen when NVRAM log exceeds 32 kilobytes. It silently dies and often does not even report failure.
> 
> To circumvent this I had to limit log size to 32 kilobytes and avoid sending extra verbose data to NVRAM to ensure reliable booting on most systems. This means that we cannot easily log bless data to NVRAM, and it is best to use some other target.
> 
> For this reason I added file logging. It is very slow, expect minutes on HDD or USB flash, but reliable, as every line is immediately saved on the disk. Please note, that you will likely need `DisableWatchDog`, which got moved to Misc → Debug section.

Morning, I have generated this log using the latest build and the new log to filesystem. Just a note, it was pretty much instant. Didn't take long at all to generate.

[opencore.log](https://github.com/acidanthera/bugtracker/files/3142806/opencore.log)

**Comment by vit9696** [comment] 2019-05-03 18:17
Morning, so, the issue is that APFS file system protocol reports that there is no `\System\Library\CoreServices\boot.efi` file in `4263DF0B-77EF-4DFC-A152-78C3614D24EB` directory on your preboot volume. Great.

I added two changes in this local build, please try it.
- Opening `System\Library\CoreServices\boot.efi` without the leading slash.
- Error code printing for failed file presence checks.

[OC-NOOPT-NVMe-r1.zip](https://github.com/acidanthera/bugtracker/files/3143107/OC-NOOPT-NVMe-r1.zip)

**Comment by NCC-Lykos** [comment] 2019-05-03 20:14
> Morning, so, the issue is that APFS file system protocol reports that there is no `\System\Library\CoreServices\boot.efi` file in `4263DF0B-77EF-4DFC-A152-78C3614D24EB` directory on your preboot volume. Great.
> 
> I added two changes in this local build, please try it.
> 
> * Opening `System\Library\CoreServices\boot.efi` without the leading slash.
> * Error code printing for failed file presence checks.
> 
> [OC-NOOPT-NVMe-r1.zip](https://github.com/acidanthera/bugtracker/files/3143107/OC-NOOPT-NVMe-r1.zip)

Progress has been made, see log. Had Preboot option, looks like without leading slash detected it but failed boot on a critical error.

[opencore.log](https://github.com/acidanthera/bugtracker/files/3143431/opencore.log)

**Comment by vit9696** [comment] 2019-05-03 20:56
Hmmm, so removing the leading slash actually does work. This is very inadequate. The critical error is most likely caused by wrong path being appended. Please try this version.

[OC-NOOPT-NVMe-r2.zip](https://github.com/acidanthera/bugtracker/files/3143545/OC-NOOPT-NVMe-r2.zip)

**Comment by NCC-Lykos** [comment] 2019-05-03 21:09
> Hmmm, so removing the leading slash actually does work. This is very inadequate. The critical error is most likely caused by wrong path being appended. Please try this version.
> 
> [OC-NOOPT-NVMe-r2.zip](https://github.com/acidanthera/bugtracker/files/3143545/OC-NOOPT-NVMe-r2.zip)

[opencore.log](https://github.com/acidanthera/bugtracker/files/3143564/opencore.log)

Another error, however I don't know if this matters, but the slashes switch in this line... 

`00:000 00:000 Entry 2 is Preboot at dp PciRoot(0x0)/Pci(0x1B,0x0)/Pci(0x0,0x0)/NVMe(0x1,60-DC-B1-71-55-38-25-00)/HD(2,GPT,7A0E3772-71D0-4C32-8E3F-BF02B35886FA,0x64028,0x3B97D260)/VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,0C36B0E1CE42BF409A0C827B0B971E2F)/\System\Library\CoreServices\boot.efi`


From `/` to `\` would this cause an issue?

**Comment by vit9696** [comment] 2019-05-03 21:20
This slash separates device paths, not directory paths. For some reason your preboot volume UUID directory is missing. We checked the reversed code, and indeed found that we made a couple of mistakes. Thanks to Fritz I believe I fixed it now.

[OC-NOOPT-NVMe-r3.zip](https://github.com/acidanthera/bugtracker/files/3143579/OC-NOOPT-NVMe-r3.zip)

**Comment by NCC-Lykos** [comment] 2019-05-03 21:26
> This slash separates device paths, not directory paths. For some reason your preboot volume UUID directory is missing. We checked the reversed code, and indeed found that we made a couple of mistakes. Thanks to Fritz I believe I fixed it now.
> 
> [OC-NOOPT-NVMe-r3.zip](https://github.com/acidanthera/bugtracker/files/3143579/OC-NOOPT-NVMe-r3.zip)

Noted, here you go. Did not boot again.

[opencore.log](https://github.com/acidanthera/bugtracker/files/3143594/opencore.log)

**Comment by vit9696** [comment] 2019-05-03 21:33
Oho. I do see another issue for the good. Should implement the fix soon. So this definitely had never worked before. Question is, what does function on my system :D Probably some other code path.

**Comment by vit9696** [comment] 2019-05-03 21:48
Okay, at least I have an idea how it should work. Try that and let's hope for the best.

[OC-NOOPT-NVMe-r4.zip](https://github.com/acidanthera/bugtracker/files/3143628/OC-NOOPT-NVMe-r4.zip)

**Comment by NCC-Lykos** [comment] 2019-05-03 21:59
> Okay, at least I have an idea how it should work. Try that and let's hope for the best.
> 
> [OC-NOOPT-NVMe-r4.zip](https://github.com/acidanthera/bugtracker/files/3143628/OC-NOOPT-NVMe-r4.zip)

Hey guess what? All options recognized now. Attached log, it is a config issue for me now to figure out.

[opencore.log](https://github.com/acidanthera/bugtracker/files/3143652/opencore.log)

**Comment by MacFriedIntel** [comment] 2019-05-03 22:10
This has fixed @errorexists boot issue and is now in macOS.

**Comment by errorexists** [comment] 2019-05-03 22:18
am now able to boot on to NVME thank you for the fix an your time

**Comment by vit9696** [comment] 2019-05-03 22:42
Nice, additional thanks should go to @Download-Fritz and @NCC-Lykos for their input. Closing as fixed.

**Closed by vit9696** 2019-05-03 22:42 UTC
Labels: project:oc
