### ISSUE TITLE
ElanTouchPad：trackpoint and trackpad can not use at the same time

### ISSUE THREAD

**Issue by goomoon** [acidanthera/bugtracker#2030] opened 2022-05-30 04:01 UTC
When I enable trackpoint and trackpad in bios，first when boot in mac os ,trackpoint and trackpad work fine. But they stops suddenly after running for a few minutes. 

If I disable trackpoint in bios, the trackpad work fine forever.

Env：
machine：thinkpad 13
mac os  ：monterey(12.4)
touchpad：elan touchpad(click pad)
io interface：ps2m 
driver：https://github.com/acidanthera/VoodooPS2 （2.2.8）

**Comment by goomoon** [comment] 2022-06-04 05:20
can you help me to fix it ,think you

**Comment by timothy-ha** [comment] 2022-07-10 03:51
I have a similar issue with my Thinkpad Yoga 370 with the Elan Trackpad as well.  The issue goes away if I disable the trackpoint but somewhat defeats the purpose of hackintoshing a ThinkPad.

**Comment by vit9696** [comment] 2022-08-01 14:40
Sounds like a duplicate of https://github.com/acidanthera/bugtracker/issues/1579.

**Closed by vit9696** 2022-08-01 14:40 UTC
Labels: project:ps2
