### ISSUE TITLE
Keyboard not working in boot picker after Opt with PollAppleHotKeys=true 

### ISSUE THREAD

**Issue by vandroiy2013** [acidanthera/bugtracker#485] opened 2019-09-09 09:33 UTC
This problem occurs on Gigabyte GA-Z370M-DS3H when ShowPicker=false and PollAppleHotKeys=true after pressing Opt button to reveal Boot Picker. 
Can't drop timer, can't choose OS. 
Tried with AppleGenericInput and with UsbKbDxe.

**Comment by maddie** [comment] 2019-10-31 08:44
Happens on my Asus ROG Strix Z370-F too, had to turn it off to make keyboard work in picker again.

**Comment by DbArl** [comment] 2019-12-20 17:26
> This problem occurs on Gigabyte GA-Z370M-DS3H when ShowPicker=false and PollAppleHotKeys=true after pressing Opt button to reveal Boot Picker.
> Can't drop timer, can't choose OS.
> Tried with AppleGenericInput and with UsbKbDxe.

It‘s seems not working when you hold the option, please try press option several times. This  method works for me. But I think it's not enough Macintosh.

**Comment by gkankanh** [comment] 2019-12-22 23:39
Reproducible on GB X570 AORUS PRO WIFI MB as well.

**Comment by vit9696** [comment] 2020-01-11 01:13
Assume fixed in master.

**Closed by vit9696** 2020-01-11 01:13 UTC
Labels: bug, priority:normal, project:oc
