### ISSUE TITLE
OcSupportPkg [IA32]: 64 bit operations should be done with explicit functions

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#640] opened 2020-01-09 11:45 UTC
```
OcGuardLib.lib(BitOverflow.obj) : error LNK2001: unresolved external symbol __allmul
OcMemoryLib.lib(VirtualMemory.obj) : error LNK2001: unresolved external symbol __allmul
OcAppleRamDiskLib.lib(OcAppleRamDiskLib.obj) : error LNK2001: unresolved external symbol __allshl
OcCryptoLib.lib(BigNumPrimitives.obj) : error LNK2001: unresolved external symbol __allshl
OcCryptoLib.lib(Sha2.obj) : error LNK2001: unresolved external symbol __allshl
OcGuardLib.lib(BitOverflow.obj) : error LNK2001: unresolved external symbol __allshl
OcCpuLib.lib(OcCpuLib.obj) : error LNK2001: unresolved external symbol __allshl
OcMemoryLib.lib(VirtualMemory.obj) : error LNK2001: unresolved external symbol __allshl
OcMemoryLib.lib(MemoryMap.obj) : error LNK2001: unresolved external symbol __allshl
OcAppleRamDiskLib.lib(OcAppleRamDiskLib.obj) : error LNK2001: unresolved external symbol __aullshr
OcCryptoLib.lib(Sha2.obj) : error LNK2001: unresolved external symbol __aullshr
OcCryptoLib.lib(Sha1.obj) : error LNK2001: unresolved external symbol __aullshr
OcCryptoLib.lib(Md5.obj) : error LNK2001: unresolved external symbol __aullshr
OcGuardLib.lib(BitOverflow.obj) : error LNK2001: unresolved external symbol __aullshr
OcCpuLib.lib(OcCpuLib.obj) : error LNK2001: unresolved external symbol __aullshr
OcMemoryLib.lib(VirtualMemory.obj) : error LNK2001: unresolved external symbol __aullshr
OcMemoryLib.lib(MemoryMap.obj) : error LNK2001: unresolved external symbol __aullshr
```

**Comment by vit9696** [comment] 2020-01-09 12:05
Please provide an initial diff resolving these issues as we cannot reproduce them on our machines.

**Comment by nms42** [comment] 2020-01-09 15:44
Just a few attached. The rest of issues are hard ones. )-;
[some.diff.txt](https://github.com/acidanthera/bugtracker/files/4041187/some.diff.txt)

**Comment by vit9696** [comment] 2020-01-09 16:10
Thanks, closing in favour of #635.

**Closed by vit9696** 2020-01-09 16:10 UTC
Labels: enhancement, priority:low, project:oc
