### ISSUE TITLE
[VoodooPS2] I can't scan keycodes of Fn shortcuts for (Fn + F8...)

### ISSUE THREAD

**Issue by jfrostbite** [acidanthera/bugtracker#872] opened 2020-04-25 02:04 UTC
Hi,everybody
I have a trouble for my KeyBoard, such as title, I have LogScanCodes to 1 and can't scan keycodes of Fn shortcuts for (Fn + F8...Fn + F9),them for My brightness levels ,but I can't scan it's key codes, it's no responding, I don't know what is the problem, I need your help, Thx.

**Comment by armenio** [comment] 2020-04-25 03:11
You can use ioio to log scan codes.
ioio -s ApplePS2Keyboard LogScanCodes 1
https://github.com/RehabMan/OS-X-ioio

And use ACPIDebug to debug n determine your EC Queries
https://github.com/RehabMan/OS-X-ACPI-Debug

**Comment by jfrostbite** [comment] 2020-04-25 05:06
> You can use ioio to log scan codes.
> ioio -s ApplePS2Keyboard LogScanCodes 1
> https://github.com/RehabMan/OS-X-ioio
> 
> And use ACPIDebug to debug n determine your EC Queries
> https://github.com/RehabMan/OS-X-ACPI-Debug

Thx, I do it, but

**Comment by vit9696** [comment] 2020-04-25 12:39
Some hardware has functional keys routed through EC or similar device instead of normal PS/2 controller. You usually need to make ACPI changes for this to work (take a key press from the device and simulate a PS2 event). Since this is not a support forum and since our PS2 driver gets no keys, I am closing this as not a bug.

**Closed by vit9696** 2020-04-25 12:40 UTC
Labels: project:ps2

**Comment by mishurov** [comment] 2022-10-26 17:07
@vit9696 the extension doesn't log anything anywhere anymore: I tried the debug version, tried `ioio`, tried to compile with `printf` and `os_log`, tried to set `LogScanCodes` in the kext's Info.plist : nothing.
