### ISSUE TITLE
OcSupportPkg/Library/OcCpuLib/OcCpuLib.c:39:10: fatal error: 'Register/Msr/SandyBridgeMsr.h' file not found

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#451] opened 2019-08-10 08:43 UTC
Same problem with vs2019ce:

OcSupportPkg\Library\OcCpuLib\OcCpuLib.c(39): fatal error C1083: Cannot open include file: 'Register/Msr/SandyBridgeMsr.h': No such file or directory

**Comment by vit9696** [comment] 2019-08-10 08:44
Is [correct](https://github.com/acidanthera/audk) EDK II version being used?

**Comment by nms42** [comment] 2019-08-10 08:46
Original one.
There is the only file

Vacuum:GIT nms$ find . -name SandyBridge\*.h
./edk2/MdePkg/Include/Register/Intel/Msr/SandyBridgeMsr.h
Vacuum:GIT nms$

**Comment by nms42** [comment] 2019-08-10 08:47
I mean tianocore edk2 one.

**Comment by vit9696** [comment] 2019-08-10 08:54
Unstable development edk2 versions are not supported as specified in the [documentation](https://github.com/acidanthera/OpenCorePkg/blob/e611445/Docs/Configuration.tex#L509-L515). We prefer not to use bleeding edge library sets, as they usually contain numerous bugs. 

Currently supported version is [edk2-stable201905](https://github.com/tianocore/edk2/tree/edk2-stable201905), which is essentially the most recent EDK II stable tag to date. For simplicitly it is also available in [audk](https://github.com/acidanthera/audk) master tree.

When times comes, we will update to a newer stable tag and fixed up the header includes. For now, please do refrain breaking workflow to everyone involved. Closing as not a bug.

**Closed by vit9696** 2019-08-10 08:54 UTC

**Comment by al3xtjames** [comment] 2019-08-30 22:00
[edk2-stable201908][1] was published today, I guess this could be done now (along with updating audk).

[1]: https://github.com/tianocore/edk2/releases/tag/edk2-stable201908

**Comment by vit9696** [comment] 2019-08-31 08:37
Done.
