### ISSUE TITLE
Laptop with 4K display still can't work at 60hz with latest WhateverGreen

### ISSUE THREAD

**Issue by Pinming** [acidanthera/bugtracker#1377] opened 2020-12-18 07:35 UTC
For Dell Inspiron 7590 (with SHP14C7 display) with the latest WhateverGreen (IGFX: Add max pixel clock override submodule), I added the property `enable-max-pixel-clock-override` and remove the EDID in `config.plist`, but it still work at 4k @ 48Hz instead of 60Hz. 

When I attempt to set the refresh rate in System Preference, I found the selection is blank.
![image](https://user-images.githubusercontent.com/30550234/102586358-f9d50180-4144-11eb-95b8-2f609773f303.png)

In according to (https://github.com/acidanthera/WhateverGreen/pull/41), I think something about this monitor is different from most of monitors, although this problem seems that doesn't relate to maximum link rate. 

Hopefully we can find a solution. Thanks!

**Comment by M69W** [comment] 2020-12-18 09:59
https://github.com/xxxzc/xps15-9570-macos/releases/tag/201218

try it.
good luck.

**Comment by vit9696** [comment] 2020-12-18 10:01
Sounds like a configuration issue. Closing.

**Closed by vit9696** 2020-12-18 10:01 UTC
Labels: project:green

**Comment by Pinming** [comment] 2020-12-18 10:16
> https://github.com/xxxzc/xps15-9570-macos/releases/tag/201218
> 
> try it.
> good luck.

Thanks but it didn't work after removing `enable-hdmi20`.

**Comment by Pinming** [comment] 2020-12-18 10:17
> Sounds like a configuration issue. Closing.

I think it is not a configuration issue probably.
Maybe should I print the log to find the reason? Which log is needed?

**Comment by al3xtjames** [comment] 2020-12-20 00:11
If you think it isn't a configuration issue, paste the contents of the IOFBTimingRange property under AppleIntelFramebuffer@N (where N corresponds to framebuffer for your internal display).

**Comment by Pinming** [comment] 2020-12-20 13:43
> If you think it isn't a configuration issue, paste the contents of the IOFBTimingRange property under AppleIntelFramebuffer@N (where N corresponds to framebuffer for your internal display; this is usually 0). You should also post a debug log (install DEBUG binaries of Lilu & WhateverGreen, add `-liludbgall liludump=60` boot args, and upload /var/log/Lilu_x.x.x.txt).

![image](https://user-images.githubusercontent.com/30550234/102713940-9561a000-4306-11eb-933a-6833eec7a634.png)
[Lilu_1.5.0_20.3.txt](https://github.com/acidanthera/bugtracker/files/5720987/Lilu_1.5.0_20.3.txt)
Thank you!

**Comment by al3xtjames** [comment] 2020-12-20 21:33
maxPixelClock in IOFBTimingRange is 675000000 Hz, so `-igfxmpc` succeeded. This should be more than enough for 4K60. The presence of the 48 Hz refresh rate is also strange, so post your stock EDID.

If you have 10.15 installed, you could compare `-cdfon` and `-igfxmpc`.

**Comment by Pinming** [comment] 2020-12-21 02:52
> maxPixelClock in IOFBTimingRange is 675000000 Hz, so `-igfxmpc` succeeded. This should be more than enough for 4K60. The presence of the 48 Hz refresh rate is also strange, so post your stock EDID.
> 
> If you have 10.15 installed, you could compare `-cdfon` and `-igfxmpc`.

Stock EDID of SHP14C7:
```
00FFFFFFFFFFFF004D10C71400000000161D0104B52213780EDF50A35435B5260F5054000000010101010101010101010101010101014DD000A0F0703E803020350058C210000018A4A600A0F0703E803020350058C210000018000000FE005454334458804C513135364431000000000002410332001200000B010A20200138
```
On 10.15, It could boot normal when injected `-cdfon` (or enabled `enable-hdmi20`). But when enabled `-igfxmpc`, it also display at 48hz.

**Comment by Xhichn** [comment] 2020-12-21 13:58
The same problem also occurs on my Lenovo m73, with i3-4350t, using a DP 1.4 port. I try both `-igfxmpc` and `-cdfon` on macOS Catalina and when **only** using `-cdfon` the screen can work on 4k@60Hz. I found that the `IOFBTimingRange` of using `-igfxmpc` is the same as using `-cdfon` 's, but the screen just works on 4k@30Hz actually.

**Comment by al3xtjames** [comment] 2020-12-21 21:18
@Pinming Hmm, it looks like it is common for newer panels to include a timing block with a 48 Hz refresh rate (SHP14D0 on XPS 9500 also does this). I was able to reproduce your issue with the SHP14C7 EDID. I think CoreDisplay.framework is rejecting some other field in the timing data.

@Xhichn You are using WhateverGreen 1.4.5, which does not support `-igfxmpc`.

**Comment by zhen-zen** [comment] 2020-12-21 21:49
Mine EDID has single 4K60 mode and prior to your patch, I have to manually add a 48Hz option in Big Sur. Now I have removed the EDID patch and the panel is recognized. Maybe the second descriptor should be removed to force 60Hz.

And in userspace, using `CGDisplayCopyAllDisplayModes` could find the 3840*2160 resolution, but the refresh rate returns 0 for all modes. However, it was recognized as 48Hz before with patched EDID.

**Comment by Xhichn** [comment] 2020-12-22 00:07
> @Xhichn You are using WhateverGreen 1.4.5, which does not support `-igfxmpc`.

Uh, it's my mistake and I am sorry to brother you with my carelessness. Now I complie WhateverGreen from source code and it works! Thanks for your hardworking!

**Comment by al3xtjames** [comment] 2020-12-22 00:32
@Pinming Hmm, for some reason I can't reproduce 48 Hz limit issue with the SHP14C7 EDID (unlike what I said earlier). Perhaps you could try manually removing the 48 Hz timing block in your EDID like @zhen-zen suggested.

**Comment by Pinming** [comment] 2020-12-22 04:42
> @Pinming Hmm, for some reason I can't reproduce 48 Hz limit issue with the SHP14C7 EDID (unlike what I said earlier). Perhaps you could try manually removing the 48 Hz timing block in your EDID like @zhen-zen suggested.

After I injected EDID of AUO41EB (another 4k monitor of Dell Inspiron 7590), it can display at 4K60. Big thanks to your contribution! 

However, is there any method to fix this problem without injecting other monitor's EDID?

**Comment by al3xtjames** [comment] 2020-12-22 05:47
Good to hear that. Could you post the AUO41EB EDID? My guess is that CheckTimingWithRange is rejecting the 60 Hz timing in your SHP14C7 EDID (as 4K60 works with `-cdfon`, which makes CheckTimingWithRange to always return 0).

**Comment by Pinming** [comment] 2020-12-22 07:04
AUO41EB
```
00ffffffffffff0006afeb4100000000221c0104b522137802af95a65435b5260f50540000000101010101010101010101010101010152d000a0f0703e803020350058c11000001a52d000a0f07068823020350025a51000001a000000fe00375837314880423135365a414e0000000000054122b2001200000b010a2020
0139
```

**Comment by EugeneKey** [comment] 2020-12-24 06:22
Someone might find it useful:
I was using version 1.4.6 with enable-max-pixel-clock-override however this did not work for my Dell 7559
After that I added an EDID patch which I generated in Hackintool and now it works as 4k@60Hz

**Comment by fabiannagel** [comment] 2021-01-06 16:00
@EugeneKey I'm trying to accomplish the same thing with `-igfxmpc`, only for an external 4K DisplayPort monitor. Could you help me out and tell me the individual steps you followed? My patch has no effect at all, sadly. Thanks!

**Comment by al3xtjames** [comment] 2021-01-08 22:29
> Someone might find it useful:
> I was using version 1.4.6 with enable-max-pixel-clock-override however this did not work for my Dell 7559
> After that I added an EDID patch which I generated in Hackintool and now it works as 4k@60Hz

Could you post your original and modified EDIDs?
