### ISSUE TITLE
Speed of logging to file is random

### ISSUE THREAD

**Issue by joevt** [acidanthera/bugtracker#2074] opened 2022-07-06 04:17 UTC
I am currently using a Mac mini 2018 with latest OpenCore 0.8.2 source code e733af273708aa56eacb4afbd46cfbf8b63ed8ce

If I have logging to file enabled (`Target` |= 0x40) then the log statements from OpenCore appear too slowly, sometimes exceeding 500 ms per line. The rate is consistent per boot but each boot may have a different rate. If the rate of debug output is too slow and booting to OC menu takes longer than 5 minutes then the Mac restarts (because of EFI watchdog timer?). When it restarts, the debug output rate is usually lower (e.g. 100 ms or 70 ms per line) and OpenCore successfully boots.

Without logging to file, each line is usually under 10 ms.

# Examples:
### 450 ms:
```
02:597 00:445 OC: Boot timestamp - 2022.07.05 06:18:59
03:496 00:448 OCCPU: MP services threads 4 (enabled 4) - Success
03:947 00:451 OCCPU: MP services Pkg 1 Cores 4 Threads 1 - Success
04:399 00:452 OCCPU: Found Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
```
### 480 ms:
```
01:436 00:492 OC: Boot timestamp - 2022.07.04 05:16:52
01:920 00:483 OCCPU: MP services threads 4 (enabled 4) - Success
02:405 00:485 OCCPU: MP services Pkg 1 Cores 4 Threads 1 - Success
02:889 00:484 OCCPU: Found Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
```
### 70 ms:
```
00:318 00:075 OC: Boot timestamp - 2022.07.04 05:22:15
00:387 00:069 OCCPU: MP services threads 4 (enabled 4) - Success
00:460 00:072 OCCPU: MP services Pkg 1 Cores 4 Threads 1 - Success
00:531 00:071 OCCPU: Found Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
```
### 100 ms:
```
00:420 00:112 OC: Boot timestamp - 2022.07.04 10:25:07
00:527 00:107 OCCPU: MP services threads 4 (enabled 4) - Success
00:636 00:108 OCCPU: MP services Pkg 1 Cores 4 Threads 1 - Success
00:746 00:110 OCCPU: Found Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
```
### 10 ms:
```
00:378 00:002 OC: Boot timestamp - 2022.07.05 05:59:08
00:386 00:002 OCCPU: MP services threads 4 (enabled 4) - Success
00:393 00:006 OCCPU: MP services Pkg 1 Cores 4 Threads 1 - Success
00:399 00:006 OCCPU: Found Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
```

In all cases, `DisplayDelay` is 0.

I timed each line in `InternalLogAddEntry` to find which took the longest time.
```C++
  UINT64  LongestTime = 0;
  UINT32  LongestLine = 0;
  UINT64  TscLast     = 0;

#define TIMING(l) \
	do { \
		UINT64 CurrentTsc = GetTiming0 (OcLog); \
		UINT64 duration = CurrentTsc - (TscLast ? TscLast : CurrentTsc); \
		TscLast = CurrentTsc; \
		if (duration > LongestTime) { \
			LongestTime = duration; \
			LongestLine = l; \
		} \
	} while (0)

	TIMING(__LINE__);
```

The result was this line:
```
      	TIMING(__LINE__);
        OcSetFileData (
          OcLog->FileSystem,
          OcLog->FilePath,
          Private->AsciiBuffer,
          (UINT32)Private->AsciiBufferSize
          );
        TIMING(__LINE__);
```

I suppose the next step might be to find the line in `OcSetFileData` that takes the most time. Hopefully the problem can be found in OpenCore code where it can be fixed rather than in Apple UEFI. I'll follow up if I find something. I am reporting the issue to see if anyone has a suggestion.

### Other info that is probably not relevant to this issue but may be of interest:
I have connected a Sonnet Echo Express III-D with PCIe serial card and have setup serial debug output from OpenCore. I am trying to determine why my patches to displaypolicyd (using my fork of Lilu/WhateverGreen) sometimes cause macOS Monterey 12.4 boot to hang. I am unable to get xnu to do kprintf to the serial card with the Mac mini 2018 like I could with my iMac 27 inch 2013. The OpenCore log says it patched xnu successfully.

**Comment by mikebeaton** [comment] 2022-07-07 14:29
Please keep separate issues separate. If you wish to raise the serial kprintf issue, please move it to separate issue.

Thank you for careful reporting of logging file speed issue. It is known that the logging is particularly slow - in order to be safe on some particularly broken FAT drivers on older machines. It is not especially known that logging is both slow and variable in speed, as you have shown. Issue being examined.

**Comment by mikebeaton** [comment] 2022-07-07 14:33
Actually, I would just mention that I do know, from my own experience, that logging is extremely slow when the ESP volume is full, so that there is no space to write the log. Perhaps you could double-check as to whether or not that is when you are getting the same issue.

**Comment by joevt** [comment] 2022-07-07 14:53
I don't think it's full. Besides, it doesn't make sense for it to be slow for one boot (e.g. 480 ms per line) and faster the next boot (e.g. 70 ms per line) if I haven't changed any files between boots.

Can you check a log file to see what time you get between each line starting from `OC: Boot timestamp`?

**Comment by mikebeaton** [comment] 2022-07-07 16:32
Yes, I am seeing around a factor of 4 change in delays between lines between different boots, for no apparent reason, as you are reporting; ~7ms->~28ms, consistently one value on one boot, and another on another boot; so much faster than yours, but a surprising variation. Unfortunately, I suspect it remains something out of our control, to do with firmware FAT drivers.

I'm not yet sure whether there's any change which preserves the structure and approach of the file logging system (which is designed to be safe, not necessarily fast) while avoiding this issue, however.

**Comment by mikebeaton** [comment] 2022-07-10 06:23
@joevt - Thanks for the report. Addressed in https://github.com/acidanthera/OpenCorePkg/commit/279f054df51592289b921ccbd05dacebb25508ac .

Weirdly, on a Dell hack here, the speed of logging is indeed variable (as you reported) and switching to 'fast' logging (i.e. normal file writes, instead of the required (on some firmware) safe approach of rewriting the whole file), is both ~ 10x faster, and less variable; but on an MBP10,2, 'fast' and 'slow' logging are both more or less exactly the same speed, and not variable.

Still, for the machines where this does make a significant difference, it's been deemed worth adding this as an option.

I would be interested to hear you report as to whether using the newly added unsafe logging bit makes logging (hopefully) faster and less variable, for you.

**Closed by mikebeaton** 2022-07-10 06:23 UTC

**Comment by mikebeaton** [comment] 2022-07-11 03:35
Hi @joevt,

I could just add, I appreciate that the commit above does not fix the underlying issue of randomly variable write speed with each boot, which you reported and I've agreed that I'm seeing too. Since many firmware implementations share much of the same (EDK-II) code, it currently seems almost certain that this is an issue in the firmware driver (i.e. in EDK-II FAT32 code; and that the Apple firmware I checked is using it's own, different code). It's slightly surprising behaviour (consistently faster, or slower, on different boots), but there's no critical problem here, so any further investigation is likely to proceed at low priority.

If you have time to proceed your timing investigations further, to prove - or otherwise - that the process taking the random, fixed-per-boot additional time is within the call to file write in the driver, please do so; it would indeed be useful to have it confirmed, or otherwise.

**Comment by joevt** [comment] 2022-07-12 12:10
I timed `OcSetFileData` and found that `Fs->Close (File);` took ≈80% of the time.
The next slowest line is the one before that `Status      = File->Write (File, &WrittenSize, (VOID *)Buffer);`
All the other lines take no time in comparison.

The times are ≈130 ms per line, so OpenCore is reaching the bootpicker before the 5 minute deadline. I'm not getting the 480 ms timing that I got before. Maybe because I removed some stuff from the EFI partition.

I did get ≈80 ms per line during one boot and ≈110 ms during another boot so it does appear to still be random.

Here is the timing code:
```C
#include <Library/OcCpuLib.h>
#include <Library/PrintLib.h>

STATIC
UINT64
GetTiming ()
{
  UINT64 CurrentTsc = 0;
  if (TscFrequency == 0) {
    TscFrequency = OcGetTSCFrequency ();
  }
  if (TscFrequency != 0) {
    CurrentTsc = AsmReadTsc ();
  }
  return CurrentTsc;
}

STATIC
VOID TIMING (
	UINT32 l)
{
	UINT64 CurrentTsc = GetTiming ();
	UINT64 duration = CurrentTsc - (TscLast ? TscLast : CurrentTsc);
	TscLast = CurrentTsc;
	if (duration > LongestTime[0]) {
		LongestTime[3] = LongestTime[2];
		LongestTime[2] = LongestTime[1];
		LongestTime[1] = LongestTime[0];
		LongestTime[0] = duration;
		LongestLine[3] = LongestLine[2];
		LongestLine[2] = LongestLine[1];
		LongestLine[1] = LongestLine[0];
		LongestLine[0] = l;
	}
}

STATIC
VOID ResetTiming ()
{
	LongestTime[0] = LongestTime[1] = LongestTime[2] = LongestTime[3] = 0;
	LongestLine[0] = LongestLine[1] = LongestLine[2] = LongestLine[3] = 0;
	TscLast     = 0;
	TIMING(__LINE__);
}

STATIC
VOID DumpTiming ()
{
	CHAR16 UnicodeLineBuffer[100];
	UnicodeSPrint (
		UnicodeLineBuffer,
		sizeof (UnicodeLineBuffer),
		L" (%d:%lld,%d:%lld,%d:%lld,%d:%lld) ",
		LongestLine[0], DivU64x64Remainder (MultU64x32 (LongestTime[0], 1000), TscFrequency, NULL),
		LongestLine[1], DivU64x64Remainder (MultU64x32 (LongestTime[1], 1000), TscFrequency, NULL),
		LongestLine[2], DivU64x64Remainder (MultU64x32 (LongestTime[2], 1000), TscFrequency, NULL),
		LongestLine[3], DivU64x64Remainder (MultU64x32 (LongestTime[3], 1000), TscFrequency, NULL)
		);
	gST->ConOut->OutputString (gST->ConOut, UnicodeLineBuffer);
}
```

With the above code, put a `ResetTiming();` at the top of the function, a `DumpTiming();` at the end of the function, and a bunch of `TIMING(__LINE__);` around all the important lines like this:

```C
{
	ResetTiming();
	...
	TIMING(__LINE__);
	Fs->Close (File);
	TIMING(__LINE__);
	...
	DumpTiming();
	return Status;
}
```

If your fast log doesn't close the file after every line then it should be much faster. I'll test it later today.

**Comment by mikebeaton** [comment] 2022-07-12 12:19
The reason close is slow rather than write I believe is likely to be simply an issue of flushing - most of the write isn't actually flushed until the close.

Might bear repeating (and this is by design) that the slow logging writes the _entire_ 256kB contents of the log file (zeros and all) on every line. Why? Because allowing a file to incrementally increase in size, as it normally would when writing it, completely trashes the entire ESP partition on some early, broken UEFI FAT32 drivers.

Would be happy to receive results on the faster logging.

**Comment by joevt** [comment] 2022-07-13 04:35
I removed my timing code and recorded some tests using the time for the first line of the log that looks like this:
`OCCPU: MP services threads 4 (enabled 4) - Success`

Results (in ms):
Logging to file safe: 86, 112, 70, 103, 57

Logging to file unsafe: 33, 34, 83, 33, 33, 83, 33

So unsafe mode is still random like safe mode but it is faster. The speed is still consistent for the boot (meaning the speed of that early line is similar to the speed of the subsequent lines).

The drive containing the EFI partition is external USB-C 10 Gbps NVMe which may be slower than an internal drive.

I backed up the EFI partition before testing. Disk Utility detected no problems after testing. And there were no diffs between the backup and current contents of the partition (except the new log files).

The log files generated by the unsafe mode do not include padding for 256 KiB size which is nice. The size of the new log files are ≈122 KB instead of 262 KB.

Is the EFI watchdog supposed to cause a restart if the OpenCore bootpicker is shown onscreen for more than 5 minutes? I think so. Just want to confirm.

**Comment by joevt** [comment] 2022-07-13 05:09
Also, my results are with serial port output enabled. I'm sure output to file without serial output would be faster.

**Comment by mikebeaton** [comment] 2022-07-13 05:14
That's pretty much matching what I'm getting - except my 'unsafe' logs at 3-4ms are so fast that I'm not really seeing the variation. Thanks for the research! I think we'll leave it there. There's obviously something intriguing going on in the FAT32 driver, but it's not high on the priority list.

**Comment by mikebeaton** [comment] 2022-07-13 05:15
> Is the EFI watchdog supposed to cause a restart if the OpenCore bootpicker is shown onscreen for more than 5 minutes? I think so. Just want to confirm.

Yes, of course. Unless you disable it using OpenCore `DisableWatchdog`.

**Comment by joevt** [comment] 2022-07-13 05:46
Disabling serial output gets these unsafe mode times (different boots):
77, 29, 29
which seems to indicate that serial doesn't add a lot of time (except for really really long lines of text)
Maybe Thunderbolt -> USB is slow in EFI.
