### ISSUE TITLE
Allow prelinked property tree modifications

### ISSUE THREAD

**Issue by Download-Fritz** [acidanthera/bugtracker#394] opened 2019-06-19 13:29 UTC
We might want to modify the existing prelinked property tree, such as to modify device driver matching properties to allow loading on officially unsupported hardware. It is unclear whether there are not preferable ways to satisfy all use-cases users have.

Modification should likely be based off the DOM interface used for prelinking injected KEXTs. We definitely want to replace contents, however adding and removing might have use-cases as well. While adding and setting whole keys could be identical syntactically for most elements, arrays are a special case, as one might want to add an array member without removing the others, and there is no key to individually uniquely identify them.

**Comment by vit9696** [comment] 2019-06-19 15:48
I observed the use cases of plist-only patches, and they are not justified well enough for us to care. Most of these patches are caused by the lack of knowledge and implement inadequate hacks that mess with macOS design for no reason. For example:

- Patching IOProbeScore in kexts, like [this](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/ee1cbe2/config_patches.plist#L56).
    - If Apple kexts have higher priority than VoodooI2C or anything alike, then VoodooI2C should just have higher probe score. CC @kprinssu 
    - If Apple kexts do not need to be loaded at all, we support blocking kexts from loading via `config.plist` `Block` section.
- Patching IONameMatch in kexts, like [this](https://www.tonymacx86.com/threads/clover-patches-for-working-pci-sd-card-reader-work-in-progress.210169).
    - Injecting `device-id` via `DeviceProperties` solves this problem, and the patch is merely inadequate.
    - For Airport devices we specially have AirportBrcmFixup.kext.
    - For more complex issues the approach is described in [I/O Kit Fundamentals - Matching](https://developer.apple.com/library/archive/documentation/DeviceDrivers/Conceptual/IOKitFundamentals/Matching/Matching.html#//apple_ref/doc/uid/TP0000015-TP9). One can always build a plist-only kext for matching one device onto another and/or override the properties. For instance, that is how USB power injection works.
- Making NVIDIA Web Drivers load on unsupported macOS version
    - WhateverGreen.kext does the change automatically, and unlike this hack it does not require config changes after os update in the first place.
- Rebinding F1/F2 buttons on Apple USB keyboard to make some [userspace tools handle brightness](https://github.com/Bensge/NativeDisplayBrightness/releases)
    - If this problem is in userspace, it is just the tool that needs needs to be updated, [like this](https://github.com/KAMIKAZEUA/NativeDisplayBrightness)
    - There also are ways to rebind buttons for Apple keyboards, e.g. [FunctionFlip](http://kevingessner.com/software/functionflip)
    - You can create a plist-only kext just as usual...

To summarise, I simply do not know whether there are more bizarre attempts to implement mad hacks to nonexistent problems, however, it comes without saying that people do that just because they can.

Proper implementation of plist patching in OpenCore done with semantic analysis of nodes, and not just mere find hex, replace hex, requires thought and proper architecture just as Fritz mentioned. Without the use case I will not bother implementing this.

Furthermore, I will not let this to land until somebody gives a justified design and architecture either. VMware guys already patch prelinkedkernel plist with find-and-replace hex methods, and their thoughtlessly designed code borked the Catalina kernel, and will cost people a lot of money this year: https://communities.vmware.com/thread/611961. For the good we will not follow.

Closing.

**Closed by vit9696** 2019-06-19 15:48 UTC
Labels: enhancement, priority:low, project:oc
