### ISSUE TITLE
VoodooPS2 trackpad physical buttons do not work on Lenovo V110-15ISK

### ISSUE THREAD

**Issue by ciccio-90** [acidanthera/bugtracker#2087] opened 2022-07-15 17:26 UTC
You can find my EFI folder here: 
https://github.com/ciccio-90/Lenovo_V110-15ISK_Hackintosh_OpenCore_macOS_Monterey
[MacBook Pro.ioreg.zip](https://github.com/acidanthera/bugtracker/files/9122825/MacBook.Pro.ioreg.zip)

Moreover I attached my IOReg file.

**Comment by Edwardwich** [comment] 2022-07-15 23:48
![Screenshot 2022-07-16 at 4 17 11 AM](https://user-images.githubusercontent.com/35195176/179325186-7c249da0-7b68-4983-9019-19c028b01afe.png)
add VoodooRMI.kext
like this
![Screenshot 2022-07-16 at 4 18 40 AM](https://user-images.githubusercontent.com/35195176/179325248-c1c1232c-d0c7-4b12-80a8-320e5ce15a9c.png)

**Comment by ciccio-90** [comment] 2022-07-16 08:57
After adding the kexts you suggested (VoodooRMI.kext and VoodooSMBus.kext) into the kexts folder and after
modifying the config.plist as below:
...
<dict>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>VoodooPS2Controller.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VoodooPS2Controller</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
			<dict>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Mouse.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VoodooPS2Mouse</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
			<dict>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Keyboard.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VoodooPS2Keyboard</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
			<dict>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Trackpad.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VoodooPS2Trackpad</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>

			<dict>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>VoodooPS2Controller.kext/Contents/PlugIns/VoodooInput.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<false/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VoodooInput</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
			<dict>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>VoodooRMI.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VoodooRMI</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
			<dict>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>VoodooRMI.kext/Contents/PlugIns/VoodooInput.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VoodooInput</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
			<dict>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>VoodooSMBus.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VoodooSMBus</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
			<dict>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>VoodooRMI.kext/Contents/PlugIns/RMISMBus.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/RMISMBus</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
...

 the trackpad no longer works.

**Comment by Edwardwich** [comment] 2022-07-16 09:01
> After adding the kexts you suggested (VoodooRMI.kext and VoodooSMBus.kext) into the kexts folder and after
> modifying the config.plist as below:
> 
>                        <dict>
> 				<key>Arch</key>
> 				<string>Any</string>
> 				<key>BundlePath</key>
> 				<string>VoodooPS2Controller.kext</string>
> 				<key>Comment</key>
> 				<string></string>
> 				<key>Enabled</key>
> 				<true/>
> 				<key>ExecutablePath</key>
> 				<string>Contents/MacOS/VoodooPS2Controller</string>
> 				<key>MaxKernel</key>
> 				<string></string>
> 				<key>MinKernel</key>
> 				<string></string>
> 				<key>PlistPath</key>
> 				<string>Contents/Info.plist</string>
> 			</dict>
> 			<dict>
> 				<key>Arch</key>
> 				<string>Any</string>
> 				<key>BundlePath</key>
> 				<string>VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Mouse.kext</string>
> 				<key>Comment</key>
> 				<string></string>
> 				<key>Enabled</key>
> 				<true/>
> 				<key>ExecutablePath</key>
> 				<string>Contents/MacOS/VoodooPS2Mouse</string>
> 				<key>MaxKernel</key>
> 				<string></string>
> 				<key>MinKernel</key>
> 				<string></string>
> 				<key>PlistPath</key>
> 				<string>Contents/Info.plist</string>
> 			</dict>
> 			<dict>
> 				<key>Arch</key>
> 				<string>Any</string>
> 				<key>BundlePath</key>
> 				<string>VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Keyboard.kext</string>
> 				<key>Comment</key>
> 				<string></string>
> 				<key>Enabled</key>
> 				<true/>
> 				<key>ExecutablePath</key>
> 				<string>Contents/MacOS/VoodooPS2Keyboard</string>
> 				<key>MaxKernel</key>
> 				<string></string>
> 				<key>MinKernel</key>
> 				<string></string>
> 				<key>PlistPath</key>
> 				<string>Contents/Info.plist</string>
> 			</dict>
> 			<dict>
> 				<key>Arch</key>
> 				<string>Any</string>
> 				<key>BundlePath</key>
> 				<string>VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Trackpad.kext</string>
> 				<key>Comment</key>
> 				<string></string>
> 				<key>Enabled</key>
> 				<true/>
> 				<key>ExecutablePath</key>
> 				<string>Contents/MacOS/VoodooPS2Trackpad</string>
> 				<key>MaxKernel</key>
> 				<string></string>
> 				<key>MinKernel</key>
> 				<string></string>
> 				<key>PlistPath</key>
> 				<string>Contents/Info.plist</string>
> 			</dict>
> 
> 			<dict>
> 				<key>Arch</key>
> 				<string>Any</string>
> 				<key>BundlePath</key>
> 				<string>VoodooPS2Controller.kext/Contents/PlugIns/VoodooInput.kext</string>
> 				<key>Comment</key>
> 				<string></string>
> 				<key>Enabled</key>
> 				<false/>
> 				<key>ExecutablePath</key>
> 				<string>Contents/MacOS/VoodooInput</string>
> 				<key>MaxKernel</key>
> 				<string></string>
> 				<key>MinKernel</key>
> 				<string></string>
> 				<key>PlistPath</key>
> 				<string>Contents/Info.plist</string>
> 			</dict>
> 			<dict>
> 				<key>Arch</key>
> 				<string>Any</string>
> 				<key>BundlePath</key>
> 				<string>VoodooRMI.kext</string>
> 				<key>Comment</key>
> 				<string></string>
> 				<key>Enabled</key>
> 				<true/>
> 				<key>ExecutablePath</key>
> 				<string>Contents/MacOS/VoodooRMI</string>
> 				<key>MaxKernel</key>
> 				<string></string>
> 				<key>MinKernel</key>
> 				<string></string>
> 				<key>PlistPath</key>
> 				<string>Contents/Info.plist</string>
> 			</dict>
> 			<dict>
> 				<key>Arch</key>
> 				<string>Any</string>
> 				<key>BundlePath</key>
> 				<string>VoodooRMI.kext/Contents/PlugIns/VoodooInput.kext</string>
> 				<key>Comment</key>
> 				<string></string>
> 				<key>Enabled</key>
> 				<true/>
> 				<key>ExecutablePath</key>
> 				<string>Contents/MacOS/VoodooInput</string>
> 				<key>MaxKernel</key>
> 				<string></string>
> 				<key>MinKernel</key>
> 				<string></string>
> 				<key>PlistPath</key>
> 				<string>Contents/Info.plist</string>
> 			</dict>
> 			<dict>
> 				<key>Arch</key>
> 				<string>Any</string>
> 				<key>BundlePath</key>
> 				<string>VoodooSMBus.kext</string>
> 				<key>Comment</key>
> 				<string></string>
> 				<key>Enabled</key>
> 				<true/>
> 				<key>ExecutablePath</key>
> 				<string>Contents/MacOS/VoodooSMBus</string>
> 				<key>MaxKernel</key>
> 				<string></string>
> 				<key>MinKernel</key>
> 				<string></string>
> 				<key>PlistPath</key>
> 				<string>Contents/Info.plist</string>
> 			</dict>
> 			<dict>
> 				<key>Arch</key>
> 				<string>Any</string>
> 				<key>BundlePath</key>
> 				<string>VoodooRMI.kext/Contents/PlugIns/RMISMBus.kext</string>
> 				<key>Comment</key>
> 				<string></string>
> 				<key>Enabled</key>
> 				<true/>
> 				<key>ExecutablePath</key>
> 				<string>Contents/MacOS/RMISMBus</string>
> 				<key>MaxKernel</key>
> 				<string></string>
> 				<key>MinKernel</key>
> 				<string></string>
> 				<key>PlistPath</key>
> 				<string>Contents/Info.plist</string>
> 			</dict>
> 
>  the trackpad no longer works.
> 
> 

Ioreg

**Comment by ciccio-90** [comment] 2022-07-16 09:02
[MacBook Pro.ioreg.zip](https://github.com/acidanthera/bugtracker/files/9125461/MacBook.Pro.ioreg.zip)

**Comment by Edwardwich** [comment] 2022-07-16 12:29
@ciccio-90 post efi

**Comment by Edwardwich** [comment] 2022-07-16 12:34
Arrange kernel like this

![Screenshot 2022-07-16 at 5 01 42 PM](https://user-images.githubusercontent.com/35195176/179355013-51d81e8e-cc9f-408e-b55a-72cc758df15d.png)
![Screenshot 2022-07-16 at 5 01 46 PM](https://user-images.githubusercontent.com/35195176/179355018-e706012c-7f34-4120-8dc1-9e9d6ea1f2e6.png)

**Comment by ciccio-90** [comment] 2022-07-16 13:48
Nothing to do, the trackpad still doesn't work.

**Comment by Edwardwich** [comment] 2022-07-16 16:43
> Nothing to do, the trackpad still doesn't work.
try this and send ioreg
[Lenovo_V110-15ISK_Hackintosh_OpenCore_macOS_Monterey-main.zip](https://github.com/acidanthera/bugtracker/files/9126212/Lenovo_V110-15ISK_Hackintosh_OpenCore_macOS_Monterey-main.zip)

**Comment by 559911** [comment] 2022-07-17 05:29
![WechatIMG308](https://user-images.githubusercontent.com/78580537/179385146-0d06e8ec-793c-49b7-a9e7-34f66ad723a0.jpeg)
My t460s after update to ventura these buttons not work.

**Comment by Edwardwich** [comment] 2022-07-17 06:29
@559911 update kext

**Comment by ciccio-90** [comment] 2022-07-17 10:55
@Edwardwich After using you EFI I’m having the following kernel panic and I cannot come back.

![Uploading F74F8F21-1964-4444-8520-BAF48E986CEF.jpeg…]()

**Comment by ciccio-90** [comment] 2022-07-17 11:43
@Edwardwich Same as previous after using your EFI.
[MacBook Pro.ioreg.zip](https://github.com/acidanthera/bugtracker/files/9127527/MacBook.Pro.ioreg.zip)

**Comment by Edwardwich** [comment] 2022-07-17 11:49
> > Nothing to do, the trackpad still doesn't work.
> > try this and send ioreg
> > [Lenovo_V110-15ISK_Hackintosh_OpenCore_macOS_Monterey-main.zip](https://github.com/acidanthera/bugtracker/files/9126212/Lenovo_V110-15ISK_Hackintosh_OpenCore_macOS_Monterey-main.zip)

its not booted?

**Comment by Edwardwich** [comment] 2022-07-17 11:54
ineed apci dump

**Comment by Edwardwich** [comment] 2022-07-17 12:04
https://dortania.github.io/Getting-Started-With-ACPI/Laptops/trackpad-methods/manual.html#checking-gpi0

**Comment by ciccio-90** [comment] 2022-07-17 12:09
What I should do?

**Comment by Edwardwich** [comment] 2022-07-17 12:51
> What I should do?
[EFI Debug OC 0.8.zip](https://github.com/acidanthera/bugtracker/files/9127648/EFI.Debug.OC.0.8.zip)
add to usb run and wait for end rest ans send system report hear

**Comment by ciccio-90** [comment] 2022-07-17 13:22
@Edwardwich Here you are!
[SysReport.zip](https://github.com/acidanthera/bugtracker/files/9127710/SysReport.zip)
[opencore-2022-07-17-131125.txt](https://github.com/acidanthera/bugtracker/files/9127711/opencore-2022-07-17-131125.txt)

**Comment by Edwardwich** [comment] 2022-07-17 13:43
[EFI.zip](https://github.com/acidanthera/bugtracker/files/9127744/EFI.zip)
if start send ioreg

**Comment by ciccio-90** [comment] 2022-07-17 13:54
@Edwardwich It starts but the trackpad does not work, anyway here you are the ioreg!
[MacBook Pro.ioreg.zip](https://github.com/acidanthera/bugtracker/files/9127783/MacBook.Pro.ioreg.zip)

**Comment by Edwardwich** [comment] 2022-07-17 14:12
@ciccio-90  battery work?

**Comment by Edwardwich** [comment] 2022-07-17 14:18
> @Edwardwich It starts but the trackpad does not work, anyway here you are the ioreg!
> [MacBook Pro.ioreg.zip](https://github.com/acidanthera/bugtracker/files/9127783/MacBook.Pro.ioreg.zip)
> 

Do you have windows ?

I want to see I2C or where he connected the trackpad

**Comment by ciccio-90** [comment] 2022-07-17 14:25
No, I don't have windows.

**Comment by Edwardwich** [comment] 2022-07-17 14:37
[EFI.zip](https://github.com/acidanthera/bugtracker/files/9127875/EFI.zip)
try this send ioerg

**Comment by ciccio-90** [comment] 2022-07-17 14:46
@Edwardwich Nothing also this time!
[MacBook Pro.ioreg.zip](https://github.com/acidanthera/bugtracker/files/9127901/MacBook.Pro.ioreg.zip)

**Comment by Edwardwich** [comment] 2022-07-17 14:48
RMI and I2C kext no work

**Comment by Edwardwich** [comment] 2022-07-17 14:51
> @Edwardwich Nothing also this time!
> [MacBook Pro.ioreg.zip](https://github.com/acidanthera/bugtracker/files/9127901/MacBook.Pro.ioreg.zip)
> 

I need windows for fix

**Comment by ciccio-90** [comment] 2022-07-17 14:55
I would not want to install windows and then have to install macOS again. Can a linux live distro help you?

**Comment by Edwardwich** [comment] 2022-07-17 14:57
hat is not support forum

you can't help it on bugtracker

**Comment by Edwardwich** [comment] 2022-07-17 15:00
https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/FORUMS.md

**Comment by ciccio-90** [comment] 2022-07-17 15:05
I have already tried to ask for help on the forums but without luck.
https://www.insanelymac.com/forum/topic/348796-voodoops2-trackpad-physical-buttons-dont-work/#comment-2765853

**Comment by vit9696** [comment] 2022-08-01 15:15
Sounds like a duplicate of https://github.com/acidanthera/bugtracker/issues/1192.

**Closed by vit9696** 2022-08-01 15:15 UTC
Labels: project:ps2
