### ISSUE TITLE
Incorrect frequency reading of Westmere CPU (formerly Nehalem-C)

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#622] opened 2019-12-29 15:22 UTC
I opened a separate issue as it relates to a separate processor type not AMD, but the debug logs are in [Issue#618](https://github.com/acidanthera/bugtracker/issues/618)
Plus we have the guidelines of the CPU frequency calculation by Intel in the [ADM manual](https://www.intel.com/content/www/us/en/architecture-and-technology/64-ia-32-architectures-software-developer-vol-3b-part-2-manual.html):
"18.18.3.2 For Intel® Processors Based on Microarchitecture Code Name Nehalem
The scalable bus frequency is encoded in the bit field MSR_PLATFORM_INFO[15:8] and the nominal TSC frequency can be determined by multiplying this number by a bus speed of 133.33 MHz."
whereas for:
"18.18.3.1   For Intel® Processors Based on Microarchitecture Code Name Sandy Bridge, Ivy Bridge, Haswell and Broadwell The scalable bus frequency is encoded in the bit field MSR_PLATFORM_INFO[15:8] and the nominal TSC frequency can be determined by multiplying this number by a bus speed of 100 MHz."

**Comment by startergo** [comment] 2019-12-30 22:05
It looks like Intel Processor identification utility from Windows improperly identifies the processors speed similar to OC:
`Current processor: 2
Active cores per processor: 6
Disabled cores per processor: 0
Processor Name: Intel(R) Xeon(R) X5690 CPU @ 3.47GHz
Type : 0
Family : 6
Model : 44
Stepping : 2
Revision: 31
Maximum CPUID Level: 11
L1 Instruction Cache: 6 x 32 KB
L1 Data Cache: 6 x 32 KB
L2 Cache: 6 x 256 KB
L3 Cache: 12 MB
Packaging: LGA1366
Expected Processor Frequency: 3.47 GHz
Reported Processor Frequency: 3.70 GHz
Expected System Bus Frequency: 133 MHz
Reported System Bus Frequency: 137 MHz
Number of processors in system: 2
Current processor: 1
Active cores per processor: 6
Disabled cores per processor: 0
Processor Name: Intel(R) Xeon(R) X5690 CPU @ 3.47GHz
Type : 0
Family : 6
Model : 44
Stepping : 2
Revision: 31
Maximum CPUID Level: 11
L1 Instruction Cache: 6 x 32 KB
L1 Data Cache: 6 x 32 KB
L2 Cache: 6 x 256 KB
L3 Cache: 12 MB
Packaging: LGA1366
Expected Processor Frequency: 3.47 GHz
Reported Processor Frequency: 3.69 GHz
Expected System Bus Frequency: 133 MHz
Reported System Bus Frequency: 129 MHz`

This detection has some similarities with the OC detection:
`00:000 00:000 OC: OpenCore is now loading (Vault: 0/0, Sign 0/0)... 
00:074 00:074 OC: Boot timestamp - 2019.12.24 03:29:49 
00:15100:076 OCCPU: Hypervisor: 0 
00:226 00:075 OCCPU: Found Intel(R) Xeon(R) CPU X5690 @ 3.47GHz 
00:313 00:086 OCCPU: Signature 206C2 Stepping 2 Model 2C Family 6 Type 0 ExtModel 2 ExtFamily 0 
00:390 00:076 OCCPU: Detected Apple Processor Type: 05 -> 0501 
00:465 00:074 OCCPU: Ratio Min 12 Max 26 Current 0 Turbo 28 28 27 27 
00:542 00:077 OCCPU: Timer address is 408 from LPC 
00:717 00:175 OCCPU: CPUFrequencyFromTSC 3458000769Hz 3458MHz 
00:792 00:075 OCCPU: CPUFrequency 3458000769Hz 3458MHz 
00:868 00:075 OCCPU: FSBFrequency 133000029Hz 133MHz 
00:943 00:074 OCCPU: Pkg 1 Cores 6 Threads 12`
OC detects incorrectly Current CPU ratio=0 (min12-max26) So the CPU power management is not working.  

HWINFO properly detects the current CPU idle speed at ratio 12:

`  | CPU ID: | 000206C2
-- | -- | --
  | CPU Brand Name: | Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
  | CPU Vendor: | GenuineIntel
  | CPU Stepping: | B1
  | CPU Code Name: | Westmere-EP
  | CPU Technology: | 32 nm
  | CPU S-Spec: | SLBVX
  | CPU Thermal Design Power (TDP): | 130.0 W
  | CPU Thermal Design Current (TDC): | 110.0 A
  | CPU Max. Case Temperature (Tcase_max): | 78.5 °C
  | CPU Max. Junction Temperature (Tj,max): | 101 °C
  | CPU Type: | Production Unit
  | CPU Platform: | Socket B1 (LGA1366 FC-LGA6)
  | Microcode Update Revision: | 1F
  |   |  
  | Number of CPU Cores: | 6
  | Number of Logical CPUs: | 12
  |   |  
[Operating Points]
  | CPU LFM (Minimum): | 1600.0 MHz = 12 x 133.3 MHz
  | CPU HFM (Base): | 3466.7 MHz = 26 x 133.3 MHz
  | CPU Turbo Max: | 3733.3 MHz = 28 x 133.3 MHz [Locked]
  | CPU Current: | 1596.1 MHz = 12 x 133.0 MHz
  |   |  
  | CPU Bus Type: | FSB (QDR)`

From within OSX normal boot without OC ioregistry:
`"processor-lapic" = 0x0
    | | |   "clock-frequency" = <00693bce>=3460000000
    | | |   "processor-number" = 0x0
    | | |   "timebase-frequency" = <00ca9a3b>=1000000000
    | | |   "processor-id" = 0x0
    | | |   "bus-frequency" = <ffffffff>
    | | |   "cpu-type" = <0105>
    | | |   "device_type" = <70726f636573736f7200>
    | | |   "name" = <4350553000>
    | | |   "processor-index" = 0x0`

Booting through OC ioregistry:
`"processor-lapic" = 0x0
    | | |   "clock-frequency" = <00c39dd0> =3500000000 
    | | |   "processor-number" = 0x0
    | | |   "timebase-frequency" = <00ca9a3b>=1000000000 
    | | |   "processor-id" = 0x0
    | | |   "bus-frequency" = <00e1f505> =1000000000 
    | | |   "cpu-type" = <0105>
    | | |   "device_type" = <70726f636573736f7200>
    | | |   "name" = <4350553000>
    | | |   "processor-index" = 0x0`

**Comment by vit9696** [comment] 2020-01-04 17:07
Hello,

> From within OSX normal boot without OC ioregistry

First of all, could you please clarify what does "OSX normal boot" mean? Is that a MacPro5,x or similar?

> OC detects incorrectly Current CPU ratio=0 (min12-max26)

We indeed do not know how to obtain current CPU ratio for Westmere CPUs, however, all these values are not used anyhow, and are only present for debugging issues.

The only thing that OpenCore passes to the operating system is FSBFrequency, and its value looks correct to me (133MHz). Could you check whether this value differs between normal and OpenCore boot in IODeviceTree:/efi/platform? Also, any difference in other IODeviceTree:/efi/platform values will be helpful. Perhaps we *are not supposed* to set FSBFrequency at all?

> The biggest difference is that the external clock is read differently:
> External Clock: 25 MHz
> External Clock: 133 MHz

As for SMBIOS changes you mentioned, I can confirm that we indeed have the code to update it:

```
  //
  // Models newer than Sandybridge require quad pumped bus value instead of a front side bus value.
  //
  if (CpuInfo->Model >= CPU_MODEL_SANDYBRIDGE) {
    Table->CurrentPtr.Standard.Type4->ExternalClock = OC_CPU_SNB_QPB_CLOCK;
  } else {
    Table->CurrentPtr.Standard.Type4->ExternalClock = (UINT16) DivU64x32 (CpuInfo->FSBFrequency, 1000000);
  }
```

Personally I am not positive what is correct here, as I do not know whether External Clock is actually Crystal Clock.

> So the CPU power management is not working.

I am not positive any of these can affect power management. If you actually have MacPro, and then changed your mac model, then your power management is most likely broken due to mac model change. You will need CPUFriend to inject power management properties for your CPU on other models.

**Comment by startergo** [comment] 2020-01-04 18:09
Yes indeed it is a cMP5,1 and the only things changed are: board ID and SKU ( those are set for iMac Pro values to get full AMD hardware acceleration and full AMD DRM playback shikigva=144 ). This maintains original values in the about this Mac and the system report--> Hardware overview is identical to the original values. All iMessage keys are identical to the original values.
CPUFriend does not seem to work.
![Screen Shot 2020-01-04 at 1 07 21 PM](https://user-images.githubusercontent.com/7897244/71769792-6e427080-2ef3-11ea-9797-a51911b01aac.png)
![Screen Shot 2020-01-04 at 1 02 19 PM](https://user-images.githubusercontent.com/7897244/71769793-70a4ca80-2ef3-11ea-8d29-f24c96c09ef8.png)

**Comment by startergo** [comment] 2020-01-04 18:24
Kernel compatibility differs:
IODeviceTree:/efi/kernel-compatibility
OC values:
<f6 fd 79 b2>
Regular boot:
<de d2 ef 65>

**Comment by startergo** [comment] 2020-01-04 18:57
[Here](https://github.com/cyring/CoreFreq/blob/master/corefreqd.c) is an example code for calculation of the current CPU ratio based on [this](https://stackoverflow.com/questions/8351944/finding-out-the-cpu-clock-frequency-per-core-per-processor) discussion (Bottom of the page).

**Comment by vit9696** [comment] 2020-01-04 19:09
Like I said, it is cosmetics. We will update the code to provide more sensical values in Type 4 SMBIOS, but Apple itself failed badly there, and nobody noticed (even when iMac12,x had no values at all), because the value is pretty much unused.

```
MacPro5,1      Type4: 133 MHz, Type132: 6400 MT/s
MacPro6,1      Type4: 25 MHz,  Type132: no
iMacPro1,1     Type4: 25 MHZ,  Type132: no
iMac8,1        Type4: 266 MHz, Type132: no
iMac10,1       Type4: 266 MHz, Type132: no
iMac11,1       Type4: 133 MHz, Type132: 4800 MT/s
iMac12,1       Type4: Unknown, Type132: no
iMac13,2       Type4: 25 MHz,  Type132: no
iMac14,1       Type4: 25 MHz,  Type132: no
iMac15,1       Type4: 25 MHz,  Type132: no
iMac16,1       Type4: 25 MHz,  Type132: no
iMac17,1       Type4: 25 MHz,  Type132: no
iMac18,3       Type4: 25 MHz,  Type132: no
iMac19,1       Type4: 100 MHz, Type132: no
Macmini8,1     Type4: 100 MHz, Type132: no
MacBookpro15,2 Type4: 100 MHz, Type132: no
```

Their code in AppleSMBIOS implies that Type4 * 4 = Type132 = FSB speed (MT/s), you can guess that all models before iMac19,1 are just borked and nobody cares.

If CPUFriend does not help your power management by injecting `/System/Library/Extensions/IOPlatformPluginFamily.kext/Contents/PlugIns/ACPI_SMC_PlatformPlugin.kext/Contents/Resources/MacPro5_1.plist`, which you had to manually convert into a SSDT or a plist-only kext, into ACPI_SMC_PlatformPlugin.kext, then most likely something else is broken. In either case, this is our of the scope of OpenCore or our other projects, and here you will have to investigate on your own.

**Comment by vit9696** [comment] 2020-01-04 19:43
Type4 values are fixed in master.

**Closed by vit9696** 2020-01-04 19:43 UTC
Labels: help wanted, project:oc

**Comment by startergo** [comment] 2020-01-04 19:50
That is fine. Why am I not able to remove the presense of StartupPowerEvents, InitialTSC even if the keys are removed from the data hub?

**Comment by vit9696** [comment] 2020-01-04 19:58
This is the limitation of the configuration. Since these fields are legit (removing them does not change macOS behaviour) and as they do not do any harm, we do not see a need to overcomplicate configuration.
