### ISSUE TITLE
Black screen issue when rebooting after using Windows10

### ISSUE THREAD

**Issue by ZISQO** [acidanthera/bugtracker#913] opened 2020-05-12 01:16 UTC
The OpenCore boot picker was black screened when i switching from Windows10  to MacOS on Recently OpenCore 0.5.9 DevBuild (this issue has been started from about 2 days ago, It's working fine to boot up MacOS first and reboot to select Windows 10 OS in OpenCore 0.5.9)

This issue is solved by Reset NVRAM using the official release of OpenCore 0.5.8.
**My meant was MacOS boot has no problem at all**, but when using the latest Devbuild, switching to Windows 10 and rebooting does not need to reset NVRAM with that 0.5.8 usb stick.

Currently, the Config.plist values ​​for Open Core 0.5.8 and 0.5.9 are the same and the SyncRuntimePermissions option is also enabled. In the latest 0.5.9 Devbuild, the boot picker output for booting macOS is normal, and the operating system boots all well, but when switching to Windows 10, Windows 10 also works well, but the problem has been started after rebooting Windows 10, the OpenCore bootloader was black screened until the Reset NVRAM with OC 0.5.8 USB stick.

- ASUS X299 TUF mk1
- i7-7800X
- XFX 5700XT

** if disabled SyncRuntimePermissions option in Config.plist was no problem but won't booting up Windows 10 on OC 0.5.9 (the error 0xc000000d has found that bluescreen) so i must be select enforcement Windows 10 disk from CMOS bios or Press F8 then select Win10 OS will working fine. 

and i think Sync Runtime Permissions option will change my NVRAM setting after Windows 10 rebooting with recently 0.5.9 version. 

thank you for reading :)

**Comment by vit9696** [comment] 2020-05-12 17:58
I understood roughly nothing but:

> The OpenCore boot picker was black screened when i switching from Windows10 to MacOS on Recently OpenCore 0.5.9 DevBuild

I.e. you rebooted from Windows 10 and saw black screen? Please attach your EFI folder and OpenCore debug log.

**Comment by ameenjuz** [comment] 2020-05-12 22:03
@vit9696 
i  have windows 10 issue after resetNvram
when i resetnvram then windows 10 boot break with blue screen
without resetnvram boot fine
Attached EFI
[EFI.zip](https://github.com/acidanthera/bugtracker/files/4618623/EFI.zip)

**Comment by vit9696** [comment] 2020-05-12 22:52
@ameenjuz try disabling `RequestBootVarFallback` and maybe remove `BlessOverride` entry (and restore Windows bootloader). If it still persists, that's probably Windows bug. It is not like Windows is bug-free, and I do not believe they fully test with NVRAM cleanup.

**Comment by ameenjuz** [comment] 2020-05-12 23:31
thanks you are great @vit9696  
disabling RequestBootVarFallback fixed my windows issue after reset nvram but one issue still persist now i reset nvram windows booted fine when i come back from windows to boot menu then appeared double windows partition icon in boot menu
i tried to remove BlessOverride entry to fix double windows icon but windows partition disappeared from bootmenu
anyidea
i never faced like this issue before

**Comment by vit9696** [comment] 2020-05-12 23:40
Where is debug log of both cases and full description of what is installed where (disks, partitions, operating systems)?

**Comment by Andrey1970AppleLife** [comment] 2020-05-12 23:46
@ameenjuz Recover Windows's  BOOTx64.efi

**Comment by ameenjuz** [comment] 2020-05-13 00:48
@vit9696 
when i reset nvram then one icon of windows is gone but recome back when i boot windows
attached debug log
[opencore-2020-05-13-004222.txt](https://github.com/acidanthera/bugtracker/files/4619169/opencore-2020-05-13-004222.txt)

**Comment by vit9696** [comment] 2020-05-13 00:51
There is nothing in the log, you have OpenCanopy, but it is not DEBUG. Also make sure you have all the files up to date.

**Comment by ameenjuz** [comment] 2020-05-13 00:58
yes i have OpenCanopy 
this is log of debug version

![Screen Shot 2020-05-13 at 3 53 33 AM](https://user-images.githubusercontent.com/21066935/81759514-9fe4cd00-94cd-11ea-95c7-12601b357847.png)
[OpenCore-0.5.9-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/4619197/OpenCore-0.5.9-DEBUG.zip)

**Comment by Andrey1970AppleLife** [comment] 2020-05-13 01:03
Need to use all files from debug. You have a release OpenCanopy.efi

**Comment by ameenjuz** [comment] 2020-05-13 01:12
@vit9696 @Andrey1970AppleLife 
new extracted log from debug version

[opencore-2020-05-13-010432.txt](https://github.com/acidanthera/bugtracker/files/4619241/opencore-2020-05-13-010432.txt)

**Comment by vit9696** [comment] 2020-05-13 01:20
Apparently you have Windows bootloader on two EFI partitions. Works as intended. I assume RequestBootVarFallback is also the cause for the first case, closing as resolved.

**Comment by vit9696** [comment] 2020-05-13 03:48
Right, I see what happens now. You have three operating systems listed in your BootOrder entry:

```
31:996 00:127 OCB: 0 -> Boot0080 = PciRoot(0x0)/Pci(0x17,0x0)/Sata(0x0,0x0,0x0)/HD(5,GPT,2A75A575-441B-44BF-B670-9785E219BBD8,0x1366B800,0x88B8C88)/VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,7795564FB9E10F45B920CD5A3463139D)/\3B21F342-0278-4E73-971D-33C1F14D700E\System\Library\CoreServices\boot.efi
32:249 00:253 OCB: 1 -> Boot0001 = HD(1,GPT,8FB90A16-388B-433C-B30A-4ABDBC9FF7C9,0x800,0x64000)/\EFI\Microsoft\Boot\bootmgfw.efi
32:377 00:127 OCB: 2 -> Boot0000 = HD(1,GPT,8FB90A16-388B-433C-B30A-4ABDBC9FF7C9,0x800,0x64000)/\EFI\Android\grubx64.efi
```

First is macOS. Second is Windows. And third is Android?!

**Comment by ameenjuz** [comment] 2020-05-13 04:02
@vit9696 
First of all have you seen my uploaded video on OpenCore discussion?
Wasn't my laptop preinstalled with Android and i don't have android os installed
How to fully reset nvram and can i should completelly erase EFI partition?
I don't have anyidea how to solve this

**Comment by vit9696** [comment] 2020-05-13 04:04
Yes, I did see your video. I also had to edit my reply above multiple times due to more material I discovered. So, you are sure that you do not have an Android installation on your HDD? But maybe you have something in Windows, which registers an Android boot option? Or perhaps you had Android in the past?

**Comment by ameenjuz** [comment] 2020-05-13 04:35
@vit9696 
Perhaps i have forgotten may be i install andriod in past
what i do?  do i erase EFI partition or remove Microsoft folder
 how to remove EFI\Android\grubx64.efi from nvram
I don't see like this entry in bois

![20200513_071428](https://user-images.githubusercontent.com/21066935/81771411-8b173200-94eb-11ea-99ee-e291a0c0fb5f.jpg)

**Comment by vit9696** [comment] 2020-05-13 05:06
You can reset NVRAM from OpenCore. Afterwards make log. And make one more log after booting to Windows. If Android entry appears after you boot to Windows, then you have some software in Windows adding it.

**Comment by ameenjuz** [comment] 2020-05-13 05:11
Do not work reset nvram using terminal sudo nvram -c
How to reset nvram using UEFI Shell

**Comment by ameenjuz** [comment] 2020-05-13 05:40
@vit9696 resetnvram from boot menu with debug version
become remove OpenCore entry from bois
i couldn't get log after booting windows because opencore entry lost from bois after reset nvram with debug version

[opencore-2020-05-13-051952.txt](https://github.com/acidanthera/bugtracker/files/4620052/opencore-2020-05-13-051952.txt)

[opencore-2020-05-13-052702.txt](https://github.com/acidanthera/bugtracker/files/4620057/opencore-2020-05-13-052702.txt)

**Comment by vit9696** [comment] 2020-05-13 06:19
Well, looks good to me? Any problem?

**Comment by ZISQO** [comment] 2020-05-13 11:30
> I understood roughly nothing but:
> 
> > The OpenCore boot picker was black screened when i switching from Windows10 to MacOS on Recently OpenCore 0.5.9 DevBuild
> 
> I.e. you rebooted from Windows 10 and saw black screen? Please attach your EFI folder and OpenCore debug log.


So terrible sorry late my feedback. finally i'm fixed up this issue.
(my exact question was rebooted from Windows 10 and saw black screen with Boot Chime on OC 0.5.9)

** macOS 10.15.4 / Windows 10  was working fine with OC 0.5.9 (05-13-2020) devbuild
1. Change HFSplus.efi to VboxHfs.efi
2. Disabled Custom Boot Entries under Config.plist/Misc/Entries
3. Set to Yes SyncRuntimePermissions option (will fixing 0xc000000d error with bluescreen)

** Now Black Screen has been goes by my memorial.. hhhhh 
by the way, Doesn't remmended to add Custom boot list on Config.plist/Misc/Entries option?

[EFI.zip](https://github.com/acidanthera/bugtracker/files/4621608/EFI.zip)
[opencore-2020-05-13-110108.txt](https://github.com/acidanthera/bugtracker/files/4621612/opencore-2020-05-13-110108.txt)

**Comment by vit9696** [comment] 2020-05-13 12:27
Not recommended.

Just in case current master received another fix on entry duplication.

Closing this as resolved.

**Closed by vit9696** 2020-05-13 12:27 UTC
Labels: project:oc

**Comment by ZISQO** [comment] 2020-05-13 14:50
> Not recommended.
> 
> Just in case current master received another fix on entry duplication.
> 
> Closing this as resolved.

thanks!

**Comment by ameenjuz** [comment] 2020-05-13 17:36
@vit9696 thanks you fixed Deduplicate icon in latest commit changes
worked fine no issue in both macOS and windows 10 are working fine after resetnvram

![Screen Shot 2020-05-13 at 8 29 52 PM](https://user-images.githubusercontent.com/21066935/81845470-44f8b780-9559-11ea-852e-1f1b18ff2c6a.png)
