### ISSUE TITLE
Ice lake boot screen glitch seems fixed by this small WhateverGreen patch

### ISSUE THREAD

**Issue by kingo132** [acidanthera/bugtracker#1805] opened 2021-09-28 23:57 UTC
Hi, WEG teams and other friends, yesterday @m0d16l14n1 send me his finding of the screen glitch when booting into the desktop with ice lake CPU.

He says it may be related to the DBuf error he saw in the boot log here.

![image](https://user-images.githubusercontent.com/46492291/135179696-65703673-dac7-45e5-84f8-0f617a133988.png)

So he wondered if we could bypass this error with some WEG patches.

![image](https://user-images.githubusercontent.com/46492291/135179773-5aee1a77-97d4-4f91-a4d1-8cd56b8fe357.png)

I saw there're 3 conditions that can make it goes to DBuf error, they are
1. v3
2. ((unsigned int *)this + 64)
3. ((_DWORD *)this + 37)

I tried to hook this function by WEG and printed these values 

![image](https://user-images.githubusercontent.com/46492291/135179918-3659cab5-e745-4a56-baec-086af418def6.png)

The result is here

![image](https://user-images.githubusercontent.com/46492291/135179958-223deaf4-9310-4a86-8ce6-9d317e62fc1d.png)

As you can see in the screenshot, the value of v3 is first 0 and then 40 when boot, and I guess it was DBuf value. When it is 0, the DBuf error happens, and according to what @m0d16l14n1 says, the glitch happens.

![image](https://user-images.githubusercontent.com/46492291/135180075-b863d69c-41a7-435e-a1cd-40bf80d38687.png)

You can see the DBuf error log is alongside with zero v3 value.

So I just made a small test, to hardcode that v3 value to always 40.

![image](https://user-images.githubusercontent.com/46492291/135180153-ddc19a23-a7be-4dc4-be85-cd7f69acfb55.png)

Some magic happens, the glitch seems gone, and some friends in Ice Lake gitter group tested it, the glitch is gone as well.

I think it's an interesting finding, but I have no knowledge about what happened, I even don't know what this DBuf is.

So I'm pushing this finding forward to ask if the WEG team or other friends could do a more robust patch based on this finding. Or at least asking for some clues about what happened and how to set a more reliable DBuf value.

Thanks to everyone who concern about this problem.

**Comment by kingo132** [comment] 2021-09-29 01:34
I think it's better to hardcode that dbuf value here in the AppleIntelPlan::updateDBUF function.

![image](https://user-images.githubusercontent.com/46492291/135187963-aecea189-811e-4bce-8fb0-e1f999dc2817.png)

**Comment by kingo132** [comment] 2021-09-29 02:14
Another interesting finding, there are a lot of hardcoded dbuf values in the ice lake framebuffer as well.

![image](https://user-images.githubusercontent.com/46492291/135191615-136cff36-a890-47f5-93ea-ed43b14a718b.png)

**Comment by m0d16l14n1** [comment] 2021-09-29 03:13
Hello, @kingo132! Thank you again for opening the issue with your ideas and mainly that fix. 

DBuf is display data buffer (according to some of Intel docs > https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-icllp-vol12-displayengine_0.pdf

That's where I found that explanations and some more stuff about that

**Comment by kingo132** [comment] 2021-09-29 03:47
After some more tests, I think I can only get this dirty patch to live along with.

![image](https://user-images.githubusercontent.com/46492291/135199645-7328f2be-5f50-4ad9-a5c6-cbfa3044c65a.png)

However, it works, if not, find your correct dbuf value in the boot log, hardcode that value yourself, and then it should work.

This knowledge about all these intel panels or igfx or dbuf has beyond my ability. I will look into this later when I have time.

**Comment by Lorys89** [comment] 2021-09-29 05:57
the fix works great on my dell iclthe fix works great on my dell icl 💪💪
great job guys

**Comment by vit9696** [comment] 2021-09-30 06:14
`+36` value comes from `__ZN15AppleIntelPlane19updateRegisterCacheEv`, which takes it from a register in `__ZN15AppleIntelPlane4initE9IGPlaneID` (`a2` is plane index here):

```
    v4 = (unsigned int)((a2 / 5) << 12);
    v5 = (unsigned int)((a2 % 5) << 8)
    v5 + v4 + 0x7027C;
```

Need to check out what this register is and fix it, in my opinion, rather than try to to simulate correct value. CC @0xFirewolf.

**Comment by vit9696** [comment] 2021-09-30 06:19
Defined [here](https://github.com/torvalds/linux/blob/477f70cd2a67904e04c2c2b9bd0fa2e95222f2f6/drivers/gpu/drm/i915/i915_reg.h#L7245) in Linux actually. Should have docs on 01.org.

**Comment by 0xFireWolf** [comment] 2021-09-30 09:00
Those values define the position for the plane buffer. 
The actual register address is determined by the plane identifier (and pipe number as well?).
Here is the function prototype.

```c++
void AppleIntelPlane::updateDBUF(AppleIntelPlane* this, UInt32 start, UInt32 end)
{
    // Field at 0x10C (UInt32) stores the raw value of the plane buffer config register
    // Bit 0 - 10 encode the start position;
    // Bit 16 - 26 encode the end position.
    // The rest bits are reserved.
    this->field_0x10c = start & 0x7FF | (end << 16) & 0x7FF;

    // Field at 0x90 (UInt32) stores the start position
    this->field_0x90 = start;

    // Field at 0x94 (UInt32) stores the end position
    this->field_0x94 = end;

    // This function will configure the register and returns void
    AppleIntelPlane::setupPlanarSurfaceDBUF(this);
}
```

`AppleIntelPlane::setupPlanarSurfaceDBUF()` checks whether either `start` or `end` is 0. 
If so, it prints the error saying that internal cached DBuf values are not set.

As vit9696 mentioned above, those three member fields (at 0x90, 0x94, 0x10C) are initially set by `AppleIntelPlane::updateRegisterCache()`. However, as you can see, calling the function `AppleIntelPlane::updateDBUF()` will overwrite those cached values, and that function has three callers `AppleIntelFramebufferController::allocateDefaultDBUF()`, `AppleIntelFramebufferController::setupOptimizedDBUF()`, and `AppleIntelFramebuferrController::LightUpEDP()`.

`LightUpEDP()` is fine, because it just passes the cached values (Fields at 0x90 and 0x94) to `updateDBUF()`. The initial call of `updateRegisterCache()` should also be fine, otherwise your builtin display would not be working when you boot your laptop. As such, the other two callers are suspicious, as they may pass zeros to the update function.

That being said, the root cause is somewhat deeper. Congratulation on your progress. : )
However, I think your current hard-code approach may have a side effect on external displays, as all planes will use the same buffer position [40, 1023].

**Comment by vit9696** [comment] 2021-10-02 08:17
Resolved by https://github.com/acidanthera/WhateverGreen/pull/92.

**Closed by vit9696** 2021-10-02 08:17 UTC
Labels: help wanted, project:green
