### ISSUE TITLE
OpenCore feature request: Option to turn NumLock on at start-up

### ISSUE THREAD

**Issue by Goshin** [acidanthera/bugtracker#2085] opened 2022-07-13 13:49 UTC
When FileVault is enabled, we need to enter the password before booting into the system, in which case I think it would be more convenient to type in the password with the keypad.

Therefore I was thinking if there is a way the num lock can be turned on by default for laptops without the option in BIOS setup to change the num lock state at start-up.

I managed to enable the keypad at start-up by changing the `gAikPs2KeyToUsbMap` keymap in `AIKMap.c`, for example, changing the definition for the PS2 scan code 0x47 (which is Keypad 7 pressed) to `UsbHidUsageIdKbKpPadKeySeven`.

```
  {
    UsbHidUsageIdKbKpKeyHome,
    AIK_DEBUG_STR ("Home"),
    AIK_DEBUG_STR ("^ Home ^")
  }, // 0x47
```

But I think there must be a more proper and universal way to implement this.
I am still struggling to understand the keyboard input lib and its interaction with other components. Though I don't fully understand the input targets, I tried adding a key in `gAikSelf.Target` in `OcAppleGenericInputKeycodeInit()` to emulate NumLock pressing after initialization, but it doesn't work.

@vit9696, any thoughts regarding this?

**Comment by vit9696** [comment] 2022-08-01 15:14
To be honest, I think there is none. We get keycodes from the driver, and when they differ based on the hardware input there is not much we can change. @mhaeuser, any ideas?

**Comment by Goshin** [comment] 2022-08-06 09:07
From my observation, the obtained PS2 scan codes for keypad keys would not change based on the num lock state, but I don't know which part to handle the num lock state changing. Is it the AKMA target? Would it make sense to emulate a num lock pressing?

**Comment by mhaeuser** [comment] 2022-08-08 05:31
@vit9696 https://github.com/acidanthera/OpenCorePkg/blob/f7c1a3d483fa2535b6a62c25a4f04017bfeee09a/Library/OcAppleEventLib/KeyHandler.c#L438

**Comment by mikebeaton** [comment] 2022-08-08 14:22
@mhaeuser - I think this would be relevant too:
https://github.com/acidanthera/OpenCorePkg/blob/master/Platform/OpenUsbKbDxe/KeyBoard.c#L1711-L1739
i.e. it is basically up to the driver to keep track of what locks (num/caps/scroll) are active, and to light the LEDs accordingly
i believe that doesn't sound good for any universal way of setting this, though evidently it could be done in any given driver which we manage?

**Comment by mikebeaton** [comment] 2022-08-08 22:53
@Goshin - This is the opposite of the result I am seeing on some local machines I played with here. I can enter numbers in FV2 password, but cannot use the numeric keypad as arrow keys, even if I want to.

Please can you confirm that if you get to FV2 password and press numeric keypad digits 2, 4, 6 or 8, you get:

 - Obscured password character appearing, y/n?
 - Cursor movement (at least for 4 and 6 keys), y/n?

Thx.

**Comment by Goshin** [comment] 2022-08-09 08:43
@mikebeaton It seems in your case the num lock is on by default. I cannot enter numbers but can only move the cursor until I press the NumLock key.

**Comment by mikebeaton** [comment] 2022-08-09 09:39
Hmm. From what I've seen, that must be firmware support for Num Lock in that case.

Could you confirm some more guesses/investigation:

 - I believe you must be using KeySupport = true (not OpenUsbKbDxe driver)?
 - I would guess that when you get into real macOS, num lock no longer works, and you can only enter numbers (y/n)?

Thanks.

**Comment by mikebeaton** [comment] 2022-08-09 21:19
@Goshin - I am potentially volunteering to work on this, if we can do anything. But I am now not sure that we can.

It would be useful to also know:

 - Whether you have a:
   - Laptop or desktop
   - Internal or external keyboard
   - Apple or non-Apple (generic PC) keyboard

My current working theory, after a bit of research and digging into the code, is that the num lock of a generic PC keyboard will never work in macOS (always locked to numbers; because their drivers just don't support it); whereas an Apple keyboard (and presumably some other apple specific 3rd party keyboards) supports num lock in hardware (i.e. by actually changing the scan codes it sends).

If I'm right, then when you are in arrow mode, your arrow keys will operate the OC menu, and when you are in number mode, your number keys will select the OC boot item (when using the default, text-only boot picker) - neither of which happens with a generic PC keyboard (which is what I am using, fyi).

I would be interested to know if this stacks up. Though if it does, I think we can do precisely nothing (because the arrow key codes your kb would be sending in arrow mode would be indistinguishable from arrow key code from the real arrow keys - if I'm right).

**Comment by mikebeaton** [comment] 2022-08-10 12:33
Continuing to look into the above, I'm revising my ideas again, and stating that I believe there is no num lock feature in macOS at all (not even with Apple keyboards): num pad keys just basically always work as numbers (unless you've got accessibility mouse keys enabled, in which case num pad keys move the _mouse_ cursor, not the text cursor).

So I'm somewhat confused as to how your keyboard can do anything other than num keys as num keys in macOS (incl. in our - I believe correct, i.e. same as macOS - FV2 input support).

**Comment by Goshin** [comment] 2022-08-10 21:56
Hi, @mikebeaton. Thanks for the update. The hardware I am testing on is a laptop with a PS/2 embedded keyboard. I also have a USB keyboard I can test with.

I believe the num lock works differently in the FileVault lock screen and the full OS. Seems like macOS has not implemented the num lock in the first place, but I think one can still make that work by manually tracking the num lock state in the keyboard driver (for example VoodooPS2Keyboard) and reporting ADB codes based on the state.

However, (at least in my case) the num lock works well in the OC boot entry menu and the FileVault lock screen. I can actually turn num lock on in the OC boot menu and it will still remain on in the FileVault lock screen. I assume the default state is set by the firmware or something because some motherboards come with the setting for the default NumLock state in the BIOS setup. But based on the fact that the scan codes would not change based on the num lock state, my guess is that the driver is the one responsible for keeping the track of the lock states, so potentially we can do something about it.

**Comment by mikebeaton** [comment] 2022-08-10 22:26
My understanding is also that it is the driver which is responsible for keeping track of any lock state, including num lock.

I'd still be interested to know, can your keypad keys with numlock off control movement from item to item in the OC menu? And can your keypad keys with num lock on select OC boot entries by number (in the text-only builtin boot picker, which is the only picker which allows this)?

FV2 password prompt still uses firmware or OC implementations of the relevant protocols, so state would be expected to persist between OC and the FV2 prompt.

**Comment by Goshin** [comment] 2022-08-10 22:31
> I'd still be interested to know, can your keypad keys with numlock off control movement from item to item in the OC menu? And can your keypad keys with num lock on select OC boot entries by number (in the text-only builtin boot picker, which is the only picker which allows this)?

Yes, I can use keypad keys 2 and 8 as arrow keys by default, and use the keypad to select entries by the number after I press NumLock.

**Comment by mikebeaton** [comment] 2022-08-10 22:33
Thank you. Can you assist clarify how/whether num lock works for you in macOS, and if so, using which driver?

**Comment by Goshin** [comment] 2022-08-10 22:38
NumLock does not work in macOS. I can only type in numbers with the keypad.

**Comment by mikebeaton** [comment] 2022-08-10 22:40
I don't use VoodooPS2 and have not worked on it. Were you suggesting it does implement numlock in macOS, or just that it could?

**Comment by mikebeaton** [comment] 2022-08-10 22:59
Current situation is that macOS doesn't support num lock, and isn't supposed to, including at the FV2 password prompt. On the other hand, macOS is supposed to be in num mode the whole time, including at the FV2 password prompt. And yours is not...

You're using KeySupport, which is built on the keys returned by the existing firmware driver. My current understanding is that your firmware driver must actually be changing the scan codes sent, depending on the num lock setting, because OC menu movement and menu item selection are based on scan codes. Hence USB kb numpad keys with a normal USB driver will never operate either of these functions (as the true scan codes for the numpad keys are not the same as the numeric or the cursor keys, ofc).

This puts me back round to thinking that we can't change how your keyboard behaves (i.e. can't force it to numeric mode) without inadvertently forcing your actual cursor keys (... assuming you have separate ones? ...) to work as numbers too.

What we really want is, indeed, to actually change the num lock state of your driver, but I don't think we have any way to do that.

**Comment by mikebeaton** [comment] 2022-08-11 19:12
@Goshin - I think I'm finally understanding what we're seeing here. The issue is OC's KeySupport. When using that, OC does not have access to the raw scan codes from the keyboard. KeySupport layers on top of the UEFI _text_ input mode (which is basically always present, hence is a good thing to work with), to restore faked scan codes which can be used downstream in Apple-compatible drivers which - e.g. - are required for FV2 input to work (and are used to drive the OC menus as well). Since in KeySupport mode we just see text input keys - cursor left, right; numbers - there is no way to distinguish which real key they came from.

You could try loading the Ps2KeyboardDxe.efi driver. I eventually managed to replicate exactly the behaviour you are seeing using KeySupport on OVMF - and then to fix it (i.e. to get to number keys working as number keys) using that driver.

**Comment by mikebeaton** [comment] 2022-08-12 09:13
@Goshin - I think I'll close this now. Sorry for taking a while to get there (and thanks to other members of the OC team for pointers in the right direction!).

**TL/DR:**
 - We are unlikely to change how `KeySupport` works, and it has the side effect of respecting the num lock of the underlying firmware keyboard driver, even though macOS is (effectively) always in num lock state (and therefore, ideally, the FV2 password input should be, too)
 - Since it's the initial num lock state of the underlying keyboard driver which matters here, the only things you can do are:
   - Not use `KeySupport` (i.e. use `OpenUsbKbDxe` instead; only applies if you have a USB keyboard)
   - Change the initial num lock state of your firmware keyboard driver in firmware settings (where available)
   - Change to a different driver (e.g. `Ps2KeyboardDxe`, as suggested above)

**Closed by mikebeaton** 2022-08-12 09:13 UTC
Labels: help wanted, project:oc

**Comment by mikebeaton** [comment] 2022-08-12 11:40
Oh dear - except for `KeySupportMode=AMI`, which your clearly using (perhaps via `Auto`), which does get scan codes... should probably have done this a while ago, but do you want to pm me? @mikebeaton:matrix.ispras.ru (if you don't have it, you'd need to sign up for free on element.io, you do not have to be on the same server to send and receive messages).

**Comment by Goshin** [comment] 2022-08-12 12:57
Thanks for the detailed explanation, @mikebeaton. I have done some testing with OCInputLib. Yes, Indeed I can get the scan codes in `KeyData->PS2ScanCode`. And I can confirm like you mentioned the EFIKey in `KeyData->EfiKey` does change based on the num lock state.

```cpp
  //
  // Firstly check for APTIO protocol, which reported a PS/2 key to us.
  // Otherwise try to decode UnicodeChar and Scancode from simple input.
  //
  if ((KeyData->PS2ScanCodeIsValid == 1) && (KeyData->PS2ScanCode < AIK_MAX_PS2KEY_NUM)) {
    Ps2Key = gAikPs2KeyToUsbMap[KeyData->PS2ScanCode];
    if (Ps2Key.UsbCode != UsbHidUndefined) {
      //
      // We need to process numpad keys separately.
      //
      AIKTranslateNumpad (&Ps2Key.UsbCode, KeyData->EfiKey);
      *Key = APPLE_HID_USB_KB_KP_USAGE (Ps2Key.UsbCode);
    }
  } 
```

Regarding your suggestion about Ps2KeyboardDxe, I tried to load it along with OpenUsbKbDxe, but I cannot get the embedded PS/2 keyboard working without `KeySupport` enabled, which is strange. According to the configuration manual, `KeySupport` should not be enabled when `OpenUsbKbDxe` is used, but the weird thing is I cannot make the keyboard work without either of them. I will do more testing.

Thanks again for your time on the investigation.

**Comment by mikebeaton** [comment] 2022-08-12 14:02
> Regarding your suggestion about Ps2KeyboardDxe, I tried to load it along with OpenUsbKbDxe, but I cannot get the embedded PS/2 keyboard working without KeySupport enabled, which is strange. According to the configuration manual, KeySupport should not be enabled when OpenUsbKbDxe is used, but the weird thing is I cannot make the keyboard work without either of them. I will do more testing.

That's a misunderstanding, I was suggesting using `Ps2KeyboardDxe` while keeping everything the same (so, while keeping `KeySupport`, and not while using `OpenUsbKbDxe`).

**Comment by mikebeaton** [comment] 2022-08-12 14:06
I'm looking at the same bit of code as you, above. Do you get different scan codes in num lock mode and non-num lock mode? It seems you must, or the behaviour would not change?

**Comment by mikebeaton** [comment] 2022-08-13 08:38
@vit9696 @mhaeuser  - Looking at this again https://github.com/acidanthera/OpenCorePkg/blob/master/Library/OcInputLib/Keycode/AIKTranslate.c#L179-L201, I think we could force num lock, but only in `AMI` mode.

In `AMI` mode only, `gAikPs2KeyToUsbMap` always translates the num pad PS/2 scan codes to cursor keys, then `AIKTranslateNumpad` spots if numeric typing characters have come through at the same time, and changes the translation. So a new option `AmiForceNumeric` or similar could cause a different function to be called there, instead of `AIKTranslateNumpad`, which could force the relevant ten PS/2 scan codes to always translate as number keys.

But:
 - It would only ever work in `AMI` mode, not `V1` or `V2` (which would continue to reflect the underlying driver's numlock, as `AMI` mode does now).
 - It would (intentionally) ignore the true num lock state, so  won't match the light on the keyboard

So less than ideal, and somewhat confusing as an option. What we'd like (at least, to match real Mac behaviour) is to do is always force FV2 input to num lock, under all variants of `KeySupport`, but we basically can't, as per my [comments above](https://github.com/acidanthera/bugtracker/issues/2085#issuecomment-1212900505).

**Comment by Goshin** [comment] 2022-08-14 11:45
> That's a misunderstanding, I was suggesting using Ps2KeyboardDxe while keeping everything the same (so, while keeping KeySupport, and not while using OpenUsbKbDxe), see:

Hi @mikebeaton, I tried using Ps2KeyboardDxe with KeySupport, but it works the same as before. I cannot input numbers until I press the NumLock key. As you explained, `gAikPs2KeyToUsbMap` maps the keypad to arrow keys and changes the keycode based on obtained `KeyData->EfiKey`. So it still obtains key input via `AmiReadEfikey()` rather than directly from the PS/2 protocol?
