### ISSUE TITLE
Installer not working with 5700XT (pikera)

### ISSUE THREAD

**Issue by peteha** [acidanthera/bugtracker#901] opened 2020-05-08 23:32 UTC
Z390 - ASUS-Z390F
i9 9900k
5700XT
OC 0.5.8
Latest - Lilu 1.4.4 and Whatevergreen - 1.3.9

When clean install using 5700XT  installer fails with crash.
[Installer Log 6-May-2020.txt](https://github.com/acidanthera/bugtracker/files/4602167/Installer.Log.6-May-2020.txt)

Removed pikera mod and used RX580 worked perfectly.  

After install switched out RX580 to 5700XT and re-added pikera. Runs fine.

**Comment by vit9696** [comment] 2020-05-09 01:10
The issue happens in `GPUInfo` framework (`/System/Library/PrivateFrameworks/GPUInfo.framework/Versions/A/GPUInfo`). `get_gpu_EFIATYROM(__GPUWranglerGPU*, __CFDictionary*)` function (`__Z17get_gpu_EFIATYROMP16__GPUWranglerGPUP14__CFDictionary`) is accessing `ATY,Rom#` property, which seems to be present but of different type. Basically the code looks as follows:

```C
CFDataRef theData = (CFDataRef)GPUWranglerGPUCopyProperty(a1, 0LL, "ATY,Rom#");
if (theData != NULL) {
  /* other code */
  const char *str = (const char *)CFDataGetBytePtr(theData);
  size_t strLen = strlen(str); ///< crash here, str is 0x7c8
  /* other code */
}
```

The problem is that `ATY,Rom#` has CFStringRef type, and thus `CFDataGetBytePtr` returns some trash (`0x7c8`), which therefore crashes the whole thing.

The reason `ATY,Rom#` is set as data is because `AMDRadeonX6000Framebuffer.kext` in `AMDRadeonX6000_AmdRadeonController::reportControllerProperties()` function (`__ZN34AMDRadeonX6000_AmdRadeonController26reportControllerPropertiesEv`) actually sets it as a string when not present:

```C
  if (fProvider->getProperty_1("ATY,Rom#") == NULL) {
    const char *romName = vbiosHandler->getRomName();
    if (romName == NULL)
      romName = "NOT-DETECTED-???";
    /* virtual bool setProperty(const char * aKey, const char * aString); */
    fProvider->setProperty("ATY,Rom#", romName);
  }
```

The string will not be present when a GPU without Apple EFI ROM is used and thus this code will be in use. Filed FB7694132.

As a temporary measure add the following kernel patch in OpenCore:

```
Find: 41 54 59 2C 52  6F 6D 23 00
Replace: 41 4D 44 2C 52  6F 6D 23 00
Identifier: com.apple.kext.AMDRadeonX6000Framebuffer
Count: 1
```

**Closed by vit9696** 2020-05-09 01:10 UTC
Labels: help wanted, project:green

**Comment by blazvizjak** [comment] 2020-05-15 15:30
I'm very new to this so sorry for a stupid question, but using ProperTree does this patch need to be written as data? What should I put for Mask and ReplaceMask?

**Comment by blazvizjak** [comment] 2020-05-15 18:02
@peteha Were you successful in applying this patch? If so ... can you just paste that patch from config.plist maybe? Thank you!

**Comment by yurique** [comment] 2020-05-24 18:29
I tried applying this patch:
![image](https://user-images.githubusercontent.com/919230/82761733-56697b80-9e05-11ea-8073-2915e797ba77.png)

But it didn't help me. Getting the same `Thread 0 Crashed` at `get_gpu_EFIATYROM(__GPUWranglerGPU*, __CFDictionary*) + 665` -> `_platform_strlen + 18`

**Comment by yurique** [comment] 2020-05-24 18:29
@vit9696 sorry for @'ing you, but maybe you can help? :)

**Comment by vit9696** [comment] 2020-05-24 20:44
Try injecting `ATY,Rom#` via DeviceProperties with any value in this case.

**Comment by yurique** [comment] 2020-05-24 23:24
@vit9696 thanks a LOT! This has worked :)

![image](https://user-images.githubusercontent.com/919230/82767224-cb04e000-9e2e-11ea-95df-d725aaecf46f.png)

**Comment by rutgerfarry** [comment] 2020-05-25 03:52
Hey guys I'm having the same issue with my 5700XT. @yurique how did you get the correct `PciRoot(....` for your GPU? Am not sure how to get this value from Windows. Thanks!

**Comment by vit9696** [comment] 2020-05-25 06:23
Yes, that's the thing, just slightly awkwardly named, there are no commas between bytes in PCI, the separator is # instead of /, and the case is wrong. Windows always does things its own way I guess. It seems you have the following path:

```
PciRoot(0x0)/Pci(0x3,0x1)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)
```

I am not quite sure it points to the right device (e.g. the last Pci may be extra), and whether the byte order is correct in the second node (could be Pci(0x1,0x3) instead).

It is much easier to boot to macOS recovery and just run gfxutil to be honest.

**Comment by yurique** [comment] 2020-05-25 15:29
@rutgerfarry I used the `OpenCore Configurator` for this.

It automatically added some properties, but put some weird character into the `model` value - OpenCore booted just fine, but ProperTree was not happy about it (I removed the symbol in text editor).

![image](https://user-images.githubusercontent.com/919230/82825566-27f6a980-9eb4-11ea-925a-bb46b7bc5a98.png)

![image](https://user-images.githubusercontent.com/919230/82825625-3e9d0080-9eb4-11ea-8c1b-844e09356d30.png)

![image](https://user-images.githubusercontent.com/919230/82825593-347b0200-9eb4-11ea-97d7-eb30d7ac3533.png)

![image](https://user-images.githubusercontent.com/919230/82825766-7ad06100-9eb4-11ea-989c-d7351aa8c2e5.png)

**Comment by rutgerfarry** [comment] 2020-05-25 19:34
Thanks @vit9696 and @yurique! I'd been trying so many different fixes, but this is the one that actually ended up working. Would love to further understand what is happening here and perhaps add it to the Opencore Desktop Guide to help others having this issue... or would a fix like this be added to Whatevergreen in the future?

**Comment by blazvizjak** [comment] 2020-05-25 20:35
@yurique or @rutgerfarry how did you get the AAPL, slot name value? I don't have a working hackintosh to run OpenCore Configurator on it :/

**Comment by yurique** [comment] 2020-05-25 20:38
@blazvizjak I used OpenCore configurator, and it populated those three properties automatically when I selected the graphics card from the list of devices (`AAPL,slot_name`, `device_type` and `model`). I only added `ATY,Rom#` manually.

**Comment by blazvizjak** [comment] 2020-05-25 20:59
OK since I can't runt OpenCore configurator on hackintosh machine I've booted to macOS recovery and ran gfxutil and copied value for GFX0 which was: PciRoot(0x0)/Pci(0x3,0x1)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0) and "deducted" AAPL,slot-name to be: Internal@0,3,1/0,0/0,0/0 which seemed to do the trick.

**Comment by Toslim84** [comment] 2020-06-15 07:44
> @vit9696 thanks a LOT! This has worked :)
> 
> ![image](https://user-images.githubusercontent.com/919230/82767224-cb04e000-9e2e-11ea-95df-d725aaecf46f.png)

What is your gpu details?

**Comment by johanlantz** [comment] 2020-07-15 15:37
Sorry for posting on a closed thread but I am just ordering the pieces for my Hackintosh and currently the MSI AMD Radeon RX 5700 XT Mech might be the only card small enough to fit in the itx case I have selected.

So, I basically wonder:
1. khronokernel added this under an MSI comment. Does this mean only MSI 5700 cards were affected?
2. I understand from the comments from @blazvizjak and @yurique that a solution was found. Is this solution still a manual thing or has it been soved by weg or OS updates over the last 2 months?
3. Is it correct that this only happens at install time, so using the igpu during installation and then pluggin in the card is also an option (unless this is already resolved)?

Thanks for any input, still learning here and trying to get the specs right 😄

**Comment by mateossh** [comment] 2020-07-17 10:35
@johanlantz from what I understand:

1. All AMD Navi from MSI are affected (RX 5000 series).
2. I don't know what "weg" means, but a few days ago I was installing Catalina 10.15.5 and I had to apply patches from comments above (I have MSI RX 5700 MECH something).
3. From my observations: 
3.1 when you boot installer, it doesn't load `AMDRadeonX6000Framebuffer.kext` (I saw in OpenCore logs that kext patching failed while booting installer), but when you boot system from hard drive it does load and patch;
3.2 installer will crash in the end if you don't inject `ATY,Rom#`.

To be honest I use config with both kext patch and injecting `ATY,Rom#` and everything works fine

**Comment by johanlantz** [comment] 2020-07-17 11:00
@mateossh Thank you so much for the answer. My parts are on the way and I had to select the exact same card as you have due to space reasons in the case.

I am just beginning to learn about opencore so this will be my first Hackintosh project.

So, I take it that with the fixes described here you got your installation working.

Do you mind if I ask you about your impressions of the MSI XT 5700 Mech otherwise in macOS? Does it work as you expected?

**Comment by Toslim84** [comment] 2020-07-17 14:38
Stuck on the same issue here (very first ryzentosh with MSI RX 5700 MECH). 
Btw can anyone help me on how can I found [ ATY,Rom# ] on windows platform?

**Comment by vandroiy2013** [comment] 2020-07-17 14:39
This is not a support forum! 
Locked.
