### ISSUE TITLE
CsrUtil.efi in TextMode with argument shows output for a very short time

### ISSUE THREAD

**Issue by perez987** [acidanthera/bugtracker#1655] opened 2021-05-28 21:00 UTC
If I set the new tool CsrUtil.efi in TextMode with argument (status, clear, toggle value, etc.), when executed from the picker the text output is seen for such a short time that it is impossible to read what it says. This is the tool in config.plist:

```
<key>Arguments</key>
<string>status</string>
<key>Auxiliary</key>
<true/>
<key>Comment</key>
<string>CsrUtil</string>
<key>Enabled</key>
<true/>
<key>Flavour</key>
<string>Auto</string>
<key>Name</key>
<string>CsrUtil</string>
<key>Path</key>
<string>CsrUtil.efi</string>
<key>RealPath</key>
<false/>
<key>TextMode</key>
<true/>
```

If I run CsrUtil.efi from Open Shell everything seems to work fine.

Anyway, thank you so much for your hard work and such a wonderful idea (Toggle SIP and CsrUtil.efi).

**Comment by MikeBeaton** [comment] 2021-05-28 22:56
Hmm - the current logic is that if it detects multiple args all sent in the first arg, separated by space, then it was called as a Tool and it will wait for a key input.

This was intended to be enough to detect likely calls as a Tool from OC.

Can you confirm that "toggle 0x6F" (along with e.g. "disable 0", "enable 0x67", etc., etc.) pause for a key press?

**Comment by MikeBeaton** [comment] 2021-05-28 23:37
Have adopted more robust detection method - should be fixed (for all possible arguments) - thanks
https://github.com/acidanthera/OpenCorePkg/commit/45f12af2207e6407990b09c063378c7a013cb8e0

**Closed by MikeBeaton** 2021-05-28 23:37 UTC
Labels: project:oc

**Comment by perez987** [comment] 2021-05-29 08:54
Thank you Mike. I’ll try and comment.

**Comment by perez987** [comment] 2021-05-29 09:41
New build works fine. Thanks.

**Comment by MikeBeaton** [comment] 2021-05-29 21:33
Okay - thanks for the heads up on the issue @perez987 - cheers
