### ISSUE TITLE
Incorrect RAM speed

### ISSUE THREAD

**Issue by naveenkrdy** [acidanthera/bugtracker#612] opened 2019-12-12 20:36 UTC
Hi !
I see my RAM speed reading showing incorrect in About this Mac and in System Information -> Memory .
![Screen Shot 2019-12-13 at 2 00 02 AM](https://user-images.githubusercontent.com/18463250/70746695-4de82180-1d4c-11ea-9aab-4cee41bd48ba.png)

My  actual RAM speed is 1600 Mhz but its showing as 800 Mhz for some reason.
Is there any workaround or fix is there for Opencore ?

Using opencore v0.5.3 
Let me know if any log dump is needed.

Thanks !

**Comment by vit9696** [comment] 2019-12-17 19:49
Hi,

I believe this is a duplicate of https://github.com/acidanthera/bugtracker/issues/381. If this is cosmetics, then you could ignore this. Otherwise you could contribute a feature or wait. It will help a lot if you could provide us with an *original* and *patched* SMBIOS dumps for your machine in https://github.com/acidanthera/bugtracker/issues/381. Thanks.

Closing as duplicate.

**Closed by vit9696** 2019-12-17 19:49 UTC
