### ISSUE TITLE
Retina 2012 Macbookpro retina can't run "edit" in openshell, get error "edit initalization was not successful"

### ISSUE THREAD

**Issue by kocoman1** [acidanthera/bugtracker#1648] opened 2021-05-22 12:04 UTC
Retina 2012 Macbookpro retina can't run "edit" in openshell, get error "edit: initalization was not successful"

**Comment by vit9696** [comment] 2021-05-22 12:33
Duplicate of https://github.com/acidanthera/bugtracker/issues/1080

**Closed by vit9696** 2021-05-22 12:33 UTC
Labels: project:oc
