### ISSUE TITLE
HfsPlusLegacy fails to load when using OpenCore 0.9.7 OpenDuet

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [acidanthera/bugtracker#2365] opened 2023-12-27 10:13 UTC
system: MSI P55A-G55, Intel Core i5-750, PowerColour Radeon HD 7870

When using the OpenDuet from OpenCore 0.9.7, HfsPlusLegacy fails to load with the error `05:979 00:081 OC: Driver HfsPlusLegacy.efi at 0 cannot be loaded - Not started!`. Downgrading to OpenCore 0.9.6's OpenDuet fixes this issue. EFI and OpenCore log are attached. OpenCore 0.9.7 did make a few changes to OpenDuet so I'm assuming one of those broke loading of HfsPlusLegacy.
[opencore-2023-12-27-062137.txt](https://github.com/acidanthera/bugtracker/files/13777664/opencore-2023-12-27-062137.txt)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/13777679/EFI.zip)

**Comment by mikebeaton** [comment] 2023-12-27 11:03
Duplicate of #2363, although thanks for the additional information about when it breaks.

**Closed by mikebeaton** 2023-12-27 11:03 UTC
