### ISSUE TITLE
Can't boot to windows with "SetupVirtualMap=Yes"

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#614] opened 2019-12-16 07:27 UTC
My Notebook is
Dell Latitude E5450
Proc : Intel Core i3 5010U
Ram : 4GB DDR3
Storage : SSD

I am using OpenCore 0.5.4 Latest Compiled from Resources.

A. If i set SetupVirtualMap=No", i can boot to Windows and everything is fine and smooth but i can't boot to macOS (just Apple logo without loading bar)

B. If i set SetupVirtualMap=Yes" , i can't boot to windows (just crash and reboot after select entry of windows) but i can boot macOS with this.

I have upload debug log with "SetupVirtualMap=Yes" when boot to Windows and macOS
[opencore-2019-12-16-071501 (Log boot to Windows).txt](https://github.com/acidanthera/bugtracker/files/3966525/opencore-2019-12-16-071501.Log.boot.to.Windows.txt)
[opencore-2019-12-16-071717 (Log boot to MacOS).txt](https://github.com/acidanthera/bugtracker/files/3966526/opencore-2019-12-16-071717.Log.boot.to.MacOS.txt)

**Comment by vit9696** [comment] 2019-12-17 19:55
I do not see how this can happen. Could you try removing this code and checking if it works for Windows? https://github.com/acidanthera/OcSupportPkg/blob/268ae1b/Library/OcAppleBootCompatLib/ServiceOverrides.c#L742-L749 (it will obviously break macOS).

**Comment by vit9696** [comment] 2019-12-17 19:55
CC @Download-Fritz

**Comment by andreszerocross** [comment] 2019-12-17 20:19
> I do not see how this can happen. Could you try removing this code and checking if it works for Windows? https://github.com/acidanthera/OcSupportPkg/blob/268ae1b/Library/OcAppleBootCompatLib/ServiceOverrides.c#L742-L749 (it will obviously break macOS).

After delete that code and recompiled OC with ./macbuild.tool
Result :
1. Boot to Windows normally and smooth with OC
2. Stuck / Hang in Apple Logo without loading bar when i boot into macOS 

:)

**Comment by andreszerocross** [comment] 2019-12-20 11:27
Any info??? :(

**Comment by Download-Fritz** [comment] 2019-12-20 11:31
This is not a forum, updates will be provided as updates are available and as long as the issue is not closed, it is not forgotten.

**Comment by vit9696** [comment] 2020-01-04 19:54
Should be resolved in master.

**Closed** 2020-01-04 19:54 UTC
Labels: priority:normal, project:oc
