### ISSUE TITLE
OpenCore Legacy Duet Release 0.8.8

### ISSUE THREAD

**Issue by chris1111** [acidanthera/bugtracker#2215] opened 2023-02-07 10:45 UTC
Some probleme to booting USB `install macOS Ventura`
This is the message I have
![IMG_2814](https://user-images.githubusercontent.com/6248794/217223177-2a4abb30-f36b-4612-9334-626ba56c96b1.jpeg)

Other strange thing, it will create an empty folder  NVRAM in EFI ?

![Screenshot 2023-02-07 at 5 35 03 AM](https://user-images.githubusercontent.com/6248794/217223489-c9e6bbd4-4796-4911-a72c-3bb5a92b56ce.png)

**Comment by mikebeaton** [comment] 2023-02-07 12:32
"Emulated NVRAM load failed" should just be a warning message, actually nothing to do with the crash.

Please provide full debug log, and also (anonymised if you wish) config.plist.

**Comment by chris1111** [comment] 2023-02-07 14:06
USB installer stop at this point nothing more

**Comment by mikebeaton** [comment] 2023-02-07 15:13
I didn't understand the word 'Legacy' in your title (I thought you probably meant OCLP; but also that this still might be - unproven - an OC issue). As you meant Duet and legacy boot then a) the NVRAM message makes sense, but still isn't the issue, and b) I believe this is a duplicate of #2206 (which is being tracked).

**Comment by chris1111** [comment] 2023-02-07 15:40
Yes I edit the tittle it's Duet
I will see the link you provided
Thanks

**Comment by mikebeaton** [comment] 2023-02-08 14:21
Please can you confirm whether or not this is fixed by: https://github.com/acidanthera/OpenCorePkg/commit/092af5d99c764cbe06372dfed3fa03af719550cc

Download the `macOS XCODE5 Artifacts` zip file from the bottom of page https://github.com/acidanthera/OpenCorePkg/actions/runs/3840701149 , and check whether the contained versions of OC fixes the problem.

**Comment by chris1111** [comment] 2023-02-08 14:47
> Please can you confirm whether or not this is fixed by: https://github.com/acidanthera/OpenCorePkg/commit/092af5d99c764cbe06372dfed3fa03af719550cc
> 
> 
> 
> Download the `macOS XCODE5 Artifacts` zip file from the bottom of page https://github.com/acidanthera/OpenCorePkg/actions/runs/3840701149 , and check whether the contained versions of OC fixes the problem.


I will test when back home after work thanks

**Comment by chris1111** [comment] 2023-02-08 20:07
Not working, same issue for me descrid [here](https://github.com/acidanthera/bugtracker/issues/2215)


![217223177-2a4abb30-f36b-4612-9334-626ba56c96b1](https://user-images.githubusercontent.com/6248794/217639146-77d29080-2fbc-43a2-acb9-5bf24a96fd88.jpeg)

**Comment by chris1111** [comment] 2023-02-08 20:08
> Please can you confirm whether or not this is fixed by: [acidanthera/OpenCorePkg@092af5d](https://github.com/acidanthera/OpenCorePkg/commit/092af5d99c764cbe06372dfed3fa03af719550cc)
> 
> Download the `macOS XCODE5 Artifacts` zip file from the bottom of page https://github.com/acidanthera/OpenCorePkg/actions/runs/3840701149 , and check whether the contained versions of OC fixes the problem.


Not working, same issue for me descrid [here](https://github.com/acidanthera/bugtracker/issues/2215)


![217223177-2a4abb30-f36b-4612-9334-626ba56c96b1](https://user-images.githubusercontent.com/6248794/217639146-77d29080-2fbc-43a2-acb9-5bf24a96fd88.jpeg)

**Comment by chris1111** [comment] 2023-02-08 21:17
@mikebeaton 
Ive test LegacyDuet boot file of release  0.8.9, 0.8.8, 0.8.7, 0.8.6, 0.8.5, 0.8.4 , 0.8.3
Same isssue 
LegacyDuet boot file` 0.8.2` Boot OK on EFI 0.8.9 ✅ 

So in my opinion some thing wrong in LegacyDuet Release 0.8.3
I see `Added emulated NVRAM driver for use separately from OpenDuet` ?

**Comment by mikebeaton** [comment] 2023-02-08 22:05
> I see Added emulated NVRAM driver for use separately from OpenDuet ?

I don't believe it's that. It's been thoroughly tested. The first time into OpenDuet (after that change) you would expect there to be no NVRAM store (the first time only, not after that) and you would expect it to create an NVARM folder. The warning you are seeing is not the issue.

**Comment by mikebeaton** [comment] 2023-02-10 23:15
Apologies, only just had a chance to look at this properly, this WARN level error occurs the first time you load emulated NVRAM, because there is no nvram.plist file present, until you have installed the script. You have OpenCore set to halt on WARN with HaltLevel.

**Closed** 2023-02-10 23:30 UTC
Labels: project:oc, project:duet

**Comment by chris1111** [comment] 2023-02-10 23:50
Ok thanks 
see my HaltLevel
![Screenshot 2023-02-10 at 6 43 08 PM](https://user-images.githubusercontent.com/6248794/218223042-56ffb1c1-b4fe-411e-92c8-a53d0e658551.png)

I remove all number then this is what I have now

Do you have anny number to try?


![IMG_2824](https://user-images.githubusercontent.com/6248794/218223286-ffa96b30-3d85-4ddf-b9d9-40298d2c85ef.png)

**Comment by mikebeaton** [comment] 2023-02-11 02:18
Your HaltLevel is WARN | ERROR , please set it to ERROR (2147483648).

**Comment by chris1111** [comment] 2023-02-11 10:29
> Your HaltLevel is WARN | ERROR , please set it to ERROR (2147483648).

Thanks for the reply

I already try this value last night  its the value in DOC/Sample.plist 
It give me same red screen

**Comment by mikebeaton** [comment] 2023-02-13 01:44
@chris1111 - In testing the various versions of OpenDuet above, you basically showed that there is a warning message for no NVRAM file on first load of Duet from 0.8.3 upwards (since the emulated NVRAM was updated with several features useful to Duet users, including saving CTRL+Enter changes to the NVRAM file, at that version), and since you had abort at WARN set in your config.

If we switch to abort at ERROR only (not ERROR + WARN) then we will not get stopped by that, and instead we hit a segfault? Why? I suspect it is an installation issue. It is not being otherwise reported.

If you still believe it is an OC issue, the best way to pin down the commit at which a problem happened is bisection:

> Find a newer commit which has the problem. Find an older commit which does not have the problem. Then, test a commit half way between them. Then, depending on whether this has the problem or not, it becomes the latest known commit with the problem, or the earliest known commit without it. And we start again. By choosing a commit half way each time, you can find the problem commit within 32 commits in 5 tests, or within 1024 commits in 10 tests. (git has tools to assist with this 'bisection' process, but you can also do it manually.)

OC builds are listed here: https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true

**Comment by chris1111** [comment] 2023-02-18 14:18
> @chris1111 - In testing the various versions of OpenDuet above, you basically showed that there is a warning message for no NVRAM file on first load of Duet from 0.8.3 upwards (since the emulated NVRAM was updated with several features useful to Duet users, including saving CTRL+Enter changes to the NVRAM file, at that version), and since you had abort at WARN set in your config.
> 
> If we switch to abort at ERROR only (not ERROR + WARN) then we will not get stopped by that, and instead we hit a segfault. Why? I suspect it is an installation issue. It is not being otherwise reported.
> 
> If you still believe it is an OC issue, the best way to pin down the commit at which a problem happened is bisection:
> 
> > Find a newer commit which has the problem. Find an older commit which does not have the problem. Then, test a commit half way between them. Then, depending on whether this has the problem or not, it becomes the earliest known commit with the problem, or the latest known commit without it. And we start again. By choosing a commit half way each time, you can find the problem commit within 32 commits in 5 tests, or within 1024 commits in 10 tests. (git has tools to assist with this 'bisection' process, but you can also do it manually.)
> 
> OC builds are listed here: https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true


Ok thank you mike I will try to find

**Comment by chris1111** [comment] 2023-04-28 16:05
So after a couple more test and using `LogoutHook` on my SSD ventura for testing this utility, I have the idea to copy the folder NVRAM and its content to  my test USB install macOS Ventura ➦ OC 0.9.2 Duet and strangely its work without issue 

In my starting post issue I told you the OC try to locate Emulated  NVRAM then create an Empty folder NVRAM
See previous picture

![217639146-77d29080-2fbc-43a2-acb9-5bf24a96fd88](https://user-images.githubusercontent.com/6248794/235196911-789a61eb-c852-4921-a5ab-2de65f8ae574.jpeg)

Problemes is gone also Red screen gone by adding this folder 
![Screenshot 2023-04-28 at 12 01 57](https://user-images.githubusercontent.com/6248794/235197386-d7076f2b-3a90-41f9-90cf-37b17f4bcb87.png)

So what you think? 
Why new OpenCore Duet work with this folder then old OpenCore is not need?

**Comment by chris1111** [comment] 2023-04-30 13:02
Last night after installing macOS Ventura on my Dell Optiplex 790 Legacy PC, during the istallation after the third reboot macOS Installer or OpernCore rename my nvram.plist to nvram.used so error Emulated load failled appears, I simply duplicate the file then rename one the duplicate file nvram,.plist and I lock the file

![Screenshot 2023-04-30 at 09 00 51](https://user-images.githubusercontent.com/6248794/235354299-c24f74b9-d462-4c7c-8f2b-2a1bc64debb2.png)


issue as never revenue because I make another install for making sure

**Comment by chris1111** [comment] 2023-05-07 18:19
[resolved.](https://github.com/acidanthera/bugtracker/issues/2206#issuecomment-1537500228)
