### ISSUE TITLE
Character display abnormally in OpenCoreShell edit

### ISSUE THREAD

**Issue by gongzhenjeef** [acidanthera/bugtracker#402] opened 2019-07-01 00:24 UTC
I use UEFI Shell to edit config.plist some time for convenience. After OpenCore support Tools entry, I added latest release of OpenCoreShell to it.
On my laptop, the tab character is displayed as corresponding single white rectangle with correct indentation . I also added Shell64U.efi from Clover package and that one functions normally.
However, the tab character just don't display on my desktop. There's no indent between different levels. But I still have to move cursor corresponding characters behind to edit a character. E.g. to add content to <string></string>, I have to move the cursor under second "r" to insert at a correct position.

By the way, will OC support reload config.plist at entry selection menu or loading some config1.plist like Clover? Maybe a new separate issue is needed?

**Comment by vit9696** [comment] 2019-07-02 19:31
Hi, I am not sure what the issue is. Does Clover shell fail to display symbols or what? If so, this is probably out of our scope… We have a list of known shell issues here: https://github.com/acidanthera/bugtracker/issues/364.

As for reloading config, most of the stuff, like SMBIOS patches, ACPI, or UEFI drivers and protocols are from hard to impossible to revert and redo. We believe our best choice here is to reboot, with ctrl+alt+del key combination it is fairly quick.

**Comment by gongzhenjeef** [comment] 2019-07-03 00:37
Hello, I copied Shell64U.efi from Clover and added it to OC Tools. On both machine, their shell could edit config.plist without this symbol issue.

**Comment by vit9696** [comment] 2019-07-05 11:37
KK, marking as resolved.

**Closed by vit9696** 2019-07-05 11:37 UTC
Labels: project:shell
