### ISSUE TITLE
BrightnessKey does not respond to modifier for quarter step increment

### ISSUE THREAD

**Issue by zhen-zen** [acidanthera/bugtracker#1202] opened 2020-10-06 01:28 UTC
With `Option-Shift-Vol+-` or `Option-Shift-Brightness+-`, related adjustment could be more preciser at a 1/4 step. 

However, it seems that the modifier does not work when it's from separate HID keyboards. After the separation, the brightness one doesn't respond to the modifier while volume one still works.

My proposal is to add a specific message sending keyboard event to VoodooPS2 or other keyboard. If there's no kext responding to the message (via bool `eatKey`), it will then fallback to the driver itself.

cc @usr-sse2

**Comment by zhen-zen** [comment] 2020-10-06 01:43
I drafted the first part in https://github.com/acidanthera/VoodooPS2/pull/31

**Comment by vit9696** [comment] 2020-10-06 09:42
This sounds right to me design-wise. Is there a particular reason besides the Xcode issues it is marked as draft?

**Comment by zhen-zen** [comment] 2020-10-06 16:04
It will cause a KP as well at https://github.com/acidanthera/BrightnessKeys/blob/123b2d42f30ed7637f021e2de2bf7924ba8c746a/BrightnessKeys/BrightnessKeys.cpp#L169. I think they are related since "jump to definition" on the last "BrightnessKeys::notificationHandler" will not go to the exact method below, but to `IOService.h` where is referred by `OSMemberFunctionCast`.

**Comment by vit9696** [comment] 2020-10-06 16:28
The jumping and Xcode issues are all "fine", if you check any other `OSMemberFunctionCast` you will see that it has exactly the same issue. May I see the exact panic you get?

**Comment by zhen-zen** [comment] 2020-10-06 21:01
Unfortunately, it just freeze during `start()` and I couldn't get any information via bootloader or `kextutil`. And the kext panic at exact that line, maybe some RTTI issue? Earlier with `VoodooPS2`, I got similar issue using `OSDynamicCast` when `com.apple.iokit.IOACPIFamily` is missing from `Info.plist`. But it seems that nothing's missing.

And the Xcode one is a bit confusing, I'm not sure if they are connected. I use the same code for notification in https://github.com/zhen-zen/YogaSMC/blob/master/YogaSMC/YogaWMI.cpp#L130 and jump there would direct to the exact methods. However, on VoodooPS2 it's broken as well.

<img width="1093" src="https://user-images.githubusercontent.com/66577170/95259355-e8ce5280-07db-11eb-97f3-843a040d2ce0.png">
<img width="1036" src="https://user-images.githubusercontent.com/66577170/95259387-f4217e00-07db-11eb-95ac-2a7dcd3cdd62.png">

**Comment by vit9696** [comment] 2020-10-08 07:12
Could it be due to different definitions in the SDK? You probably do not use MacKernelSDK in YogaSMC yet, do you? Try with and without it, maybe it clarifies anything.

Also, try reimplementing that cast in your code and adding some surrounding prints, maybe it helps to understand where exactly it freezes.

**Comment by zhen-zen** [comment] 2020-10-10 09:17
Yes, you are right. I just switched to MacKernelSDK and then that part won't jump to specific function in Xcode.

And I finally got some kind of clue with the panic. It will panic as long as `_NotificationServices` is accessed. I changed that to OSArray and it still panic. Right after the notifier is added, it will panic at the `setObject` line in `NotificationHandler`. Also, if I commented out that sections, it will still panic when pressing the key at `getCount()` line in `dispatchMessages`

Another unexpected issue is with the `propertyMatching` method. Generated `IOPropertyMatch` dictionary contains nothing instead of the notification key. So every drivers are matched then.

I suspect that something's wrong at init() that fails both OSSet and OSSymbol.

**Comment by vit9696** [comment] 2020-10-10 10:35
Well, as for MacKernelSDK, the cause is most likely some change in the headers themselves. Try to identify them maybe?

As for `_notificationServices`, did you check it for null?

**Comment by zhen-zen** [comment] 2020-10-10 17:24
Yes, I added both non-null check there, but the issue still. Now I moved initialization of those two variable to `start()` and it doesn't cause any kps. Quite weird since other kexts could initialize correctly at `init()`.

**Comment by vit9696** [comment] 2020-10-11 12:36
`ADDPR(debugEnabled)` should be handled by Lilu I believe. Along with the `-liludbgall` key. Am I misunderstanding something?

**Comment by zhen-zen** [comment] 2020-10-11 18:14
No. I suppose everything's broken in `init()` for this kext. After I moved `ADDPR(debugEnabled) = checkKernelArgument("-brkeysdbg") || checkKernelArgument("-liludbgall");` there, it failed to parse my `boot-arg` and display debug log.

**Closed** 2020-12-26 22:37 UTC
Labels: project:brkeys
