### ISSUE TITLE
[AudioDxe] Open PCI I/O protocol - Access Denied

### ISSUE THREAD

**Issue by seffs** [acidanthera/bugtracker#2201] opened 2023-01-17 16:51 UTC
AudioDxe is unable to connect to the audio device. Here the relevant parts in the debugging log:

```
01:333 00:112 OCAU: OcAudioInstallProtocols (0, 0)
01:446 00:112 OCAU: 4B228577-6274-4A48-82AE-0713A1171987 protocol - Not Found
01:559 00:112 OCAU: C32332DF-FC56-4FE1-9358-BA0D529B24CD protocol - Not Found
01:671 00:112 OCAU: F4CB0B78-243B-11E7-A524-B8E8562CBAFA protocol - Not Found
01:784 00:112 OCAU: 3224B169-EC34-46D2-B779-E1B1687F525F protocol - Not Found
....
06:652 00:111 OC: Driver AudioDxe.efi at 3 () is being loaded...
06:764 00:112 OCABC: EfiBootRt candidate - <nil>
06:875 00:111 OCABC: IsEfiBootRt 0 (BP 1, Apple 0)
06:986 00:111 OCB: Arch filtering 0(212992)->6FA49018(212992) caps 4 - Success
07:126 00:139 OCCPU: TSC Adjust 0
07:237 00:111 OCCPU: Known Model Core Crystal Clock Frequency    24000000Hz
07:349 00:111 OCCPU: CPUFrequencyFromART  2592000000Hz  2592MHz = 24000000 * 216 / 2
07:460 00:111 HDA: GPIO setup stages 0x0 GPIO pin mask 0x0 (auto) Restore NSNPEN 0 Force device <null string> Setup delay 0
07:572 00:111 OC: Driver AudioDxe.efi at 3 is successfully loaded!
07:683 00:111 OC: Driver AudioDxe.efi at 3 needs connection.
07:795 00:111 OC: Connecting drivers...
07:920 00:125 HDA: Connecting controller - PciRoot(0x0)/Pci(0x1F,0x3)
08:031 00:111 HDA: Open PCI I/O protocol (try DisconnectHda quirk?) - Access Denied
...
11:015 00:001 OCAU: OcAudioInstallProtocols (0, 0)
11:017 00:001 OCAU: 4B228577-6274-4A48-82AE-0713A1171987 protocol - Success
11:019 00:001 OCAU: C32332DF-FC56-4FE1-9358-BA0D529B24CD protocol - Success
11:021 00:001 OCAU: F4CB0B78-243B-11E7-A524-B8E8562CBAFA protocol - Success
11:023 00:001 OCAU: 3224B169-EC34-46D2-B779-E1B1687F525F protocol - Not Found
11:024 00:001 OCAU: No AudioIo instances - Not Found
11:026 00:001 OCAU: Cannot find specified audio device - Not Found
11:028 00:001 OC: Audio connection failed - Not Found
```

When running `pci` in OpenShell `PciRoot(0x0)/Pci(0x1F,0x3)` gets reported as `Mixed mode device`. 
I've already verified that PCI address and codec are correct with ioreg. This is what I've tried so far:
- Activate DisconnectHda
- --force-device=<pci-address> argument in AudioDxe
- --gpio-setup argument in AudioDxe  

*** Removed PlatformInfo from EFI.zip

[EFI.zip](https://github.com/acidanthera/bugtracker/files/10437437/EFI.zip)
[opencore-2023-01-17-120625.txt](https://github.com/acidanthera/bugtracker/files/10437401/opencore-2023-01-17-120625.txt)

Additional info for better context:
- Acer E5
- Realtek ALC255 (Maybe not relevant for AudioDxe, but I had some trouble finding the appropiate layout-id. It needs ComboJack fix for headset mic to work)
- This machine is kind of special regarding UEFI boot. A manual entry has to be done for OC in the FW for it to be detected. Secure Boot is deactivated already. Some security check may prevent the bootloader of connecting to the device, but given that everything else works, this might not be the case.

**Comment by mikebeaton** [comment] 2023-01-17 17:05
At first look glance, it looks to me like you have tried the right things, and it is surprising that the result is 'Access Denied'.

If anyone else looking at this can spot what the issue is, please do say so - but for now it looks to me like you've got a genuine new issue on your hardware. Please be aware the AudioDxe development may not be highest priority at the moment (especially e.g. without equivalent hardware on which to reproduce the bug). All the same, if the issue is valid, as it looks, it can be tracked here and addressed in due course, or when more info becomes available.

**Comment by seffs** [comment] 2023-01-17 17:20
Noted. I added some observations too. Thanks for the effort

**Comment by mikebeaton** [comment] 2024-01-04 05:17
@seffs - Could you try the `macOS XCODE5 Artifacts` from this build https://github.com/acidanthera/OpenCorePkg/actions/runs/7405598402 to see if it helps?

(You need to be logged in to GitHub and you need to wait for a moment before the build artifacts appear.)

**Comment by mikebeaton** [comment] 2024-01-11 22:27
Tested and the suggested change, now on master as https://github.com/acidanthera/OpenCorePkg/commit/b24d13e6ab6c5d3f0f8dd59f12164079fbcd0600, fixes this. You are correct that these Acer's are [_very_ quirky](https://bbs.archlinux.org/viewtopic.php?id=260808) in terms of how you have to enable boot entries.

**Closed by mikebeaton** 2024-01-11 22:27 UTC
Labels: help wanted, project:audio

**Comment by nelthera** [comment] 2024-01-13 05:04
Hello there, Im just starting my hackintosh build and encounter the error, I see that there's a fix on the comment above but I don't know what am I supposed to change, could you please give a short instruction according what needs to be changed please.

here's my configuration

![Screenshot 2024-01-13 at 12 02 14](https://github.com/acidanthera/bugtracker/assets/156487737/096223f7-6267-44f5-93c3-63d14aaffb28)

macOS Ventura 13.6.3
AMD Ryzen 9 5900HX 
AMD Radeon Vega 8 (working)
I cannot really configure what's the audio I am using

here's the last log of the OpenCore

> 00:000 00:000 
Snp->undi.initialize()  8000h:6h
00:577 00:577 HDA: Open PCI I/O protocol (try DisconnectHda quirk?) - Access Denied
00:637 00:059 LNX: ScanLoaderEntries \ - Volume Corrupt
00:638 00:001 BEP: Unable to fetch boot entries - Volume Corrupt
01:458 00:820 AAPL: #[EB.H.IS|!] Err(0xE) <- RT.GV boot-signature 7C436110-AB2A-4BBB-A880-FE41995C9F82
01:459 00:000 AAPL: #[EB.H.IS|!] Err(0xE) <- RT.GV boot-image-key 7C436110-AB2A-4BBB-A880-FE41995C9F82
01:460 00:000 AAPL: #[EB|H:IS] 0
01:461 00:000 AAPL: #[EB|LOG:INIT] 2024-01-13T04:40:05
01:462 00:000 AAPL: #[EB|VERSION] <"boot.efi 577.140.2~22 (Official), built 2023-10-28T12:17:33-0700">
01:463 00:000 AAPL: #[EB|BUILD] <"BUILD-INFO[403]:{"DisplayName":"boot.efi","DisplayVersion":"577.140.2~22","RecordUuid":"20D8C842-28B8-49D3-9BAF-9FBE0DB28178","BuildTime":"2023-10-28T12:17:33-0700","ProjectName":"efiboot","ProductName":"boot.efi","SourceVersion":"577.140.2","BuildVersion":"22","BuildConfiguration":"Release","BuildType":"Official","Compiler":"clang-1403.0.22.11","SdkVersion":"13.6","SdkBuild":"22G417","TargetArchitectures":"x86_64"}">

[EFI.zip](https://github.com/acidanthera/bugtracker/files/13926820/EFI.zip)

**Comment by xiao-mantou** [comment] 2024-01-13 07:23
@nelthera 
Just updated opencore to new built mention [above](https://github.com/acidanthera/bugtracker/issues/2201#issuecomment-1876323924). It fixed `HDA: Open PCI I/O protocol (try DisconnectHda quirk?) - Access Denied` for me on HP laptop.

**Comment by seffs** [comment] 2024-01-13 23:52
@mikebeaton I just tested it on my E5.

It works! Thanks a lot
