### ISSUE TITLE
RestricEvents CPU Name with AMD

### ISSUE THREAD

**Issue by Shaneee** [acidanthera/bugtracker#1625] opened 2021-05-03 22:02 UTC
I'm having issues with RestrictEvents with regards to changing the CPU name when using an AMD CPU. CPU is shown as Unknown with or without RestrictEvents.kext in place and with or without any of the accompanying boot args. I've attached the Lilu debug log.

AMD Ryzen 5 5600X
MSI MPG X570 Gaming Plus

Thanks

[Lilu_1.5.4_20.5.txt.zip](https://github.com/acidanthera/bugtracker/files/6418013/Lilu_1.5.4_20.5.txt.zip)

**Comment by simonintense** [comment] 2021-05-03 22:25
Hiya,
Im having the same problem as Shaneee using a 5900X on a Asus STRIX X570-E. 
With or without the boot argument revcpu=1 my 5900X is listing as a 12-Core Intel Xeon W. 
Ive also attached a Lilu begun log.

Thanks, 

[Lilu_1.5.3_20.4.txt.zip](https://github.com/acidanthera/bugtracker/files/6418129/Lilu_1.5.3_20.4.txt.zip)

**Comment by vit9696** [comment] 2021-05-03 22:54
@Shaneee for you the issue should be misconfigured OpenCore. Please attach the OpenCore DEBUG log and config.plist. Make sure it is the latest 0.6.9 version.

@simonintense for you either RestrictEvents is RELEASE, or you forgot to add `-liludbgall`. Please fix. Also include OpenCore log and config.plist.

**Comment by simonintense** [comment] 2021-05-03 23:43
Hi Vit,
Sorry about that,  I was using the debug version of RestrictEvents and Lilu but I guess I must of made a typo when I added the boot arguments.
Here it is again plus my OpenCore Log and Config.plist.

Thanks Again, 

[Lilu_1.5.3_20.4.txt.zip](https://github.com/acidanthera/bugtracker/files/6418375/Lilu_1.5.3_20.4.txt.zip)
[opencore-2021-05-03-233649.txt.zip](https://github.com/acidanthera/bugtracker/files/6418377/opencore-2021-05-03-233649.txt.zip)
[Config.plist.zip](https://github.com/acidanthera/bugtracker/files/6418378/Config.plist.zip)

**Comment by vit9696** [comment] 2021-05-04 00:07
@simonintense it says you have just 2 cores. Do you have any special configuration? How many cores does macOS see? Try running `sysctl machdep.cpu` in terminal?

**Comment by simonintense** [comment] 2021-05-04 00:20
It shows all my cores in big sur and all results from tests are normal and where you would expect them to be. 
apps like cinibench and luxmark see my 5900x and use all its cores.

**Comment by vit9696** [comment] 2021-05-04 00:29
Well, I still need `sysctl machdep.cpu` to understand what is going on.

**Comment by simonintense** [comment] 2021-05-04 00:37
Sorry I turned off my System and was about togo to bed and responding from my iPad.
Heres the results of sysctl machdep.cpu


[CPU INFO.zip](https://github.com/acidanthera/bugtracker/files/6418517/CPU.INFO.zip)

**Comment by vit9696** [comment] 2021-05-04 00:38
Thanks! The log output is correct here, but for some reason it is not giving me what I request in RestrictEvents. I will ping you back once I discover it.

**Comment by simonintense** [comment] 2021-05-04 00:39
Thank you, Amazing work :)

**Comment by vit9696** [comment] 2021-05-04 01:09
Please try https://github.com/acidanthera/RestrictEvents/commit/b5ace0985f0aeb3e6a3d6475b8cdf87889d5b6e1. Will also need new Lilu logs.

**Comment by Shaneee** [comment] 2021-05-04 08:49
> @Shaneee for you the issue should be misconfigured OpenCore. Please attach the OpenCore DEBUG log and config.plist. Make sure it is the latest 0.6.9 version.
> 

Here's the OpenCore DEBUG log and my config.

[Archive.zip](https://github.com/acidanthera/bugtracker/files/6419933/Archive.zip)

**Comment by simonintense** [comment] 2021-05-04 08:59
Just tried with the latest RestrictEvents and I'm getting the same results.

[Lilu_1.5.3_20.4.txt.zip](https://github.com/acidanthera/bugtracker/files/6420005/Lilu_1.5.3_20.4.txt.zip)

**Comment by aluveitie** [comment] 2021-05-04 14:09
Maybe this is helpful, the AMD power management kext also reads the CPU details (unaffected by kernel patches):
https://github.com/trulyspinach/SMCAMDProcessor/blob/master/AMDRyzenCPUPowerManagement/AMDRyzenCPUPowerManagement.cpp

**Comment by vit9696** [comment] 2021-05-04 20:06
@Shaneee @simonintense please try https://github.com/acidanthera/RestrictEvents/commit/491676a731ee0ed0c56e82556c15a4de218dde17. Need just the Lilu logs (regardless whether it works).

@aluveitie thx, this code is basically mine though. Problem is, AMD patches are seemingly incorrect, and they break CPU topology in macOS in a way that you cannot distinguish 1 CPU and 2 CPUs for whatever reason at least on @simonintense computer. His topology contains just the 2 cores on one CPU, while it is obviously not true.

**Comment by simonintense** [comment] 2021-05-04 20:49
@vit9696 The latest version is working and now displaying my 5900X Correctly in About This Mac. 
Excellent  :)

[Lilu_1.5.3_20.4.txt.zip](https://github.com/acidanthera/bugtracker/files/6423847/Lilu_1.5.3_20.4.txt.zip)

**Comment by Shaneee** [comment] 2021-05-04 21:20
Still showing as Unknown. I assume that in it's self is the main issue I've got but not sure as to why it's showing as that,

[Lilu_1.5.4_20.5.txt.zip](https://github.com/acidanthera/bugtracker/files/6424020/Lilu_1.5.4_20.5.txt.zip)

![Screenshot 2021-05-01 at 22 18 01](https://user-images.githubusercontent.com/16089049/117071382-f5da0280-ad26-11eb-9a78-05334bf75118.png)

**Comment by vit9696** [comment] 2021-05-05 02:00
@simonintense great. I still want to confirm something. Could you test https://github.com/acidanthera/RestrictEvents/commit/afc6961292c3dc862dded76bcd6ebed366f6c39a and provide Lilu log? Want to make sure the hack with the package count is really needed and file a bug on AMD-OSX.

@Shaneee I can say that you clearly use an old version. In a very old commit I made a mistake (wrote choise instead of chosen) and yet you have choise. Make sure you picked the latest one from https://dortania.github.io/builds/?product=RestrictEvents&viewall=true.

Yet that sounds weird. Am I right that without RestrictEvents and with ProcessorType = 0 you see Unknown CPU? Can you provide `dmidecode` output in this case? I only need the `Apple specific Processor Type` part. This sounds like either you are using an old OpenCore or there is a bug in OpenCore which we need to fix.

**Comment by Shaneee** [comment] 2021-05-05 08:52
> @Shaneee I can say that you clearly use an old version. In a very old commit I made a mistake (wrote choise instead of chosen) and yet you have choise. Make sure you picked the latest one from https://dortania.github.io/builds/?product=RestrictEvents&viewall=true.
> 
> Yet that sounds weird. Am I right that without RestrictEvents and with ProcessorType = 0 you see Unknown CPU? Can you provide `dmidecode` output in this case? I only need the `Apple specific Processor Type` part. This sounds like either you are using an old OpenCore or there is a bug in OpenCore which we need to fix.

Yes with ProcessorType set to 0 with or without RestrictEvents then I see Unknown CPU. sysctl reports it correctly however.

I can't see 'Apple specific Processor Type' from dmidecode but here's the Processor section from it,
`Handle 0x0083, DMI type 4, 48 bytes
Processor Information
	Socket Designation: AM4
	Type: Central Processor
	Family: Zen
	Manufacturer: Advanced Micro Devices, Inc.
	ID: 10 0F A2 00 FF FB 8B 17
	Signature: Family 25, Model 33, Stepping 0
	Flags:
		FPU (Floating-point unit on-chip)
		VME (Virtual mode extension)
		DE (Debugging extension)
		PSE (Page size extension)
		TSC (Time stamp counter)
		MSR (Model specific registers)
		PAE (Physical address extension)
		MCE (Machine check exception)
		CX8 (CMPXCHG8 instruction supported)
		APIC (On-chip APIC hardware supported)
		SEP (Fast system call)
		MTRR (Memory type range registers)
		PGE (Page global enable)
		MCA (Machine check architecture)
		CMOV (Conditional move instruction supported)
		PAT (Page attribute table)
		PSE-36 (36-bit page size extension)
		CLFSH (CLFLUSH instruction supported)
		MMX (MMX technology supported)
		FXSR (FXSAVE and FXSTOR instructions supported)
		SSE (Streaming SIMD extensions)
		SSE2 (Streaming SIMD extensions 2)
		HTT (Multi-threading)
	Version: AMD Ryzen 5 5600X 6-Core Processor
	Voltage: 1.1 V
	External Clock: 102 MHz
	Max Speed: 3700 MHz
	Current Speed: 3700 MHz
	Status: Populated, Enabled
	Upgrade: Socket AM4
	L1 Cache Handle: 0x0080
	L2 Cache Handle: 0x0081
	L3 Cache Handle: 0x0082
	Serial Number: Unknown
	Asset Tag: Unknown
	Part Number: Unknown
	Core Count: 6
	Core Enabled: 6
	Thread Count: 12
	Characteristics:
		64-bit capable
		Multi-Core
		Hardware Thread
		Execute Protection
		Enhanced Virtualization
		Power/Performance Control`

**Comment by vit9696** [comment] 2021-05-05 09:03
Are you using the latest version of [dmidecode](https://github.com/acidanthera/dmidecode/releases)? On my board I see the following in the end of the output, and personally I expect the same from yours.

In case you do not want to share this in public, please send me the complete output in private along with the IOReg saved with IORegistryExplorer. You can use my nickname at `pm.me` domain.

```
System Boot Information
	Status: No errors detected

Handle 0x0029, DMI type 131, 8 bytes
0000: 83 08 29 00 05 07 00 00

Apple specific Processor Type
	CPU: 0x0705

Handle 0x0027, DMI type 128, 96 bytes
0000: 80 60 27 00 00 00 00 00 37 E1 0F F8 3F FF 1F FF
0010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Apple specific FirmwareVolume
	FirmwareFeatures: 0xF80FE137
	FirmwareFeaturesMask: 0xFF1FFF3F

Handle 0x002B, DMI type 133, 12 bytes
0000: 85 0C 2B 00 01 00 00 00 28 A2 C3 A4

Apple specific PlatformFeature
	PlatformFeature: 0x00000001

Handle 0x002C, DMI type 134, 20 bytes
0000: 86 14 2C 00 32 2E 32 32 46 30 30 31 36 00 00 00
0010: 00 00 00 00

Apple specific SmcVersion
	SmcVersion: 2.22F0016

Handle 0x0026, DMI type 127, 4 bytes
0000: 7F 04 26 00

End Of Table
```

**Comment by simonintense** [comment] 2021-05-05 09:03
The latest commit is working great for me.
Heres the log for it. :)

[Lilu_1.5.3_20.4.txt.zip](https://github.com/acidanthera/bugtracker/files/6426002/Lilu_1.5.3_20.4.txt.zip)

**Comment by vit9696** [comment] 2021-05-05 09:09
@simonintense, yes, you have 2+10 cores in the CPU topology. This looks broken, I am going to file a bug in AMD-OSX, but could you confirm that you use the latest version of the AMD patches just in case?

**Comment by simonintense** [comment] 2021-05-05 09:11
Yes indeed, the kernel patches are all up to date.

**Comment by Shaneee** [comment] 2021-05-05 11:15
> Are you using the latest version of [dmidecode](https://github.com/acidanthera/dmidecode/releases)? On my board I see the following in the end of the output, and personally I expect the same from yours.
> 
> In case you do not want to share this in public, please send me the complete output in private along with the IOReg saved with IORegistryExplorer. You can use my nickname at `pm.me` domain.

Didn't have the latest. I've now got that and I've sent you both requested files.

**Comment by vit9696** [comment] 2021-05-05 13:10
@Shaneee checked both.

```
Apple specific Processor Type
	CPU: 0x0F01
```

The same value is also present in `IODeviceTree:/cpus/C000`. This means the specified CPU is Xeon W and OpenCore is working correctly. If you stilll see `Unknown` in About Mac instead of Intel Xeon W, then you either have some weird AMD bug or corrupted system files. Both cases are out of the scope of this issue. Still:

* The former can be checked by providing `sysctl machdep.cpu` output as macOS uses `machdep.cpu.core_count` to determine the CPU description string in addition to the SMBIOS value. Please provide that and I can confirm that it is correct or not.
* The latter can be checked by installing a fresh macOS copy.

I am closing this as there seemingly are no issues on our end: OpenCore provides valid data to the system, RestrictEvents chooses the patch correctly. Feel free to provide more info though.

**Closed by vit9696** 2021-05-05 13:10 UTC
Labels: project:rev

**Comment by Pavo-IM** [comment] 2021-05-18 00:51
Just wanted to add the issue is also coming up when using macOS on KVM+Qemu when using a specific CPU model.

```xml
<cpu mode='custom' check='none'>
  <model fallback='forbid'>Cascadelake-Server</model>
  <topology sockets='1' dies='1' cores='16' threads='2'/>
</cpu>
```

and since my CPU is AMD Threadripper 3970X I also add this at the end

```xml
<qemu:commandline>
  <qemu:arg value='-cpu'/>
  <qemu:arg value='Cascadelake-Server,vendor=GenuineIntel,+invtsc,kvm=on'/>
</qemu:commandline>
```

Here is the log file:
[Lilu_1.5.4_20.5.txt](https://github.com/acidanthera/bugtracker/files/6497600/Lilu_1.5.4_20.5.txt)

Here is what System Profiler shows:
![Screen Shot 2021-05-17 at 8 44 34 PM](https://user-images.githubusercontent.com/33814640/118573974-88c86300-b751-11eb-8cc5-5b7fac4a882c.png)

And here is what `sysctl machdep.cpu` shows:
`machdep.cpu.brand_string: Intel Xeon Processor (Cascadelake)`

**Comment by Pavo-IM** [comment] 2021-05-18 14:57
It seems like its looking at the CPUInfo EBX,ECX and EDX to determine if its a `GenuineIntel` or a `AuthenticAMD`. Anyway to make it override that detection if `revcpu=1` and only use the value of `revcpuname` if given, but if no value given use the `mechdep.cpu.brand_string`?

**Comment by vit9696** [comment] 2021-05-18 21:43
Well, specifying revcpu=1 does enable the code regardless of the CPUID vendor, but it still needs to know the core count, and I presume it works incorrectly given the screenshot showing single core Xeon. Can you provide the log output?

**Comment by Pavo-IM** [comment] 2021-05-18 21:46
The log output is in the above comment, and yes it shows the same with or without RestrictEvents enabled.

**Comment by vit9696** [comment] 2021-05-18 21:50
May I see `dmidecode` and `sysctl machdep.cpu` outputs?

**Comment by Pavo-IM** [comment] 2021-05-19 12:25
Sure thing.
[dmidecode_dump.txt](https://github.com/acidanthera/bugtracker/files/6508625/dmidecode_dump.txt)
[macdep.cpu_dump.txt](https://github.com/acidanthera/bugtracker/files/6508626/macdep.cpu_dump.txt)

**Comment by vit9696** [comment] 2021-05-19 12:47
Well, no bug on our side as your CPU topology is broken.

```
machdep.cpu.core_count: 1
machdep.cpu.cores_per_package: 16
machdep.cpu.logical_per_package: 32
```

It says that you have 16 cores and 32 vcores on the package, but only one core is available. I believe you should fix that, as `machdep.cpu.core_count` should show 16.

**Comment by Pavo-IM** [comment] 2021-05-19 13:10
Do you know how I can fix this with KVM+Qemu?

**Comment by vit9696** [comment] 2021-05-19 13:24
No, but you can ask on Qemu Devel maybe (https://lists.nongnu.org/mailman/listinfo/qemu-devel)?

**Comment by Pavo-IM** [comment] 2021-05-19 16:12
So... I have done little experimenting and here are the new results.
![Screen Shot 2021-05-19 at 12 06 31 PM](https://user-images.githubusercontent.com/33814640/118846537-cf75a480-b89a-11eb-8af4-9b877f66151f.png)
![Screen Shot 2021-05-19 at 12 06 27 PM](https://user-images.githubusercontent.com/33814640/118846553-d4d2ef00-b89a-11eb-932f-686536f4d8e1.png)

I changed the cpu section into this....
```xml
<cpu mode='host-passthrough' check='none' migratable='on'>
    <cache mode='passthrough'/>
    <feature policy='require' name='topoext'/>
 </cpu>
```

Changed the qemucommandline section into this....
```xml
<qemu:commandline>
    <qemu:arg value='-device'/>
    <qemu:arg value='isa-applesmc,osk=ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc'/>
    <qemu:arg value='-smbios'/>
    <qemu:arg value='type=2'/>
    <qemu:arg value='-cpu'/>
    <qemu:arg value='host,vendor=GenuineIntel,+invtsc,kvm=on'/>
</qemu:commandline>
```

Added the following to the Emulate section of the config.plist...
![Screen Shot 2021-05-19 at 12 09 42 PM](https://user-images.githubusercontent.com/33814640/118846873-27141000-b89b-11eb-8f73-40a535ca03be.png)

And removed the topology kernel patch out of the config.plist. 

RestrictEvents and Lilu's debug dump below....
[Lilu_1.5.4_20.5.txt](https://github.com/acidanthera/bugtracker/files/6510242/Lilu_1.5.4_20.5.txt)

It is still not taking the `revcpuname` value and patching System Info section for CPU brand string. Any other suggestions or experiments you want me to do?

**Comment by vit9696** [comment] 2021-05-19 16:38
Well, currently it sees 1 core: `RestrictEvents       rev: @ (DBG) calculated 1 cores in pkg 0 amd 0`. Single core CPUs were unsupported by RestrictEvents. I fixed it in master, please update.

**Comment by Pavo-IM** [comment] 2021-05-19 17:02
Now it shows as Unknown for CPU in System Info.
![Screen Shot 2021-05-19 at 12 59 31 PM](https://user-images.githubusercontent.com/33814640/118853814-29c63380-b8a2-11eb-9927-e7bb4c49299a.png)

I added 3841 (0F01) for `ProcessorType` in the PlatformInfo > Generic section.

And here is what the different settings for the config.plist is...
![Screen Shot 2021-05-19 at 12 59 04 PM](https://user-images.githubusercontent.com/33814640/118854050-71e55600-b8a2-11eb-9a82-49d2a3e3f79d.png)

Here is the varies dumps....
[dmidecode_dump.txt](https://github.com/acidanthera/bugtracker/files/6510543/dmidecode_dump.txt)
[Lilu_1.5.4_20.5.txt](https://github.com/acidanthera/bugtracker/files/6510544/Lilu_1.5.4_20.5.txt)
[machdep.cpu_dump.txt](https://github.com/acidanthera/bugtracker/files/6510545/machdep.cpu_dump.txt)

**Comment by Pavo-IM** [comment] 2021-05-19 17:09
Got it working now, removed 3841 (0F01) from `ProcessorType` in the PlatformInfo > Generic section.
![Screen Shot 2021-05-19 at 1 08 58 PM](https://user-images.githubusercontent.com/33814640/118855091-6e060380-b8a3-11eb-92c6-d0e9757352e4.png)
![Screen Shot 2021-05-19 at 1 09 02 PM](https://user-images.githubusercontent.com/33814640/118855100-70685d80-b8a3-11eb-8b71-a7befb8425a7.png)

**Comment by Pavo-IM** [comment] 2021-05-19 17:16
Everything working as intended now, Thanks @vit9696.

**Comment by AudioG** [comment] 2021-06-15 19:16
@vit9696 Hi Vit and sorry to bother you but as of the latest commit of RestrictEvents 1.0.3 the CPU info in about this Mac has stopped displaying as a 5900X again. If I roll RestrictEvents back 1 commit and Lilu back by 8 Commits it all starts working again. Very Strange.
Heres the Lilu Logs from 11.4 and 12.0 and also my sysctl output.

[Terminal Saved Output.zip](https://github.com/acidanthera/bugtracker/files/6658109/Terminal.Saved.Output.zip)
[Lilu_1.5.4_20.5.txt.zip](https://github.com/acidanthera/bugtracker/files/6658110/Lilu_1.5.4_20.5.txt.zip)
[Lilu_1.5.4_21.0.txt.zip](https://github.com/acidanthera/bugtracker/files/6658111/Lilu_1.5.4_21.0.txt.zip)

**Comment by vit9696** [comment] 2021-06-15 20:25
Make sure you have the latest version of them all and file a new bugreport. Also test just the RestrictEvents and no other userspace plugin.

**Comment by AudioG** [comment] 2021-06-15 20:28
Ok sure will do thank you. would you prefer it done via 11.4 or 12.0 or does it not matter to you?

**Comment by vit9696** [comment] 2021-06-15 20:33
11.4.

**Comment by dreamwhite** [comment] 2021-08-21 14:17
Hi there,
sorry for bothering you again with this issue but I can't find a way to change the CPU name of a AMD Ryzen 5 2600 (6C/12T) on a ASUS PRIME X470-PRO.

I'm using Lilu 1.5.5 and RestrictEvents 1.0.3 DEBUG versions as well as `-liludbg -revdbg liludump=120` for getting the Lilu debug logs.

Below the config.plist I'm using: [config.plist.zip](https://github.com/acidanthera/bugtracker/files/7025611/config.plist.zip)
Please note that I'm on macOS Big Sur 11.5.2 (20G95) and installed it using `com.apple.recovery.boot` method using `macrecovery.py`.

From the IORegistryExplorer dump I'm noticing that the `cpu-type` value is `<01 0F>` which is for 8+ cores CPU ([source](https://github.com/acidanthera/OpenCorePkg/blob/master/Include/Apple/IndustryStandard/AppleSmBios.h#L138-L145)) which is definitely wrong. 

It should be one of [those](https://github.com/acidanthera/OpenCorePkg/blob/master/Include/Apple/IndustryStandard/AppleSmBios.h#L103-L107).

According to [RestrictEvents README.md](https://github.com/acidanthera/RestrictEvents/#restrictevents) following statement:

> Note: Apple CPU identifier must be 0x0F01 for 8 core CPUs or higher and 0x0601 for 1, 2, 4, or 6 cores. This is the default in OpenCore for non-natively supported CPUs.

Furthermore, in the Lilu debug log, obtained after 120 seconds, there's a strange line:

```
RestrictEvents       rev: @ (DBG) calculated 1 cores in pkg 0 amd 1
RestrictEvents       rev: @ (DBG) calculated 6 cores in pkg 1 amd 1
RestrictEvents       rev: @ (DBG) chosen 6-Core Intel Core i5 patch for 6 core CPU
```
Is this even normal? 😅 
I don't know if it matters, but the system language is Italian. Can this interfere in any way with the RestrictEvents CPU name patching?

I attach also the `dmidecode` output as well as `sysctl machdep.cpu` where it's clearly visible that the CPU is a 6-core and 12-threads:

[dmidecode_output.txt](https://github.com/acidanthera/bugtracker/files/7025641/dmidecode_output.txt)

[sysctl_machdep.cpu.txt](https://github.com/acidanthera/bugtracker/files/7025633/sysctl_machdep.cpu.txt)


Please let me know if you need an IORegistryExplorer dump and how can I send it to you (Telegram, Matrix.org, email address) since I don't wanna spread serial numbers worldwide >>
Thanks in advance and have a nice day
dreamwhite

**Comment by vit9696** [comment] 2021-08-21 14:23
Must set ProcessorType to 0x0601 explicitly in the config.

**Comment by dreamwhite** [comment] 2021-08-21 14:33
> Must set ProcessorType to 0x0601 explicitly in the config.

Oh okay, I updated the comment and read right now your advice. Do you think it's the best choice or OpenCore ProcessorType detection must be changed?

**Comment by vit9696** [comment] 2021-08-21 17:32
No, we do not care enough about AMD to change anything.
