### ISSUE TITLE
Boot Picker Screen not select default picker on Legacy Bios

### ISSUE THREAD

**Issue by huytbt** [acidanthera/bugtracker#1131] opened 2020-08-31 17:25 UTC
Hi team,

I am using HP Z600 Workstation. This does not support EFI and NVRAM, only Bios.
I have installed the emulator NVRAM. I am having a problem on the boot picker. It cannot select default disk.
I go to System Preferences> Startup Disk -> Choose another disk (Catalina HD) -> Reboot.
The boot picker always chooses Preboot (this is Big Sur HD) which I expect is the Catalina HD.
I also check /EFI/nvram.plist and I see it contains Boot0080, efi-boot-device, efi-boot-device-data.
Please help solve this problem.

Thanks

**Comment by vit9696** [comment] 2020-08-31 17:48
Without logs and EFI folder this is a support request, not a bugreport. Closing.

**Closed by vit9696** 2020-08-31 17:48 UTC

**Comment by huytbt** [comment] 2020-08-31 17:51
Sorry @vit9696 , I will update logs EFI folder later.
Sorry for my mistake
