### ISSUE TITLE
Can't boot Recovery if VboxHFS.efi is used

### ISSUE THREAD

**Issue by cattyhouse** [acidanthera/bugtracker#399] opened 2019-06-24 22:28 UTC
macOS 10.14.6 beta 3 (APFS on HP EX900 NVME SSD)
opencore 0.03
config.plist / ConnectDrivers=YES

issue: 

I **don't have any HFS+ partition** on my macOS, however if i load VboxHFS.efi in config.plist, i'm not able to boot into **Recovery**, it shows a Apple logo forever, but if i load HFSPlus.efi instead, then all is well. I have tested this many times, and i spend hours to find out it is the Vboxhfs.efi problem.

Both drivers are able to boot macOS fine. No, I did not use both efi at the same time. Does the order in Drivers array matter? i don't know, did not test that.

**Comment by vit9696** [comment] 2019-06-24 22:38
Recovery images use HFS+ filesystem, thus you are required to have HFS+ driver for recovery to work. We should document it some day in Configuration.pdf.

**Comment by cattyhouse** [comment] 2019-06-24 23:19
iirmc, during the findings, the vboxhfs.efi booted 10.14.5 installer from a hfs+ usb drive fine.

**Comment by vit9696** [comment] 2019-06-24 23:24
Hm, seems that I misread the question. Are you using our driver? I.e. from here: https://github.com/acidanthera/AppleSupportPkg/releases. Others will not work, as they lack bless support.

**Comment by cattyhouse** [comment] 2019-06-24 23:27
I can’t remember where i got vboxhfs.efi, but i know i got all the rest of efi from your repo. I will test the linked one right away. Be right back.

**Comment by cattyhouse** [comment] 2019-06-24 23:33
Ok, i downloaded the vboxhfs.efi from the link, and then did a Hex Fiend compare with the one that failed to boot Recovery, it says Documents are identical.

**Comment by vit9696** [comment] 2019-06-24 23:38
This is quite strange to be honest. We know that recovery booting is very slow with VBoxHFS (at least 3 times slower), but so far it did not fail for us. Could you please upload your Recovery partition contents? It is somewhat unlikely that we will work on it reasonably soon though.

CC @nms42

**Comment by cattyhouse** [comment] 2019-06-24 23:44
sure, it has a size of ~500M, i'm uploading it to my dropbox kinda slow, i'll post link when finishing.

**Comment by cattyhouse** [comment] 2019-06-24 23:59
the Recovery partition is still being uploading. here is a screenshot of the configurations that failed to boot Recovery on SSD. If i change it to HFSPlus.efi, then it will boot. 

<img width="1341" alt="Screen Shot 2019-06-25 at 07 53 53" src="https://user-images.githubusercontent.com/3365320/60059424-15fa0d00-971f-11e9-945e-5ec3f0d89492.png">

**Comment by cattyhouse** [comment] 2019-06-25 00:02
Recovery Partiton, 10.14.6 Beta (18G59b)
https://www.dropbox.com/s/b4ahryl6eowvyfr/30DF1598-C31D-4B8F-9FB2-42DBB19262C0.7z?dl=0

**Comment by cattyhouse** [comment] 2019-06-25 07:20
Update: i did not enable FV2. a friend said he can enter recovery without loading any hfs+ efi, he has FV2 enabled, and he is on macOS 10.14.5

**Comment by nms42** [comment] 2019-06-29 08:14
I have no resources (workbench) to investigate the problem now.

Still, is it possible to boot recovery from previous versions with vboxhfs.efi?

**Comment by cattyhouse** [comment] 2019-06-29 08:18
I only have 10.14.6 beta 3 installed, i'm not able to test other versions. I will test again on 10.14.6 final and feed back

**Comment by nms42** [comment] 2019-06-29 08:51
> I will test again on 10.14.6 final and feed back

If any logs/messages will be available, upload it here, please

**Comment by cattyhouse** [comment] 2019-06-29 08:54
> > I will test again on 10.14.6 final and feed back
> 
> If any logs/messages will be available, upload it here, please


sure, but it stuck at the while Apple Logo with black background as soon as i choose Recovery (few seconds delay), with or without -v boot arg, the same.

**Comment by nms42** [comment] 2019-06-29 09:24
Well,
it will take time to investigate.

**Comment by vit9696** [comment] 2019-06-29 10:30
Logs can be saved to file. You can enable file logging in Debug -> Target (and set a high debugging level, use debug OpenCore and INFO, WARN, ERROR debug mask). Wait while it gets written for a short while, and then force-shutdown with the power button, eject the flash drive, save the log, and attach it here.

**Comment by cattyhouse** [comment] 2019-06-29 13:18
i really would like to provide opencore.log, but i don't see it. All files opencore.efi, bootx64.efi, vboxhfs.efi are debug versions. attached are my settings, i only see some "start end" messages when boot Recovery, and it stuck there, after shutdown i don't see opencore.log
![Screen Shot 2019-06-29 at 21 14 59](https://user-images.githubusercontent.com/3365320/60384696-6375d180-9ab3-11e9-9b64-7a3682da8410.png)

**Comment by vit9696** [comment] 2019-06-29 13:55
You forgot to add log enable bit to Target, and, and neither of them is Data. Must be Number.

**Comment by cattyhouse** [comment] 2019-06-29 13:57
> You forgot to add log enable bit to Target, and, and neither of them is Data. Must be Number.

ok, all Number, i will do that. To get opencore.log, what's your suggested value on Target, DisplayLevel, Haltlevel
thanks

**Comment by vit9696** [comment] 2019-06-29 13:59
Ugh, is not it in the docs? Well, to make it quicker: DisplayLevel: 0x80000042 (2147483714), Target 0x41 (65).

**Comment by cattyhouse** [comment] 2019-06-29 14:14
ok, finally, i got the opencore.log, but this is not the log of booting Recovery, because as soon as i boot from the USB stick (with opencore EFI ), it stuck with some on screen messages, i don't get a chance to see the boot menu. 

anyway, log attached
[opencore.log](https://github.com/acidanthera/bugtracker/files/3341958/opencore.log)

**Comment by vit9696** [comment] 2019-06-29 14:16
Ugh, without the boot log it is kind of helpless. Please provide the boot log. E.g. by using a second HDD or by running UEFI Shell from EFI\BOOT\BOOTx64.efi on USB stick and copying the created log there.

**Comment by cattyhouse** [comment] 2019-06-29 14:26
Sorry i don't understand, as i said, **with Target=65, DisplayLevel=2147483714, HaltLevel=2147483648(all Number),** i don't get a chance to see the Boot Menu, it stopped at attached message, and screen turns gray, i had to force shutdown, then there comes the opencore.log in the root of EFI volume . 

Resetting the 3 items to default value, i'm able to see the Boot Menu, but this way it does not produce opencore.log

![log](https://user-images.githubusercontent.com/3365320/60385492-56111500-9abc-11e9-9839-fc8f67468ac5.jpg)

**Comment by vit9696** [comment] 2019-06-29 14:40
Change Target=65 to 67.

**Comment by cattyhouse** [comment] 2019-06-29 14:49
Great, now i got chance to select Recovery. opencore.log and screenshot attached. I hope this is useful

[opencore.log](https://github.com/acidanthera/bugtracker/files/3341986/opencore.log)

![Recovery](https://user-images.githubusercontent.com/3365320/60385785-092f3d80-9ac0-11e9-9fc1-85388204e990.jpg)

**Comment by vit9696** [comment] 2019-06-29 15:04
Looks good to me. Please wait for 5 full minutes. In my opinion, it is just slow.

**Comment by cattyhouse** [comment] 2019-06-29 15:13
You are right. I used a stop watch, it took 2min 58sec to start booting Recovery. That’s amazing, HFSPlus.efi boot right away, no delay.

**Comment by vit9696** [comment] 2019-06-29 15:38
Not a bug, closing.

**Closed by vit9696** 2019-06-29 15:38 UTC
Labels: enhancement, project:oc
