### ISSUE TITLE
Boot hang while using VirtualSMC v1.1.2

### ISSUE THREAD

**Issue by Giovix92** [acidanthera/bugtracker#818] opened 2020-04-08 01:57 UTC
Hello, I have an ASUS X550VXK (7700hq, uhd630, efi folder https://github.com/Giovix92/efi_x550vxk) running MacOS Catalina 10.15.4. I've just updated VirtualSMC from 1.1.1 to 1.1.2 (and added other modules aswell), Lilu is already at 1.4.3, the latest one. While booting I get a hang right before the apple logo (image attached). Even though, apple logo will show up after some mins, still without arriving at the login screen. 

![IMG_20200408_033447](https://user-images.githubusercontent.com/19226770/78736164-ca7ebb80-794c-11ea-97b0-0d516c884a40.jpg)

**Comment by marianopela** [comment] 2020-04-08 09:03
Same on Lenovo Ideapad s540-14IWL i5-10210u

**Comment by 07151129** [comment] 2020-04-08 21:04
Does it also hang with older versions of VirtualSMC? Have you tried disabling all the VirtualSMC plugins?

**Comment by Giovix92** [comment] 2020-04-08 21:35
> Does it also hang with older versions of VirtualSMC? Have you tried disabling all the VirtualSMC plugins? Does it work with FakeSMC?

Yeah, tried without any module aswell. It doesn't happen with VirtualSMC 1.1.1 though.

**Comment by vit9696** [comment] 2020-04-08 21:46
What happens if you boot with the debug versions and and -liludbgall boot argument? Could you post a movie or similar? Also, are you sure you are on the latest version of OpenCore (we do not support Clover)?

**Comment by Giovix92** [comment] 2020-04-08 21:50
> What happens if you boot with the debug versions and and -liludbgall boot argument? Could you post a movie or similar? Also, are you sure you are on the latest version of OpenCore (we do not support Clover)?

Well yeah, I can do a movie for sure.
Running Clover 5107 as of now, planned to switch to OpenCore soon.

**Comment by marianopela** [comment] 2020-04-10 15:29
> What happens if you boot with the debug versions and and -liludbgall boot argument? Could you post a movie or similar? Also, are you sure you are on the latest version of OpenCore (we do not support Clover)?

I'll try that as I'm having the same issue on last OC version

**Comment by marianopela** [comment] 2020-04-11 08:32
Here is an OC debug log, if it's helpful [opencore-2020-04-11-082344.txt](https://github.com/acidanthera/bugtracker/files/4464271/opencore-2020-04-11-082344.txt)

And this is my config
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/4464274/config.plist.zip)

**Comment by arabesc** [comment] 2020-04-11 14:56
I have the same issue with 1.1.2, the previous version works.
Config: ASUS Z270-I / i7700K / Clover 5107 / Lilu 1.4.3 / OSX 10.15.4 (19E287).

**Comment by vit9696** [comment] 2020-04-11 18:58
```
194:488 00:077 OC: Prelink injection Lilu.kext (Lilu) - Success
194:569 00:080 OC: Prelink injection VirtualSMC.kext (SMC) - Invalid Parameter
194:624 00:054 OC: Prelink injection WhateverGreen.kext (Video card) - Success
194:699 00:074 OC: Prelink injection AppleALC.kext (Sound) - Invalid Parameter
194:739 00:040 Dependency as.vit9696.VirtualSMC was not found for kext ru.usrsse2.SMCBatteryManager
194:822 00:082 OC: Prelink injection SMCBatteryManager.kext (Battery) - Invalid Parameter
194:857 00:035 Dependency as.vit9696.VirtualSMC was not found for kext ru.usrsse2.SMCLightSensor
194:919 00:061 OC: Prelink injection SMCLightSensor.kext (Light Sensor) - Invalid Parameter
194:958 00:039 Dependency as.vit9696.VirtualSMC was not found for kext as.vit9696.SMCProcessor
195:030 00:072 OC: Prelink injection SMCProcessor.kext (Prosessor) - Invalid Parameter
195:066 00:035 Dependency as.vit9696.VirtualSMC was not found for kext ru.joedm.SMCSuperIO
195:128 00:061 OC: Prelink injection SMCSuperIO.kext (SuperIO) - Invalid Parameter
```

The log shows that VirtualSMC did not inject. The reason is probably an outdated version Lilu. Closing as not a bug, please reopen if using the latest version of Lilu still fails.

**Closed** 2020-04-11 18:58 UTC
Labels: project:vsmc
