### ISSUE TITLE
[VoodooPS2] Trackpad not Working nor Buttons

### ISSUE THREAD

**Issue by dafes** [acidanthera/bugtracker#690] opened 2020-02-01 21:20 UTC
System: 
* Lenovo Thinkpad x270
* i7-7600U with Intel 620

MacOS:
* 10.14.6 (18G103)

Trackpad with Physical Buttons above and Trackpoint like [here](http://www.notebookreview.com/wp-content/uploads/sites/2/P1450498_1920.jpg)

On my Laptop only the Trackpoint is woking with the lates release.
The Trackpad and Buttons are not responding.

I tried some different Versions and forks but at the Moment only the "old" [Rehabman](https://github.com/RehabMan) Version [1.9.2](https://bitbucket.org/RehabMan/os-x-voodoo-ps2-controller/downloads/RehabMan-Voodoo-2018-1008.zip) is working but without Gesture Control and the three Physical Buttons seems all mapped to `right click`

I have no ACPI Patches in place which affect the settings of the Kext. Also i tried the different variants of the `VoodooPS2Trackpad.kext` beginning with the unmodified Kext to setting the IOKitPersonalities/Synaptics TouchPad/Platform Profile/LENOVO of the x270 to `Thinkpad_ClickPad` or `Thinkpad_TrackPad`

**Comment by dafes** [comment] 2020-02-01 21:37
some debug log when i swipe over the trackpad
```
======synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0ApplePS2Keyboard: sending key e048=7e down
ApplePS2Keyboard::message: type=e3ff8066, provider=<ptr>, argument=<ptr>, argument=f8b22c11, cmp=e0028010
ApplePS2Keyboard::message: type=e3ff806e, provider=<ptr>, argument=<ptr>, argument=f8b22c11, cmp=e0028010
VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0ApplePS2Keyboard: sending key e048=7e up
ApplePS2Keyboard::message: type=e3ff8066, provider=<ptr>, argument=<ptr>, argument=ffc86d3c, cmp=e0028010
ApplePS2Keyboard::message: type=e3ff806e, provider=<ptr>, argument=<ptr>, argument=ffc86d3c, cmp=e0028010
VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0ApplePS2Keyboard: sending key 1d=3b down
ApplePS2Keyboard::message: type=e3ff8066, provider=<ptr>, argument=<ptr>, argument=d724247, cmp=e0028010
VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0VoodooPS2 w: 0
buttons 0synaptics_parse_hw_state: =============NORMAL PACKET=============synaptics_parse_hw_state: finger 0 pressure 0 width 8
synaptics_parse_hw_state lastFingerCount=0 clampedFingerCount=0 left=0ApplePS2Keyboard: sending key 26=25 down
```

**Comment by Sniki** [comment] 2020-02-01 22:52
@dafes Do you have VoodooInput.kext installed as well ?

**Comment by dafes** [comment] 2020-02-02 08:30
> @dafes
> 
> 1. Do you have VoodooInput.kext installed as well ?
> 2. Are you using Clover or OpenCore ?

1.) Yes at first only with the `acidanthera` version and now also with the jpe230 [version ](https://github.com/acidanthera/bugtracker/files/3786222/VoodooPS2Controller.kext.zip) you build.
On the jpe230 build the Trackpad is working but without any button. The "trackpad click" is just generating a `No Available Windows` message

2.) clover and the kexts are inside the clover/kext/others folder

**Comment by prabs77** [comment] 2020-02-02 19:05
I have the same issue. But this is on HP 450 G5.

**Comment by Tarik02** [comment] 2020-02-03 07:06
Seems to be a duplicate of #557. I suggest you to use my fork of VoodooPS2 (without VoodooInput at all): https://github.com/Tarik02/VoodooPS2/tree/my. It is based on 2.0.4. Here is prebuilt: [VoodooPS2Controller.kext.zip](https://github.com/acidanthera/bugtracker/files/4146635/VoodooPS2Controller.kext.zip)

**Closed** 2020-02-03 08:42 UTC
Labels: duplicate, project:ps2

**Comment by dafes** [comment] 2020-02-03 15:04
@Tarik02 still not working. With the precompiled Kext the trackpad is working but every click is interpreted as i believe the middle mouse click.
Physical Buttons are not working at all

**Comment by Tarik02** [comment] 2020-02-03 21:10
@dafes middle click is very strange. In macOS, natively it is not possible to do middle click with touchpad. Seems that this is force click, which can be enabled/disabled via settings.

**Comment by Topuz** [comment] 2020-02-17 12:19
> Seems to be a duplicate of #557. I suggest you to use my fork of VoodooPS2 (without VoodooInput at all): https://github.com/Tarik02/VoodooPS2/tree/my. It is based on 2.0.4. Here is prebuilt: [VoodooPS2Controller.kext.zip](https://github.com/acidanthera/bugtracker/files/4146635/VoodooPS2Controller.kext.zip)

Thanks for this! After weeks of experimentation, this is the _only_ version of acidanthera's VoodooPS2 with properly working gestures on myThinkPad P50. I've tried all of them, including Sniki's, with various issues.

For reference, this is how my trackpad looks:
![Lenovo-ThinkPad-P50-Touchpad](https://user-images.githubusercontent.com/3016596/74652890-52cfb400-5187-11ea-8ec7-316c9751eed6.jpg)

Pretty much everything works exactly as expected: trackpoint, three physical buttons above the trackpad and trackpad itself (it's just a trackpad, you can't click it). The left and right physical buttons below the trackpad also work properly, but the middle one doesn't (not really an issue since I almost never use it, would be cool though if it could be mapped to force click). All the gestures work properly except swiping for notification center (strange) and four finger gestures are very unreliable (which is to be expected for this trackpad I think).

Once again thank you, you've made my hackintosh experience much more complete and pleasant.

**Comment by Tarik02** [comment] 2020-02-17 12:22
@Topuz, glad to help.

**Comment by xs9627** [comment] 2020-03-01 23:58
> #557

Works very well on my Thinkpad S430.
With acidanthera's latest version, the trackpad only works in 20% chance and need to restart again and again to get trackpad and trackpad work together.

Thanks very much.

**Comment by Tarik02** [comment] 2020-03-02 07:06
@xs9627 that's strange. Can't even guess what this issue can be about. I do not have a tracepoint, but the trackpad works okay for me after sleep. Can you describe more precisely how it "does not work"? Maybe it works, but like acidanthera's? What happens if you disable touchpad and enable it (with FN key)?

**Comment by xs9627** [comment] 2020-03-02 08:03
@Tarik02 thanks for your quick reply. "Dose not work" means the trackpad, tranckpoint and physical buttons do not have any response, either with one finger or multiple fingers.
I didn't found a touchpad switch button with FN key, I thinks the touchpad can't turn off manually.
With Rehabman Version 1.9.2 is working after sleep.

**Comment by Tarik02** [comment] 2020-03-02 09:01
Hmm, I think that's something strange with touchpad mode. I will try to do some investigation later.

**Comment by xs9627** [comment] 2020-03-02 09:07
Thanks very much. It's really an old date machine though. I searched a while, but didn't found anything useful.

**Comment by Tarik02** [comment] 2020-03-02 19:59
@xs9627 can you try to disable/enable DynamicEW mode?

**Comment by xs9627** [comment] 2020-03-02 23:39
> @xs9627 can you try to disable/enable DynamicEW mode?

Tried, but with no luck, nothing changed.
Found following log may help? Every time wake from sleep got 'Unexpected byte0 data' error
`2020-03-03 07:19:58.716812+0800 0xf3       Default     0x0                  0      0    kernel: (VoodooPS2Trackpad) VoodooPS2Trackpad starting: Synaptics TouchPad reports type 0x47, version 8.1
2020-03-03 07:36:23.198645+0800 0x1886     Default     0x0                  0      0    kernel: (VoodooPS2Trackpad) ApplePS2SynapticsTouchPad: Unexpected byte0 data (00) from PS/2 controller
2020-03-03 07:36:23.202980+0800 0x1886     Default     0x0                  0      0    kernel: (VoodooPS2Trackpad) ApplePS2SynapticsTouchPad: Unexpected byte0 data (fa) from PS/2 controller`

**Comment by Tarik02** [comment] 2020-03-03 06:55
That's strange. Seems the touchpad wakes too late or idk. Did you try to toggle DynamicHW with `ioio` after sleep?

**Comment by xs9627** [comment] 2020-03-03 09:35
Just tried `ioio` after sleep and also no help.

I tried uncomment the `UNDOCUMENTED_INIT_SEQUENCE_PRE ` then the trackpad and trackpoint all works after sleep. I'm not quite familiar with cpp and I know it's not a good way to fix, but so far it works all good.

```
 //#define FULL_HW_RESET
 //#define SET_STREAM_MODE
-//#define UNDOCUMENTED_INIT_SEQUENCE_PRE
+#define UNDOCUMENTED_INIT_SEQUENCE_PRE
 #define UNDOCUMENTED_INIT_SEQUENCE_POST

 // enable for trackpad debugging
@@ -2082,7 +2082,7 @@ bool ApplePS2SynapticsTouchPad::setTouchPadModeByte(UInt8 modeByteValue)
 #endif

     // Disable stream mode before the command sequence.
-    i = 0;
+    //i = 0;
     request.commands[i++].inOrOut = kDP_SetDefaultsAndDisable;     // F5
     request.commands[i++].inOrOut = kDP_SetDefaultsAndDisable;     // F5
     request.commands[i++].inOrOut = kDP_SetMouseScaling1To1;       // E6
```

**Comment by Tarik02** [comment] 2020-03-03 10:47
@xs9627 That's good. Seems someone faced this problem before:
```
#ifdef UNDOCUMENTED_INIT_SEQUENCE_PRE
    // Also another attempt to solve wake from sleep problems.  Probably not needed.
    i = 0;
```

**Comment by showcheap** [comment] 2020-03-09 02:43
> But some time (about 20%) the trackpoint not work after sleep.

Facing same issue, after sleep trackpoint not work, but the trackpad still works.

I'm using latest VoodoPS2

**Comment by xs9627** [comment] 2020-03-09 06:21
After reboot many times, I finally got the sleep issue fixed.
The issue is when awake from sleep, the trackpad, tranckpoint and physical buttons do not have any response, either with one finger or multiple fingers. (100% occur)

It cost by this commit 85b9a8d5058e26529d10a5c80f76c7f666b8fd14. With this change I got following error each time when wake from sleep,
```
kernel: (VoodooPS2Trackpad) ApplePS2SynapticsTouchPad: Unexpected byte0 data (00) from PS/2 controller
kernel: (VoodooPS2Trackpad) ApplePS2SynapticsTouchPad: Unexpected byte0 data (fa) from PS/2 controller
```
After revert the commit, everything works. And so far the trackpoint works all good from sleep.
This is the v2.1.2 kext I compile.
[VoodooPS2Controller.kext.zip](https://github.com/acidanthera/bugtracker/files/4304900/VoodooPS2Controller.kext.zip)


@showcheap , did you use the SSDT-Thinkpad_Clickpad.dsl or SSDT-Thinkpad_Trackpad.dsl? I also set the force pass through like followings, but I'm not sure if it relates.
```
"ForcePassThrough", ">y",
"SkipPassThrough", ">y",
```

**Comment by VictorGamer072YT** [comment] 2020-04-15 16:23
@Tarik02 Thank you, your kext is the only one that I could find that works with gestures and has the tracepoint and its buttons fully working, however, the buttons for the touchpad it self don't work, and scrolling up and down is a bit weird, other than these 2 issues, everything works just fine, so Thank you.
