### ISSUE TITLE
OpenCorePkg: when I update opencore to 0.5.5 or later, Boot Camp Assistant internal error.

### ISSUE THREAD

**Issue by DbArl** [acidanthera/bugtracker#806] opened 2020-04-06 08:13 UTC
It's works fine in 0.5.4, SMBIOS Mac Pro 7,1. and many people has the same problem in pcbeta.
http://bbs.pcbeta.com/viewthread-1846427-1-1.html
update to version 0.5.5 or late internal error.

**Comment by vit9696** [comment] 2020-04-06 08:16
You have incorrect configuration likely caused by config.plist rename of `AdviseWindows`. Boot Camp Assistant works fine for me.

**Comment by vit9696** [comment] 2020-04-06 08:17
Duplicate of https://github.com/acidanthera/bugtracker/issues/803.

**Closed by vit9696** 2020-04-06 08:16 UTC
