### ISSUE TITLE
Sleep/wake problem with VirtualSMC

### ISSUE THREAD

**Issue by ornulf** [acidanthera/bugtracker#388] opened 2019-06-12 18:48 UTC
My rig is not going into sleep mode at all when booting on VirtualSMC version 1.0.4.
When booting on FakeSMC version 6.11-474-1802, sleep and wake is working as it should.

**Comment by vit9696** [comment] 2019-06-13 05:23
Try to provide more details about your hardware. Also, did you test sleep/wake without any VirtualSMC plugins? Remove them all and retry.

**Comment by ornulf** [comment] 2019-06-13 08:24
Have tested a little bit further with and without plugins in different combinations, and it seems impossible to activate sleep. VirtualSMC together with only SMCProcessor produce an imminent crash and restart all the times I test that combination. VirtualSMC together with all other plugins or without SMCProcessor produce no action at all but blank screen until I move the cursor and the blank screen lit up again.
My hardware:
Asus WS C422, Xenon W-2175, RX Vega 64,64 GB Kingston ECC, DDR4 2666 Mhz, Samsung 960 Pro 1TB.

<img width="806" alt="Screenshot 2019-06-13 at 10 19 03" src="https://user-images.githubusercontent.com/7491023/59415900-b453ad80-8dc4-11e9-8c4f-55a31b7d48e1.png">

**Comment by vit9696** [comment] 2019-06-13 09:00
Well, try to upload the configuration but firstly update to latest OpenCore, kexts, and drivers from master. Perhaps we could find something, but I am afraid our best advice right now is to use what works best for you. Resolving this issue without the hardware will be hard and slow, and we cannot do it right now.

**Comment by ornulf** [comment] 2019-06-13 14:18
I'm booting on OpenCore-v0.0.3-RELEASEwith dynamic XCPM and CPUID together with
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/3286588/config.plist.zip)

 latest kext and drivers.

**Comment by vit9696** [comment] 2019-06-13 14:26
Regarding your config. I list the issues that can very well cause sleep issues:
- All your ACPI patches are broken, as they match DSDT with TableSignature, and basically invalidate all SSDTs used. I would request you to use empty TableSignature, or, better, remove all these patches. I do not believe any of them is any helpful, and the documentation explicitly forbids these "rename" patches.
- UsbInjectAll, do not use it, create legacy kext describing your USB ports, even at a price of losing some.
- Drop All Oem - is very dangerous, try without it.
- I have no idea of what is in SSDTs, but this can also cause issues.
- I am pretty sure RequestBootVarRouting & ProvideConsoleGop should be YES on your board
- IgnoreInvalidFlexRatio and ReleaseUsbOwnership *might* help, but do not use them if they do not
- Also check DMAR / VT-d settings

**Comment by J1mmyS** [comment] 2019-06-13 14:46
I think this is due to iMacPro1,1 SMBIOS having no SmcRevision value, please see [my post at InsanelyMac](https://www.insanelymac.com/forum/topic/335292-virtualsmc-%E2%80%94-smc-emulator/?do=findComment&comment=2677385)

**Comment by vit9696** [comment] 2019-06-13 14:49
:o the heck. But this is pretty much how it is supposed to work on iMac Pro (and in fact all T2 based machines). Can anybody confirm it with Macmini and MacBookPro15,x models?

**Comment by ornulf** [comment] 2019-06-13 16:15
You advice me to skip UsbInjectAll even if I have a (rehabman) SSD-UIAC.aml with all my ports mapped?
I have a kext with the same port mappings. Do you recommend to use that instead?

**Comment by vit9696** [comment] 2019-06-13 17:20
@ornulf, yes, the latter is cleaner. UsbInjectAll is mainly useful for debugging, afterwards it is extra dust. As for the sleep issue @J1mmyS seems to be right, but I am not sure how exactly it can be caused. Could you try adding `vsmcgen=2` boot argument and check sleep? Dump & compare SMC key values for REV, RBr, RPlt, and RGEN afterwards with smcread.

**Comment by ornulf** [comment] 2019-06-13 18:51
Can confirm that changing SMCRevision value in section DataHub  from "02004100 0F00" --> "02410F00 0001" make sleep function as it should. But remember that my cpu is identified as 0x0505E3 dynamically in OC revision 0.0.3. I don't no if that could be a culprit. Do you still need debug stuff? if so you have to have patience because I need to find out how to produce them.

**Comment by ornulf** [comment] 2019-06-13 19:16
With boot argument vsmcgen=2 no working sleep. After putting the rig into manual sleep the screen went blank and after a while freeze and reboot.
[Panic Report.rtf.zip](https://github.com/acidanthera/bugtracker/files/3287747/Panic.Report.rtf.zip)

**Comment by vit9696** [comment] 2019-06-13 20:53
This panic is caused by your CPU/GPU and is unrelated to SMC/sleep from what I can tell. Could you recheck more times? This panic is most likely random thing.

As for the bug, it needs investigating, SMCRevision (REV) and SMCBranch (RBr) are not supposed to be used on T2 models in the first place, first time to hear that their miss is affecting sleep. I would like you to properly find the trigger point for sleep to work in terms oF SMC keys. Most likely it configures some driver differently…

**Comment by vit9696** [comment] 2019-06-14 11:02
Please try this version: [vsmc-genfix-r1.zip](https://github.com/acidanthera/bugtracker/files/3290332/vsmc-genfix-r1.zip)

**Comment by J1mmyS** [comment] 2019-06-14 12:17
> Please try this version: [vsmc-genfix-r1.zip](https://github.com/acidanthera/bugtracker/files/3290332/vsmc-genfix-r1.zip)

Manually filled SMC data (as per iMac18,3 in MacInfoPkg) under platforminfo:
[REV ] type [{rev] 7B726576 len [ 6] attr [90] -> 02410F000001
[RBr ] type [ch8*] 6368382A len [ 8] attr [80] -> 6A31333700000000
[RPlt] type [ch8*] 6368382A len [ 8] attr [80] -> 6A31333700000000
[RGEN] type [ui8 ] 75693820 len [ 1] attr [80] -> 02
=> Sleep OK

Automatic:
[REV ] missing
[RBr ] missing
[RPlt] type [ch8*] 6368382A len [ 8] attr [80] -> 6A31333700000000
[RGEN] type [ui8 ] 75693820 len [ 1] attr [80] -> 03
=> Sleep not working

**Automatic + vsmc-genfix-r1:**
[REV ] missing
[RBr ] missing
[RPlt] type [ch8*] 6368382A len [ 8] attr [80] -> 6A31333700000000
[RGEN] type [ui8 ] 75693820 len [ 1] attr [80] -> 02
**=> Sleep OK again!**

**Comment by vit9696** [comment] 2019-06-14 12:24
Fixed in master, thanks!

**Closed** 2019-06-14 12:23 UTC
Labels: help wanted, priority:low, project:vsmc

**Comment by J1mmyS** [comment] 2019-06-14 12:50
Thank you!

**Comment by ornulf** [comment] 2019-06-14 13:11
Thank's very much.
