### ISSUE TITLE
CpuTSCSync Triggers Kernel Panic on macOS versions prior to Big Sur

### ISSUE THREAD

**Issue by williambj1** [acidanthera/bugtracker#1789] opened 2021-09-13 14:31 UTC
Hi Developers!

When using CpuTSCSync with macOS version prior to Big Sur (confirmed on macOS Catalina and Mojave), CpuTSCSync will trigger a kernel panic **during wake up**. (The laptop enters sleep mode without issues). Works fine on macOS Big Sur and Monterey.

This was confirmed on two different laptops, all running the latest version of Lilu (v1.5.6) and CpuTSCSync (v1.0.4).

CpuTSCSync v1.0.3 works flawlessly despite not having support for macOS Monterey.

Panic Report:

```text
Anonymous UUID:       DCEB661B-398C-7C93-86CA-B23D7D14E711

Tue Sep 14 00:04:39 2021

*** Panic Report ***
panic(cpu 0 caller 0xffffff8006e15b04): "Kernel stack memory corruption detected"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-4903.271.2/libkern/stack_protector.c:37
Backtrace (CPU 0), Frame : Return Address
0xffffff811b7f3aa0 : 0xffffff80067ae6ed mach_kernel : _handle_debugger_trap + 0x47d
0xffffff811b7f3af0 : 0xffffff80068ea185 mach_kernel : _kdp_i386_trap + 0x155
0xffffff811b7f3b30 : 0xffffff80068db8ba mach_kernel : _kernel_trap + 0x50a
0xffffff811b7f3ba0 : 0xffffff800675bb40 mach_kernel : _return_from_trap + 0xe0
0xffffff811b7f3bc0 : 0xffffff80067ae107 mach_kernel : _panic_trap_to_debugger + 0x197
0xffffff811b7f3ce0 : 0xffffff80067adf53 mach_kernel : _panic + 0x63
0xffffff811b7f3d50 : 0xffffff8006e15b04 mach_kernel : _IOHibernateSystemHasSlept + 0x4d4
0xffffff811b7f3d70 : 0xffffff8006eb04de mach_kernel : __ZN14IOPMrootDomain15powerChangeDoneEm + 0x33e
0xffffff811b7f3de0 : 0xffffff8006e4013f mach_kernel : __ZN9IOService8all_doneEv + 0x71f
0xffffff811b7f3e40 : 0xffffff8006e3cdad mach_kernel : __ZN9IOService23actionPMWorkQueueInvokeEP11IOPMRequestP13IOPMWorkQueue + 0x8ed
0xffffff811b7f3ea0 : 0xffffff8006e39803 mach_kernel : __ZN13IOPMWorkQueue17checkRequestQueueEP11queue_entryPb + 0x53
0xffffff811b7f3ef0 : 0xffffff8006e396a0 mach_kernel : __ZN13IOPMWorkQueue12checkForWorkEv + 0x80
0xffffff811b7f3f30 : 0xffffff8006e56e72 mach_kernel : __ZN10IOWorkLoop15runEventSourcesEv + 0x1e2
0xffffff811b7f3f70 : 0xffffff8006e563cc mach_kernel : __ZN10IOWorkLoop10threadMainEv + 0x2c
0xffffff811b7f3fa0 : 0xffffff800675b0ce mach_kernel : _call_continuation + 0x2e

BSD process name corresponding to current thread: kernel_task
Boot args: keepsyms=1 -v

Mac OS version:
18G103

Kernel version:
Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64
Kernel UUID: C41337A1-0EC3-3896-A954-A1F85E849D53
Kernel slide:     0x0000000006400000
Kernel text base: 0xffffff8006600000
__HIB  text base: 0xffffff8006500000
System model name: MacBookPro14,2 (Mac-CAD6701F7CEA0921)
```

I'm not sure if #1759 is also related to this issue, and I don't understand why the author closed it.

Thanks and have a nice day.

**Comment by zfdx123** [comment] 2021-09-13 14:38
There are no problems during hibernation, but at the moment of awakening, the kernel goes into panic.（Catalina）

Thanks and have a nice day.

**Comment by wy414012** [comment] 2021-09-14 04:20
@williambj1 The reason for the closure is that I directly reconstructed it and should help you solve the problem. [build-push](https://github.com/wy414012/CpuTscSync/runs/3594645232)

**Comment by wy414012** [comment] 2021-09-14 13:54
The reason for closing is self-compilation.[This should solve your problem.](https://github.com/wy414012/CpuTscSync/suites/3765073363/artifacts/92568658)

**Comment by vit9696** [comment] 2021-09-16 07:09
I think I agree.

**Closed by vit9696** 2021-09-16 07:09 UTC
Labels: project:tscs

**Comment by williambj1** [comment] 2021-09-16 07:17
> I think I agree.

@vit9696 Sorry but I believe @wy414012 is telling a lie here. Nothing in the source code was changed in the fork. I did not compile CpuTSCSync myself instead it was downloaded from the official release. I am not the only person experiencing this issue. Thanks.

**Comment by williambj1** [comment] 2021-09-16 07:21
```sh
$ md5 '/Volumes/EFI/EFI/OC/Kexts/CpuTscSync.kext/Contents/MacOS/CpuTscSync'
MD5 (/Volumes/EFI/EFI/OC/Kexts/CpuTscSync.kext/Contents/MacOS/CpuTscSync) = 7f814ca59d90fd3c62b76a76c57354df
$ md5 '/Users/***/Downloads/CpuTscSync-1/CpuTscSync.kext/Contents/MacOS/CpuTscSync'
MD5 (/Users/***/Downloads/CpuTscSync-1/CpuTscSync.kext/Contents/MacOS/CpuTscSync) = 7f814ca59d90fd3c62b76a76c57354df
```

**Comment by wy414012** [comment] 2021-09-16 07:23
@williambj1 You got it wrong, what I said was that I rolled back the code and recompiled the solution after the fork. If you don't want to manually roll back, you can download it from my branch. https://github.com/wy414012/CpuTscSync

**Comment by williambj1** [comment] 2021-09-16 07:27
> @williambj1 You got it wrong, what I said was that I rolled back the code and recompiled the solution after the fork. If you don't want to manually roll back, you can download it from my branch. https://github.com/wy414012/CpuTscSync

In this case, is Monterey support still available?

**Comment by wy414012** [comment] 2021-09-16 07:29
@williambj1 Yes, it works well on processing below 6 cores.

**Comment by wy414012** [comment] 2021-09-16 07:32
@williambj1 Before the official version is released, it is impossible to determine what caused it, but the current test situation shows that it works well on processors with less than 6 cores and 12 threads.

**Comment by zfdx123** [comment] 2021-09-16 07:32
@wy414012 
Your code comes from 1.0.3. Although it solves the old kernel panic problem, I don't think it addresses the root cause.
And we may not only have devices with less than six cores.
Please correct me if I'm wrong.

**Comment by williambj1** [comment] 2021-09-16 07:33
@wy414012 Sorry but at this point I am **very** skeptical with your words, given that Monterey Support was completely removed in your fork. https://github.com/acidanthera/CpuTscSync/compare/master...wy414012:yaming-network#diff-155165b606cd7fd52acb647d28b303d8b464bd1f61be01ad597da6603855f43fL16

**Comment by wy414012** [comment] 2021-09-16 07:35
SSDT-PLUG.aml must exist in macOS12 to refer to the models I maintain. https://github.com/wy414012/OpenCore-GA-b75/

**Comment by williambj1** [comment] 2021-09-16 07:39
@wy414012 Sorry but I think that is enough non-sense.

@vit9696 I sincerely apologise for introducing such a chaos. But may I kindly request a reconsideration? Thank you very much.

**Comment by stevezhengshiqi** [comment] 2021-09-16 14:56
I agree with @williambj1 's point, there exists a kernel panic on macOS10.15 using the latest artifact built from the official workflow.
What @wy414012 did in his fork is just to roll back to v1.0.3 and adding Lilu and MacKernelSDK as submodules, which does not contribute to this issue. He seems does not understand how GitHub Action works, and using old version is not the main goal here.
