### ISSUE TITLE
Very fresh Lilu(?) falls flat

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#1922] opened 2022-01-12 11:18 UTC
Very fresh Lilu, as of this morning, falls flat. macos -- High Sierra.

![IMG_20220112_120354](https://user-images.githubusercontent.com/3739370/149130186-08f0122d-3fed-4ab1-b5b6-1f59dd6c6a78.jpg)

**Comment by aksm-unmei** [comment] 2022-01-12 17:44
Maybe you want to check kext order list in config.plist. Lilu is always first, top of the list, then VirtualSMC.

**Comment by nms42** [comment] 2022-01-13 05:51
> Maybe you want to check kext order list in config.plist. Lilu is always first, top of the list, then VirtualSMC.

Same config.plist, just "brand new" Lilu. Under Clover it fails same way.

**Comment by vit9696** [comment] 2022-01-13 05:53
Wrong booter quirks it looks to me. It tries to access EFI services and then dies, likely from a page fault when trying to read something from a NULL pointer (thus CR2 0x48).

- Need more information about this machine.
- config.plist
- OC boot log
- whether old Lilu worked or something
- any more details

**Comment by aksm-unmei** [comment] 2022-01-13 05:53
> > Maybe you want to check kext order list in config.plist. Lilu is always first, top of the list, then VirtualSMC.
> 
> 
> 
> Same config.plist, just "brand new" Lilu. Under Clover it fails same way.

well, that sounds weird... Mine working fine with latest Clover and OC on Cata, Big Sur and Monterey.

**Comment by vit9696** [comment] 2022-02-11 11:49
Closing due to no info. Please reopen if reproducible on the latest versions.

**Closed by vit9696** 2022-02-11 11:49 UTC
Labels: bug, project:lilu, priority:normal

**Comment by nms42** [comment] 2022-02-11 14:02
Just for the record,
it was my fault due to misconfiguration.
