### ISSUE TITLE
After the update of VoodooPS2, there is a problem with the light of the caps lock.

### ISSUE THREAD

**Issue by chiccheung** [acidanthera/bugtracker#514] opened 2019-10-13 17:46 UTC
As I said, when I use VoodooPS2Controller-2.0.3-RELEASE, the light of the caps lock button work normally.
After I installed VoodooPS2Controller-2.0.4-RELEASE, when I switch between upper and lower case, the light flashes briefly and then no longer lights up.
Please confirm if the update caused a new problem.
I can provide a log to help solve it, but I don't know how to do it.
PS：I am using Open-Core 0.5.2 with macOS 10.15.

**Comment by Andrw0830** [comment] 2019-10-13 21:43
I can confirm same issue on my Dell Inspiron 7567 with same OpenCore version.

**Comment by ameenjuz** [comment] 2019-10-14 03:57
Exact i have same issue caps lock light on VoodooPS2Controller-2.0.4-RELEASE   didn't seem such issue to earlier VoodooPS2Controller-2.0.3-RELEASE

**Comment by gncy2013** [comment] 2019-10-14 04:42
Same issue on XPS 13 9360

**Comment by vit9696** [comment] 2019-10-14 06:18
Hmm, the thing is, this is a tradeoff between having working led and having working keyboard switch. See this issue: https://github.com/acidanthera/bugtracker/issues/435. To my eyes it is a lot more important to have #435 fixed than care about the LED.

**Comment by corint1** [comment] 2019-10-14 06:29
same issue on Lenovo Ideapad 530S

**Comment by frol** [comment] 2019-10-14 06:34
Without [the fix I submitted](https://github.com/acidanthera/bugtracker/issues/435#issuecomment-529858985) my CapsLock Light worked, but there was no effect at all (and even worse, Karabiner reported stuck key with a semipermanent notification). The fix solved the functionality issue and the light works correctly for me.

**Comment by chiccheung** [comment] 2019-10-14 11:43
Anyway, I think it's not realistic to adapt a driver to all models. But I have already rolled back to the previous version, and now everything works great.

**Comment by chiccheung** [comment] 2019-10-14 11:59
> Hmm, the thing is, this is a tradeoff between having working led and having working keyboard switch. See this issue: #435. To my eyes it is a lot more important to have #435 fixed than care about the LED.
> 
> CC @frol, @usr-sse2
However, I think the problem with led lights has caused me a lot of trouble. I often don't know if I am in uppercase or lowercase. And the previous version of the case switching function is great, I like it. And it is not very important to me use the Caps Lock key to change input source.After all, we can use ctrk+space to switch it. Disable the case switch mode of Caps Lock key in the System Preferences tab.

**Comment by frol** [comment] 2019-10-14 14:14
For me (Lenovo Y50-70) the caps lock didn’t work at all (well, except the light indicator) with the previous workaround. I wonder if you need any of the two workarounds at all.

**Comment by frol** [comment] 2019-10-17 17:37
It seems that some of the hardware is not broken and do not need any of the workarounds (neither the old one nor the current one), so it might be reasonable to put the workaround behind a boot flag.

**Comment by DrConflict** [comment] 2019-10-20 22:57
I have a problem with the caps lock with my wireless keyboard since updating to Catalina and OC 0.5.2.
So I'm not totally sure this is related to VoodooPS2 though.

**Comment by chiccheung** [comment] 2019-10-21 05:54
> I have a problem with the caps lock with my wireless keyboard since updating to Catalina and OC 0.5.2.
> So I'm not totally sure this is related to VoodooPS2 though.
Roll back to the previous version (v2.0.3), have a try.

**Comment by DrConflict** [comment] 2019-10-22 00:15
> > I have a problem with the caps lock with my wireless keyboard since updating to Catalina and OC 0.5.2.
> > So I'm not totally sure this is related to VoodooPS2 though.
> 
> Roll back to the previous version (v2.0.3), have a try.

I never used voodoops2 before though since I have no trackpad..

**Comment by JayMonkey** [comment] 2019-10-29 14:05
Confirmed ... same issue on 2017 HP Spectre X360 laptop running VoodooPS2 2.0.4 RELEASE Version.

Caps lock key works as expected (toggles Upper/Lower case) but the led to indicate that Caps Lock is ON only flashes briefly and does not stay lit.

Issue did not occur with VoodooPS2 2.0.3 RELEASE Version

Cheers
Jay

**Comment by DrConflict** [comment] 2019-11-03 21:06
Caps lock light works again with BT keyboards now it seems. Not sure if this is because of the new OC and ASP packages or because of the new Catalina 10.15.1. Can anyone else confirm the issue is resolved for them as well since updating to the latest RELEASE packages and 10.15.1?

**Comment by hameerabbasi** [comment] 2019-11-19 09:58
I can confirm this a bug in 10.15.0 and fixed in 10.15.1, and not related to Voodoo at all. My USB keyboard had the same issue, and the update was what fixed it without any other changes.

**Comment by JayMonkey** [comment] 2019-11-19 13:50
> I can confirm this a bug in 10.15.0 and fixed in 10.15.1, and not related to Voodoo at all. My USB keyboard had the same issue, and the update was what fixed it without any other changes.

@hameerabbasi ,

That is not the case for me ..

I was already running MacOS Catalina 10.15.1 with VoodooPS2 version 2.0.3 (release ver) installed and the caps lock LED was working fine. Once i installed VoodooPS2 version 2.0.4 the issue with the Caps Lock LED started.

If I switch back to VoodooPS2 2.0.3 the issue goes away and the Caps Lock LED works as expected.
Reinstall VoodooPS2 2.0.4 and the issue comes back ... pretty conclusive.

All tests done on 2017 15" HP Spectre X360 laptop running MacOS Catalina 10.15.1

Why are you using VoodooPS2 with a USB keyboard ?, it wont do anything ....

Cheers
Jay

**Comment by hameerabbasi** [comment] 2019-11-19 13:58
I'm not. I just meant to show that a similar (though perhaps not the same) bug existed in 10.15.0.

**Comment by benbender** [comment] 2019-11-23 00:29
For my Thinkpad T480 with Mojave 10.14.6, the capslock-key is just sending the 3a=39:

````
2019-11-23 00:22:20.050047+0000 0x18f      Default     0x0                  0      0    kernel: (VoodooPS2Keyboard) ApplePS2Keyboard: sending key 3a=39 down
2019-11-23 00:22:20.273484+0000 0x18f      Default     0x0                  0      0    kernel: (VoodooPS2Keyboard) ApplePS2Keyboard: sending key 3a=39 down
2019-11-23 00:22:20.441980+0000 0x18f      Default     0x0                  0      0    kernel: (VoodooPS2Keyboard) ApplePS2Keyboard: sending key 3a=39 down
...
`````
https://github.com/acidanthera/VoodooPS2/commit/7a4d7fb4867aa9b70a7b014912a87039b5338a40 changed exactly that case and introduced the problems.

A simple solution could be to make the workaround configurable.
Would love to see that fixed and great love for all your great work! :)

**Comment by bluetechdev** [comment] 2019-12-02 22:19
Same issue on dell xps 9370

**Comment by benbender** [comment] 2019-12-03 11:42
For the time being, here is a fresh build from VoodooPS2-Master with reverted caps-lock-"fix":
[VoodooPS2Controller-2.1.0-RELEASE.zip](https://github.com/acidanthera/bugtracker/files/3916365/VoodooPS2Controller-2.1.0-RELEASE.zip)

**Comment by JayMonkey** [comment] 2019-12-03 14:06
Small update on this issue from me ...

Yesterday I Updated to VoodooPS2 V2.1 + VoodooInput V1.0.1  (master release versions) and the Caps-Lock LED issue first seen in VoodooPS2 V1.0.4 remains.

Have just Installed the test version of VoodooPS2 V2.1 from above post with reverted caps-lock fix and the issue has gone away ... Caps Lock LED now works as expected.

Thanks for taking the time to look into it and give us a temporary fix ... at least it gives us a chance to test the improved three finger support in VoodooPS2 version 2.1, hopefully the issue will get fully addressed in the next release.

Maybe some sort of config flag could be added to the info.plist enable the Caps-Lock-Fix on laptops that need it ....

Cheers
Jay

**Comment by usr-sse2** [comment] 2019-12-04 12:49
VoodooPS2Keyboard doesn’t change between versions, you can use newer VoodooPS2Trackpad with older VoodooPS2Keyboard

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by benbender** [comment] 2019-12-10 09:36
For the time being, here is a new, fresh build of VoodooPS2-Master & VoodooInput-Master with reverted caps-lock-"fix":
[VoodooPS2Controller.kext+VoodooInput.kext-MASTER-Release.zip](https://github.com/acidanthera/bugtracker/files/3944062/VoodooPS2Controller.kext%2BVoodooInput.kext-MASTER-Release.zip)

**Comment by TiagoDamascena** [comment] 2020-01-03 16:04
On my ASUS X512FA the caps lock indicator works on 2.0.4 but not work with 2.1.0 with VoodooInput 1.0.1

**Closed** 2020-01-27 10:08 UTC
Labels: project:ps2
