### ISSUE TITLE
Legacyboot is broken for anything under Big Sur with OC 0.8.8

### ISSUE THREAD

**Issue by ct85msi** [acidanthera/bugtracker#2206] opened 2023-01-25 17:21 UTC
Anything under Mac OS 11 gives me this error when I select MacOS Installer in the picker menu: OCB Loadimage Filed - Unsupported.

I tested this with 3 legacy systems, Penryn, Nehalem and Lynnfield and I could not install anything, only Big Sur+.

If I`m installing MacOS with an online image, it boots in recovery DMG, it completes the 1st stage of the installation and at the picker menu, when I select MacOS Installer it hangs with OCB Loadimage Filed - Unsupported.

If I`m doing an offline install, it gives me the error right at the first step when I select MacOS Installer in the picker menu.

Big Sur boots and installs fine with no modifications to the EFI folder.

I have emulated nvram.

I attached the Lynnfield EFI.
[EFI.zip](https://github.com/acidanthera/bugtracker/files/10501843/EFI.zip)

L.E. Attached and the Penryn EFI.

[EFI-Penryn.zip](https://github.com/acidanthera/bugtracker/files/10502102/EFI-Penryn.zip)

[opencore-2023-01-25-113923.txt](https://github.com/acidanthera/bugtracker/files/10502120/opencore-2023-01-25-113923.txt)

L.E. I can confirm that OC 0.8.7 works, does not have this bug.

**Comment by ruckusman** [comment] 2023-01-30 01:24
I was also stuck on this also, now having issues even getting OpenCore to boot - it seems that the Legacy Boot has been broken for quite some time.

Can I ask which version you used to get the boot disk made as the BootInstall_X64.tool from 0.8.7 isn't working for me.
I either get non system disk from the BIOS or if I use enoch to get the first bootloader, boot, loading from the EFI partition I am then hit with
BOOT MISMATCH!
BOOT FAIL!

This is just copying the files from the release package to the EFI/OC folder

There seems to be a lot of mismatches in the various elements to even get OpenCore.efi to load successfully

**Comment by ct85msi** [comment] 2023-01-30 08:28
I used 0.8.7 and it worked. Try to set SecureBootModel to Disabled and not Optional. I has the same error I think and after setting secureboot to disabled, it worked.

**Comment by ruckusman** [comment] 2023-01-30 08:50
Thank you, I'll try that again - I do recall having tried it previously, but I'll start with a clean slate.

I  came across your post because of the imageload error

I came across this page:
https://github.com/acidanthera/OpenCorePkg/tree/master/Legacy

So from the error, it seems that it's not the OpenCore.efi version that's at issue for the boot mismatch, it's the boot0 and boot1f32 which are the issue.

I have had this working, but I sought out other MBR and GPT boot sector codes, I'm going to work through my notes again and see if I can replicate the success

**Comment by HippoInWindow20** [comment] 2023-01-30 16:20
Following, trying to boot Mavericks on Legacy Boot

**Comment by mikebeaton** [comment] 2023-01-30 17:35
Required installers and compiled files are also in Utilities/LegacyBoot of OpenCore releases.

**Comment by ruckusman** [comment] 2023-01-31 09:08
Those legacy boot files are broken - I've compiled the boot0.nasm and boot1f32nasm an they bear no similarity to the files in the release.
Not sure which source the included legacy boot files are compiled from, but it's not in the available source files.

**Comment by ruckusman** [comment] 2023-01-31 11:02
> Following, trying to boot Mavericks on Legacy Boot, instead I'm using 0.8.5

I've posted a solution to the Legacy boot failing here if you're having difficulty getting the USB to boot.
The is with the bootX64 in the legacy tools - replacing 'boot' in the root directory of the EFI partition with the one from the zip file at least gets OpenCore.efi to load

**Comment by savvamitrofanov** [comment] 2023-02-02 07:19
@ruckusman 
The problem with USB boot seen by me and was related to BDS on buggy hardware. The problem isn't in boot files, with them all ok.
Try to increase timeout before BootDeviceSelect here (https://github.com/acidanthera/OpenCorePkg/blob/1244a542562bee51c6e79a7437057aea41b93b89/Legacy/BootPlatform/BdsDxe/BdsEntry.c#L475) to 6000000, for example and test again.

**Comment by ruckusman** [comment] 2023-02-02 10:32
I wish that were true, I can boot reliably on a GPT formatted USB with the boot file in the EFI partition using both Enoch [Chameleon] and Clover without issue.
I used the legacy BIOS block IO in Clover to boot from the GPT formatted USB -> EFI/boot

The issue previously was I believe to do with BIOS block IO being broken, it seems to have re-emerged.

I did try compiling from source, but it threw errors and failed - too much hassle right now given I spent days diagnosing what I thought was MBR and PBR issues when it was the boot file all that time.

Check what I posted here https://github.com/acidanthera/bugtracker/issues/2210 as with OC boot sectors and the modified Clover 'boot' file I can load opencore successfully

**Comment by savvamitrofanov** [comment] 2023-02-02 15:29
@ruckusman 
I compiled 0.8.9 with duet files for x64 and ia32 with mentioned patch. Please try and report if the problem gone
[duet_debug.zip](https://github.com/acidanthera/bugtracker/files/10570522/duet_debug.zip)
[duet_release.zip](https://github.com/acidanthera/bugtracker/files/10570523/duet_release.zip)
[OpenCore-0.8.9-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/10570524/OpenCore-0.8.9-DEBUG.zip)
[OpenCore-0.8.9-RELEASE.zip](https://github.com/acidanthera/bugtracker/files/10570526/OpenCore-0.8.9-RELEASE.zip)

**Comment by ruckusman** [comment] 2023-02-05 14:29
Thank you, apologies for the late reply.

I did try an EFI folder with the new files and ran the BootInstall_X64.tool from your compilation also.
There is a quirk where I need to run fdisk manually to make the first {EFI} partition active otherwise I receive non-system disk error.
With the first partition marked active I still get the BOOT MISMATCH! BOOT ERROR!.

One thing that I have noticed is using the OpenCore Patcher, which I have used successfully to make and use Monterey install media for my iMac, it creates a /System/Library/CoreServices/boot.efi, whereas a similar efi file BOOTx64.efi is located in /EFI/BOOT/BOOTx64 is in the zipped release package.

Is there an incompatibility between these files, I've inspected them in a hex viewer and they have similar strings, but they are not the same file by any means.

To me it seems that something is out of sync, is it with these files?

**Comment by mikebeaton** [comment] 2023-02-05 18:24
Is someone reporting this issue able to do a bisect and report the specific commit at which the issue first appears, please?

**Comment by ruckusman** [comment] 2023-02-05 21:42
Of the two issues in respect of Legacy Boot:
I've put the USB install media boot issue here
https://github.com/acidanthera/bugtracker/issues/2210.
I will work through back releases 0.7.9 -> 0.6.9...to try and locate the release where the issue first occurs.

For reference
BOOT MISATCH also occurred here
https://github.com/acidanthera/bugtracker/issues/1326 back at 0.6.4

For the second error
I can confirm that 0.8.7 doesn't have the ImageLoad error when the created install media is an SSD/HDD.

**Comment by chris1111** [comment] 2023-02-08 01:05
My issue [here](https://github.com/acidanthera/bugtracker/issues/2215)
it's a shame because for me OC 0.8.0 Duet worked well for me and the changes made to fix the Duet around certain config completely screwed up the boot because the proof here I compiled OC 0.8.9 myself this evening At the source and I use the Duet OC 0.8.0 boot file and I boot without problem Monterey, Ventura and install macOS Ventura 13.2 from USB install Media Using EFI folder OC O.8.9

See boot picker

![08002707](https://user-images.githubusercontent.com/6248794/217402012-9fd543f5-05e7-45d4-ad7e-6b5279c3831c.png)
![08002718](https://user-images.githubusercontent.com/6248794/217402017-cdb78f8d-9cad-4cec-8896-7b755528c0b5.png)

**Comment by mikebeaton** [comment] 2023-02-08 14:21
Please can you confirm whether or not this is fixed by: https://github.com/acidanthera/OpenCorePkg/commit/092af5d99c764cbe06372dfed3fa03af719550cc

Download the `macOS XCODE5 Artifacts` zip file from the bottom of page https://github.com/acidanthera/OpenCorePkg/actions/runs/3840701149 , and check whether the contained versions of OC fixes the problem.

**Comment by chris1111** [comment] 2023-02-08 20:05
> Please can you confirm whether or not this is fixed by: [acidanthera/OpenCorePkg@092af5d](https://github.com/acidanthera/OpenCorePkg/commit/092af5d99c764cbe06372dfed3fa03af719550cc)
> 
> Download the `macOS XCODE5 Artifacts` zip file from the bottom of page https://github.com/acidanthera/OpenCorePkg/actions/runs/3840701149 , and check whether the contained version of OC fixes the problem.

Not working, same issue for me descrid [here](https://github.com/acidanthera/bugtracker/issues/2215)


![217223177-2a4abb30-f36b-4612-9334-626ba56c96b1](https://user-images.githubusercontent.com/6248794/217639146-77d29080-2fbc-43a2-acb9-5bf24a96fd88.jpeg)

**Comment by chris1111** [comment] 2023-02-08 22:01
@mikebeaton 
Ive test LegacyDuet boot file of release  0.8.9, 0.8.8, 0.8.7, 0.8.6, 0.8.5, 0.8.4 , 0.8.3
[Same isssue](https://github.com/acidanthera/bugtracker/issues/2215) 
LegacyDuet boot file` 0.8.2` Boot OK on EFI 0.8.9 ✅ 

So in my opinion some thing wrong in LegacyDuet Release 0.8.3
I see `Added emulated NVRAM driver for use separately from OpenDuet` ?

**Comment by mikebeaton** [comment] 2023-02-10 23:30
@chris1111 - Apologies for directing you here, it was a separate issue.

@ruckusman - I am not convinced there is a real issue here. I am not getting any such issue using OpenDuet in OVMF. `BOOT MISMATCH!` means OpenDuet could not find OpenCore.efi on the drive on which it is installed. `BOOT FAIL!` means it could not find OpenCore.efi on any other drive either. Are you certain you have at least one bootable FAT drive with OpenCore on? Preferably the one onto which you installed OpenDuet.

@ct85msi - It seems you have resolved your error, correct?

**Comment by mikebeaton** [comment] 2023-02-12 13:53
Replicating some related issues now - thanks for heads up @ct85msi

**Comment by ct85msi** [comment] 2023-02-12 14:23
Thank you very much.

**Comment by ruckusman** [comment] 2023-02-12 23:26
Late in catching up, I have tried the latest compile https://github.com/acidanthera/OpenCorePkg/actions/runs/3840701149
of 0.8.9 on a USB - it still fails with BOOT MISMATCH! BOOT FAIL!

Interestingly I get the above error with USB set as first boot AND if it's the only storage device on the system.
BUT if I set USB as first boot device AND I attach my working OpenCore SSD, it does throw the BOOT MISMATCH! error.
BUT it then jumps to booting OpenCore from the EFI on the SSD.

As noted previously, the XW8600 can boot from GPT partitioned [EFI - fat32 formatted] using either Enoch Chameleon and Clover.

Given that the XW8600 seems to be an outlier in being incapable of booting OpenCore on a GPT partitioned USB AND I have a working solution booting OpenCore from an SSD, it may not be worth the effort to diagnose further unless it affects other systems also.

My main aim was to eliminate 'other' programs altogether and simplify the process -> GPT partitioned USB -> Opencore -> createinstallmedia command.

**Comment by mikebeaton** [comment] 2023-02-13 01:28
> Interestingly I get the above error with USB set as first boot AND if it's the only storage device on the system.
BUT if I set USB as first boot device AND I attach my working OpenCore SSD, it does throw the BOOT MISMATCH! error.
BUT it then jumps to booting OpenCore from the EFI on the SSD.

This is correct. As stated previously, 'BOOT MISMATCH!' means OpenDuet cannot find OpenCore in the drive on which it was installed, 'BOOT FAIL!' mean it (subsequently) cannot find any OpenCore instance on any drive.

Therefore this is as expected, and the only issue is that there is no (usable) OpenCore on the drive on which you installed OpenCore.

This is a separate issue to the one which @ct85msi has reported, and I believe should be a support/forum issue.

**Comment by vit9696** [comment] 2023-02-23 20:02
Could you please link to a build that introduced an issue? I know of no issues with LegacyBoot besides 10.4.x issues.

**Comment by chris1111** [comment] 2023-02-23 21:31
> Could you please link to a build that introduced an issue? I know of no issues with LegacyBoot besides 10.4.x issues.

Do you please just check
[my opinion some thing wrong in LegacyDuet Release 0.8.3](https://github.com/acidanthera/bugtracker/issues/2206#issuecomment-1423294963)

**Comment by mikebeaton** [comment] 2023-02-23 23:04
@chris1111 These are separate issues. Closed issues are read on this bugtracker - I believe you have a configuration issue, and I believe it is nothing to do with the emulated nvram update. My apologies for initially thinking your issues and this issue were related and directing you here, but please could you follow up on https://github.com/acidanthera/bugtracker/issues/2215 .

**Comment by vit9696** [comment] 2023-02-23 23:33
> > Could you please link to a build that introduced an issue? I know of no issues with LegacyBoot besides 10.4.x issues.
> 
> Do you please just check [my opinion some thing wrong in LegacyDuet Release 0.8.3](https://github.com/acidanthera/bugtracker/issues/2206#issuecomment-1423294963)
> 
> EDIT **** [Added emulated NVRAM driver for use separately from OpenDuet](https://github.com/acidanthera/OpenCorePkg/releases/tag/0.8.3)

A build, not a release. We need a particular commit when it stopped working. You can use https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true

**Comment by mikebeaton** [comment] 2023-02-24 09:43
@chris1111 - Well @vit9696 is happy to treat these together, and perhaps yours is the same issue.

On your issue specifically:

 - You were getting a warning message followed by halting on critical error, but this warning message is *expected* on first start (it just means you have no initial /NVRAM/nvram.plist - the location of nvram.plist was moved into that subfolder, along with other related files), and you had your system set to halt on warning messages.
 - Once you changed your system to not halt on warning messages, you got a different, kernel dump crash.
 - The upgrade to 0.8.3 was extensively tested on hacks, with no issues.
 - I also run it, not on a hack but in OVMF/QEMU, and I have no issues - not then, an not with the 0.8.8 release either.

For anybody with either issue, the specific commit at which your problem appears would be very useful (i.e. as per @vit9696's message).

---

For anybody who is not aware (and perhaps you both/all are) the technique of bisection is very fast - must faster than testing each commit one by one - to find the problem: you just choose a commit half-way between the known good and known bad commit, each time, and depending on whether that is good or bad you carry on from there, until you have two commits next to each other, one good and one bad. (This approach assumes that the issue comes in at a certain commit, within the range being tested, and stays in from them, but that's a good working assumption.)

**Comment by chris1111** [comment] 2023-04-30 05:11
Please see this [my comment on my issue ](https://github.com/acidanthera/bugtracker/issues/2215#issuecomment-1527779855)

**Comment by vit9696** [comment] 2023-05-07 09:21
Any progress on finding the relevant commit as per https://github.com/acidanthera/bugtracker/issues/2206#issuecomment-1442571576? I am willing to close this issue as there is no evidence on the particular change breaking things and on our systems legacy boot is working fine.

cc @Goldfish64 just in case

**Comment by chris1111** [comment] 2023-05-07 14:27
@vit9696  on my side I can not finding the relevant commit Sorry :)
I solved my problem by modifying `BootInstallBase.sh `
## This part ☟

![Screenshot 2023-05-07 at 10 18 12](https://user-images.githubusercontent.com/6248794/236683326-fc8f345c-d828-4d3c-bada-833eb3f8803b.png)

I simply added an `nvram.used` file in the `LegacyBoot` folder; thereby creating the missing nvram.plist file in the NVRAM folder.
I added a last command to lock the nvram.plist file because MacOS Ventura Installer can try to modify it during the installation of macOS this is what I noticed

[nvram.used.zip](https://github.com/acidanthera/bugtracker/files/11415147/nvram.used.zip)
[BootInstallBase.sh.zip](https://github.com/acidanthera/bugtracker/files/11415162/BootInstallBase.sh.zip)

This way I can install macOS with the latest OpenCore update and I use the same procedure for post install on the SSD where macOS is installed
My config is a Dell Optiplex 790 boot Legacy because it is impossible to put OpenCore UEFI on the latest Dell Bios it's a really Cheep Bios


As I already mentioned before OpenCore 0.8.3 there was no NVRAM folder created by OpenCore Duet so no I not need to modify the script .

**Comment by mikebeaton** [comment] 2023-05-07 14:37
As mentioned above, I believe there is no genuine issue the the emulated NVRAM code here; and if there is, it should probably be raised as a separate issue.

```
OCVAR: Emulated NVRAM load failed - Not Found
Halting on critical error
```
only makes sense if you have you Misc/Security/HaltLevel set to include WARN, which is not a recommended setting (it should normally be set to 2147483648 (i.e. 0x80000000), to include ERROR only).

**Comment by vit9696** [comment] 2023-05-07 14:52
Yeah, the NVRAM thing is a separate issue. I more wonder about @ct85msi and @ruckusman issue.

——

@chris1111, regarding NVRAM, can you please provide your config.plist?

@mikebeaton, I wonder if there is a possibility of some memory corruption here?

**Comment by chris1111** [comment] 2023-05-07 14:56
> Yeah, the NVRAM thing is a separate issue. I more wonder about @ct85msi and @ruckusman issue.
> 
> ——
> 
> @chris1111, regarding NVRAM, can you please provide your config.plist?
> 

Yea its here attaching

[config.plist.zip](https://github.com/acidanthera/bugtracker/files/11415277/config.plist.zip)

**Comment by vit9696** [comment] 2023-05-07 15:06
Yeah, you have `HaltLevel` set to `2147483650` (`DEBUG_WARN` and `DEBUG_ERROR`), should be `2147483648` (`DEBUG_ERROR`) for the current implementation not to stop loading.

@mikebeaton, I wonder whether we should actually change this to INFO? After all, there is nothing wrong with missing NVRAM contents if we view a warning as something that the user should correct. When halting at warnings is enabled, the setup becomes unbootable after NVRAM reset.

**Comment by chris1111** [comment] 2023-05-07 15:28
@vit9696  Yea you right `2147483648` not to stop loading. then I use `Ctrl+Enter` to the Ventura Icon disk then it create 

NVRAM Foder and nvram.plist 
Message  OCVAR: Emulated NVRAM load failed - Not Found  Is GONE

![Screenshot 2023-05-07 at 11 25 59 AM](https://user-images.githubusercontent.com/6248794/236686958-1539bf6b-fec9-4fbe-8820-dbc308f5ddb6.png)


Wonderfull !!!! thanks

**Comment by chris1111** [comment] 2023-05-07 15:32
@vit9696  @mikebeaton  Thank you both of you

**Comment by mikebeaton** [comment] 2023-05-07 16:11
> @mikebeaton, I wonder whether we should actually change this to INFO? After all, there is nothing wrong with missing NVRAM contents if we view a warning as something that the user should correct. When halting at warnings is enabled, the setup becomes unbootable after NVRAM reset.

Okay, I just updated it.

(Tbh I went both ways about this for ages - it kind of is a WARN after first boot, but since you can't tell if it's first boot in a way that's properly separate from whether the file exists, then as suggested it should not be a WARN.)

**Comment by chris1111** [comment] 2023-05-07 17:28
@mikebeaton 
as i said
then I use Ctrl+Enter to the `Ventura Icon disk` then it create

NVRAM Folder and nvram.plist
Message OCVAR: Emulated NVRAM load failed - Not Found Is GONE at next boot

**Comment by mikebeaton** [comment] 2023-05-07 17:32
Thanks, I know. With my recent change it would never have caused you all this trouble even with your previous settings.

**Comment by chris1111** [comment] 2023-05-07 18:14
> Thanks, I know. With my recent change it would never have caused you all this trouble even with your previous settings.


Test its work, see  `REL-092-2023-05-07` 😅

![07181011](https://user-images.githubusercontent.com/6248794/236695197-5fa536e3-68de-468f-a6fc-17869db9bc9d.png)

**Comment by vit9696** [comment] 2023-05-07 18:16
Closing this issue, because
- the original issue starters do not seem to provide any information about the commits causing issues for them.
- the second issue with NVRAM is resolved.

**Comment by chris1111** [comment] 2023-05-09 22:32
@mikebeaton  After updated Monterey , booting on macOS Installer this is the message I receive, with HaltLevel set to 2147483650
do you have a solution for this?

![09222126](https://github.com/acidanthera/bugtracker/assets/6248794/1b07c389-c232-442d-8ab1-d812c110ba03)

**Comment by mikebeaton** [comment] 2023-05-10 08:21
So, emulated NVRAM was never initially written under the assumption that it should never warn in normal day to day operation. I don't think there should be anything which warns every boot, but there may be things such as the two you've discovered which warn on untypical but not actually fatal issues.

I need to do an audit and put it though its paces with halt on warn enabled, as you have, and fix any remaining cases of 'warn but there's nothing for the uset to fix'.

In the meantime you will need to run with HaltLevel 2147483648.

**Comment by mikebeaton** [comment] 2023-05-10 21:38
I believe that is the only remaining INFO/WARN issue, so have [resolved it](https://github.com/acidanthera/OpenCorePkg/commit/5465c7b8207306c4b357680c1ce19668b47ba55d), and successfully run a Monterey update using emulated NVRAM on a machine here.

**Closed by mikebeaton** 2023-05-10 21:38 UTC
Labels: help wanted, project:oc
