### ISSUE TITLE
10.15 beta 4 AppleIntelMCEReporter

### ISSUE THREAD

**Issue by Pavo-IM** [acidanthera/bugtracker#424] opened 2019-07-17 02:08 UTC
Is there away we can get a new patch added to Lilu to patch AppleIntelMCEReporter.kext. Apple has introduced a new controller inside the driver called AppleIntelMCEInteruptController which has included the iMacPro1,1, MacPro6,1 and assume the new MacPro7,1 board-ids. This is causing kernel panic for Ivy Bridge-EP CPUs.
10.15 beta 3 AppleIntelMCEReporter.kext Info.plist
https://imgur.com/S9De4FP
10.15 beta 4 AppleIntelMCEReporter.kext Ino.plist
https://imgur.com/ACDbmQf

**Comment by PMheart** [comment] 2019-07-17 04:59
Hello,

I have several ideas to test:
- Patch the plist itself (by replacing MP61 to something else)
- If there were no hard to totally block the kext, it could also be done via OC Kext Block.

**Comment by PMheart** [comment] 2019-07-17 05:00
Sorry for the close. Reopening.

**Comment by vit9696** [comment] 2019-07-17 05:06
It makes sense to me to block kext with OC, Lilu has nothing to do with it. Closing as not an issue really.

**Comment by Pavo-IM** [comment] 2019-07-17 21:10
Use OC Kernel > Block did not work. This is from OC logs:
`00:000 00:000 OC: Prelink blocker com.apple.driver.AppleIntelMCEReporter init failure - Not Found`
I am assuming Kernel > Block section can only block kexts that is in the Prelink and not during booting phase. The KP is happening on update phase and fresh install phase.

**Comment by vit9696** [comment] 2019-07-17 21:13
Well, ok, do provide a panic log now then with keepsyms=1 in boot arguments and the kext file attached.

**Comment by Pavo-IM** [comment] 2019-07-17 21:14
https://imgur.com/QRawrsH

**Comment by vit9696** [comment] 2019-07-17 21:15
Please reread what I said, make good sense of it, and provide the necessary data. Thank you.

**Comment by Pavo-IM** [comment] 2019-07-17 21:33
Oh my bad here is the kext, didn't read that part lol.
[AppleIntelMCEReporter.kext.zip](https://github.com/acidanthera/bugtracker/files/3403901/AppleIntelMCEReporter.kext.zip)

**Comment by vit9696** [comment] 2019-07-17 21:34
It's keepsyns=1 instead of keepsyms=1 too, and thus no symbols are visible ^^

**Comment by Pavo-IM** [comment] 2019-07-17 21:47
![IMG_0017](https://user-images.githubusercontent.com/33814640/61414049-ffc51400-a8ba-11e9-83e7-2ddd9d72e180.jpg)

**Comment by PMheart** [comment] 2019-07-17 21:52
You are still leaving keepsyNs=1...

**Comment by vit9696** [comment] 2019-07-17 21:53
![E21CCF38-5231-442C-9532-7739BB1A8BF4](https://user-images.githubusercontent.com/4348897/61414305-4d12a700-a8f6-11e9-8434-4ee2aaf90348.jpeg)

Listen, I am patient, but if this continues, I will just close the issue until you learn how to provide bugreports. Thanks for understanding and please do save your own and my time.

**Comment by Pavo-IM** [comment] 2019-07-17 22:00
Ok I am little confused because when I provided the OC log output using Kernel > Block. You said and I quote "Well, ok, do provide a panic log now then with keepsyms=1 in boot arguments and the kext file attached." I provided a pic of the panic with keepsyns=1 already in it but forgot to attach the kext. I attached the kext next and then I posted a pic of the panic still with keepsyns=1 and now you are saying that I am not providing the information that you have asked for. So which is it? Do you want the a pic of the kernel panic with or without keepsyns=1 as a bootarg?

**Comment by PMheart** [comment] 2019-07-17 22:02
We want the bugreport with keepsyMs=1 (M is just for emphasis, which should be LOWercase in fact).

**Comment by Pavo-IM** [comment] 2019-07-17 22:04
That is not what @vit9696 said, he said specifically keepsyns=1 instead of keepsyms=1.

**Comment by MacProDude** [comment] 2019-07-17 22:05
> Well, ok, do provide a panic log now then with keepsyms=1 in boot arguments and the kext file attached.

This is what you put not keepsyns=1 it’s in the OC Pdf as keepsyms=1

**Comment by PMheart** [comment] 2019-07-17 22:09
You must be misunderstanding what @vit9696 said then.

Well, anyway, do not use keepsyNs=1 until you write the code for Apple. ;)

**Comment by MacProDude** [comment] 2019-07-17 22:10
Right so both screenshots had keepsyns, okay now i see it. yes i understood his reply.

**Comment by Pavo-IM** [comment] 2019-07-17 22:13
Here is one with keepsyms=1
![IMG_0018](https://user-images.githubusercontent.com/33814640/61415419-8c250600-a8be-11e9-83b4-6ddcd1c0a858.jpg)

**Comment by Pavo-IM** [comment] 2019-07-17 22:20
It looks like its checking something on the memory banks for the CPUs.

**Comment by vit9696** [comment] 2019-07-17 22:45
Well, to just disable this kext you could return 0 from `__ZN21AppleIntelMCEReporter5probeEP9IOServicePi`. Such a simple solution should work fine, so feel free to write a Lilu plugin for it.

The crash itself is caused by out of bounds array access:
![Снимок экрана 2019-07-18 в 1 40 46](https://user-images.githubusercontent.com/4348897/61416715-58b59c00-a8fd-11e9-81cd-1b0617713cad.png)

You have 2 physical CPUs, and this driver does not support it, and does not allocate enough memory, see `__ZN13AppleIntelMCE10Controller4InitEv`.

**Comment by Pavo-IM** [comment] 2019-08-03 03:48
10.15 beta 5 has removed AppleIntelMCEInteruptController from AppleIntelMCEReporter.kext Info.plist. It has been revered back to what 10.15 beta 3 was.

**Comment by Leoyzen** [comment] 2019-09-24 14:26
I still face the similar problem, and add Lilu/CPUFriend in kext/others of clover directory not work for me. Can you give some help or direction? the error info is here, much appreciate.
We use Penryn in kvm vm hackintosh, seem the cpu family not support in catalina.
![image](https://user-images.githubusercontent.com/5518468/65520423-1e2e3800-df1a-11e9-8dec-c11086f353ed.png)

**Comment by Leoyzen** [comment] 2019-09-24 14:30
Another similar error may related:
![image](https://user-images.githubusercontent.com/5518468/65520851-de1b8500-df1a-11e9-9c9b-d6c8cbfefb93.png)

**Comment by DuIslingr** [comment] 2019-09-25 19:38
![image0](https://user-images.githubusercontent.com/19367043/65633529-57ae8400-dfaa-11e9-87fe-a587fedc9494.png)
Trying to boot Catalina beta 9 with opencore on Qemu KVM and I keep getting this panic. CPUFriend seems to be broken.

**Comment by vit9696** [comment] 2019-09-26 08:31
@Leoyzen @DuIslingr all that is pretty strange. The screen above shows `__ZN21AppleIntelMCEReporter5probeEP9IOServicePi` was not found, and this is how CPUFriend kills the kext. @PMheart please check and update the signature.

**Comment by vit9696** [comment] 2019-09-26 12:12
The latest kext has all its symbols stripped, so it is not like we can easily disable it as before. For now consider using a mac model different from mp61, mp71, imp11.

**Comment by naveenkrdy** [comment] 2019-09-26 18:00
To block this i made a small codeless kext.
[AppleMCEReporterDisabler.kext.zip]

And also any idea why the kext blocking mechanism of OC is not working for this kext ?

(https://github.com/acidanthera/bugtracker/files/3659183/AppleMCEReporterDisabler.kext.zip)

**Comment by naveenkrdy** [comment] 2019-09-26 18:13
Here is a small codeless kext to disable it.
[AppleMCEReporterDisabler.kext.zip](https://github.com/acidanthera/bugtracker/files/3659271/AppleMCEReporterDisabler.kext.zip)

And also any idea why the kext blocking mechanism of OC is not working for this kext ?
and i have also observed that blocking  AppleIntelCPUpowermanagement.kext is also not working and due to that i had to use nullcpu kext .

**Comment by vit9696** [comment] 2019-09-26 18:46
I *think* the issue is in kextd reloading the kext after blocking. It will be nice if you could create a separate bugreport for failing kext blocking with examples of working and not working kext blocks. I think we could try increasing kext version in addition to kmod patching or maybe nulling the constructors…

**Comment by naveenkrdy** [comment] 2019-09-27 12:58
@vit9696 sure!  will create a seperate bugreport for it.

**Comment by zhang-wenchao** [comment] 2019-10-24 04:38
@naveenkrdy  Me too. I must needs AppleMCEReporterDisabler.kext and NullCPUPowerManagement.kext. Thank you for your work.

@vit9696 CPUFriend not work

**Comment by Pavo-IM** [comment] 2019-10-24 23:18
Well looks like the Disablerkext isn't working for 10.15.1 b3. Guess I'll have to use a different SMBIOS until CPUFriend or something else has figured out how to disable this from getting loaded.

**Comment by zhang-wenchao** [comment] 2019-10-26 06:00
My CPU is Intel Xeon Gold 5117，must fackcpuid 0x0306E0 to boot。

**Comment by mrmiller** [comment] 2019-10-26 06:03
Are you running OpenCore? I submitted patches a month or so ago that allow Xeon Golds (and others) to boot without a fake CPU ID. That is unrelated to this issue and workaround though.

**Comment by zhang-wenchao** [comment] 2019-10-26 08:57
This is causing kernel panic for Ivy Bridge-EP CPUs, If my don't use fakecpuid, 10.15 should work.

**Comment by Pavo-IM** [comment] 2019-10-26 16:45
Here is a pic of the new panic of AppleIntelMCEReporter
![Screenshot 2019-10-26 12 41 03](https://user-images.githubusercontent.com/33814640/67623030-6e850800-f7ee-11e9-9dc1-3232207d7434.png)

**Comment by startergo** [comment] 2019-11-18 01:32
I can report the same issue in Catalina 10.15.1 with a real MacPro5,1 and iMacPro1.1 board ID. It does not happen in Mojave. Please see here:
https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?do=findComment&comment=2697758

**Comment by Gengik84** [comment] 2019-12-02 10:06
HI
I know it's not a good solution but for now it's the only way for use some smbios.
I avoid KP by simply putting the original kext from S/L/E into EFI's folder.
I hope for a better solution and Apple will also fix some bugs about it.

**Comment by vit9696** [comment] 2019-12-04 20:46
Yes, we hope too. I removed the patch from CPUFriend as it does not work anyway, thus closing the issue.

**Closed by vit9696** 2019-12-04 20:46 UTC
Labels: bug, priority:normal, project:cpuf

**Comment by startergo** [comment] 2019-12-14 10:39
> 
> 
> HI
> I know it's not a good solution but for now it's the only way for use some smbios.
> I avoid KP by simply putting the original kext from S/L/E into EFI's folder.
> I hope for a better solution and Apple will also fix some bugs about it.

Please elaborate. To solve the issue you remove the kext from S/L/E and load it from the EFI/Kexts? Or you use some specific kext?

**Comment by Gengik84** [comment] 2019-12-14 14:31
No, you only have to put the original kext into EFI/OC/kext folder.
I didn't say to remove any kext from S/L/E.
