### ISSUE TITLE
Laptop screen is dead if system is booted in clamshell mode

### ISSUE THREAD

**Issue by antoniomcr96** [acidanthera/bugtracker#1927] opened 2022-01-16 00:01 UTC
Hi everyone, I haven't found anything similar online. I hope I'm not the only one to experience this issue.

How to reproduce:
Boot the laptop, connected to the power supply, with the LID closed and with an external monitor (in my case, through HDMI). If everything goes well, the external display will become the main display (`force-online` property probably needed), and the display of the laptop will stay off (Clamshell mode).
Reopening the LID should activate the laptop screen. However, although the screen is present in IO Registry Explorer (`PCI0 -> IGPU -> AppleFrameBuffer@0 -> display0`), the display stays black.

Everything works well if laptop is booted with the lid opened, and then clamshell mode is activated.

i5-8265 (UHD 620) with Monterey. Maybe it's a firmware issue, but it should be noted that on Windows and Linux everything works well. Connectors are correctly patched and HDMI doesn't give other issues.

EDIT: the same happens if I select the external display as the main display for boot. In other OSs, boot occurs regularly in the external display, and the builtin display of the laptop stays black with backlight. In MacOS, the backlight of internal display is never activated, even with  `force-online` property.

**Comment by vit9696** [comment] 2022-02-11 11:50
duplicate of https://github.com/acidanthera/bugtracker/issues/1623.

**Closed by vit9696** 2022-02-11 11:50 UTC
Labels: project:lilu
