### ISSUE TITLE
help:I have a question about CustomSMBIOSGuid

### ISSUE THREAD

**Issue by melxman** [acidanthera/bugtracker#410] opened 2019-07-05 03:19 UTC
I have a dell inspiron 5448 laptop.
When I use clover, I need to use the dellsmbiospatch option to load my model information correctly "Macbookpro 15,2".
Now I use 0.0.3 oc boot, enter the system, kext load is no problem, but this model information is not complete.Just like"Macbookpro 15,"
When I read the pdf, I found that the description of the CustomSMBIOSGuid is for the dell laptops. And found that it is associated with UpdateSMBIOSMode, but I used the value of UpdateSMBIOSMode according to the description and found that Create enters the system normally, but the information is still incomplete; Custom or leave the system into the system, the time is very long and the model will become dell Actual model.
So let me ask for the proper use of this feature.

My English is not good. I am sorry, the above content is from Google Translate. #

**Comment by cattyhouse** [comment] 2019-07-05 06:53
Method2:
According to this [clover issue](https://sourceforge.net/p/cloverefiboot/tickets/203/), you can use a shorter SMBIOS name to get over the limit, e.g. iMac19,2

this way, set CustomSMBIOSGuid=NO,  UpdateSMBIOSMode=create

**Comment by melxman** [comment] 2019-07-05 08:49
I'll try it later.thank you!

**Comment by vit9696** [comment] 2019-07-05 09:17
We tested setting:

* CustomSMBIOSGuid = YES
* UpdateSMBIOSMode = Custom

Works fine. Are you sure it is wrong? Please provide config.plist and dmidecode output. You can get dmidecode at https://github.com/acidanthera/dmidecode/releases.

**Comment by melxman** [comment] 2019-07-06 02:55
> We tested setting:
> 
> * CustomSMBIOSGuid = YES
> * UpdateSMBIOSMode = Custom
> 
> Works fine. Are you sure it is wrong? Please provide config.plist and dmidecode output. You can get dmidecode at https://github.com/acidanthera/dmidecode/releases.

I used your method. But the situation is still the same as I described before.
![5488-about](https://github.com/melxman/my-issues/blob/master/oc/dell-smbios-problem/5488-about.jpg)
![5488-overview](https://github.com/melxman/my-issues/blob/master/oc/dell-smbios-problem/5488-overview.jpg)

[5488-dmidecode](https://github.com/melxman/my-issues/blob/master/oc/dell-smbios-problem/5488-dmidecode)
[5488-config](https://github.com/melxman/my-issues/blob/master/oc/dell-smbios-problem/config.plist)

All the above files have been placed on my github project. I hope you have time to look at it, thank you.

**Comment by vit9696** [comment] 2019-07-06 10:24
@melxman I checked your SMBIOS and it looks correct to me:
https://github.com/melxman/my-issues/blob/fb41472/oc/dell-smbios-problem/5488-oc-dmidecode#L12-L13
https://github.com/melxman/my-issues/blob/fb41472/oc/dell-smbios-problem/5488-oc-dmidecode#L46-L53
https://github.com/melxman/my-issues/blob/master/oc/dell-smbios-problem/5488-oc-dmidecode#L76-L91

I am afraid I do not see a problem here.

**Comment by melxman** [comment] 2019-07-06 10:30
> @melxman I checked your SMBIOS and it looks correct to me:
> https://github.com/melxman/my-issues/blob/fb41472/oc/dell-smbios-problem/5488-oc-dmidecode#L12-L13
> https://github.com/melxman/my-issues/blob/fb41472/oc/dell-smbios-problem/5488-oc-dmidecode#L46-L53
> https://github.com/melxman/my-issues/blob/master/oc/dell-smbios-problem/5488-oc-dmidecode#L76-L91
> 
> I am afraid I do not see a problem here. Could you please elaborate what the bug is, and if it is _not_ a bug (but some incorrect configuration), I am afraid it should be discussed on the forums.

Can you look at the two pictures I uploaded? 
![5488-about](https://github.com/melxman/my-issues/blob/master/oc/dell-smbios-problem/5488-about.jpg)
![5488-overview](https://github.com/melxman/my-issues/blob/master/oc/dell-smbios-problem/5488-overview.jpg)

I use this config file and it will be black for a long time after the progress bar has finished. The password login box will then appear. Viewing the model information after entering the system is shown on the two images.

**Comment by vit9696** [comment] 2019-07-06 10:43
Right, the pictures did not show as you provided wrong links to them, but I do see it now. So, the situation is as follows:
- You have absolutely legit data provided by dmidecode
- About Mac shows nonsensical output
- dmidecode report and about your screenshots were made at the same time

Is this correct? I believe the issue is in wrong Mac serial. The config you provided has wrong Generic section, and Mac model is usually displayed based on serial number in About Mac.

- MLB - not provided
- ROM - not provided
- SystemSerialNumber - from iMac15,2 instead of MacBookPro15,2
- SystemUUID - not provided

**Comment by melxman** [comment] 2019-07-06 15:28
Yes,it's correct.
I'll test in Monday,thank you so much

**Comment by vit9696** [comment] 2019-07-07 20:17
Fixed in master.

**Closed** 2019-07-07 20:17 UTC
Labels: project:oc

**Comment by melxman** [comment] 2019-07-08 01:35
First of all, I am very grateful to the development team for fixing the dell  laptops' display of the  model.
Then, I would like to give feedback on the use of feelings: the speed of entering the system is still slow.

**Comment by vit9696** [comment] 2019-07-08 06:40
You are welcome, as for slow speed, well, it is a separate issue, and needs a lot more detailed description for us to fix it. I would not say that performance issues are unsolvable, but you will have to figure out way more details for us to recognise it as a bug and be able to help you. Currently we have to assume that it is a configuration problem and recommend you try seeking for help on the forums.
