### ISSUE TITLE
APFS volumes aren't detected without ApfsDriverLoader on some laptops

### ISSUE THREAD

**Issue by maxhartung** [acidanthera/bugtracker#1128] opened 2020-08-30 09:53 UTC
Hi,

For some time now, I searched all over the forums for a solution for this but nothing found. The issue is that the built-in APFS driver from OpenCore won't load (I guess). I use the ApfsDriverLoader to detect APFS volumes on my HP EliteBook 840 G2 with i5 5300U

Problem: APFS volumes aren't detected without using ApfsDriverLoader.

Tried: set GlobalConnet to true, jumpstart set to true, set -1 on mindate and version.

**My Configuration:**

HP EliteBook 840 G2
CPU: Intel Core i5 5300U
RAM: 16 GB
GPU: Intel HD Graphics 5500
SSD: Transcend TS240GMTS420S

**Some other users have this issue as well:**

https://www.reddit.com/r/hackintosh/comments/gsusp6/opencore_059_apfs_partitions_dont_show_up/

https://www.reddit.com/r/hackintosh/comments/hswo81/mac_os_not_showing_in_open_core_picker/

https://www.insanelymac.com/forum/topic/343299-hp-elitebook-840g2-with-opencore-057catalina-10154-cant-boot-first-install/

**Files:** 

[Debug_HP_EliteBook_840_G2.zip](https://github.com/acidanthera/bugtracker/files/5146606/Debug_HP_EliteBook_840_G2.zip)

I have attached the requested logs and also the system.log maybe it's useful.

**Comment by vit9696** [comment] 2020-08-30 09:58
Could you please redo the logs without ApfsDriverLoader?

**Comment by maxhartung** [comment] 2020-08-30 10:08
> Could you please redo the logs without ApfsDriverLoader?

Sure ! Here they are:

[Debug_HP_EliteBook_840_G2_NO_APFS.zip](https://github.com/acidanthera/bugtracker/files/5146616/Debug_HP_EliteBook_840_G2_NO_APFS.zip)

**Comment by vit9696** [comment] 2020-08-30 10:18
Please provide log with this version. Note, that it is based on 0.6.1 master and may require configuration update. For other files you could use [CI builds](https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true).

[OpenCore-apfs-r1.zip](https://github.com/acidanthera/bugtracker/files/5146627/OpenCore-apfs-r1.zip)

**Comment by Download-Fritz** [comment] 2020-08-30 10:33
@maxhartung Additionally, both logs without ApfsDriverLoader are incomplete (rebooted too early?). Please read what you upload before you upload.

**Comment by maxhartung** [comment] 2020-08-30 10:35
> Please provide log with this version. Note, that it is based on 0.6.1 master and may require configuration update. For other files you could use [CI builds](https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true).
> 
> [OpenCore-apfs-r1.zip](https://github.com/acidanthera/bugtracker/files/5146627/OpenCore-apfs-r1.zip)

> @maxhartung Additionally, both logs without ApfsDriverLoader are incomplete (rebooted too early?). Please read what you upload before you upload.

That was somewhat strange for me too. I did rebooted after 2 minutes (power button pressed) and I got stalled on this screen:

[Archive.zip](https://github.com/acidanthera/bugtracker/files/5146652/Archive.zip)

Should I let more time ? Like 10-20 minutes ?

**Comment by Download-Fritz** [comment] 2020-08-30 10:38
@maxhartung Do you use some slow USB flash drive to test? Yes, those may take a very, very long time to log (20 minutes sounds possible). Best use fast media or at least a flash drive with a r/w indicator. If your machine reboots without interaction, refer to _DisableWatchDog_.

**Comment by maxhartung** [comment] 2020-08-30 10:43
> @maxhartung Do you use some slow USB flash drive to test? Yes, those may take a very, very long time to log (20 minutes sounds possible). Best use fast media or at least a flash drive with a r/w indicator. If your machine reboots without interaction, refer to _DisableWatchDog_.

Even strangly that's not the case. It s Kingston DataTraveller 3.0 32 GB with write speeds of up to 70 MB/s and 150 MB/s

I don't think the USB is the problem. I will let it for 20 minutes and see

**Comment by Download-Fritz** [comment] 2020-08-30 10:46
@maxhartung Theoretical speeds do not matter at all, it probably has garbage NAND and some okay-ish cache. There was a severe decline in speed from your initial log to the one from the second archive and your new log ends in a very weird spot. Please verifiy that both the filesystem and the storage itself are working properly - with the current state, we will assume corruption or a hardware defect.

**Comment by vit9696** [comment] 2020-08-30 10:50
The drive itself may be fine, but there are two things to keep in mind:

- Older FAT32 UEFI filesystem drivers corrupt filesystems easily
- UEFI USB drivers in pre-Skylake era were particular garbage

So just like @Download-Fritz says, be extra careful.

**Comment by maxhartung** [comment] 2020-08-30 11:29
> @maxhartung Theoretical speeds do not matter at all, it probably has garbage NAND and some okay-ish cache. There was a severe decline in speed from your initial log to the one from the second archive and your new log ends in a very weird spot. Please verifiy that both the filesystem and the storage itself are working properly - with the current state, we will assume corruption or a hardware defect.



> The drive itself may be fine, but there are two things to keep in mind:
> 
> * Older FAT32 UEFI filesystem drivers corrupt filesystems easily
> * UEFI USB drivers in pre-Skylake era were particular garbage
> 
> So just like @Download-Fritz says, be extra careful.

So, you where right ! I booted using my second SSD and I have the log using the OpenCore.efi provided by vit9696 !!!

[opencore-2020-08-30-112604.txt](https://github.com/acidanthera/bugtracker/files/5146713/opencore-2020-08-30-112604.txt)

**Comment by vit9696** [comment] 2020-08-30 11:41
Right. Very strange behaviour, but try this one please.

[OpenCore-apfs-r2.zip](https://github.com/acidanthera/bugtracker/files/5146720/OpenCore-apfs-r2.zip)

**Comment by maxhartung** [comment] 2020-08-30 11:47
> Right. Very strange behaviour, but try this one please.
> 
> [OpenCore-apfs-r2.zip](https://github.com/acidanthera/bugtracker/files/5146720/OpenCore-apfs-r2.zip)

Sure ! Here you go:

[Archive.zip](https://github.com/acidanthera/bugtracker/files/5146726/Archive.zip)

**Comment by vit9696** [comment] 2020-08-30 11:51
Hmm, so you still cannot see any APFS drives I guess. This is quite strange, could you tell us a bit more on how many APFS disks do you have? Also, does the issue persist if you disable `UnblockFsConnect`?

**Comment by maxhartung** [comment] 2020-08-30 12:01
> Hmm, so you still cannot see any APFS drives I guess. This is quite strange, could you tell us a bit more on how many APFS disks do you have? Also, does the issue persist if you disable `UnblockFsConnect`?

I have 3 APFS volumes: the boot drive, the recovery, and one that is empty made fr macOS 11 but I didn't use it at all. It's macOS 10.15.6 the boot and the recovery

[Screenshot 2020-08-30 at 14 59 35](https://user-images.githubusercontent.com/16374922/91658524-83e35680-ead1-11ea-8c41-8f2b08405d24.png)

[Archive.zip](https://github.com/acidanthera/bugtracker/files/5146742/Archive.zip)

I tried with UnblockFsConnect set to false but nothing changed (see the new logs and EFI folder)

**Comment by vit9696** [comment] 2020-08-30 12:13
Hmmm, I see. Just to make it extra clear, you did not try to install macOS 11 on the volume you made for it, correct? Also, from what you know about other machines that have the same issue, do you have any basic understanding what Intel generation are they? Also Broadwell and lower or maybe there is some other pattern?

**Comment by maxhartung** [comment] 2020-08-30 12:21
> Hmmm, I see. Just to make it extra clear, you did not try to install macOS 11 on the volume you made for it, correct? Also, from what you know about other machines that have the same issue, do you have any basic understanding what Intel generation are they? Also Broadwell and lower or maybe there is some other pattern?

Yes, I didn't try to install macOS 11 on that volume.

I didn't find a pattern, one of the links which where linked, one of them has a i5-8265U so from CoffeLake generation. 

What does OpenCore different with integrated APFS driver vs the ApfsDriverLoader ? I am little bit curious

**Comment by vit9696** [comment] 2020-08-30 12:34
Basically both ApfsJumpStart and OpenCore succeed in driver loading, but driver connection (enabling the driver for your volumes) is slightly different, and it fails for OpenCore. What ApfsDriverLoader did was wrong in several ways and caused some genuine bugs on modern firmwares (like TianoCore OVMF), and that makes it harder to analyse the exact issue. We do not know what was a bug and what was an actual workaround firmware. It may take some time to track the issue. I attached another binary with further logging.

[OpenCore-apfs-r3.zip](https://github.com/acidanthera/bugtracker/files/5146770/OpenCore-apfs-r3.zip)

**Comment by startergo** [comment] 2020-08-30 12:38
I have similar issue on my cMP5,1 with one specific rx-580 with EFI vbios. without the APFS driver on automatic boot it does not show APFS drives only on firs NVRAM reset it shows them. I found that it will shows APFS drives if I use the old shell.efi from rEFIt (the 2MB one) to enter and exit shell, which makes no sense. Based on testing i think the issue is with the EFI vbios conflicting with OC.

**Comment by vit9696** [comment] 2020-08-30 12:54
@startergo this issue is unrelated and is about Apple EFI connecting only boot volume to speedup the boot. Please do not participate in this one as this will only add a lot of confusion.

**Comment by maxhartung** [comment] 2020-08-30 13:23
> Basically both ApfsJumpStart and OpenCore succeed in driver loading, but driver connection (enabling the driver for your volumes) is slightly different, and it fails for OpenCore. What ApfsDriverLoader did was wrong in several ways and caused some genuine bugs on modern firmwares (like TianoCore OVMF), and that makes it harder to analyse the exact issue. We do not know what was a bug and what was an actual workaround firmware. It may take some time to track the issue. I attached another binary with further logging.
> 
> [OpenCore-apfs-r3.zip](https://github.com/acidanthera/bugtracker/files/5146770/OpenCore-apfs-r3.zip)

Thanks for the explanation. I appreciate it ! I would really love to learn the low level stuff ! I do iOS programming for the moment. I have attached the EFI folder and the logs.

[Debug_HP_EliteBook_G2_R3.zip](https://github.com/acidanthera/bugtracker/files/5146855/Debug_HP_EliteBook_G2_R3.zip)

**Comment by vit9696** [comment] 2020-08-30 13:35
Right, please try this version. I believe it should work. Provide logs in any case.

[OpenCore-apfs-r4.zip](https://github.com/acidanthera/bugtracker/files/5146868/OpenCore-apfs-r4.zip)

**Comment by maxhartung** [comment] 2020-08-30 16:13
> Right, please try this version. I believe it should work. Provide logs in any case.
> 
> [OpenCore-apfs-r4.zip](https://github.com/acidanthera/bugtracker/files/5146868/OpenCore-apfs-r4.zip)

I tried, same result. I have attached 2 logs, one with unblock_fs_connect set to true and one set to false. Maybe it's useful.

[Debug_HP_EliteBook_840_G2_R4.zip](https://github.com/acidanthera/bugtracker/files/5147094/Debug_HP_EliteBook_840_G2_R4.zip)

**Comment by vit9696** [comment] 2020-08-30 16:35
That is really messy. Could you disable SecureBoot? I.e. set `SecureBootModel` to `Disabled` in the configuration. Without this 0.6.1 vs 0.6.0 tests are a bit biased.

**Comment by maxhartung** [comment] 2020-08-30 17:02
> That is really messy. Could you disable SecureBoot? I.e. set `SecureBootModel` to `Disabled` in the configuration. Without this 0.6.1 vs 0.6.0 tests are a bit biased.

Same result. I updated the config.plist according to the latest OpenCore 6.1 docs and set SecureBootModel to "Disabled" and every new field left as it is.

[Debug_HP_EliteBook_840_G2_R5.zip](https://github.com/acidanthera/bugtracker/files/5147148/Debug_HP_EliteBook_840_G2_R5.zip)

**Comment by vit9696** [comment] 2020-08-30 17:04
And if you change `EnableJumpstart` to `NO` and add `ApfsDriverLoader` it will work immediately? Just in case we broke something somewhere…

**Comment by maxhartung** [comment] 2020-08-30 17:17
> And if you change `EnableJumpstart` to `NO` and add `ApfsDriverLoader` it will work immediately? Just in case we broke something somewhere…

Yes, it detected the volumes but I was stuck on Apple logo. 

I will try with JumpStart set to true and with ApfsDriverLoader and see if it boots successfully. That's what I have in the original configuration. 

I couldn't get any logs because the battery died in the meantime and on Romanian trains we don't have any outlets unfortunately. 

I really appreciate the help. 

If you need the logs for the jumpStart set to false with ApfsDriverLoader or for other possible solutions, tell me and I will do it when I get home :)

**Comment by vit9696** [comment] 2020-08-30 17:26
Not really, thx for the test. I think we need to give it some thought to understand how to debug it further.

**Comment by maxhartung** [comment] 2020-08-31 05:16
> Not really, thx for the test. I think we need to give it some thought to understand how to debug it further.

No problem. If something comes up, let me now and I will test it.

**Comment by vit9696** [comment] 2020-08-31 05:44
Yes, I plan to put ApfsImageLoader code to OpenCore and add some debugging to it to better understand what is going on. I will post the builds with extra logging as they appear. Thanks.

**Comment by vit9696** [comment] 2020-09-06 09:14
Hello, are you able to run some tests today?

**Comment by maxhartung** [comment] 2020-09-06 09:26
> Hello, are you able to run some tests today? I built a version that includes ApfsDriverLoader instead of OcApfsLib with no changes, and want to make sure that it works correctly, and then try to understand the control flow.
> 
> 
> 
> [OpenCore-ocjs-r1.zip](https://github.com/acidanthera/bugtracker/files/5179349/OpenCore-ocjs-r1.zip)
> 
> 

Today nope, but tommorow yes, you can leave here the test files and instructions and I will do it when I get some free time.

**Comment by vit9696** [comment] 2020-09-06 09:27
Sure, I think we should be able to fix it in early 0.6.2 builds, because for 0.6.1 we had many other issues to tackle down.

**Comment by maxhartung** [comment] 2020-09-06 12:52
> Sure, I think we should be able to fix it in early 0.6.2 builds, because for 0.6.1 we had many other issues to tackle down.

Strange part: no APFS volumes detected. I was expecting to work this time to be honest.

[opencore-1980-01-01-000141.txt](https://github.com/acidanthera/bugtracker/files/5179658/opencore-1980-01-01-000141.txt)

**Comment by vit9696** [comment] 2020-09-06 13:42
My best guess is that the issue was missing connect call. I fixed it in this build.

[OpenCore-ocjs-r2.zip](https://github.com/acidanthera/bugtracker/files/5179720/OpenCore-ocjs-r2.zip)

**Comment by maxhartung** [comment] 2020-09-06 13:55
[Archive.zip](https://github.com/acidanthera/bugtracker/files/5179733/Archive.zip)

Still nothing..Should I update the config.plist file ?

**Comment by vit9696** [comment] 2020-09-06 14:00
Hmmmm. No. This is very surprising. I copied the exact same code we have in ApfsDriverLoader. Are you sure you have the last released ApfsDriverLoader?

**Comment by maxhartung** [comment] 2020-09-06 14:01
> Hmmmm. No. This is very surprising. I copied the exact same code we have in ApfsDriverLoader. Are you sure you have the last released ApfsDriverLoader?

Wait a minute, should I have ApfsDriverLoader in the drivers ?

**Comment by vit9696** [comment] 2020-09-06 14:11
No, I am just trying to understand why ApfsDriverLoader works for you. There must be something special about it. My other suspect is that `AudioDxe`, `HPFanReset` or maybe `HfsPlus` affect it. Try removing them.

**Comment by maxhartung** [comment] 2020-09-06 14:28
> No, I am just trying to understand why ApfsDriverLoader works for you. There must be something special about it. My other suspect is that `AudioDxe`, `HPFanReset` or maybe `HfsPlus` affect it. Try removing them.

I removed all of them leaving just OpenCanopy and OpenRuntime and same result

[Archive.zip](https://github.com/acidanthera/bugtracker/files/5179800/Archive.zip)

**Comment by vit9696** [comment] 2020-09-06 14:32
Also nothing with this one? I moved APFS loading earlier.

[OpenCore-ocjs-r3.zip](https://github.com/acidanthera/bugtracker/files/5179802/OpenCore-ocjs-r3.zip)

If it does not work, please make sure that you can use your drive with this binary:
https://github.com/acidanthera/AppleSupportPkg/releases/tag/2.1.6
Use master OpenCore version for this test from [here](https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true).

**Comment by vit9696** [comment] 2020-09-06 14:37
I additionally built ApfsDriverLoader 2.1.6 myself (recovering some buildsystem changes) and want you try it as well as the DEBUG version of the official 2.1.6 binary.

[ApfsDriverLoader-r1.zip](https://github.com/acidanthera/bugtracker/files/5179811/ApfsDriverLoader-r1.zip)

**Comment by maxhartung** [comment] 2020-09-07 11:25
> Also nothing with this one? I moved APFS loading earlier.
> 
> 
> 
> [OpenCore-ocjs-r3.zip](https://github.com/acidanthera/bugtracker/files/5179802/OpenCore-ocjs-r3.zip)
> 
> 
> 
> If it does not work, please make sure that you can use your drive with this binary:
> 
> https://github.com/acidanthera/AppleSupportPkg/releases/tag/2.1.6
> 
> Use master OpenCore version for this test from [here](https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true).


I will try them later today and report back to you. 

Master means the latest build with latest commit, true ?

**Comment by vit9696** [comment] 2020-09-07 11:30
Yes.

**Comment by maxhartung** [comment] 2020-09-07 15:17
> Yes.

Good news, download the latest debug build from Dortania, replaced the OpenCore.efi and rebooted. 

I only used 2 EFI drivers OpenRuntime and Canopy.

The APFS are showing, the boot completes

[opencore-1980-01-01-000015.txt](https://github.com/acidanthera/bugtracker/files/5183735/opencore-1980-01-01-000015.txt)

**Comment by vit9696** [comment] 2020-09-07 16:54
Huh?! Then maybe the issue is in some kind of configuration or driver? Let me know if you figure it out. I will close this since the issue is resolved.

**Comment by maxhartung** [comment] 2020-09-07 21:51
@vit9696 please see this thread:

https://github.com/acidanthera/bugtracker/issues/1139

**Comment by vit9696** [comment] 2020-09-07 21:56
Yeah, better to keep it in one place. Will try to get back to it tomorrow.

**Comment by maxhartung** [comment] 2020-09-08 17:30
> Yeah, better to keep it in one place. Will try to get back to it tomorrow.

Understood chief !

**Comment by vit9696** [comment] 2020-09-08 18:13
So, from what I understand, this should work. Try with and without GlobalConnect.

[OpenCore-ocjs-r4.zip](https://github.com/acidanthera/bugtracker/files/5190226/OpenCore-ocjs-r4.zip)

**Comment by maxhartung** [comment] 2020-09-08 20:52
> So, from what I understand, this should work. Try with and without GlobalConnect.
> 
> [OpenCore-ocjs-r4.zip](https://github.com/acidanthera/bugtracker/files/5190226/OpenCore-ocjs-r4.zip)

Sorry for late response.

 I tested in both situations and APFS volumes are detected with OpenCore-ocjs-r4.zip

I attached the logs and the last EFI configuration.

[Archive.zip](https://github.com/acidanthera/bugtracker/files/5191012/Archive.zip)

**Comment by vit9696** [comment] 2020-09-09 08:22
Hmm. That means, if you disable ConnectDrivers in UEFI section and remove all the drivers from OpenCore, even master version would work. The question is whether this is a driver or the ConnectDrivers option. Please try them all. Especially ConnectDrivers with some or no drivers.

**Comment by maxhartung** [comment] 2020-09-09 08:29
> Hmm. That means, if you disable ConnectDrivers in UEFI section and remove all the drivers from OpenCore, even master version would work. The question is whether this is a driver or the ConnectDrivers option. Please try master with them all. Especially ConnectDrivers with some or no drivers.

Remove all the drivers ? 

I only have the drivers that are required. Runtime and Canopy. No other drivers where used during testing. 

I will try adding the rest of the drivers and switch ConnectDrivers on and off and see the outcome

**Comment by vit9696** [comment] 2020-09-09 08:40
Yes, including these two. Point is to test whether APFS partitions show, the operating system may not boot.

**Comment by maxhartung** [comment] 2020-09-09 09:11
> Yes, including these two. Point is to test whether APFS partitions show, the operating system may not boot.

Good news after some time.

APFS volumes does show up if ConnectDrivers is set to NO. It works regardless if there are just OpenCore drivers or even those 2.

[Archive.zip](https://github.com/acidanthera/bugtracker/files/5193971/Archive.zip)

I attached 4 logs

CD = ConnectDrivers
Additional_Drivers = OpenCore drivers + HPFanReset.efi and HFSPlus.efi

Off topic question: is it worth it to open an issue regarding the 2-3 audio logs even when boot chime is playing ? Audio is working in OpenCore but these logs say otherwise.

03:269 00:001 OCAU: System volume is 75 (calculated from 75) - Success
03:271 00:001 OCAU: No AudioIo instances - Not Found
03:272 00:001 OCAU: Cannot find specified audio device - Not Found
03:274 00:001 OC: Audio connection failed - Not Found

**Comment by vit9696** [comment] 2020-09-09 09:54
Audio connection notifications are fine. Just ignore them.

Will APFS work if you set `ConnectDrivers` to YES and drop all the OpenCore drivers? If not, I think your workaround should be to use `GlobalConnect` = YES in APFS and `ConnectDrivers` = NO. In this case it might work fine everywhere.

**Comment by maxhartung** [comment] 2020-09-09 11:48
> Audio connection notifications are fine. Just ignore them.
> 
> Will APFS work if you set `ConnectDrivers` to YES and drop all the OpenCore drivers? If not, I think your workaround should be to use `GlobalConnect` = YES in APFS and `ConnectDrivers` = NO. In this case it might work fine everywhere.

No, it does not. I will try now what you said. 

During the tests above, the GlobalConnect was NO in APFS.

**Comment by vit9696** [comment] 2020-09-09 12:40
`GlobalConnect` does exactly what `ConnectDrivers` do, just only when APFS partitions are found. So basically you will need `GlobalConnect` if you want to use HFS+ partitions or something alike. I think we could still try to play with it a little, because this hack sounds a bit worrying to me at the moment, but I am not sure I will reach you before Friday.

**Comment by maxhartung** [comment] 2020-09-09 12:44
> `GlobalConnect` does exactly what `ConnectDrivers` do, just only when APFS partitions are found. So basically you will need `GlobalConnect` if you want to use HFS+ partitions or something alike. I think we could still try to play with it a little, because this hack sounds a bit worrying to me at the moment, but I am not sure I will reach you before Friday.

No problem. Why is worrying ? Doesn't work as expected I suppose. 

Still then, I will try some experiments with HFS volumes and post them here.

**Comment by vit9696** [comment] 2020-09-10 16:09
My primary concern is that only one driver connection attempt is possible on this system. The workaround we have looks fine, but I am worried about the consequences. Could you please try whether setting `ConnectDrivers` for this build still breaks it?

[OpenCore-ocjs-r5.zip](https://github.com/acidanthera/bugtracker/files/5203148/OpenCore-ocjs-r5.zip)

**Comment by maxhartung** [comment] 2020-09-11 09:29
> My primary concern is that only one driver connection attempt is possible on this system. The workaround we have looks fine, but I am worried about the consequences. Could you please try whether setting `ConnectDrivers` for this build still breaks it?
> 
> [OpenCore-ocjs-r5.zip](https://github.com/acidanthera/bugtracker/files/5203148/OpenCore-ocjs-r5.zip)

[Archive.zip](https://github.com/acidanthera/bugtracker/files/5208013/Archive.zip)

Hi, sorry for the late reply, it was a busy day yesterday. I am back today. 

Still no APFS volumes

**Comment by vit9696** [comment] 2020-09-11 09:33
Right, and will it work if you disable `UnblockFsConnect` and `ConnectDrivers`, and then enable `GlobalConnect`?

**Comment by maxhartung** [comment] 2020-09-11 09:41
> Right, and will it work if you disable `UnblockFsConnect` and `ConnectDrivers`, and then enable `GlobalConnect`?

[opencore-1980-01-01-000037.txt](https://github.com/acidanthera/bugtracker/files/5208083/opencore-1980-01-01-000037.txt)

Still nothing

**Comment by vit9696** [comment] 2020-09-11 09:48
Great. Now I see it. Any driver connection causes file system handles to be blocked. Therefore, `UnblockFsConnect` set to YES unlocks it first, and then you have only one chance to connect the drivers. Doing it at `ConnectDrivers` time is too early, as APFS is not loaded, but at `GlobalConnect` time is more or less fine.

Could you confirm that by enabling `UnblockFsConnect`? If still nothing, just redo this and the previous test on master version. It may be that the different connection style in r5 is simply unsuitable for you.

**Comment by maxhartung** [comment] 2020-09-11 10:20
[Archive.zip](https://github.com/acidanthera/bugtracker/files/5208288/Archive.zip)

Enabling UnblockFsConnect didn't do anything. I tried with master version and same. Still no APFS volumes only EFI partition which always appears.

**Comment by vit9696** [comment] 2020-09-11 10:21
Sorry? But what did change from the last working setup with master?

**Comment by maxhartung** [comment] 2020-09-11 10:25
I will try again, maybe it's my mistake. Just a moment please.

**Comment by maxhartung** [comment] 2020-09-11 10:34
@vit9696 

Done, user error. Master version works with:

GlobalConnect  = YES
ConnectDrivers = NO
UnblockFSConnect = YES

The R5 with same settings doesn't work.

Here is the log for the master version:

[opencore-1980-01-01-000016.txt](https://github.com/acidanthera/bugtracker/files/5208363/opencore-1980-01-01-000016.txt)

**Comment by vit9696** [comment] 2020-09-11 10:38
Yeah, right. Does disabling UnblockFSConnect break master?

**Comment by maxhartung** [comment] 2020-09-11 10:50
> Yeah, right. Does disabling UnblockFSConnect break master?

Yes, no volumes are detected. 

Off topic: Btw, there is a method to speed up the boot ? It logs everything to the screen and it's slow. Like 2 minutes till the picker appears and that s from internal SSD

**Comment by vit9696** [comment] 2020-09-11 11:17
Please try this version with these parameters:

GlobalConnect = NO
ConnectDrivers = YES
UnblockFSConnect = YES

[OpenCore-ocjs-r6.zip](https://github.com/acidanthera/bugtracker/files/5208559/OpenCore-ocjs-r6.zip)

Hopefully it will just work. I am sorry for the slow booting, it is due to logging. When we finish debugging you can set Target to 3 or 0 and install a RELEASE build, and it should boot quickly.

**Comment by maxhartung** [comment] 2020-09-11 11:34
> Please try this version with these parameters:
> 
> GlobalConnect = NO
> ConnectDrivers = YES
> UnblockFSConnect = YES
> 
> [OpenCore-ocjs-r6.zip](https://github.com/acidanthera/bugtracker/files/5208559/OpenCore-ocjs-r6.zip)
> 
> Hopefully it will just work. I am sorry for the slow booting, it is due to logging. When we finish debugging you can set Target to 3 or 0 and install a RELEASE build, and it should boot quickly.

It works ! 

Yes, I know that without logging is faster. I just didn't know if it's normal. I also use print statements in iOS dev and it slows down when I generate some XMLs. So what did you do to make it work ? Just load the driver eariler ?

[opencore-2020-09-11-112901.txt](https://github.com/acidanthera/bugtracker/files/5208621/opencore-2020-09-11-112901.txt)

**Closed** 2020-09-11 11:44 UTC
Labels: project:oc

**Comment by vit9696** [comment] 2020-09-11 11:49
It is normal, on many platforms the logging is very slow due to the underlying firmware drivers doing I/O being very slow. It writes 256 KBs per line, so it is kind of painful.

The lines you see are fine. They say that your system did **not** crash on hibernation wake last time.

I committed the fixes I gave you in r6 to master. Please make sure it works for you with the same set of parameters, which is the correct way to use it onwards.

Basically the root cause of the problem was that your firmware is flawed and blocks the disks from loading any filesystem driver. To workaround this we introduced the `UnblockFSConnect` hack. However, its implementation assumed that once we unblock the handle, it will never lock again. But it was not the case, and on your platform any attempt to connect any drivers would block the handles, making APFS driver connection after general driver connection (`ConnectDrivers`) do essentially nothing. This was fixed in master by making sure that the lock is lifted before trying to connect the APFS driver.

**Comment by maxhartung** [comment] 2020-09-11 11:58
Thank you very much for all the help and for the explanations. 

I learn something new every day !

I will try the master too when it's available on Dortania's website.

**Comment by maxhartung** [comment] 2020-09-11 12:20
Tried, works perfectly.

**Comment by thefat32** [comment] 2021-03-29 07:44
After updating my build from 0.5.7 to 0.6.7 I have this same problem. I can see APFS partitions only if I load ApfsDriverLoader.efi in drivers list. Will gather some logs and post them as soon as I can.

**Comment by thefat32** [comment] 2021-04-02 20:54
I'm sorry about the delay on this. I've tried with recommended config in this topic

```
GlobalConnect = NO
ConnectDrivers = YES
UnblockFSConnect = YES
```

With latest `ApfsDriverLoader.efi` my installation shows in boot picker, without it I couldn't find the way to get it shown in the bootpicker.

My setup is an Asus N56VB laptop (Ivy Bridge):

- Intel HM76
- Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz

Attaching logs with and without `ApfsDriverLoader.efi` and config.plist
[with-apfs-driver-loader.txt](https://github.com/acidanthera/bugtracker/files/6251204/with-apfs-driver-loader.txt)
[without-apfs-driver-loader.txt](https://github.com/acidanthera/bugtracker/files/6251205/without-apfs-driver-loader.txt)
[config.plist.txt](https://github.com/acidanthera/bugtracker/files/6251207/config.plist.txt)

Additional info: I don't know if this can cause this trouble but my installation is done in an SSD connected through an adapter for the ODD bay. Like [this one](https://www.amazon.com/-/es/Universal-bandeja-adaptador-port%C3%A1til-Toshiba/dp/B07H9X6SJF/ref=sr_1_4?__mk_es_US=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=laptop+caddy+ssd+adapter&qid=1617396796&sr=8-4)

Thank you all in advance!

**Comment by vit9696** [comment] 2021-04-02 21:23
Currently there is no way to replace one kext with another. They will conflict. You will need to patch out the class name. Like CtlnaAHCI. CC @khronokernel @dhinakg

**Comment by thefat32** [comment] 2021-04-02 21:36
Hi @vit9696, I think you posted in a wrong issue. Or I'm too dumb to understand what you were trying to say :D

**Comment by vit9696** [comment] 2021-04-03 15:24
@thefat32 your config has disabled APFS support.

```
			<key>EnableJumpstart</key>
			<false/>
```

**Comment by thefat32** [comment] 2021-04-03 18:24
OMG! You're totally right. I could swear I've had enabled it. Thank you for pointing it out, it's all working now!

**Comment by ShadyEmad111** [comment] 2023-07-21 17:57
i have the same specs but when i open the laptop it opens the bios immediatly and can't open the apfs drive @vit9696

**Comment by ahdyt** [comment] 2023-08-02 20:08
95:177 00:431 OCBP: APFS recovery volume handle missing - \System\Library\CoreServices\
95:634 00:456 OCB: APFS recovery is not present - Not Found

I got that error using hfsplus.efi or openhfsplus.efi 

UEFI
  APFS
     EnableJumpstart true
     GlobalConnect false
     HideVerbose true
     JumpstartHotPlug false
     MinDate 0
     MinVersion 0

**Comment by giapdong** [comment] 2024-05-04 16:36
Hi,
I cannot see main macOS partition when boot to picker, i see -Data partition instead. I follow all setting but all not work

When i goto recovery mode, i still see macos partition with read-only mode. So, how i can resolve it?

Thank you very much!

My PC:
| Configuration    | Model  |
| ---------------- | ------ |
| CPU              | Intel core i3 10105 |
| Motherboard      | GIGABYTE B460M AORUS PRO (rev. 1.0) |
| Graphics card    | Intel® UHD Graphics 630 |
| RAM              | G.SKILL Ripjaws V 1x8GB 2800 MHz |
| Disk             | SSD KINGSTON A2000 250GB M.2 NVMe |
| Monitor          | 2* AOC 24B1XH5 24" IPS 75Hz FHD |
| WiFi adapter     | USB TP-Link TL-WN725N Wireless N150Mbps |

[EFI.zip](https://github.com/acidanthera/bugtracker/files/15210366/EFI.zip)
