### ISSUE TITLE
Windows built by BlessOverride disappear from the boot menu

### ISSUE THREAD

**Issue by zijun-he** [acidanthera/bugtracker#875] opened 2020-04-27 06:56 UTC
`OpenCorePkg` compiles RELEASE version after adding bootstrap
BlessOverride> \ EFI \ Microsoft \ Boot \ bootmgfw.efi windows startup items built disappear.
Building windows startup items from Entries can appear in the startup menu and there is no corresponding win disk icon.
The corresponding DEBUG version BlessOverride> \ EFI \ Microsoft \ Boot \ bootmgfw.efi everything works.
The corresponding log cannot be provided, and it is not clear how to obtain the release.

```
<key>Misc</key>
	<dict>
		<key>BlessOverride</key>
		<array>
			<string>\EFI\Microsoft\Boot\bootmgfw.efi</string>
		</array>
		<key>Boot</key>
		<dict>
			<key>ConsoleAttributes</key>
			<integer>0</integer>
			<key>HibernateMode</key>
			<string>None</string>
			<key>HideAuxiliary</key>
			<true/>
			<key>HideSelf</key>
			<false/>
			<key>PickerAttributes</key>
			<integer>1</integer>
			<key>PickerAudioAssist</key>
			<false/>
			<key>PickerMode</key>
			<string>External</string>
			<key>PollAppleHotKeys</key>
			<false/>
			<key>ShowPicker</key>
			<true/>
			<key>TakeoffDelay</key>
			<integer>10000</integer>
			<key>Timeout</key>
			<integer>0</integer>
		</dict>
		<key>Debug</key>
		<dict>
			<key>AppleDebug</key>
			<false/>
			<key>DisableWatchDog</key>
			<false/>
			<key>DisplayDelay</key>
			<integer>0</integer>
			<key>DisplayLevel</key>
			<integer>2147483650</integer>
			<key>Target</key>
			<integer>3</integer>
		</dict>
		<key>Entries</key>
		<array>
			<dict>
				<key>Arguments</key>
				<string></string>
				<key>Auxiliary</key>
				<false/>
				<key>Comment</key>
				<string>Not signed for security reasons</string>
				<key>Enabled</key>
				<true/>
				<key>Name</key>
				<string>win10</string>
				<key>Path</key>
				<string>PciRoot(0x0)/Pci(0x1B,0x0)/Pci(0x0,0x0)/NVMe(0x1,2E-99-B2-71-5B-38-25-00)/HD(1,GPT,C54BB100-AECA-42E2-B6B2-91C764093855,0x28,0x64000)/\EFI\Microsoft\Boot\bootmgfw.efi</string>
			</dict>
		</array>
		<key>Security</key>
		<dict>
			<key>AllowNvramReset</key>
			<false/>
			<key>AllowSetDefault</key>
			<false/>
			<key>AuthRestart</key>
			<false/>
			<key>BootProtect</key>
			<string>None</string>
			<key>ExposeSensitiveData</key>
			<integer>6</integer>
			<key>HaltLevel</key>
			<integer>2147483648</integer>
			<key>ScanPolicy</key>
			<integer>0</integer>
			<key>Vault</key>
			<string>Optional</string>
		</dict>
		<key>Tools</key>
		<array>
			<dict>
				<key>Arguments</key>
				<string></string>
				<key>Auxiliary</key>
				<true/>
				<key>Comment</key>
				<string>Not signed for security reasons</string>
				<key>Enabled</key>
				<true/>
				<key>Name</key>
				<string>UEFI Shell</string>
				<key>Path</key>
				<string>OpenShell.efi</string>
			</dict>
		</array>
	</dict>
```

**Comment by vit9696** [comment] 2020-04-27 07:10
- What compiler did you use to build OpenCore? Is it the latest version of Xcode (11.4)?
- Please remove OpenCanopy and test with builtin picker for the time being (you have it set as External at the moment).
- Are you sure you are using macbuild.tool? If so, please make sure that you rebuilt a fresh copy (remove OpenCorePkg directory, download a fresh one, build, test).
- Provide a complete EFI directory (with Windows installation in it).
- Does it work with the starting backslash removed (`EFI\Microsoft\Boot\bootmgfw.efi`)? Please try that separately from the other steps.
- Tell us a bit more of your hardware and confguration. Firmware, chipset generation, CPU, motherboard, where operating systems are installed and what are they?

**Comment by zijun-he** [comment] 2020-04-27 07:17
I used macbuild.tool multiple times to build
GIGABYTE Z390 AORUS pro
8700k
rx580
Lenovo air13iwl is in the same situation
Test attached later

**Comment by williambj1** [comment] 2020-04-27 07:31
I did a poll in our community and it turns out that this is a widely confirmed issue.

> What compiler did you use to build OpenCore? Is it the latest version of Xcode (11.4)?
> Are you sure you are using macbuild.tool? If so, please make sure that you rebuilt a fresh copy (remove OpenCorePkg directory, download a fresh one, build, test).

Yes, Xcode 11.4 with toolchain XCODE5, and macbuild.tool, tested from builds from both CI and local system, mtoc is the prebuilt version in Acidanthera, 100% fresh clone from GitHub, fresh OpenCore and UDK. UDK is from Acidanthera as well.

> Please remove OpenCanopy and test with builtin picker for the time being (you have it set as External at the moment).

Same result with and without OpenCanopy, textmode is the same, ndk's fork has this issue as well.

> Does it work with the starting backslash removed (EFI\Microsoft\Boot\bootmgfw.efi)? Please try that separately from the other steps.

Haven't tried, will report later.

> Tell us a bit more of your hardware and confguration. Firmware, chipset generation, CPU, motherboard, where operating systems are installed and what are they?

Confirmed in Skylake and Coffeelake, APTIO V, not tested in insyde yet, This happens on Asus, Lenovo, and etc.

- HM370
- Z390
- 100 series (the tester didn't specify)

---

Btw, this happens after the bootstrap commits, using / not using bootstrap (disabled in config) gives the same result.

---

Logs will be provided later.

**Comment by zijun-he** [comment] 2020-04-27 07:33
Tested according to the test requirements and achieved the same result
OpenCore and windows boot are not in the same efi partition (ScanPolicy = 0) and can be displayed in the boot menu.

**Comment by vit9696** [comment] 2020-04-27 09:08
- Are you sure for DEBUG versions it is all fine (without OpenCanopy and such)? This makes very little sense to me. Could you try identifying the exact DEBUG binary that "fixes" the problem (you can use DEBUG and RELEASE binaries interchangeably).
- Does disabling Bootstrap AND doing NVRAM reset solve the problem?

**Comment by zijun-he** [comment] 2020-04-27 09:33
DEBUG confirms that it is working properly, first provide the DEBUG log as follows:
Disable OpenCanopy
[opencore-2020-04-27-091948.txt](https://github.com/acidanthera/bugtracker/files/4538735/opencore-2020-04-27-091948.txt)

Enable OpenCanopy
[opencore-2020-04-27-092434.txt](https://github.com/acidanthera/bugtracker/files/4538736/opencore-2020-04-27-092434.txt)

BootProtect = None How do I disable Bootstrap? Please guide me to try further

**Comment by vit9696** [comment] 2020-04-27 10:13
You disable bootstrap by turning it off (using None), and then doing NVRAM reset. On the next reboot it will be disabled.

**Comment by vit9696** [comment] 2020-04-27 10:16
Also, does DEBUG with logging disabled (Target = 0) also have the issue?

**Comment by zijun-he** [comment] 2020-04-27 10:18
Always use BootProtect = None，DEBUG Target = 0 Later

**Comment by vit9696** [comment] 2020-04-27 10:19
I.e. you have never enabled BootProtect?

**Comment by zijun-he** [comment] 2020-04-27 10:29
DEBUG Target = 0 works very well, the icon is displayed normally.
Regarding BootProtect, one of the windows icons has never been enabled. I enabled the windows icons on the other machine to be missing. After testing, all NVRAM resets.

**Comment by btwise** [comment] 2020-04-27 10:30
`  BootProtect = OC_BLOB_GET (&Config->Misc.Security.BootProtect);
  DEBUG ((DEBUG_INFO, "OC: LoadHandle %p with BootProtect in %a mode - %r\n", OcHandle, BootProtect, Status));

  if (OcHandle != NULL && AsciiStrCmp (BootProtect, "Bootstrap") == 0) {
    OcRegisterBootOption (L"OpenCore", OcHandle, OPEN_CORE_BOOTSTRAP_PATH);
  }  `
no need for` BootProtect, "None") == 0 `?

**Comment by vit9696** [comment] 2020-04-27 10:32
None is for convenience reasons. What is worrying, we cannot reproduce on our side. We really need the complete EFI directory.

**Comment by zijun-he** [comment] 2020-04-27 10:50
Remove some files that are considered insignificant and try to compress the files that meet the requirements
[EFI.zip](https://github.com/acidanthera/bugtracker/files/4539115/EFI.zip)

**Comment by ameenjuz** [comment] 2020-04-27 16:29
I compiled latest commit changes with xcode 11.4 
I comfirmed  BootProtect=None will disappear windowd partition from boot menu in release version but the debug version is reappearing windows partition in boot bemu 
I think this is bug in release version because of bootprotect and bootstrap

**Comment by vit9696** [comment] 2020-04-27 17:34
Could you try disabling `-Oz` and `-flto` in OpenCorePkg.dsc for release builds? Just remove these words from this line:
https://github.com/acidanthera/OpenCorePkg/blob/master/OpenCorePkg.dsc#L300

**Comment by ameenjuz** [comment] 2020-04-27 17:47
@vit9696 i removed this line and save with xcode 11.4
 XCODE:RELEASE_*_*_CC_FLAGS = -D OC_TARGET_RELEASE=1 $(OCPKG_BUILD_OPTIONS_GEN) $(OCPKG_ANAL_OPTIONS_GEN) -Oz -flto
shows compile error 
![Screen Shot 2020-04-27 at 8 43 46 PM](https://user-images.githubusercontent.com/21066935/80403470-4cb52c80-88c8-11ea-9889-f3b94158246e.png)

**Comment by vit9696** [comment] 2020-04-27 20:35
I did not ask you to remove the line, I asked you to remove `-Oz -flto`.

**Comment by ameenjuz** [comment] 2020-04-27 20:38
sorry for misunderstand now i removed this word -Oz -flto
compiled successfully
i will be report back after reboot and resetnvram

**Comment by ameenjuz** [comment] 2020-04-27 20:57
great now windows partition appear in boot menu 
but do not work due to blue screen stuck
my windows was working compiled before bootprotect but now doesn't work due to after added bootprotect option  i have full dsdt patched including   If (_OSI ("Darwin"))
![20200427_234223](https://user-images.githubusercontent.com/21066935/80419594-1be1f100-88e2-11ea-9339-1d05e413f716.jpg)

**Comment by vit9696** [comment] 2020-04-27 20:59
Please tell us which option caused Windows to disappear, -flto or -Oz. You can test by disabling either. As for Windows blackscreen, it is unrelated and must be some bug on your ACPI.

**Comment by ameenjuz** [comment] 2020-04-27 21:07
thanks @vit9696 
this word caused  -flto -Oz windows to disappear
i removed this word  -flto -Oz from OpenCorePkg.dsc and compiled worked
i set to BootProtect to None 
anyidea for blue screen issue during windows boot
windows icon appearing solved

**Comment by ameenjuz** [comment] 2020-04-27 21:45
windows blue screen stuck also exist in ndk version of OpenCore
i never seen windows blue screen stuck in ndk version before bootprotect option
i think that this is bootprotect bug 
please alalyze and remove code related to boot protect otherwise windows do not work

**Comment by Andrey1970AppleLife** [comment] 2020-04-27 21:56
You asked to check separately: 
without -Oz
without -flto

There is no support ndk, don't write about ndk.

**Comment by ameenjuz** [comment] 2020-04-27 22:32
@Andrey1970AppleLife 
sorry my dear i know There is no support ndk
i never seen such windows issue before  niether master branch nor fork branch

**Comment by maojinbing** [comment] 2020-04-27 23:00
> without -flto
without -flto

**Comment by ameenjuz** [comment] 2020-04-27 23:01
thanks for helping @vit9696 @Andrey1970AppleLife 
only this word -flto caused  windows to boot and disappear
i removed this word -flto from OpenCorePkg.dsc and compiled worked
i solved my problem removing this word -flto
worked fine like before
close this conversation
mark solved

**Comment by zijun-he** [comment] 2020-04-27 23:10
Removed the word -flto from OpenCorePkg.dsc and compiled it using macbuild.tool, the icon is displayed normally.
Removed the word -oz from OpenCorePkg.dsc and compiled it with macbuild.tool, the icon is not displayed.

**Comment by ameenjuz** [comment] 2020-04-27 23:12
@zijun-he 
don't remove this word -oz otherwise windows do not work and boot properly

**Comment by zijun-he** [comment] 2020-04-27 23:21
Deleting -oz for me, no trouble occurred for starting windows. Where you may be due to other problems, I am not sure.
It ’s just a test now, I am waiting for the final fix version of this issue by the project team.

**Comment by ameenjuz** [comment] 2020-04-27 23:33
@zijun-he 
good to know 
Deleting -oz for me  trouble occurred for starting windows
Deleting -flto for me, no trouble occurred for starting windows
we should test further until the final fix

**Comment by zijun-he** [comment] 2020-04-27 23:54
@ameenjuz 
Thanks for testing this issue together
I also deleted -flto -Oz test into windows and used it briefly and found no exception. I think Windows may start abnormally and may need to check other configurations. I only report on my test report. I didn't repeat your question ...

**Comment by vit9696** [comment] 2020-04-29 02:15
Should be resolved in master (https://github.com/acidanthera/OpenCorePkg/commit/cbfbc3487f91adce014d11ffdc29051e95ccc0c4). HideSelf may have been accidentally enabled regardless of the config preference.

**Closed by vit9696** 2020-04-29 02:15 UTC
Labels: project:oc

**Comment by ameenjuz** [comment] 2020-04-29 02:45
@vit9696
Good progressed excellent job
