### ISSUE TITLE
Touchpad gestures break after sleep

### ISSUE THREAD

**Issue by whatnameisit** [acidanthera/bugtracker#1385] opened 2020-12-23 08:09 UTC
Hi. I'm ussing VoodooPS2 and the touchpad name is SYN2601. Touchpad works fine until sleep. After wake, two- and three-finger gestures don't work well. They work only about 1 out of 5 times. Four-finger gestures never worked and I assume they are not supported for the touchpad on this old laptop.
I assume more logs are needed. Please tell me what logs to produce before and after sleep.
[opencore-2020-12-23-043427.txt](https://github.com/acidanthera/bugtracker/files/5733960/opencore-2020-12-23-043427.txt)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/5733978/EFI.zip)

**Comment by vit9696** [comment] 2020-12-23 12:43
Duplicate of https://github.com/acidanthera/bugtracker/issues/816.

**Closed by vit9696** 2020-12-23 12:43 UTC
Labels: project:ps2
