### ISSUE TITLE
UEFI volatile variables may not be set on APTIO V by VSMC

### ISSUE THREAD

**Issue by v10x** [acidanthera/bugtracker#515] opened 2019-10-14 14:30 UTC
This error shows on boot, the system works fine, although I wanted to open this issue to make sure it was tracked somewhere:

```
2019-10-14 06:59:36.603291-0700  localhost kernel[0]: (Lilu) Lilu:     api @ (DBG) got load request from VirtualSMC (108)
2019-10-14 06:59:36.603317-0700  localhost kernel[0]: (Lilu) Lilu:   nvram @ failed to get IODeviceTree:/options
2019-10-14 06:59:36.603721-0700  localhost kernel[0]: (Lilu) Lilu:     efi @ (DBG) successful efi call GetVariable with response 800000000000000E
2019-10-14 06:59:36.603724-0700  localhost kernel[0]: (Lilu) VirtualSMC:   efend @ failed to find valid status (800000000000000E, 8), VirtualSMC EFI module is broken
```

Platform:
- X299 Sage/10G
- Radeon VII

Versions:
- Lilu: latest stable debug release
- VirtualSMC: latest stable debug release
- AppleALC: latest stable debug release
- Whatevergreen: N/A

**Comment by vit9696** [comment] 2019-10-14 14:40
VirtualSmc.efi driver is not present in the system.

**Comment by v10x** [comment] 2019-10-14 14:45
@vit9696 The driver is actually there in OC configuration:
```
	<key>UEFI</key>
	<dict>
		<key>ConnectDrivers</key>
		<true/>
		<key>Drivers</key>
		<array>
			<string>ApfsDriverLoader.efi</string>
			<string>FwRuntimeServices.efi</string>
			<string>VirtualSmc.efi</string>
		</array>
```

its counterpart, Kext also is loaded and shows up in IOREG

```
                        <dict>
				<key>BundlePath</key>
				<string>VirtualSMC.kext</string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VirtualSMC</string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
```

**Comment by cattyhouse** [comment] 2019-10-14 14:50
Same error here even **VirtualSmc.efi is in Drivers array** : VirtualSMC:   efend @ failed to find valid status (800000000000000E, 8), VirtualSMC EFI module is broken

but everything works fine.

**Comment by vit9696** [comment] 2019-10-14 15:32
Must be old VirtualSmc.efi, the GUIDs changed several times between the releases. We will check it internally and close the issue if it is fine.

**Comment by v10x** [comment] 2019-10-14 15:38
Mine is the latest released version, I can overwrite it again and reboot if you'd like

**Comment by vit9696** [comment] 2019-10-14 15:52
Ok, I was able to reproduce it on one of my Skylake machines @_@.

**Comment by v10x** [comment] 2019-10-14 15:57
```
2019-10-14 08:53:43.569574-0700  localhost kernel[0]: (Lilu) Lilu:     api @ (DBG) got load request from VirtualSMC (108)
2019-10-14 08:53:43.569578-0700  localhost kernel[0]: (Lilu) VirtualSMC:    init @ (DBG) VirtualSMC bootstrap DBG-108-2019-10-08
2019-10-14 08:53:43.569587-0700  localhost kernel[0]: (Lilu) VirtualSMC:    prov @ (DBG) descriptor 0 was mapped
2019-10-14 08:53:43.569603-0700  localhost kernel[0]: (Lilu) VirtualSMC:    prov @ (DBG) descriptor 1 was mapped
2019-10-14 08:53:43.569606-0700  localhost kernel[0]: (Lilu) Lilu:   nvram @ failed to get IODeviceTree:/options
2019-10-14 08:53:43.570013-0700  localhost kernel[0]: (Lilu) Lilu:     efi @ (DBG) successful efi call GetVariable with response 800000000000000E
2019-10-14 08:53:43.570016-0700  localhost kernel[0]: (Lilu) VirtualSMC:   efend @ failed to find valid status (800000000000000E, 8), VirtualSMC EFI module is broken
2019-10-14 08:53:43.570020-0700  localhost kernel[0]: (Lilu) VirtualSMC:    init @ (DBG) successfully created vsmc provider instance
```

Rebooted with DEBUG mode 🤷‍♂

**Comment by vit9696** [comment] 2019-10-14 16:00
The issue is with the firmware, and it makes very little sense to me. It works just fine on some of our machines, but for some reason it fails on 3 (that much we have just discovered) other machines. All the machines with the issues are on APTIO V, yet there are working machines with APTIO V.

The easiest test is

```
nvram E09B9297-7928-4440-9AAB-D1F8536FBF0A:vsmc-status
E09B9297-7928-4440-9AAB-D1F8536FBF0A:vsmc-status VSMC%01%00%00%00
```

It will error on failure.

**Comment by v10x** [comment] 2019-10-14 16:10
```
$ nvram E09B9297-7928-4440-9AAB-D1F8536FBF0A:vsmc-status
nvram: Error getting variable - 'E09B9297-7928-4440-9AAB-D1F8536FBF0A:vsmc-status': (iokit/common) data was not found
```

**Closed** 2019-10-14 16:22 UTC
Labels: priority:normal, project:vsmc

**Comment by v10x** [comment] 2019-10-14 16:26
If I understand correctly, I can fix this before the release by moving VirtualSmc.efi up the list?

**Comment by vandroiy2013** [comment] 2019-10-14 16:28
Replace this driver to fix this issue. 
[FwRuntimeServices.efi.zip](https://github.com/acidanthera/bugtracker/files/3725422/FwRuntimeServices.efi.zip)

**Comment by v10x** [comment] 2019-10-14 16:36
Thanks, that fixed it.

Regarding the other error `nvram @ failed to get IODeviceTree:/options`, should I open another issue, is this related, or that can be ignored?

**Comment by cattyhouse** [comment] 2019-10-14 16:59
look like if VirtualSmc.efi is loaded before FwRuntimeServices.efi, the error will be gone?

**Comment by vit9696** [comment] 2019-10-14 23:44
options receive message is not an error and is expected. Reordering the driver liet does not fully resolve the problem, please rather update.
