### ISSUE TITLE
Unexpected SSD behaviour after waking up from sleep (Samsung SM961)

### ISSUE THREAD

**Issue by zombillano** [acidanthera/bugtracker#1030] opened 2020-07-08 22:19 UTC
Hi there, I want to thank you all at acindanthera for your awesome work! I came here because I was unable to find a solution to my problem. I looked everywhere and asked at so many different places (included the ones suggested here at this github repo) without any success. So I come here after a month or so trying to solve my problem.

So I'll start describing my problem: I have a stable OpenCore config with all working (battery, CPU power managment, USBs, etc, etc). What happens is that after waking up from sleep I am getting a slower speed on my SSD. First time I noticed was while using some VMs at the same time that makes some intensive work with my SSD. Before sleep everything works very well, but after waking up everything starts to act slow.

So I decided to make some benchmarks test to see the speeds that I'm getting before and after sleep. I used the script shown over [here](https://www.amsys.co.uk/using-command-line-to-benchmark-disks/), just to isolate the problem. I got these:

![Before Sleep](https://user-images.githubusercontent.com/34992400/86970240-b194ca80-c134-11ea-8552-5987bbc6f7db.png)
_Before Sleep_

![After Sleep](https://user-images.githubusercontent.com/34992400/86970278-bfe2e680-c134-11ea-8283-0ff472c5d134.png)
_After Sleep_

I'm getting this behaviour with both NVMeFix kext enabled and disabled. I did some research but I wasn't able to see what's wrong with either my SSD or my macOS instalation. I was able to reproduce this problem on macOS 10.14.5 to 10.15.5. I also tried with different versions of OpenCore, Lilu and NVMeFix kext, all with the same result.

This problem does not happen when using windows 10 or Linux distros (debian based), so I conclude that this should be a bug, though I'm not quite sure if one related to OpenCore. I know benchmarks aren't that important compared with real life use, but my work requieres to make use of multiple VM's at the same time with some intensive SSD load every now and then.

I attach the following:
- My EFI folder.
- Test script that I'm using to make test (test.sh).
- Screenshots showing behaviour.
- Kernel Logs, Lilu log and OpenCore Log.
- Datasheet of my SSD.

Setup is the next one:

**Lenovo Thinkpad T480**
- CPU: i7 8650u
- GPU: UHD 620
- RAM: 16GB 2400MHz
- SSD: Samsung SM961 512GB MZVKW512HMJP-000D1

Note: NVMe PCI-e port only has 2x lanes on T480, that's why I get around 1800MB/s before sleep (Can this be the source of the problem? 2x lanes instead of 4x lanes and this beeing misrecognized by macOS).

I can provide any other information if needed.

[EFI.zip](https://github.com/acidanthera/bugtracker/files/4893528/EFI.zip)
[Logs.zip](https://github.com/acidanthera/bugtracker/files/4893529/Logs.zip)
[SM961 datasheet.pdf](https://github.com/acidanthera/bugtracker/files/4893539/SM961.datasheet.pdf)

**Comment by 07151129** [comment] 2020-07-09 10:48
Can you post ioregistry dump before and wake?

**Comment by zombillano** [comment] 2020-07-09 13:01
Sure, I used IORegisterExplorer to make them, tell me if it would be better to give you a txt file with the output from ioreg command.

[IORegister Dumps.zip](https://github.com/acidanthera/bugtracker/files/4896946/IORegister.Dumps.zip)

**Comment by 07151129** [comment] 2020-07-09 13:06
I see you have `kIOPCIExpressASPML1    = 0x00000002` set for `pci-aspm-default` in `IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP11@1D,2/IOPP/PXSX@0`. Perhaps try injecting 0?

**Comment by zombillano** [comment] 2020-07-09 13:08
Ok, can you give me help with that? How can I inject that value?

**Comment by 07151129** [comment] 2020-07-09 13:10
The same way any device property is injected; consult the bootloader documentation.

**Comment by zombillano** [comment] 2020-07-09 13:42
Ok, somehow I was expecting something more difficult. Done but the problem still persist. Now IORegister shows `pci-aspm-default`set as 0 before and after sleep. Here are the new IORegister dumps:

[IORegister Dumps aspm fixed.zip](https://github.com/acidanthera/bugtracker/files/4897167/IORegister.Dumps.aspm.fixed.zip)

**Comment by asgmeonerandom** [comment] 2020-07-09 18:56
can you test if you get the same results on windows?

**Comment by zombillano** [comment] 2020-07-09 19:33
> can you test if you get the same results on windows?

I tested both under linux and windows and can confirm that I don't get the same behaviour that I get using macOS. Speeds keep the same before and after waking up on both OS. Speeds are also higher under windows than under macOS, like a couple hundred of MB/s more, but I'm more interested on getting this to work at the same speed before and after sleep than making it as fast as it is under windows.

**Comment by zombillano** [comment] 2020-07-11 04:15
So... Is there anything else that I can provide or do? Or something to read that can help me to find a solution?

**Comment by zombillano** [comment] 2020-07-14 01:13
I believe that this isn't possible to solve without strong knowledge on NVMe SSDs and IONVMeFamily kext. Since I don't have such amount of knowledge and I'm assuming that this would be hard to debug without hardware access to anyone with enough knowledge, I think I'm just going to sell it and buy something with full known compatibility. Thanks to all who tried to help me to solve this out! You can close this issue if you want.

**Comment by 07151129** [comment] 2020-07-20 18:32
I think it's better if we close this now. I could look at this sometime soon, but triaging this would require many experiments as there is not enough debug info, and the issue could be caused by anything, ranging from ACPI to the NVMe driver.

**Closed by 07151129** 2020-07-20 18:32 UTC
Labels: project:nvme
