### ISSUE TITLE
Save Log to UEFI variable not working

### ISSUE THREAD

**Issue by athei** [acidanthera/bugtracker#536] opened 2019-10-27 18:51 UTC
Misc/Debug/Target is set to decimal 19 therefore but the boot-log variable does not exist:
```
nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:boot-log
nvram: Error getting variable - '4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:boot-log': (iokit/common) data was not found
```

Other variables under the same GUID do work (like `4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:boot-path`).

**Comment by Andrey1970AppleLife** [comment] 2019-10-28 12:24
I checked, it works.
From your context it is clear nothing.
You didn't give information on the hardware configuration and other.

**Comment by athei** [comment] 2019-10-28 17:53
My hardware is Z390 Phantom Gaming 6 with an Intel i9-9900K. `DisableVariableWrite` is set to YES.

**Comment by vandroiy2013** [comment] 2019-10-28 17:59
Arrrgggh... 
Hardware NVRAM on this chipset is dead. Are you hoping to get a log with broken NVRAM?

**Comment by athei** [comment] 2019-10-28 18:54
But just exporting variables from OC to macOS should work just like all the other variables that are properly exported without hardware support, right? What is different with this boot-log variable?

**Comment by vit9696** [comment] 2019-10-28 20:50
All other variables are marked as volatile, and thus are available. This one is non-volatile.

**Comment by athei** [comment] 2019-10-28 20:51
Ahh tanks thought this was volatile, too.

**Comment by vit9696** [comment] 2019-10-28 20:55
Hrm, actually, I remember adding a dedicated bit for volatile/non volatile for this variable. Does it fail in both cases? If so, could just be failing to handle data after a certain step.

**Comment by athei** [comment] 2019-11-03 10:39
@vit9696  I did some testing. It does **not** make a difference whether the non-volatile bit is set or not (bit 5). My understanding is that it should work even with broken NVRAM when the non-volatile bit is unset.

That said, when I additionally set `DisableVariableWrite` to `false` macOS does not even boot (non-volatile bit not set). This seems to me that it always tries to do it non-volatile which then prevents the boot because it hangs on write. Maybe the non-volatile check is not working properly?

**Comment by vit9696** [comment] 2019-11-04 17:04
We checked the code. `DisableVariableWrite` disables writing to NVRAM as soon as boot.efi is started (to protect NVRAM from boot.efi), this basically means that the log will be killed, be that volatile or not. All in all I would say it is by design.

**Comment by vit9696** [comment] 2019-12-02 11:36
@Download-Fritz perhaps we can change this to protect only from non-volatile writes?

**Closed** 2019-12-19 12:08 UTC
Labels: invalid, project:oc
