### ISSUE TITLE
BuiltinGraphics breaks Shell clear screen in help -b

### ISSUE THREAD

**Issue by n-d-k** [acidanthera/bugtracker#837] opened 2020-04-11 15:03 UTC
Is this the current known bug with OpenShell when using command with -b?  or am I missing something in config.plist? The screen text output seems to go awol when command with -b.

![20200411_094801](https://user-images.githubusercontent.com/55958134/79047349-9ff66200-7bdb-11ea-94fd-59937c8a2813.jpg)

**Comment by vit9696** [comment] 2020-04-11 18:47
I do not understand what you tried to say here. Please be more clear what you did, what you expected to achieve, what happened. Starting with what is `command -b` in the first place.

**Comment by n-d-k** [comment] 2020-04-11 23:47
Oh, sorry for my language. What I meant is when using any shell commands accompanied by -b, for example "help -b" or "dh -b", the result output is printed over the old one, like the screenshot above.

**Comment by vit9696** [comment] 2020-04-12 00:57
Right, and how can you reproduce this? Any special configuration?

**Comment by n-d-k** [comment] 2020-04-12 01:01
It does seem happens only when using shell with Text console wrapped in GraphicsOutput.

**Comment by vit9696** [comment] 2020-04-12 01:09
What does `GraphicsOutput` or `GraphicConsole`, you mentioned in the title of the bugreport, mean? Cannot you provide the information properly? I am not keen on guessing on what you see, because just running OpenShell and typing `help -b` works fine for me in VMware.

**Comment by n-d-k** [comment] 2020-04-12 01:17
Try it on the real thing, not VMware...

**Comment by vit9696** [comment] 2020-04-12 01:22
Sorry, but I will have to close the issue if you do not explain how to reproduce it, be that VMware or not. It works fine for us on non-VMware as well.

**Comment by vit9696** [comment] 2020-04-12 01:28
Are you sure you use the latest OpenShell from the latest OpenCore release (0.5.7)?
See: https://github.com/acidanthera/OpenCorePkg/releases.

**Comment by n-d-k** [comment] 2020-04-12 01:30
Do whatever you want, I just want to let you know..since the bug is there regardless, I didn't just make it up.  And I mentioned, the text console is wrapped in GraphicOutput, is OC is currently wrapping the gST->Conout->OutputString in a GraphicOutput mode.

**Comment by vit9696** [comment] 2020-04-12 01:36
I still do not understand what `GraphicOutput` means. Do you happen to refer to `TextRenderer`? If you understand the issue, perhaps you can submit a patch?

**Comment by n-d-k** [comment] 2020-04-12 01:38
Yes, TextRenderer

**Comment by vit9696** [comment] 2020-04-12 01:43
Right, so does it only happen with `TextRenderer` in `BuiltinGraphics` mode or other modes are also affected? If it is only only `BuiltinGraphics` I think I might have an idea. It would have been really easier if you explained things directly from the beginning.

**Comment by n-d-k** [comment] 2020-04-12 01:49
I guess that's the only mode was affected.

**Comment by vit9696** [comment] 2020-05-11 01:09
That's pretty insane, I recorded the video with delays at every OutputStr. This is how it actually looks:
[PageMode.mp4.zip](https://github.com/acidanthera/bugtracker/files/4607109/PageMode.mp4.zip)

**Closed** 2020-05-11 01:45 UTC
Labels: priority:low, project:shell
