### ISSUE TITLE
SandyBrigde laptop get error allocating 0x15be pages for 10.6.8 booting

### ISSUE THREAD

**Issue by Sher1ocks** [acidanthera/bugtracker#1156] opened 2020-09-13 12:30 UTC
HI first of all, 
to vit and goldfish
thank you for hard work of old macOS.
i heard some users booted snow leopard with latest OC.
so i determined that boot snow leopard boot in my hp 4230s.

i managed all parts in high sierra. everything is good.
then. tried to boot snow leopard.
but i get "error allocating 0x15be pages"
when using clover, i can using only OsxAptioFixDrv-64.efi. i can't boot from other drivers. it shown same error like OC now.

here is pic
![KakaoTalk_Photo_2020-09-13-21-21-26](https://user-images.githubusercontent.com/2107738/93018026-fdb62c80-f607-11ea-9f47-c466e6e90d30.jpeg)
![KakaoTalk_Photo_2020-09-13-21-21-36](https://user-images.githubusercontent.com/2107738/93018030-073f9480-f608-11ea-88c6-35b2133ae1d8.jpeg)

snow leopard log(problem)
[opencore-2020-09-13-114747.txt](https://github.com/acidanthera/bugtracker/files/5214072/opencore-2020-09-13-114747.txt)

high sierra log(no problem)
[opencore-2020-09-13-114945.txt](https://github.com/acidanthera/bugtracker/files/5214074/opencore-2020-09-13-114945.txt)

Booter-Quirks Setting.
![스크린샷 2020-09-13 오후 9 22 27](https://user-images.githubusercontent.com/2107738/93018075-38b86000-f608-11ea-8863-52e8c2adb4be.png)

i tried many combinations in quirk option.
but no luck..

thanks in advance.

**Comment by vit9696** [comment] 2020-09-13 12:33
This is a duplicate of https://github.com/acidanthera/bugtracker/issues/1125. On your firmware currently the only option is DuetPkg.

**Closed by vit9696** 2020-09-13 12:33 UTC

**Comment by Sher1ocks** [comment] 2020-09-13 12:38
thanks i will try
