### ISSUE TITLE
Voodoo PS2 2.34 Update broke Touchpad Buttons and Nipple on Thinkpad L490

### ISSUE THREAD

**Issue by takobaba** [acidanthera/bugtracker#2242] opened 2023-03-12 05:30 UTC
Updated my Opencore to the latest package right now(0.9.0) and used OCAT to update KEXTs as well. When I updated VoodooPs2controller.kext to 2.3.4 the 2 click buttons and red nipple on my thinkpad stopped working.

I have rolled back to 2.3.3 and its working now.

Hackintosh Ventura 13.2.1
Thinkpad L490 - i7 8550
Opencore 0.9.0
All kexts are the latest stable available

I am not sure what sorta logs to collect specific to this case and how to.

**Comment by 1Revenger1** [comment] 2023-03-12 05:35
Is this an Elans trackpad too? Likely a duplicate of Duplicate of https://github.com/acidanthera/bugtracker/issues/2240
Can you try the build/instructions in my last post there?

**Closed by 1Revenger1** 2023-03-12 05:35 UTC
Labels: project:ps2
