### ISSUE TITLE
BlueToolFixup.kext breaks macOS incremental OTA Updates

### ISSUE THREAD

**Issue by TonyC5** [acidanthera/bugtracker#2433] opened 2024-10-16 19:22 UTC
When BlueToolFixup.kext is injected via OC, incremental OTA macOS updates fail and revert to a download of the full macOS installer.  A work-around is to temporarily disable Kernel > Add > BlueToolFixup.kext in OC config.plist, perform the macOS OTA update and then re-enable BlueToolFixup.kext after the macOS incremental update completes.

If BluetoolFixup.kext is left enabled during the entire macOS update process, the macOS update completes successfully with the full macOS installer (after failing with the incremental macOS installer).

I am currently testing this with release versions of Open Core 1.0.2, Lilu.kext 1.6.9 and BlueToolFixup.kext 2.6.9 with both macOS Sonoma and Sequoia.

I am using BlueToolFixup.kext with  Intel BlueTooth (Open Wireless Project Bluetooth version 2.5.0 kexts), but have seen reports by others indicating that this BlueToolFixup.kext / macOS OTA issue occurs when using BlueToolFixup.kext with Brcm chipsets.

Note that only BlueToolFixup.kext needs to be disabled / re-enabled.  The other Bluetooth kexts can remain enabled during the incremental macOS update.

My System Specs

- Wi-Fi/Bluetooth m.2 card: Intel 9560NGW
- SMBIOS macMini8,1
- BlueToolFixup.kext 2.6.9 (Release)
- IntelBluetoothFirmware.kext and IntelBTPatcher.kext 2.5.0
- Lilu.kext 1.6.9 (Release)
- RestrictEvents.kext 1.1.5 (Release) with revpatch=sbvmm
- Open Core 1.0.2 (Release)
- csr-active-config = 0x0 (SIP fully enabled)

I am not using any Wi-Fi (no Wi-Fi kexts).

**Comment by khronokernel** [comment] 2024-10-21 18:19
Duplicate of https://github.com/acidanthera/bugtracker/issues/2080.

**Closed by khronokernel** 2024-10-21 18:19 UTC
Labels: project:brcm
