### ISSUE TITLE
IGPU frequency stuck at 1GHz when using hardware video decode with Apple GuC

### ISSUE THREAD

**Issue by tiger511** [acidanthera/bugtracker#800] opened 2020-04-04 10:59 UTC
Here is how to reproduce:
1) Use latest whatevergreen 

2) Use igfxfw=2 boot arg

3) Open safari

4) Watch a streaming .eg: https://mixer.com/shroud?vod=xjN2eVd4SUCLiQ00iU-CLw

5)GPU frequency will reach 1GHz and stuck there

Then even closing safari doesn't fix this.GPU stuck at full frequency until sleep/reboot.Looks like using GPU decode breaks something which causes the iGPU to stay at high frequency even on idle.

My hardware: i7-8750h
iGPU: Intel UHD 630

**Comment by vit9696** [comment] 2020-04-04 11:02
Well, we cannot control what Intel firmware does and how it interfaces with the operating system. Most likely the same issue happens with real macs. I can leave this open with help wanted, but we do not plan to explore it ourselves.

**Comment by Andrey1970AppleLife** [comment] 2020-04-04 11:04
We don't approve content distribution 18+

**Comment by tiger511** [comment] 2020-04-04 11:04
> We don't approve content distribution 18+

You mean the example link?

**Comment by vit9696** [comment] 2020-04-04 11:07
@Andrey1970AppleLife it is just some game children play, no porn or such, the prompt at the website is misleading. Let's have the issue open if somebody could contribute more technical information.

**Comment by tiger511** [comment] 2020-04-04 11:12
> Well, we cannot control what Intel firmware does and how it interfaces with the operating system. Most likely the same issue happens with real macs. I can leave this open with help wanted, but we do not plan to explore it ourselves.

I don't think same happens with real macs.Even playing any video in apple tv does the same too.Sleep or Reboot cycle fixes it.I have to figure out if its related to Apple GuC or no.i suppose igfxfw=5 will use host preemptive firmware without apple GuC?

**Comment by vit9696** [comment] 2020-04-04 11:16
Correct, removing `igfxfw=2` will also work the same way.

**Comment by Mateo1234454545** [comment] 2020-04-04 12:22
Mine Intel UHD620 goes up to 0,15ghz and then drops to 0 after video exit.

**Comment by tiger511** [comment] 2020-04-04 13:43
Okay i confirmed my theory.This bug is related to GuC only.When i'm using Host preemptive scheduler,it works fine.But When i load Apple GuC with igfxfw=2 boot args, playing above video in safari make it stuck in  highest turbo boost GPU frequency.Sleep/wake reloads the GuC firmware (I found it in kernel log )and it goes back to normal.

Without GuC:
<img width="1241" alt="Screen Shot 2020-04-04 at 7 16 29 PM" src="https://user-images.githubusercontent.com/53279423/78452258-1f4fd700-76ac-11ea-8cb9-ddf2abf83af8.png">

With GuC:
<img width="1425" alt="Screen Shot 2020-04-04 at 7 31 57 PM" src="https://user-images.githubusercontent.com/53279423/78452264-270f7b80-76ac-11ea-87d3-4b316f75c049.png">

With GuC Even after quitting all app,still stuck at high frequency:
<img width="1259" alt="Screen Shot 2020-04-04 at 7 32 10 PM" src="https://user-images.githubusercontent.com/53279423/78452274-2e368980-76ac-11ea-9e9c-99538c6b263e.png">

I have macbook air 2014 to test on.But since it's preskylake, it doesn't support GuC.Unfortunately i don't have any other real mac with post skylake hardware to test it.Maybe someone can test it for us?

**Comment by tiger511** [comment] 2020-04-04 13:44
> Mine Intel UHD620 goes up to 0,15ghz and then drops to 0 after video exit.

Are you using latest Whatevergreen from master branch with igfxfw=2 boot args?

**Comment by Mateo1234454545** [comment] 2020-04-04 13:46
> > Mine Intel UHD620 goes up to 0,15ghz and then drops to 0 after video exit.
> 
> Are you using latest Whatevergreen from master branch with igfxfw=2 boot args?

I'm using latest kext but without igfxfw argument.

**Comment by tiger511** [comment] 2020-04-04 13:53
> I'm using latest kext but without igfxfw argument.

can you please use that boot arg and let me know if your gpu behaves normal with above video in safari.

**Comment by JosephDuffy** [comment] 2020-04-08 17:34
I'll try and add what I can to this:

I'm using latest WhateverGreen with `igfxfw=2 shikigva=80` boot args. I have an i9-9900k (UHD630) and an RX 580.

The linked video in Safari does not cause the GFX frequency to go up at all. Although I cann't get DRM content (e.g. Amazon Prime Video) to play in Safari so perhaps Safari isn't using the iGPU as it should?

When playing a very high bitrate video (400mbps HEVC) in VLC there's a small ramp up, then it stays at 1.2GHz (I assume the max), then when it's finished it goes back down to 0.

<img width="512" alt="Screenshot 2020-04-08 at 18 30 17" src="https://user-images.githubusercontent.com/1325813/78814810-2ede6100-79c7-11ea-9bca-09c1a1de10f8.png">

If I play a video in Firefox (e.g. Twitch) the iGPU will go up and down, but I've never even seen it go above 1GHz.

<img width="512" alt="Screenshot 2020-04-08 at 16 14 34" src="https://user-images.githubusercontent.com/1325813/78814864-49183f00-79c7-11ea-9328-1bb11a509e91.png">

Note that prior to the latest WhateverGreen version – and without `igfxfw=2` – I cannot play the 400mbps HEVC video for more than a couple of seconds before it pauses. So for me this update has massively improved my iGPU performance 🙌

It I manage to get DRM content to play in Safari (I had it work _once_, but after a reboot it started failing) I'll provide an update regarding the original video posted here.

**Comment by tiger511** [comment] 2020-04-08 18:34
@JosephDuffy  I don't think GuC firmware is loading for you.Did you check log to see which firmware is loaded for iGPU? Use this command to check: 
`log show --last=boot|grep -i igpu`
Also your monior connected to AMD GPU or iGPU?

**Comment by JosephDuffy** [comment] 2020-04-09 12:18
> @JosephDuffy I don't think GuC firmware is loading for you.Did you check log to see which firmware is loaded for iGPU? Use this command to check:
> `log show --last=boot|grep -i igpu`
> Also your monior connected to AMD GPU or iGPU?

In that output I have `kernel: (AppleIntelKBLGraphics) [IGPU] Graphics accelerator is using scheduler: Apple Firmware`.

The system logs in Hackintool contains `kernel[0]: (AppleIntelKBLGraphics) <AppleIntelKBLGraphics`IGGuC::loadBinary(bool)> [IGPU] Graphics Firmware Version: 2.14.0.0`.

**Comment by tiger511** [comment] 2020-04-09 14:38
Then it is indeed using Apple GuC.What looked weird to me in your graph is  "GFX REQ" and "GFX AVG".Usually when i use GuC, both of them show somewhat same number.Without GuC, GFX REQ average usually shows "0.35" straight line like your pic.

**Comment by JosephDuffy** [comment] 2020-04-09 16:23
> Then it is indeed using Apple GuC.What looked weird to me in your graph is "GFX REQ" and "GFX AVG".Usually when i use GuC, both of them show somewhat same number.When GPU is not in use GFX REQ shows 0. But without GuC, GFX REQ usually shows "0.35" or a higher number with a straight line like your pic.

GFX req is always 1.2GHz, which I thought was odd, but other than no DRM in Safari (which also doesn't work without Apple GuC) it all seems to work. 1.2GHz seems to be the max my iGPU will go up to.

**Comment by Utmostmao** [comment] 2020-04-18 16:28
I encountered the same problem.

**Comment by Utmostmao** [comment] 2020-04-18 16:30
I encountered the same problem.
GPU frequency will reach 1GHz and stuck there.(When opening the app store and playing video ads）

**Comment by chromer030** [comment] 2020-04-18 17:21
I also tested and have this problem , when opening App Store and playing ads , GPU frequency stuck at 1GHZ , my build is Skylake based.

**Comment by vasishath** [comment] 2020-04-27 02:47
> I also tested and have this problem , when opening App Store and playing ads , GPU frequency stuck at 1GHZ , my build is Skylake based.

How did u manage to enable GuC loading on skylake ? AFAIK, it loads only on 300 series chipset and later

**Comment by 07151129** [comment] 2020-06-28 12:29
Can you post the kernel log that includes the moment when after stopping a video the frequency becomes stuck? I would also need a relevant timestamp (hour and minute).

**Comment by nickhx** [comment] 2020-06-28 18:54
Hi, I get the following error message in the kernel log as soon as I kill the window in Safari running the above test...

error	19:52:30.266223+0100	symptomsd	received unknown kernel SysInfo stat '96' -> '0'
default	19:52:31.039201+0100	kernel	[IGFB][ERROR  ]  updateSliceConfig Requesting Invalid Slice Count
default	19:52:31.039211+0100	kernel	[IGFB][ERROR  ]  updateSliceConfig Requesting Invalid EU Count

**Comment by 07151129** [comment] 2020-06-28 18:57
Can you please post a complete log obtained from running `log show --predicate 'process == "kernel"' --last boot --style syslog`? Make sure you boot with `debug_agpm=0xffffffff agpmlogmask=0xffffffff`.

**Comment by nickhx** [comment] 2020-06-28 19:08
No problem, kernel log attached.  I started the above website just after 20:05 and then closed the window at 20:06.  Let me know if you need anything else. 

[kernellog.log](https://github.com/acidanthera/bugtracker/files/4842847/kernellog.log)

**Comment by 07151129** [comment] 2020-06-28 19:19
> No problem, kernel log attached. I started the above website just after 20:05 and then closed the window at 20:06. Let me know if you need anything else.
> 
> [kernellog.log](https://github.com/acidanthera/bugtracker/files/4842847/kernellog.log)

You are still missing the two arguments I specified:

> Boot args: brcmfx-country=IE igfxfw=2 igfxonln=1 igfxagdc=0

**Comment by nickhx** [comment] 2020-06-28 19:37
Forgot to clear NVRAM after updating boot args in config.plist.... Here you go.
[kernellog2.log](https://github.com/acidanthera/bugtracker/files/4842899/kernellog2.log)

**Comment by tiger511** [comment] 2020-06-28 22:22
Laptop Started at 4:17. Opened safari and started playing the stream at 4:18  and the gpu stuck at 1.05 GHz.I took the log at 4:19 and the GPU was still stuck at 1.05 GHz
[igpu.log](https://github.com/acidanthera/bugtracker/files/4843076/igpu.log)

**Comment by tiger511** [comment] 2020-06-28 22:33
Stream started at exact 4:32:00 AM and the GPU freequency stuck at 1.05GHz at roughly around  4:32:10 AM.
[igpu2.log](https://github.com/acidanthera/bugtracker/files/4843088/igpu2.log)

**Comment by 07151129** [comment] 2020-07-02 12:36
Does booting with AGPM help in any way? (`AGPM` class  in IORegistry)

**Comment by tiger511** [comment] 2020-07-02 14:50
> Does booting with AGPM help in any way? (`AGPM` class in IORegistry)

How do i boot with AGPM?

**Comment by tiger511** [comment] 2020-07-11 15:36
@07151129  Any update on the issue what might cause it?

**Comment by benbender** [comment] 2020-07-25 01:02
@07151129 did you noticed 
````
2020-06-28 20:03:48.173184+0100  localhost kernel[0]: (AppleGraphicsPowerManagement) [AGPM][INFO ][CONTROLLER  ][start                   ] fIsExternalGPU 0
2020-06-28 20:03:48.173224+0100  localhost kernel[0]: (IOPlatformPluginFamily) X86PlatformPlugin::cgRegisterPLimitCallbackHandler - There are 0 entries in the linked list before target 0xffffff8036fa1800 callback 0xffffff7f832c5eae name AGPM, LINK at 0xffffff803557a458 contains 0xffffff80348fff60
2020-06-28 20:03:48.173227+0100  localhost kernel[0]: (IOPlatformPluginFamily) X86PlatformPlugin::cgRegisterPLimitCallbackHandler - There are 0 entries in the linked list before target 0xffffff8036fa1800 callback 0xffffff7f832c5eae name AGPM, LINK at 0xffffff803557a458 contains 0xffffff80348fff60
2020-06-28 20:03:48.173313+0100  localhost kernel[0]: (IOPlatformPluginFamily) HE2N_Key Does Not Exist, use kSMCPStatesIGPU for Internal GPU
2020-06-28 20:03:48.173314+0100  localhost kernel[0]: (IOPlatformPluginFamily) HE2N_Key Does Not Exist, use kSMCPStatesIGPU for Internal GPU
2020-06-28 20:03:48.173329+0100  localhost kernel[0]: (IOPlatformPluginFamily) X86PlatformPlugin::cgRegisterPLimitCallbackHandler - There are 0 entries in the linked list before target 0xffffff8036fa1800 callback 0xffffff7f832c5eae name AGPM, LINK at 0xffffff803557a490 contains 0xffffff80348fffa0
2020-06-28 20:03:48.173332+0100  localhost kernel[0]: (IOPlatformPluginFamily) X86PlatformPlugin::cgRegisterPLimitCallbackHandler - There are 0 entries in the linked list before target 0xffffff8036fa1800 callback 0xffffff7f832c5eae name AGPM, LINK at 0xffffff803557a490 contains 0xffffff80348fffa0
2020-06-28 20:03:48.173384+0100  localhost kernel[0]: (AppleGraphicsPowerManagement) [AGPM][INFO ][CONTROLLER  ][start                   ] GPU = IGPU Initialized, Control ID 16
2020-06-28 20:03:48.173428+0100  localhost kernel[0]: (AppleGraphicsPowerManagement) [AGPM][INFO ][CONTROLLER  ][start                   ] Exited AGPMController::start()
2020-06-28 20:03:48.174374+0100  localhost kernel[0]: Boot args: brcmfx-country=IE igfxfw=2 igfxonln=1 igfxagdc=0
```

In the log above? Im seeing this entries also on a similar machine and seem to have issues with agpm/c-stated below 3.

**Comment by zombillano** [comment] 2020-07-28 23:16
Another one with this problem. I've been doing some test and I found a very reproducible test. What I do is the following:

1. Open a youtube video at whatever resolution settings that you want in whichever browser you want (I use firefox 79). I do see CPU/GPU usage with Intel Power Gadget.
2. After the video starts change the video resolution to any other setting different to the one you already choose. This will trigger GPU usage to the max (in my case 1.15Ghz). If you pause the video and then continue the video the GPU usage will start to work as intended. Depending on the resolution choosen you will see some higher or lower GPU usage peaks every now and then.
3. If you decide to put your computer to sleep while it was using the GPU at max it will keep like that even after waking up and closing your browser. This can only be solved by a restart.

This is an issue because it increases both temperatures and PKG power. Although it can be easily prevented by pausing the video after it starts in order to recover normal usage of the GPU I think it is an inconvenient. 

My setup is a thinkpad T480 with a i7-8650u (Kaby Lake Refresh) and Intel UHD 620. If you need me to provide any logs I can do it.

**Comment by nickhx** [comment] 2020-08-08 18:20
Just upgraded to Big Sur and now struggling to reproduce this bug.  Anyone else?

**Comment by vit9696** [comment] 2020-08-09 06:04
In the modern WhateverGreen `igfxfw=2` is not benefitial, as host scheduler performance is fixed (by default). Closing this.

**Closed by vit9696** 2020-08-09 06:04 UTC
Labels: help wanted, project:green

**Comment by zombillano** [comment] 2020-08-09 06:55
Why did you close this if is still unsolved?. I wasn't using igfxfw at all and I had this issue

**Comment by Mateo1234454545** [comment] 2020-08-13 11:34
It has nothing to do with boot-args like igfxfw.
My guess is that something is broken with the latest commits of whatevergreen.

**Comment by zombillano** [comment] 2020-08-13 12:25
@vit9696 I found that WEG 14.0 doesn't have this issue. Could you reopen this one so we can give some more details and try to find a solution? My theory is that the changes made to adapt WEG to Big Sur broke something and it causes the high GPU load even on idle. This has nothing to do with boot-args.

**Comment by vit9696** [comment] 2020-08-13 13:21
WEG 1.4.1 got new IGPU performance control support, which you can disable `igfxnorspc=1`, this is documented.

**Comment by Mateo1234454545** [comment] 2020-08-13 15:12
> WEG 1.4.1 got new IGPU performance control support, which you can disable `igfxnorspc=1`, this is documented.

Doesn't solve the problem.

Booted with igfxnorspc=1 boot-arg on Big Sur. 
Watched a video on safari and then closed the lid. 
When waking from sleep gpu was stuck at max 1.1.ghz making laptop unussable. 
Had to rebbot.

**Comment by tiger511** [comment] 2020-08-13 16:16
> > WEG 1.4.1 got new IGPU performance control support, which you can disable `igfxnorspc=1`, this is documented.
> 
> Doesn't solve the problem.
> 
> Booted with igfxnorspc=1 boot-arg on Big Sur.
> Watched a video on safari and then closed the lid.
> When waking from sleep gpu was stuck at max 1.1.ghz making laptop unussable.
> Had to rebbot.

With `igfxnorspc=11` flag you have disabled the new performance control.You have to remove this arg.

**Comment by vit9696** [comment] 2020-08-13 16:44
Hrm. So, do you all confirm that WhateverGreen 1.4.0 works correctly? Please confirm that. Afterwards, please find the commit where things broke for you. You can get prebuilt binaries for every commit [here](https://dortania.github.io/builds/?product=WhateverGreen&viewall=true).

**Comment by tiger511** [comment] 2020-08-13 17:13
> Hrm. So, do you all confirm that WhateverGreen 1.4.0 works correctly? Please confirm that. Afterwards, please find the commit where things broke for you. You can get prebuilt binaries for every commit [here](https://dortania.github.io/builds/?product=WhateverGreen&viewall=true).

I dont think that's the case.This issue exists since version 1.3.8 till current version 1.4.1 . By the way in WEG 1.4.1 , what difference does it make if we use `igfxfw=2` ? Does it load Apple GuC without this flag?

**Comment by vit9696** [comment] 2020-08-13 17:26
Hrm, I am afraid there is some level of confusion here.

1. Apple GuC, enabled exclusively by `igfxfw=2` boot argument and disabled by default is bugged, and will eventually lead to IGPU locking at high frequency. This thing is not planned to be investigated or fixed.
2. CPU scheduling performance was fixed by WEG 1.4.0 allowing the IGPU frequency to reach high values without GuC. This is enabled by default and can be disabled by `igfxnorspc=1`. We believe it works correctly.
3. Without `igfxfw=2` and with `igfxnorspc=1` WEG 1.4.1 should also work correctly, but the IGPU will not be able to reach high frequencies.

If you believe that anything of the three does not hold, please provide more detail.

**Comment by cattyhouse** [comment] 2020-08-13 18:00
B360M-HDV, i5-8400, no problem here:

WEG: 1.4.1 
During Quicktime Screen recording: **GFX AVG 1.05 , GFX REQ: 1.03**
After Quitting Quicktime: **GFX AVG 0.00 , GFX REQ: 1.03**

**Comment by Mateo1234454545** [comment] 2020-08-13 18:15
I compiled a kext before commit :https://github.com/acidanthera/WhateverGreen/commit/6a1990e5413f5323d24df4ed2a4c6a9ed5b41836

and till now everything is fine. Needs more time though becasue the problem doesn't occureverytime after waking.

Please try it and see fr yourself.
https://github.com/acidanthera/WhateverGreen/commit/6a1990e5413f5323d24df4ed2a4c6a9ed5b41836

note: with this version I have noticed better power management , too. With 1.4.1 fans and temps were getting crazy when wathcing video.

**Comment by 07151129** [comment] 2020-08-13 18:22
> CPU scheduling performance was fixed by WEG 1.4.0 allowing the IGPU frequency to reach high values without GuC. This is enabled by default and can be disabled by igfxnorspc=1. We believe it works correctly.

It's `igfxnorpsc`. In my experiments the frequency went down just fine due to forcewake clears, so it was OK to request maximum frequency all the time, but I guess for some users some domain bits get never cleared. Unfortunately, I don't think I can reproduce this on my machine.

**Comment by zombillano** [comment] 2020-08-13 19:24
> Hrm. So, do you all confirm that WhateverGreen 1.4.0 works correctly? Please confirm that. 

It does, indeed. Will try to see which commit broke the functionallity.

> B360M-HDV, i5-8400, no problem here.

Yours uses UHD 630 but the desktop variant. AFAIK this may be affecting only laptops, at least I have only seen that problem on laptops.

> Needs more time though becasue the problem doesn't occureverytime after waking.

I can trigger it by changing resolution or speed while seeing videos on youtube, give it a try.

> note: with this version I have noticed better power management , too. With 1.4.1 fans and temps were getting crazy when wathcing video.

I think your issue with temps are caused by getting stuck at high frequencies which makes the whole system consume more energy and therefore getting hot, not because "bad" power management on 1.4.1.

I think the best that I can do is explain my setup:
* i7 8650u - UHD 620 (so, mobile variant)
* I don't have any boot args
* I use the recommended device-id and  AAPL,ig-platform-id that appears [here](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md)

What I mean with this is that the problems I have with 1.4.1 are not caused by any misconfiguration or boot-args.

> > CPU scheduling performance was fixed by WEG 1.4.0 allowing the IGPU frequency to reach high values without GuC. This is enabled by default and can be disabled by igfxnorspc=1. We believe it works correctly.
> 
>  This behaviour may be specific to 10.16.
I'm on 10.15.6, so it isn't 10.16 only.  I think that the modifications on the code to make WEG work with 10.16 is what caused this issues, will try to see which commit causes that.

**Comment by Mateo1234454545** [comment] 2020-08-13 20:23
> I can trigger it by changing resolution or speed while seeing videos on youtube, give it a try.

Tried. No problem with the kext I uploaded.


> Most likely your issue with temps is caused by getting stuck at high frequencies which makes the whole system consume more energy and therefore getting hot, not because "bad" power management on 1.4.1.

No , that's not the case. Even when gpu isn't stuck at max , when watching a video or opening an app , gpu behaves "abnormaly" and causes temps to go up. First time I heard the fans go to max speed when just watching video (with WEG 1.4.1 and Big Sur).


> What I mean with this is that the problems I have with 1.4.1 are not caused by any misconfiguration or boot-args.

 I agree on that.

**Comment by Mateo1234454545** [comment] 2020-08-13 20:24
> I'm on 10.15.6, so it isn't 10.16 only. I think that the modifications on the code to make WEG work with 10.16 is what caused this issues, will try to see which commit causes that.

For me the bad commit is https://github.com/acidanthera/WhateverGreen/commit/6a1990e5413f5323d24df4ed2a4c6a9ed5b41836

**Comment by vit9696** [comment] 2020-08-13 21:09
@Mateo1234454545 if this is the case, then `igfxnorpsc=1` should definitely resolve the problem. The only reason why it would not is if you fail to add the argument. Make sure that you add it via OpenCore config.plist and check that you did not forget to add `boot-args` to the `Delete` section.

**Comment by Mateo1234454545** [comment] 2020-08-13 21:45
I did , but didn't do anything.

To be more precise , I builded the kext including the commit : https://github.com/acidanthera/WhateverGreen/commit/fee20a9db39467131d550e4e664c29bd859eabf0 , because I wanted to run on Big Sur.
So any later commit could be the bad one.
It is difficult for me to find out which one.

**Comment by 07151129** [comment] 2020-08-13 22:54
This issue is about GuC PM, not host scheduler. Refrain from posting here unless it's about GuC.

**Comment by zombillano** [comment] 2020-08-14 19:14
Ok, last one. I can confirm that acidanthera/WhateverGreen@6a1990e is the bad commit. 

> then `igfxnorpsc=1` should definitely resolve the problem.

This kinda solves the problem. It perform worst in terms of thermal and power efficency. Now it doesn't get stuck at 1GHz but at 300 Mhz, although it gets back to 0 after a few minutes. Not an ideal solution but at least I think we are getting close.


> This issue is about GuC PM, not host scheduler. Refrain from posting here unless it's about GuC.

Right, I won't post anymore over here. Can I ask you a favor? Is it possible for you to open an issue dedicated to this problem? I'd do it by myself but I think you will make a better job at giving a proper title and description. Thanks in advance!

**Comment by sanoj-m** [comment] 2021-08-14 08:00
i got the 1.2GHz stuch fixed by force loading GuC using igfxfw=2 boot arg

**Comment by Ubsefor** [comment] 2021-09-15 07:24
As another workaround, you may try to use `HibernationFixup` kext to disable IGPU state restoration after sleep, at least it seemed to help me, as I cannot load Apple GuC on my machine.

**Comment by Mateo1234454545** [comment] 2021-09-15 07:38
> As another workaround, you may try to use `HibernationFixup` kext to disable IGPU state restoration after sleep, at least it seemed to help me, as I cannot load Apple GuC on my machine.

And if you use this kext what value should we enter at "Opencore's Hibernate mode" ?

**Comment by Ubsefor** [comment] 2021-09-15 07:45
> > As another workaround, you may try to use `HibernationFixup` kext to disable IGPU state restoration after sleep, at least it seemed to help me, as I cannot load Apple GuC on my machine.
> 
> And if you use this kext what value should we enter at "Opencore's Hibernate mode" ?

There’s `Auto` string, which, according to `Configuration.pdf` detects whether native RTC/NVRAM (or both) hibernation is possible.

**Comment by Wilber666** [comment] 2022-04-06 04:06
10th intel igpu has this problem too.（i5.10500h）
