### ISSUE TITLE
Hang with RX 6600 after verbose boot

### ISSUE THREAD

**Issue by dgilman** [acidanthera/bugtracker#2213] opened 2023-02-04 23:07 UTC
It looks like there's a race condition leading to a hang on Radeon RX 6600 cards (not 6600 XT) when OpenCore starts MacOS X in verbose mode (with `-v` in boot-args). I can confirm this on my machine, it has [several attestations on reddit](https://www.reddit.com/r/hackintosh/comments/uo2guh/comment/iaisngh/), and this appears to be the same issue that #2194 was seeing, although they were wrong in calling it a kernel panic.

### Description

The system console comes up as part of the verbose boot as normal. All the log messages appear to be normal, and the system appears to boot as far as the part where the window manager would start and MacOS X would switch graphics modes for the GUI. However, instead of making the graphics mode switch, the system hangs. The graphics card appears to power off and the attached monitor powers off from no signal, which is why it's getting described as "black screen", "blank screen", etc online. In rare cases the system with reboot after ~10 seconds instead of hanging forever.

### Commentary

It is not a kernel panic, I have never seen panic output in the console output. Debug builds of OpenCore and Lilu seem to turn it from a hang into a reboot, but not always. A release build of OpenCore with the `-v` flag set hangs roughly 19/20 times. Using debug builds of OpenCore, and especially using debug builds of Lilu with its verbose flags, seems to increase the chances it boots successfully. Debug builds seem to increase the chance of a reboot after ~10 sec instead of hanging forever.

### Logs
[OpenCore logs from the EFI partition](https://pastebin.com/nDWxwcuh). Unfortunately they do not seem very helpful.

I tried to dump the Apple system console logs with `log show --debug --last 1h --predicate 'process == "kernel"'` but they do not appear to be persisted if the system crashes. Is there a technique to getting the console logs saved in this situation?

### Configuration

OpenCore 0.8.8, debug builds. ASRock Radeon RX 6600. This was happening on MacOS 12 and 13. [config.plist](https://pastebin.com/G97LNGVi)

**Comment by Core-i99** [comment] 2023-02-05 12:56
I believe this is a duplicate of https://github.com/acidanthera/bugtracker/issues/2126#issue-1384491529

**Comment by dgilman** [comment] 2023-02-05 13:33
I do have a smarphone camera recorded boot log. It doesn't correspond to the plist I posted above because it was before I had narrowed the issue down to verbose mode, but I believe it is typical of the hang. [Here is the video](https://youtu.be/Sg7bMDGaDBk), I don't see anything like the newUserClientFailed() in the other ticket. Although I am not totally sure what my takeaway is from that ticket.

**Closed** 2023-02-11 16:36 UTC
Labels: help wanted, project:green
