### ISSUE TITLE
Can’t use latest maciASL version 1.5.9 on MacBook Air M1 because of missing admin privileges

### ISSUE THREAD

**Issue by kasti0** [acidanthera/bugtracker#1478] opened 2021-02-06 23:30 UTC
Device: MacBook Air M1
MaciAsl Version: 1.5.9
Issue: can’t be opened/ run because of missing admin privileges 
What I tried so far: open the information and set the privileges for every possible user to „read and write“ (suggested by Apple support for that issue).
The issue persists and I’m the only admin and user of that device. Version 1.5.8 works fine.

**Comment by khronokernel** [comment] 2021-02-06 23:59
Duplicate of https://github.com/acidanthera/bugtracker/issues/1395

**Closed by khronokernel** 2021-02-06 23:59 UTC

**Comment by kasti0** [comment] 2021-02-07 00:16
sorry I couldn't find any issues related to M1 and/ or admin privileges. the solution with "codesign -fs - --deep" worked!
