### ISSUE TITLE
QuietTimeAfterTyping works every 10-15th boot

### ISSUE THREAD

**Issue by witampanstwa** [acidanthera/bugtracker#1415] opened 2021-01-06 19:49 UTC
As the title says, VoodooPS2Controller's `QuietTimeAfterTyping` feature is loaded quite rarely. This has really intensified in the last couple of months (release 2.1.6 for example, fails only about 50% of the time) and that's why I've started to notice it only just recently.

I've narrowed down the culprit of the issue to be acidanthera/VoodooPS2@8841fd8aa28555a14b02ae52baf1980437eda18f, the very first commit under the 2.1.2 tag (commits coming after this one don't fix the issue).

I'm running Haswell; both Catalina (15.6) and Big Sur (11.1) yield the same behaviour for me.

**Comment by lvs1974** [comment] 2021-01-07 13:28
@witampanstwa: I added some additional debug statements.
Could you install these debug kexts, reproduce this issue and attach system log, please?
[VoodooPS2Controller-2.2.1-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/5781813/VoodooPS2Controller-2.2.1-DEBUG.zip)

**Comment by witampanstwa** [comment] 2021-01-07 16:04
Sure, here you go

Console log stream, filtered through "any PS2":
[console.txt](https://github.com/acidanthera/bugtracker/files/5782579/console.txt)
16:33:04–started triggering continuous 1-finger touchpad contact event
16:33:05-triggered a keypress event
16:33:06-released touchpad event triggering

`dmesg | egrep -i "Voodoo|PS2|I2C|Input"`:
[dmesg.txt](https://github.com/acidanthera/bugtracker/files/5782597/dmesg.txt)

**Comment by lvs1974** [comment] 2021-01-07 17:17
@witampanstwa: sorry for mentioning it now, but I think you filtered my additional messages.
Please provide a full log.

**Comment by witampanstwa** [comment] 2021-01-07 17:34
@lvs1974 Oh, that might've in fact been the case. Although, I'm afraid I don't see any messages like those you mentioned anyway actually

[console2.txt](https://github.com/acidanthera/bugtracker/files/5783082/console2.txt)
18:29:41–started triggering continuous 1-finger touchpad contact event
18:29:42–triggered a keypress event
18:29:43–released touchpad event triggering
± .5 s

**Comment by lvs1974** [comment] 2021-01-07 17:46
@witampanstwa: it is quite strange.
I have checked all sources for VoodooPS2 and VoodooI2C (with all modules), but I did not manage to find lines (or any part of line) from you latest post!
Can you install DebugEnhancer.kext (Lilu plugin) and take a new log with dmesg, please (without filtering)?

**Comment by witampanstwa** [comment] 2021-01-07 17:54
@lvs1974 
[dmesg2.txt](https://github.com/acidanthera/bugtracker/files/5783171/dmesg2.txt)
18:52:00–started triggering continuous 1-finger touchpad contact event
18:52:01–triggered a keypress event
18:52:02–released touchpad event triggering
± .5 s

**Comment by lvs1974** [comment] 2021-01-07 18:14
@witampanstwa: it is much better, at least I can analyse such logs.
Could you run IORegistryExplorer, find there node VoodooPS2Elan and property QuietTimeAfterTyping? 
Current value is 500000000 (nanosecond) = 500 msec = 0.5 sec, is it correct?
It means you need to do something with touchpad in less than 0.5 seconds after key pressing to see any something in log related to touch event rejection...

**Comment by witampanstwa** [comment] 2021-01-07 18:18
@lvs1974 Well, bad news, nothing is found 😟
![Screenshot 2021-01-07 at 19 16 51](https://user-images.githubusercontent.com/33933917/103929019-e94cf100-511c-11eb-9e15-d05467eec1ba.png)

**Comment by lvs1974** [comment] 2021-01-07 18:21
@witampanstwa: I would not expect IORegistryExplorer can find anything, I think search is broken there.
Try to find it manually, or save current IOReg to file and put here.
Please replace voodoo kexts before, I fixed & added some log statements.
[VoodooPS2Controller-2.2.1-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/5783291/VoodooPS2Controller-2.2.1-DEBUG.zip)

**Comment by witampanstwa** [comment] 2021-01-07 18:24
> It means you need to do something with touchpad in less than 0.5 seconds after key pressing to see any something in log related to touch event rejection...
That's what I was in fact doing--I kept interacting with the touchpad continuously throughout the 3 seconds I'd been describing earlier

**Comment by lvs1974** [comment] 2021-01-07 18:29
@witampanstwa: anyway, would be nice to have a look at IOReg.

**Comment by witampanstwa** [comment] 2021-01-07 18:33
@lvs1974 

IOReg dump
[Robert’s MacBook Pro](https://we.tl/t-suQyvPNe9S)

`dmesg`
[dmesg3.txt](https://github.com/acidanthera/bugtracker/files/5783329/dmesg3.txt)
19:28:15–started triggering continuous 1-finger touchpad contact event
19:28:16–triggered a keypress event
19:28:17–released touchpad event triggering
± .5 s

**Comment by witampanstwa** [comment] 2021-01-07 18:48
> Ok found it; it's set to 100 ms

Actually, when I said this, I looked at the `VoodooI2CELANTouchpadDriver` node, not the `ApplePS2Elan`. `VoodooI2CELANTouchpadDriver` is in fact the one which value is applied in practice (that is, when it works every earlier mentioned 10-15th boots)

**Comment by lvs1974** [comment] 2021-01-07 18:56
Please have a look at these pictures:
![Screen Shot 2021-01-07 at 19 45 32](https://user-images.githubusercontent.com/27740976/103931794-261ae700-5121-11eb-8785-7c73a5c2e19e.png)
![Screen Shot 2021-01-07 at 19 46 16](https://user-images.githubusercontent.com/27740976/103931800-27e4aa80-5121-11eb-84a6-231370fc3609.png)

You have 2 touchpads and 2 VoodooInput instances.
VoodooI2CELANTouchpadDriver has QuietTimeAfterTyping = 0x64  = 100000000 nanoseconds = 100 mseconds (0.1 sec),
this value is quite small I think!
I am not an expert here, but for me it looks very strange (I mean using two different touchpads). 

You can try to find QuietTimeAfterTyping in Info.plist for all VoodooI2C* kexts and set it to 1500.
After reboot and try again.

**Comment by lvs1974** [comment] 2021-01-07 18:58
And I would try to remove VoodooPS2Mouse.kext and VoodooPS2Trackpad.kext from VoodooPS2Controller.kext!!!

**Comment by witampanstwa** [comment] 2021-01-07 18:59
Oh, didn't know I could modify that; wouldn't this brake the signature?

**Comment by lvs1974** [comment] 2021-01-07 19:00
@witampanstwa: if you load these kexts using bootloader, you cannot break anything!

**Comment by lvs1974** [comment] 2021-01-07 19:03
Be aware that QuietTimeAfterTyping can be found more than once in one Info.plist, I would set them all to 1500.

**Comment by witampanstwa** [comment] 2021-01-07 19:08
@lvs1974 
![Screenshot 2021-01-07 at 20 06 22](https://user-images.githubusercontent.com/33933917/103933587-eb667e00-5123-11eb-9ade-82722504efd4.png)
![Screenshot 2021-01-07 at 20 05 35](https://user-images.githubusercontent.com/33933917/103933595-edc8d800-5123-11eb-8c7f-98a6c54bb138.png)
Ok, now I have only one instance of the `QuietTimeAfterTyping`, one instance of a touchpad driver (have already removed PS2 touchpad drivers as you'd suggested), yet the issue remains.

**Comment by witampanstwa** [comment] 2021-01-07 19:17
@lvs1974 Yeah, same behaviour still

![Screenshot 2021-01-07 at 20 16 18](https://user-images.githubusercontent.com/33933917/103934422-359c2f00-5125-11eb-903d-4dd9490cfa61.png)
![test](https://user-images.githubusercontent.com/33933917/103934344-1b625100-5125-11eb-9ab1-c23717e13b56.mov)

**Comment by lvs1974** [comment] 2021-01-07 19:24
I tried on my laptop - and it also does not work (in my case I have another class - VoodooI2CPrecisionTouchpadHIDEventDriver, which is inherited from VoodooI2CMultitouchHIDEventDriver, and VoodooI2CMultitouchHIDEventDriver implements the same logic:
```
void VoodooI2CMultitouchHIDEventDriver::handleInterruptReport(AbsoluteTime timestamp, IOMemoryDescriptor* report, IOHIDReportType report_type, UInt32 report_id) {
    // Touchpad is disabled through ApplePS2Keyboard request
    if (ignore_all)
        return;
    
    uint64_t now_abs;
    clock_get_uptime(&now_abs);
    uint64_t now_ns;
    absolutetime_to_nanoseconds(now_abs, &now_ns);
    
    if (report_type == kIOHIDReportTypeInput && readyForReports())
        clock_get_uptime(&last_multi_touch_event);
    
    // Ignore touchpad interaction(s) shortly after typing
    if (now_ns - key_time < max_after_typing)
        return;
```

Probably I do not understand it all, the way how it should work...

**Comment by lvs1974** [comment] 2021-01-07 19:25
Probably the best way to clear this up - ask VoodooI2C authors....

**Comment by witampanstwa** [comment] 2021-01-07 19:26
I've been there, and Kishor said the issue could indeed be the PS2 itself

**Comment by lvs1974** [comment] 2021-01-07 19:28
But now PS2 is not used here, this logic implemented in VoodooI2CELANTouchpadDriver!
From PS2 keyboard VoodooI2CELANTouchpadDriver only receives a message with the last key press time!

**Comment by witampanstwa** [comment] 2021-01-07 19:35
Yeah, so the guilty here could be VoodooPS2 just as VoodooI2C; however–I did some testing (not reliant on the VoodooInput as I'd installed it as a standalone module so that it would be always at the latest build), and it was the VoodooPS2 2.1.2 which proved as the guilty, at least in context with it's predecessor (2.1.1), which had not failed my tests once

**Comment by vit9696** [comment] 2021-01-08 07:36
From the conversation above to me this looks like there is a race condition in VoodooI2C, which results in the issue you observe. The change in VoodooPS2 only altered the order of the events, and coincidentally made the bug in VoodooI2C more obvious. So far there is no evidence of any real bug in VoodooPS2 as the actions of it are very simple, and the logic is pretty much all in the I2C side. For now I close this until further information is discovered. Feel free to post more details if found.

CC @zhen-zen

**Closed by vit9696** 2021-01-08 07:36 UTC
Labels: project:ps2

**Comment by lvs1974** [comment] 2021-01-08 11:18
@witampanstwa: could you try an attached version, please?
I think I have managed to fix it (at least now it works with my touchpad - class VoodooI2CPrecisionTouchpadHIDEventDriver).

**Comment by witampanstwa** [comment] 2021-01-08 11:37
@lvs1974 Yeah, seems to be working.
Is this something that can go on master, or just a dirty fix though? Because I've opened an issue on I2C already

**Comment by lvs1974** [comment] 2021-01-08 11:42
@witampanstwa: is is already in master:
https://github.com/acidanthera/VoodooPS2/commit/dc3571249f59d3aa0bfd867596bb7121373c8ee9

**Comment by zhen-zen** [comment] 2021-01-11 07:30
The fix is a bit confusing since just to remove the notification source check won't help with a possible race condition issue. Also the `notificationHandler` routine should work as intended and is replicated in a few drivers. 

For me, it sounds like https://github.com/VoodooI2C/VoodooI2CHID/blob/master/VoodooI2CHID/Info.plist#L103 (processed in init()) is too early and won't be captured. Maybe publish the property in start() could solve the problem.

**Comment by lvs1974** [comment] 2021-01-11 07:53
@zhen-zen: fix is self-explainable I think. This issue is not related to the moment when RM,deliverNotifications has been published in IOReg. It is only related to notificationHandler and using received INotifier pointer: we cannot reliably compare stored pointer (_publishNotify or _terminateNotify) with received pointer, since we receive a completely different pointer in notifications. I added logging into notificationHandler and notificationHandlerGated and discovered this issue.

**Comment by zhen-zen** [comment] 2021-01-12 02:01
For me it doesn't make sense if returned pointer won't match received ones. Just digged into `IOService.cpp` and the pointer seems to be the same.

The handler is invoked in [`IOService::invokeNotifier( _IOServiceNotifier * notify )`](https://github.com/apple/darwin-xnu/blob/d4061fb0260b3ed486147341b72468f836ed6c8f/iokit/Kernel/IOService.cpp#L3613)
```
ret = (*notify->handler)(notify->target, notify->ref, this, notify);
```

Which is called from [`IOService::addMatchingNotification()`](https://github.com/apple/darwin-xnu/blob/d4061fb0260b3ed486147341b72468f836ed6c8f/iokit/Kernel/IOService.cpp#L5769)
```
next->invokeNotifier( notify );
```

The `_IOServiceNotifier *notify` (derived from `IONotifier`) here is assembled [earlier](https://github.com/apple/darwin-xnu/blob/d4061fb0260b3ed486147341b72468f836ed6c8f/iokit/Kernel/IOService.cpp#L5759)

```
	ret = notify = (_IOServiceNotifier *) installNotification( type, matching,
	    handler, target, ref, priority, &existing );
```
So what passed to the handler should be the same as the return of `addMatchingNotification`.

The `IOService::installNotification()` invokes `IOService::doInstallNotification()` and further `IOService::setNotification()`. 

The latter one will [initialize](https://github.com/apple/darwin-xnu/blob/d4061fb0260b3ed486147341b72468f836ed6c8f/iokit/Kernel/IOService.cpp#L5590) the `_IOServiceNotifier ` returned later and also [add it into `gNotifications`](https://github.com/apple/darwin-xnu/blob/d4061fb0260b3ed486147341b72468f836ed6c8f/iokit/Kernel/IOService.cpp#L5614).

Post-install calls to `invokeNotifier` (`invokeNotifiers`) will get current installed notifiers with `IOService::copyNotifiers`, which returns active notifier from `gNotifications`.
