### ISSUE TITLE
Explore 10.15 hibernation support options

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [acidanthera/bugtracker#484] opened 2019-09-08 15:51 UTC
On 10.15 the mode 25 of hibernation behaves as simply a sleep.

**Comment by lvs1974** [comment] 2019-09-09 16:21
I will have a look at this issue, but it would be much easier to get kernel open sources before.

**Comment by lvs1974** [comment] 2019-09-14 16:01
@vit9696, @Andrey1970AppleLife:
I have managed to get a log from 10.15 beta 8:

> PMRD: sleep params v2, type 5, flags 0x0, wake 0x250f, timer 0, poweroff 0
> IOCPUSleepKernel
> PMRD: trace point 0x17
> IOPlatformSleepAction -> AppleSMC
> PMRD: trace point 0x18
> PMRD: trace point 0x19
> ACPI SLEEP
> Facs->FirmwareWakingVector: 0x2000
> Facs->Length: 0x40
> Facs->Version: 0x2
> Facs->XFirmwareWakingVector: 0x0
> Facs->OspmFlags: 0x0
> PMRD: trace point 0x1a
> hibernate_page_list_setall(preflight 0) start
> hibernate_teardown started
> hibernate_teardown: wired_pages 292326, free_pages 1724271, active_pages 40002, inactive_pages 24731, speculative_pages 0, cleaned_pages 0, compressor_pages 24
> hibernate_teardown_pmap_structs done: last_valid_compact_indx 228884
> hibernate_teardown: mark_as_unneeded_pages 2048, 21702, 17646
> hibernate_teardown completed - discarded 41396
> hibernate_page_list_setall time: 382 ms
> pages 675488, wire 220574, act 40002, inact 0, cleaned 0 spec 0, zf 24731, throt 0, compr 24, xpmapped 40000
>   did discard act 66967 inact 115304 purgeable 41330 spec 166556 cleaned 0
> WARNING: hibernate_page_list_setall skipped 18209 xpmapped pages
> hibernate_page_list_setall found pageCount 285331
> IOHibernatePollerOpen, ml_get_interrupts_enabled 0
> IOHibernatePollerOpen(0)
> PMStats: Hibernate write took 0 ms
> all time: 0 ms, comp bytes: 0 time: 0 ms 0 Mb/s, crypt bytes: 0 time: 0 ms 0 Mb/s, 
> image 0 (0%), uncompressed 0 (0), compressed 0 (0%), sum1 de5df5da, sum2 0
> svPageCount 0, zvPageCount 0, wiredPagesEncrypted 0, wiredPagesClear 0, dirtyPagesEncrypted 0
> **hibernate_write_image done(e00002c7)**
> sleep
> hibernate_rebuild started
> hibernate_rebuild_pmap_structs done: last_valid_compact_indx 228884
> hibernate_rebuild completed - took 60 msecs
> ACPI S3 WAKE

Error code e00002c7 = kIOReturnUnsupported?
So, sleepimage cannot be written properly.

BTW: nvram.plist also cannot be written in 10.15, Lilu file API returns error code 30.

**Comment by vit9696** [comment] 2019-09-17 15:34
This looks like XNU bug to me, it might be caused by read only root file system. In my opinion, wait for the release of the kernel source code and take actions then.

**Comment by usr-sse2** [comment] 2019-11-07 08:30
> it might be caused by read only root file system
Is it resolved by mounting it read-write?

**Comment by lvs1974** [comment] 2019-11-07 08:38
> > it might be caused by read only root file system
> 
> Is it worked around by mounting it read-write?

Actually only root file system is mounted in read-only mode, but folder /private/var/vm - is a hardlink, and it can be modified (I checked it by using sudo touch xxx).
I also created a new HFS+ partition and changed a path to the sleepimage:
by command 'sudo pmset -a hibernatefile xxx', but hibernation did not work anyway.

**Comment by usr-sse2** [comment] 2019-11-07 08:41
@lvs1974 I meant nvram.plist, not sleepimage.

**Comment by lvs1974** [comment] 2019-11-07 08:45
> @lvs1974 I meant nvram.plist, not sleepimage.

Yes, that is the reason. I can try to write nvram.plist to the root of /Volume/Data, but I have some doubts regarding Clover, can it enumerate volumes inside of container, to find this nvram.plist?

**Comment by lvs1974** [comment] 2019-11-26 07:52
I have managed to get a new log with new details:
`ACPI SLEEP
Facs->FirmwareWakingVector: 0x2000
Facs->Length: 0x40
Facs->Version: 0x2
Facs->XFirmwareWakingVector: 0x0
Facs->OspmFlags: 0x0
ACPI switch to MemPool
acpi_sleep_kernel hib=1, cpu=0
HBFX @ hibernate_write_image is called
PMRD: trace point 0x1a
hibernate_page_list_setall(preflight 0) start
hibernate_teardown started
hibernate_teardown: wired_pages 268519, free_pages 1735607, active_pages 40006, inactive_pages 37147, speculative_pages 0, cleaned_pages 0, compressor_pages 12
hibernate_teardown_pmap_structs done: last_valid_compact_indx 201575
hibernate_teardown: mark_as_unneeded_pages 2048, 21809, 17860
hibernate_teardown completed - discarded 41717
hibernate_page_list_setall time: 429 ms
pages 757993, wire 196458, act 40006, inact 0, cleaned 0 spec 0, zf 37147, throt 0, compr 12, xpmapped 40000
  did discard act 86089 inact 101689 purgeable 64334 spec 232258 cleaned 0
WARNING: hibernate_page_list_setall skipped 34758 xpmapped pages
hibernate_page_list_setall found pageCount 273623
IOHibernatePollerOpen, ml_get_interrupts_enabled 0
IOHibernatePollerOpen(0)
HBFX @ IOPolledFileWrite before write, position = 4096, blockSize = 4096, bufferOffset = 0, bufferLimit = 131072, bufferHalf = 0, extentRemaining = 14909440
HBFX @ IOPolledFileWrite is ok, size: 2896, ioStatus: 0
HBFX @ IOPolledFileWrite poller service name: Samsung SSD 850 PRO 256GB Media
HBFX @ IOPolledFileWrite after write, position = 6992, blockSize = 4096, bufferOffset = 2896, bufferLimit = 131072, bufferHalf = 0, extentRemaining = 14909440
HBFX @ IOPolledFileWrite before write, position = 6992, blockSize = 4096, bufferOffset = 2896, bufferLimit = 131072, bufferHalf = 0, extentRemaining = 14909440
IOPolledInterface::startIO[0] 0xe00002c7
IOPolledFileWrite(0x<ptr>, 0x<ptr>, 598016, 0x<ptr>) : IOStartPolledIO(0x<ptr>, kIOPolledWrite, 0, 0x131f46b000, 131072) returned 0xe00002c7
HBFX @ IOPolledFileWrite is failed, result is: e00002c7, size: 598016, ioStatus: -1
HBFX @ IOPolledFileWrite poller service name: Samsung SSD 850 PRO 256GB Media
HBFX @ IOPolledFileWrite after write, position = 135168, blockSize = 4096, bufferOffset = 131072, bufferLimit = 131072, bufferHalf = 0, extentRemaining = 14909440
PMStats: Hibernate write took 0 ms
all time: 0 ms, comp bytes: 0 time: 0 ms 0 Mb/s, crypt bytes: 0 time: 0 ms 0 Mb/s, 
image 0 (0%), uncompressed 0 (0), compressed 0 (0%), sum1 ed338d0b, sum2 0
svPageCount 0, zvPageCount 0, wiredPagesEncrypted 0, wiredPagesClear 0, dirtyPagesEncrypted 0
hibernate_write_image done(e00002c7)
HBFX @ hibernate_write_image has finished, result is: 0, write counter: 2
sleep
sleep
ucode: Re-applying update after wake (CPU #0)
hibernate_rebuild started
hibernate_rebuild started
hibernate_rebuild_pmap_structs done: last_valid_compact_indx 201575
hibernate_rebuild_pmap_structs done: last_valid_compact_indx 201575
hibernate_rebuild completed - took 61 msecs
hibernate_rebuild completed - took 61 msecs
fpu_state: AVX, state_size: 832
ret from acpi_sleep_cpu hib=0
ACPI S3 WAKE
Facs->FirmwareWakingVector: 0x0
Facs->Length: 0x40
Facs->Version: 0x2
Facs->XFirmwareWakingVector: 0x0
Facs->OspmFlags: 0x0
AppleACPIPlatformPower Wake reason: PWRB EH01 EH02 (User)
AppleACPIPlatformPower Wake reason: PWRB EH01 EH02 (User)
PMRD: trace point 0x22
IOPlatformWakeAction -> AppleRTC
IOPlatformWakeAction -> AppleKeyStore
IOPlatformWakeAction -> AppleSMC
PMRD: trace point 0x23
ucode: Re-applying update after wake (CPU #1)
TSC sync for cpu 1: 0x0000000048c32fe7 delta 0xa1 (161)
Started cpu 1 (lapic id 00000001)
ucode: Re-applying update after wake (CPU #2)
TSC sync for cpu 2: 0x0000000049436a57 delta 0xa1 (161)
Started cpu 2 (lapic id 00000002)
ucode: Re-applying update after wake (CPU #3)
TSC sync for cpu 3: 0x0000000049c74310 delta 0xcf (207)
Started cpu 3 (lapic id 00000003)
AppleKeyStoreUserClient: Assertion timer fired
gIOLastWakeAbsTime: 114050145288
HibernationFixup:    HBFX @ (DBG) IOHibernateSystemWake is called, result is: 0
HibernationFixup:    HBFX @ (DBG) IOHibernateSystemWake: wake type is: User
HibernationFixup:    HBFX @ (DBG) IOHibernateSystemWake: wake reason is: PWRB EH01 EH02
RTC: getGMTTimeOfDay 1574751168
time_slept (7 s 972334 u)
PMRD: System Wake`

The first portion of data (2896 bytes) was written without any issues,
and for the next one (598016 bytes) method IOPolledInterface::startIO returned error.
So, this issue is not in the kernel, but in some kext implementing interface IOPolledInterface.

**Comment by lvs1974** [comment] 2019-11-26 11:48
I've seen a few reports regarding this issue on native Macs:
1. https://discussions.apple.com/thread/250744881
2. https://www.macuser.de/threads/hibernatemode-25-scheint-unter-catalina-nicht-mehr-zu-funktionieren.833973/
3. https://blog.macsales.com/53855-how-to-fix-macos-catalina-installation-issues/

**Comment by vit9696** [comment] 2019-11-26 22:53
Yes, thanks for the fix. I merged the patch in OpenCore master in https://github.com/acidanthera/OpenCorePkg/commit/40c42c23f09958703e9ef3e9aacfc6468829bc35 and https://github.com/acidanthera/OcSupportPkg/commit/d33c448213a1048d7048b3ab38297cf9d8ed9dd7. Now this extends the original quirk with TRIM support to other features.

For NVMe more research will be needed I guess. I do not see anything like that right away as well.

**Comment by vit9696** [comment] 2019-11-30 14:14
Tested NVMe on a few machines, works fine. Closing as fixed.

**Closed by vit9696** 2019-11-30 14:14 UTC
Labels: enhancement, priority:high, project:hbfx, project:oc

**Comment by zawn** [comment] 2020-09-02 07:06
@lvs1974 Hello, I also encountered this problem, how can I get the relevant logs?
