### ISSUE TITLE
Boot Chime delay before Boot Picker

### ISSUE THREAD

**Issue by isorropisths** [acidanthera/bugtracker#1259] opened 2020-11-04 15:02 UTC
Hi there

Enabling boot chime adds a 15 seconds delay before the boot picker / Apple Logo appears. The boot chime does sound though.
Disabling boot chime, the delay goes away.

Enabling OpenCore logging, I can see on the screen that it waits for 15 seconds on
"04:988 00:000 OC: Wave Resources\Audio\OCEFIAudio_VoiceOver_Boot.wav was requested"
and then as soon as I can hear the boot chime, it continues off.

I've included my EFI, and OpenCore log file.
[EFI.zip](https://github.com/acidanthera/bugtracker/files/5488497/EFI.zip)
[opencore-2020-11-04-144523.txt](https://github.com/acidanthera/bugtracker/files/5488500/opencore-2020-11-04-144523.txt)

**Comment by vit9696** [comment] 2020-11-04 15:05
A duplicate of https://github.com/acidanthera/bugtracker/issues/740 really.

**Closed by vit9696** 2020-11-04 15:05 UTC
Labels: duplicate, project:oc
