### ISSUE TITLE
Kernel panic with Lilu and SMCDellSensors on Catalina (10.15.7)

### ISSUE THREAD

**Issue by zearp** [acidanthera/bugtracker#1315] opened 2020-11-20 17:44 UTC
When using the latest OpenCore (37c1030), Lilu (63f37bf) and VirtualSMC (65593a3) I get a panic after some time idle which can be triggered earlier by streaming videos in Safari that use the native Safari player. The OS fully freezes including keyboard/mouse inputs and writes stuff to the disk (judging by the hdd led). It required a manual reboot.

Reverting to previous commits of VirtualSMC didn't help but reverting to Lilu commit 575bd85 did fix it. Reverting VirtualSMC may have been unnecessary but I had to try it in order to pin down which ~~commit~~ kext caused the issue.

I searched for previous issues and found something sort of similar but my config already has DisableLinkeditJettison enabled. Gathered as much information as I could, please let me know if more logs or other actions are required.

[opencore-2020-11-20-171506.txt](https://github.com/acidanthera/bugtracker/files/5575205/opencore-2020-11-20-171506.txt)
[Lilu_1.5.0_19.6.txt](https://github.com/acidanthera/bugtracker/files/5575209/Lilu_1.5.0_19.6.txt)
[Kernel_2020-11-20-181554-panic.txt](https://github.com/acidanthera/bugtracker/files/5575214/Kernel_2020-11-20-181554-panic.txt)

**Comment by vit9696** [comment] 2020-11-20 22:07
@lvs1974 you got a recursion there.

**Comment by lvs1974** [comment] 2020-11-20 23:06
@zearp: please try attached version:
[SMCDellSensors.kext.zip](https://github.com/acidanthera/bugtracker/files/5576508/SMCDellSensors.kext.zip)

**Comment by zearp** [comment] 2020-11-21 00:00
@lvs1974 That solved it -- can't reproduce the panic anymore, thank you!

**Comment by vit9696** [comment] 2020-11-21 06:16
Ugh, but how can onKextLoad be called multiple times per one kext? This fixes looks wrong to me and sounds like a bug on Lilu side, not on SMCDellSensors side. Lilu should only invoke the handler when a kext is actually reloaded and it is marked as reloadable in the request.

**Comment by vit9696** [comment] 2020-11-21 06:19
Cannot it be caused by these lines: https://github.com/acidanthera/Lilu/blob/1266231/Lilu/Sources/kern_patcher.cpp#L724-L726

**Comment by vit9696** [comment] 2020-11-21 06:22
@zearp does the issue reproduce for you with Lilu 575bd85c and SMCDellSensors 65593a30? You can download them at https://dortania.github.io/builds/

**Comment by vit9696** [comment] 2020-11-21 06:56
You do mark the kext as reloadable (why?), so I kind of get it that Lilu can post a request a second time in this case. And from the request it is clear that kext reloading should not happen itself (so it is likely the lines I mentioned). However, if we think conceptually of the issue reloading should not happen for any kext at all on Big Sur, as kext loading on the fly is simply not supported there.

**Comment by lvs1974** [comment] 2020-11-21 09:36
@zearp: could you check this Lilu version with previous version of SMCDellSensors, please? 
[Lilu-1.5.0-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/5577339/Lilu-1.5.0-DEBUG.zip)

**Comment by zearp** [comment] 2020-11-21 12:30
@vit9696 With those two versions I can not reproduce the panic.

@lvs1974 With the attached Lilu and Dell sensor kext 65593a30 it will panic. Let me know if you need me to try with other versions.

[Lilu_1.5.0_19.6.txt](https://github.com/acidanthera/bugtracker/files/5577599/Lilu_1.5.0_19.6.txt)
[Kernel_2020-11-21-132305_panic.txt](https://github.com/acidanthera/bugtracker/files/5577601/Kernel_2020-11-21-132305_panic.txt)

**Comment by lvs1974** [comment] 2020-11-21 13:39
@zearp: could you try attached SMCDellSensors and previously attached Lilu, please?
[SMCDellSensors.kext.zip](https://github.com/acidanthera/bugtracker/files/5577706/SMCDellSensors.kext.zip)
Could you also turn on setting ApplePanic in OpenCore and get panic reports from EFI partition?

**Comment by zearp** [comment] 2020-11-21 14:01
@lvs1974 It doesn't panic with the Lilu + Dell sensor you've posted. I'll attach the OpenCore boot log and Lilu log just in case it's helpful.

[Lilu_1.5.0_19.6.txt](https://github.com/acidanthera/bugtracker/files/5577732/Lilu_1.5.0_19.6.txt)
[opencore-2020-11-21-134941.txt](https://github.com/acidanthera/bugtracker/files/5577733/opencore-2020-11-21-134941.txt)

**Comment by lvs1974** [comment] 2020-11-21 15:23
Fix is in VirtualSMC master: d94ed4560ecacdffc1c279bc6c839c11d3901f48.

**Closed** 2020-11-22 07:55 UTC
Labels: project:vsmc
