### ISSUE TITLE
"StartImage failed" possibly due to random high slide value

### ISSUE THREAD

**Issue by zhen-zen** [acidanthera/bugtracker#979] opened 2020-06-14 23:00 UTC
The memory map of my laptop have few available pages. After enabling `DevirtualiseMmio`, I managed to get 0x10000 more pages, which corresponding to 128 slides. Then I encountered fewer boot failure than before.
I compared the logs and found failed ones usually have slide value closer to the maximum available slide. The logs collected after enabling `AppleDebug` have offsets of up to 22 slides. However, high slide values may also allow a smooth boot.
So I suspect higher slide value may result in things like memory allocation failure when loading the kernel. Or maybe the memory map of that boot contains more valuable information but is not recorded.
Then I tried to reduce the available range by 32 in [CustomSlide.c](https://github.com/zhen-zen/OpenCorePkg/commit/341577750d823b23b5c0e16034b27504d6656a20), no failure occurred for recent 6 or 7 reboots.

**Comment by zhen-zen** [comment] 2020-06-14 23:02
Log of boot failures:
`grep slide $(grep -l "StartImage failed" *.txt) --no-filename`
`
05:038 00:014 OCABC: No slide values are usable! Falling back to 0 with 0x1326F000 bytes!
06:596 00:003 OCABC: Only 83/256 slide values are usable!
06:599 00:003 OCABC: Valid slides - 0-82
04:545 00:003 OCABC: Only 83/256 slide values are usable!
04:549 00:003 OCABC: Valid slides - 0-82
06:388 00:004 OCABC: Only 28/256 slide values are usable!
06:392 00:004 OCABC: Valid slides - 0-27
22:125 00:004 OCABC: Only 156/256 slide values are usable!
22:129 00:004 OCABC: Valid slides - 0-155
05:342 00:005 OCABC: Only 68/256 slide values are usable!
05:348 00:005 OCABC: Valid slides - 0-67
02:595 00:001 OCABC: Only 68/256 slide values are usable!
02:596 00:001 OCABC: Valid slides - 0-67
03:374 00:002 OCABC: Only 68/256 slide values are usable!
03:377 00:002 OCABC: Valid slides - 0-67
06:348 00:004 OCABC: Only 156/256 slide values are usable!
06:353 00:004 OCABC: Valid slides - 0-155
06:395 00:004 AAPL: [EB|#MBA:NV] (hbfx-patch-pci=XHC,IMEI,IGPU,RP01 -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=134)
06:404 00:004 AAPL: [EB|#MBA:OUT] (hbfx-patch-pci=XHC,IMEI,IGPU,RP01 -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=134)
02:076 00:001 OCABC: Only 156/256 slide values are usable!
02:077 00:001 OCABC: Valid slides - 0-155
02:090 00:001 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=150)
02:094 00:001 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=150)
04:872 00:002 OCABC: Only 156/256 slide values are usable!
04:875 00:002 OCABC: Valid slides - 0-155
04:896 00:002 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=134)
04:901 00:002 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=134)
04:268 00:001 OCABC: Only 156/256 slide values are usable!
04:269 00:001 OCABC: Valid slides - 0-155
04:283 00:001 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=145)
04:286 00:001 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=145)
04:275 00:001 OCABC: Only 156/256 slide values are usable!
04:276 00:001 OCABC: Valid slides - 0-155
04:290 00:001 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=136)
04:293 00:001 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=136)
02:171 00:002 OCABC: Only 67/256 slide values are usable!
02:173 00:001 OCABC: Valid slides - 0-66
02:191 00:001 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=51 )
02:195 00:002 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=51 )
01:909 00:001 OCABC: Only 67/256 slide values are usable!
01:910 00:001 OCABC: Valid slides - 0-66
01:924 00:001 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=52 )
01:927 00:001 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=52 )
02:776 00:002 OCABC: Only 67/256 slide values are usable!
02:779 00:002 OCABC: Valid slides - 0-66
02:800 00:002 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=45 )
02:804 00:002 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=45 )
02:986 00:003 OCABC: Only 67/256 slide values are usable!
02:990 00:003 OCABC: Valid slides - 0-66
03:019 00:003 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=54 )
03:025 00:003 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=54 )
`
Log of boot successes:
`grep slide $(grep -l "EXITBS:START" *.txt)`
`
05:843 00:003 OCABC: Only 155/256 slide values are usable!
05:847 00:003 OCABC: Valid slides - 0-154
05:881 00:003 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=43 )
05:889 00:003 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=43 )
02:194 00:001 OCABC: Only 156/256 slide values are usable!
02:196 00:001 OCABC: Valid slides - 0-155
02:209 00:001 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=73 )
02:212 00:001 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=73 )
05:066 00:004 OCABC: Only 156/256 slide values are usable!
05:071 00:004 OCABC: Valid slides - 0-155
05:115 00:004 AAPL: [EB|#MBA:NV] (-liludbg -nvmefoff -vsmcdbg slide=150)
05:125 00:004 AAPL: [EB|#MBA:OUT] (-liludbg -nvmefoff -vsmcdbg slide=150)
04:378 00:002 OCABC: Only 156/256 slide values are usable!
04:380 00:002 OCABC: Valid slides - 0-155
04:404 00:002 AAPL: [EB|#MBA:NV] (-liludbg -nvmefoff -vsmcdbg slide=96 )
04:409 00:002 AAPL: [EB|#MBA:OUT] (-liludbg -nvmefoff -vsmcdbg slide=96 )
03:038 00:002 OCABC: Only 156/256 slide values are usable!
03:040 00:002 OCABC: Valid slides - 0-155
03:059 00:001 AAPL: [EB|#MBA:NV] (-liludbg -nvmefoff -vsmcdbg slide=97 )
03:063 00:001 AAPL: [EB|#MBA:OUT] (-liludbg -nvmefoff -vsmcdbg slide=97 )
03:339 00:002 OCABC: Only 156/256 slide values are usable!
03:342 00:002 OCABC: Valid slides - 0-155
03:368 00:002 AAPL: [EB|#MBA:NV] (-liludbg -nvmefoff -vsmcdbg slide=68 )
03:374 00:002 AAPL: [EB|#MBA:OUT] (-liludbg -nvmefoff -vsmcdbg slide=68 )
06:414 00:003 OCABC: Only 156/256 slide values are usable!
06:418 00:003 OCABC: Valid slides - 0-155
06:455 00:003 AAPL: [EB|#MBA:NV] (-liludbg -nvmefoff -vsmcdbg slide=26 )
06:463 00:003 AAPL: [EB|#MBA:OUT] (-liludbg -nvmefoff -vsmcdbg slide=26 )
04:820 00:002 OCABC: Only 156/256 slide values are usable!
04:823 00:002 OCABC: Valid slides - 0-155
04:844 00:002 AAPL: [EB|#MBA:NV] (-liludbg -nvmefoff -vsmcdbg slide=37 )
04:848 00:002 AAPL: [EB|#MBA:OUT] (-liludbg -nvmefoff -vsmcdbg slide=37 )
04:102 00:002 OCABC: Only 156/256 slide values are usable!
04:105 00:002 OCABC: Valid slides - 0-155
04:128 00:002 AAPL: [EB|#MBA:NV] (-hbfx-disable-patch-pci -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=115)
04:134 00:002 AAPL: [EB|#MBA:OUT] (-hbfx-disable-patch-pci -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=115)
03:757 00:002 OCABC: Only 156/256 slide values are usable!
03:759 00:002 OCABC: Valid slides - 0-155
03:786 00:002 AAPL: [EB|#MBA:NV] (-hbfx-disable-patch-pci -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=77 )
03:792 00:002 AAPL: [EB|#MBA:OUT] (-hbfx-disable-patch-pci -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=77 )
05:001 00:002 OCABC: Only 156/256 slide values are usable!
05:003 00:002 OCABC: Valid slides - 0-155
05:027 00:002 AAPL: [EB|#MBA:NV] (-hbfx-disable-patch-pci -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=21 )
05:032 00:002 AAPL: [EB|#MBA:OUT] (-hbfx-disable-patch-pci -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=21 )
05:018 00:002 OCABC: Only 156/256 slide values are usable!
05:020 00:002 OCABC: Valid slides - 0-155
05:044 00:002 AAPL: [EB|#MBA:NV] (hbfx-patch-pci=XHC,IMEI,IGPU,RP01 -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=81 )
05:049 00:002 AAPL: [EB|#MBA:OUT] (hbfx-patch-pci=XHC,IMEI,IGPU,RP01 -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=81 )
03:951 00:003 OCABC: Only 156/256 slide values are usable!
03:954 00:003 OCABC: Valid slides - 0-155
03:983 00:003 AAPL: [EB|#MBA:NV] (hbfx-patch-pci=XHC,IMEI,IGPU,RP01 -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=154)
03:989 00:003 AAPL: [EB|#MBA:OUT] (hbfx-patch-pci=XHC,IMEI,IGPU,RP01 -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=154)
04:272 00:001 OCABC: Only 156/256 slide values are usable!
04:274 00:001 OCABC: Valid slides - 0-155
04:287 00:001 AAPL: [EB|#MBA:NV] (hbfx-patch-pci=XHC,IMEI,RP01 -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=2  )
04:290 00:001 AAPL: [EB|#MBA:OUT] (hbfx-patch-pci=XHC,IMEI,RP01 -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=2 )
04:621 00:002 OCABC: Only 156/256 slide values are usable!
04:623 00:001 OCABC: Valid slides - 0-155
04:642 00:001 AAPL: [EB|#MBA:NV] (hbfx-patch-pci=XHC,IMEI,RP01 -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=90 )
04:646 00:001 AAPL: [EB|#MBA:OUT] (hbfx-patch-pci=XHC,IMEI,RP01 -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=90 )
05:250 00:002 OCABC: Only 156/256 slide values are usable!
05:252 00:002 OCABC: Valid slides - 0-155
05:278 00:002 AAPL: [EB|#MBA:NV] (hbfx-patch-pci=XHC,IMEI,RP01 -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=107)
05:283 00:002 AAPL: [EB|#MBA:OUT] (hbfx-patch-pci=XHC,IMEI,RP01 -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=107)
05:681 00:003 OCABC: Only 156/256 slide values are usable!
05:685 00:003 OCABC: Valid slides - 0-155
05:718 00:003 AAPL: [EB|#MBA:NV] (hbfx-patch-pci=RP01 -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=31 )
05:725 00:003 AAPL: [EB|#MBA:OUT] (hbfx-patch-pci=RP01 -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=31 )
04:275 00:001 OCABC: Only 156/256 slide values are usable!
04:277 00:001 OCABC: Valid slides - 0-155
04:290 00:001 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=80 )
04:293 00:001 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=80 )
02:862 00:001 OCABC: Only 156/256 slide values are usable!
02:863 00:001 OCABC: Valid slides - 0-155
02:877 00:001 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=51 )
02:880 00:001 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=51 )
03:159 00:002 OCABC: Only 156/256 slide values are usable!
03:161 00:002 OCABC: Valid slides - 0-155
03:182 00:002 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=99 )
03:187 00:002 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=99 )
04:302 00:001 OCABC: Only 155/256 slide values are usable!
04:304 00:001 OCABC: Valid slides - 0-154
04:317 00:001 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=15 )
04:320 00:001 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=15 )
03:195 00:003 OCABC: Only 67/256 slide values are usable!
03:198 00:003 OCABC: Valid slides - 0-66
03:227 00:003 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=38 )
03:233 00:003 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=38 )
04:166 00:005 OCABC: Only 67/256 slide values are usable!
04:171 00:004 OCABC: Valid slides - 0-66
04:216 00:004 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=21 )
04:226 00:005 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=21 )
09:620 00:001 OCABC: Only 67/256 slide values are usable!
09:621 00:001 OCABC: Valid slides - 0-66
09:634 00:001 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=2  )
09:637 00:001 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=2 )
05:071 00:002 OCABC: Only 67/256 slide values are usable!
05:073 00:002 OCABC: Valid slides - 0-66
05:097 00:002 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=13 )
05:102 00:002 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=13 )
02:492 00:001 OCABC: Only 67/256 slide values are usable!
02:493 00:001 OCABC: Valid slides - 0-66
02:506 00:001 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=12 )
02:509 00:001 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=12 )
01:853 00:001 OCABC: Only 67/256 slide values are usable!
01:855 00:001 OCABC: Valid slides - 0-66
01:868 00:001 AAPL: [EB|#MBA:NV] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=9  )
01:871 00:001 AAPL: [EB|#MBA:OUT] (-hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=9 )
`

**Comment by vit9696** [comment] 2020-06-15 08:51
@zhen-zen I think we understand what the issue is. Modern firmwares allocate memory from 4GB top to bottom, and thus may require the memory that is essentially free during spare slide determination when macOS boots.

From this point of view it does not sound great to resolve the problem with `if there are M <= N slides, use the first slide`. I wonder if the following in the case: `if there are M > N slides, the use of M - 1 slide will still fail to boot`, just there is less probability that `M - 1` slide will be chosen in this case. Also, making the exclusive use of the first slide means that the second slide is unavailable, but is this actually the case? I think not.

Maybe it is a bit more complicated when more memory is available, e.g. since N will be 255 MAX, and there can be free memory even afterwards when more slides are available. But all in all it should not be that different.

What we need here is definitely some user configuration option as we cannot have a unified value for everyone. But its purpose is what I am unsure about. My first idea is to try to just restrict the use of slides above certain value. Like if a slide is > 220, let's not use it. Maybe try that?

**Comment by zhen-zen** [comment] 2020-06-17 04:15
I got your idea about the concern of a static slide when is `M <= N`. Or the modification could be like https://github.com/zhen-zen/OpenCorePkg/commit/7533d5514746eb398f9daf017ec0605ff90c8c8f .
And the hard-coded value here is just used to verify the hypothesis and are not ready to commit. It maybe changed to a variable if there's some kind of support or proof. I suppose it's an offset here based on the log of available slides of 155 and 66. And with more slides available, there's lower chance of boot failure. And the largest offset I have observed so far is 21.
For the issue itself, I haven't got any new insights. This sort of hack do work in past 20 boots successfully. After I reverted it just now, I tried 3 times before the system boots up (55/48/56 chosen out of 67 available slides), although it seems to be a probabilistic thing.

**Comment by zhen-zen** [comment] 2020-06-17 06:22
I added a preliminary customized offset at https://github.com/zhen-zen/OpenCorePkg/commit/2e929809e88a3bfa029846af0cc13f92c2ae9006 .

**Comment by vit9696** [comment] 2020-06-17 10:33
Hmm, I checked your change and am unsure we actually understood each other. `SlideSupport->ValidSlideCount` is literally the amount of slides, the slides themselves may be anything. Rather, I expected that we did not add the slides that exceed some value, i.e. `SlideSupport->ValidSlides[X] >= SlideOffset`.

That's because `SlideSupport->ValidSlides[X]` directly translates to physical kernel base (by multiplication and constant addition). So you may basically have 32 slides, which are `0, 1, 2, 3, 4, … 31` or they can be `0, 1, 2, 3, …, 172, 173, 174`. From this point of view It will not quite work if we just say "do not use last N slides" as it will likely discard valid slides.

Also, that's not good that 0 value behaves as a limit, because the existing users will accidentally have not working setups this way. I would suggest to treat 0 as a special value really.

**Comment by zhen-zen** [comment] 2020-06-17 19:16
I was trapped in my old implementation and didn't get your ideas. So it's the corresponding physically memory address that exceed some boundary and leads to boot failure. I'm going to dump the addresses and find that.

**Comment by zhen-zen** [comment] 2020-06-17 21:22
I'm sorry but I should have noticed this earlier. I just walked through the whole boot log and compared them side by side after trimming the timestamp. The only difference besides the slide value is AAPL log from boot.efi. Maybe it could provide some insights.

>17:486 00:060 OC: Prelinked status - Success
17:502 00:016 AAPL: [EB|`LD:LKFS] } Ok(0)
17:504 00:001 AAPL: [EB|`LD:LKC] } Ok(0)
17:506 00:002 AAPL: [EB|#FWFM] 0xFF9FFF3F
17:508 00:001 AAPL: [EB|#FWFT] 0xFD8FF426
17:510 00:001 AAPL: [EB|#CSR:OUT] 0x00000067
17:512 00:001 AAPL: [EB|`BST:FBS] {
17:514 00:001 AAPL: [EB|`CS:PFDTI]
17:515 00:001 AAPL: [EB|`CS:PFAKD] S: 128
17:517 00:001 AAPL: [EB|`BST:FBS] BA.ADSZ: 128
17:519 00:001 AAPL: [EB|`CS:PFCSKSD] U
17:521 00:001 AAPL: [EB|`CS:PFCSKSD] K
17:522 00:001 AAPL: [EB|`BST:FBS] BA.KSDSZ: 136
17:524 00:001 OCSMC: SmcReadValue Key 4D535463 Size 1
17:526 00:001 OCSMC: SmcReadValue Key 4D534163 Size 2
17:528 00:001 AAPL: [EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49
17:529 00:001 AAPL: [EB|#LOG:DT] 2020-06-17T20:32:00
17:531 00:001 AAPL: [EB|#LOG:EXITBS:START] 2020-06-17T20:32:00

>21:870 00:004 AAPL: [EB|`LD:LKFS] } Err(0x9)
21:872 00:002 AAPL: [EB|`LD:LKC] } Err(0x9)
21:874 00:002 AAPL: [EB|#WL|8] 0x01 0x09  22 0x09
21:877 00:002 AAPL: [EB|#STOP|`B:MN] Err(0x9) @ LD:LKC
21:879 00:002 AAPL: [EB|#WL|9] 0x01 0x0B  22 0x09
21:881 00:002 AAPL: Exiting efiboot...
21:883 00:002 AAPL: [EB|#WL|10] 0x01 0x0B  22 0x09
21:886 00:002 AAPL: [EB|#LOG:EXIT] 2020-06-17T20:31:22
31:869 09:983 OC: Boot failed - Aborted
31:872 00:002 OCB: StartImage failed - Aborted

I also printed both `Slide, SlideSupport->ValidSlides[Slide])` in debug log. And it seems the memory addresses are continuous.

`grep slide $(grep -l "EXITBS:START" *.txt)`

>06:963 00:001 OCABC: Only 68/256 slide values are usable!
06:965 00:001 OCABC: Valid slides - 0-67
06:966 00:001 OCABC: Using slide 17 @ 17
06:983 00:001 AAPL: [EB|#MBA:NV] (-alcdbg -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=17 )
06:986 00:001 AAPL: [EB|#MBA:OUT] (-alcdbg -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=17 )
10:828 00:002 OCABC: Only 68/256 slide values are usable!
10:831 00:002 OCABC: Valid slides - 0-67
10:833 00:002 OCABC: Using slide 42 @ 42
10:863 00:002 AAPL: [EB|#MBA:NV] (-alcdbg -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=42 )
10:868 00:002 AAPL: [EB|#MBA:OUT] (-alcdbg -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=42 )

`grep slide $(grep -l "StartImage failed" *.txt)`

>13:994 00:004 OCABC: Only 68/256 slide values are usable!
13:999 00:004 OCABC: Valid slides - 0-67
14:003 00:004 OCABC: Using slide 66 @ 66
14:046 00:004 AAPL: [EB|#MBA:NV] (-alcdbg -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=66 )
14:056 00:004 AAPL: [EB|#MBA:OUT] (-alcdbg -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=66 )
12:623 00:002 OCABC: Only 68/256 slide values are usable!
12:625 00:002 OCABC: Valid slides - 0-67
12:627 00:002 OCABC: Using slide 62 @ 62
12:649 00:002 AAPL: [EB|#MBA:NV] (-alcdbg -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=62 )
12:653 00:002 AAPL: [EB|#MBA:OUT] (-alcdbg -hbfxdbg -hbfx-dump-nvram -liludbg -nvmefoff -vsmcdbg slide=62 )

**Comment by vit9696** [comment] 2020-06-17 21:58
`Err(0x9)` is `EFI_OUT_OF_RESOURCES`, basically this is the return code used for out of memory, allocation failure. The error you get basically means that it cannot allocate memory for the kernel (LKFS is LoadKernelFileSystem or something like that).

Therefore it seems that you cannot allocate memory after `0x200000 * SLIDE + 0x100000`, where `42 < SLIDE <= 67`. I guess what we need here is to figure out this `SLIDE` value by perhaps using `slide=X` boot argument manually, and then make a configuration option to not mark slides as valid after that value.

**Comment by vit9696** [comment] 2020-06-20 17:34
Closing as resolved.

**Closed by vit9696** 2020-06-20 17:34 UTC
Labels: project:oc
