### ISSUE TITLE
No OTA updates available for some SMBIOS, T2 related, server side, also for all SMBIOS with VMM flag

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#1769] opened 2021-09-02 09:57 UTC
Hello,
I'm testing monterey and I noticed no ota update available from beta 5 to beta 6.
I thought about an error on my end, even if I verified multiple times, then I upgraded from a full installer.
Today I noticed this, opened by @khronokernel and well explained:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/471

I know you don't support betas, but my feeling is that this won't change with next versions.

**Comment by vit9696** [comment] 2021-09-02 13:59
We heard about this issue, but do not have the resources to investigate it in the nearest future. Help is wanted to provide us with the solution.

**Comment by 82ghost82** [comment] 2021-09-02 14:07
I was sure you were informed about this, I opened this just to keep track of the issue.
It's not a stopper, workarounds exist, so this has not to be fixed anytime soon.
Hopefully someone else too will join the development.

**Comment by Lorys89** [comment] 2021-09-02 20:08
have you tried setting securebootmodel to default?

**Comment by 82ghost82** [comment] 2021-09-02 20:38
No, but default now falls back to x86legacy, so there shouldn't be any difference.

**Comment by Lorys89** [comment] 2021-09-02 20:42
> No, but default now falls back to x86legacy instead of that of imacpro, so there shouldn't be any difference.
> Which oc version are you referring?

oc 0.7.2 ota update from beta 5 to beta 6, found by setting securebootmodel to default in my hacks with smbios macmini 8.1 and imac 20.1 and macbook pro 16.2

**Comment by 82ghost82** [comment] 2021-09-03 10:03
Thank you very much, I need sometime to download the install assistant of beta 5 (I have only b4 and b6 full installers); I will clean install b4, upgrade to b5 with the install assistant and try the ota to b6.

In the meantime:
3. Whether macOS 11 boots fine. There should be no change here.
No issues here, SMBIOS: imacpro1,1, securebootmodel=Default

Will be back in a few hours.

**Comment by 82ghost82** [comment] 2021-09-03 12:38
Tested this (2):
Requesting an update with x86legacy on a T2 mac model (e.g. iMacPro1,1) and not getting anything.

SecureBootModel=Default
ApECID=0
SMBIOS: iMacPro1,1

_2. Whether issue (2) is present. There is a chance it got fixed, though I doubt it._
Issue not solved

_3. Whether macOS 11 boots fine. There should be no change here._
As written above no issue with 11.5.2

_4. Whether macOS 12 boots fine. There should be no change here._
Monterey beta 5 installs and boots fine with latest commit

**Comment by vit9696** [comment] 2021-09-03 12:45
Need to test 1. This is important as a first step.

**Comment by 1alessandro1** [comment] 2021-09-03 13:08
I'd like to also address the fact that with configurations such as:

- SMBIOS: iMac19,1 (non-T2)
- macOS version: 11.x
- SecureBootModel: Default (now equal to `x86legacy` since OC 0.7.2, otherwise there's no possibility to install updates on monterey and newer)
- `ApECID` different from `0` (64 bit integer)

There's no way to bless the disk or install from webrecovery (hence boot macOS) as described in the past (April), in [this post on AppleLife](https://applelife.ru/threads/opencore-obsuzhdenie-i-ustanovka.2944066/page-596#post-934540) where the error "Unable to verify macOS" appears when finishing a download from webrecovery (note: these tests were made on Big Sur, not on Catalina, which requires a hack from the terminal - and it's something which should not happen on > 10.15, since the configuration.pdf says only on 10.15 and below) 

This means that since the only way to update from Softwareupdate on macOS 12 and newer is to use x86legacy, for now ApECID cannot be nonzero on any configuration.

But for now, yes, it's better to test `x86legacy` and `ApECID = 0` configs, since those are the most likely to boot

**Comment by 82ghost82** [comment] 2021-09-03 13:23
Tested this (1):
_Updating with x86legacy as a secure boot model on non-T2 mac model (e.g. iMac19,1) and having an update failure._

SecureBootModel=Default
ApECID=0
SMBIOS: iMac19,1

_1. Whether issue (1) is present. I hope to have addressed it._
Sorry, no update available from beta 5

**Comment by vit9696** [comment] 2021-09-03 13:30
Are you sure? This has never been an issue. Maybe needs pressing CMD+R.

**Comment by 82ghost82** [comment] 2021-09-03 13:33
Yes, quite sure, I checked SIP and authenticated root were enabled, I resetted nvram, I checked the system is iMac19,1, I checked my internet connection worked, I rebooted several times after each try, I refreshed the system preference panel, but no update is showing.

**Comment by vit9696** [comment] 2021-09-03 14:40
Does the update show with AppleSecureBoot set to Disabled? (no need to update). Also please provide the DEBUG log from OC. @khronokernel this does not line with your comments, what can you say on that?

**Comment by telepati** [comment] 2021-09-03 14:43
Issue 1 is not correct. I have never got an update failure with 19,1 which I always used this SMBIOS.

**Comment by vit9696** [comment] 2021-09-03 14:48
With Default AppleSecureBootModel?

**Comment by mbarbierato** [comment] 2021-09-03 14:55
@vit9696 i have some friend with z390 with smbios imac19,1 and SecureBootModel set to Default and the update is show

**Comment by vit9696** [comment] 2021-09-03 14:57
Are you sure these people updated to https://github.com/acidanthera/OpenCorePkg/commit/239c1a533d101c9e46c675a48585dbe548998582 however?

**Comment by telepati** [comment] 2021-09-03 15:01
> @vit9696 i have some friend with z390 with smbios imac19,1 and SecureBootModel set to Disabled and the update is show with Default isn't show

This is weird. I am using TUF Z390, 9900K, UHD 630 with 19,1, and SecureBootModel Disable or Default always worked for me. And I didn't early update my OC this month. I am still using Release version of OC 0.7.2.

**Comment by 82ghost82** [comment] 2021-09-03 15:14
Disabled or Default doesn't make any difference for me on iMac19,1 smbios, no update is shown.
This log is for:
SecureBootModel=Default
ApECID=0
SMBIOS: iMac19,1

![1u](https://user-images.githubusercontent.com/18054052/132028415-37d9746a-3035-4cd4-acdd-549fff3c9f54.png)
![2u](https://user-images.githubusercontent.com/18054052/132028421-41173a5a-ecc0-4dd0-9af9-ac4b9471d78a.png)
![3u](https://user-images.githubusercontent.com/18054052/132028425-7d5bdab0-c792-42f2-ae74-2bbb762ae30b.png)

[opencore-2021-09-03-150403.txt](https://github.com/acidanthera/bugtracker/files/7106893/opencore-2021-09-03-150403.txt)

**Comment by telepati** [comment] 2021-09-03 15:17
@82ghost82 could you please share your "diskutil apfs list"

**Comment by 82ghost82** [comment] 2021-09-03 15:25
[disk-list.txt](https://github.com/acidanthera/bugtracker/files/7106974/disk-list.txt)

Volume is sealed, and unfortunately I already tried what you wrote, except downgrading opencore.

**Comment by vit9696** [comment] 2021-09-04 03:30
Retest with build from https://github.com/acidanthera/OpenCorePkg/runs/3511625931

**Comment by 82ghost82** [comment] 2021-09-04 07:04
Thanks
Test on monterey b5, imac 19,1 smbios:

SecureBootModel=Default
No update available :(
[Monterey-b5-iMac191-SecBootMod-Default.txt](https://github.com/acidanthera/bugtracker/files/7109355/Monterey-b5-iMac191-SecBootMod-Default.txt)

SecureBootModel=Disabled
Assert [OpenCore] String.c (630) : String != ((void *) 0)
Halting on critical error

**Comment by TheHackGuy** [comment] 2021-09-04 17:26
I must say that I had beta 6 not showing. So I used SWUSwitcher. I switched to the "Regular Updates" and then back to the "Developer Program Members". And then the update was showing for me. Some friends of me got it working this way too.

But this can probably not really help you...

**Comment by 82ghost82** [comment] 2021-09-04 18:43
Thank you for your contribution.
I don't know about SWUSwitcher, but from your description I think it simply unenroll/enroll in the DeveloperSeed program with the seedutil utility , which I tried (unenroll and enroll again) from the terminal without any luck.

**Comment by TheHackGuy** [comment] 2021-09-04 19:22
I use oc 0.7.2 but I downloaded that before the release. So I have an older commit of 0.7.2
I think my friend has 0.7.3 so can be that that is the problem.

**Comment by 82ghost82** [comment] 2021-09-05 07:47
Tried also 0.7.2 release with iMac19,1 smbios, SecureBootModel Default/Disabled/x86legacy, clear nvram at each change, unenroll/enroll DeveloperSeed, deleted/not deleted csr-active-config entry in config.plist (in both cases sip enabled - **not** apple internal): nothing, no luck, that damn update is not showing...and since I trust you all there should be something new introduced, or can be my error (possible, yes, but trust me I checked and rechecked a lot of times, and since now I always updated with delta ota, so I know what to check, it's not the first time).
One thing I want to add is that I'm not logged in into my apple id (since this was never done before and I always received ota delta updates), I'm running qemu with ovmf code/vars (stable 202108), a virtual hd (raw image file 160 GB), a virtio ethernet bridged to the host, a usb wifi, and my cpus are passed through (2x 2687w v1, with 14 cores + hyperthreading, so not all cores are active).
This hardware/configuration was never an issue, but I don't know what changed, so everything matters.

Can I ask you if it's normal the red dot in the following picture? You can access that window from system preference panel --> software update --> advanced; I cannot select neither Train/profile and show preliminary updates.

![screen](https://user-images.githubusercontent.com/18054052/132119275-ef30319e-25c3-4371-8eac-eace3e0712c0.png)

**Comment by antoniomcr96** [comment] 2021-09-05 09:31
A possible workaround that allowed me to update my laptop with a T2 SMBIOS (MacBookPro15,2) consists of:
- using a T2 SecureBootModel string ("j132" in my case);
- in this way the update should be shown in system preferences;
- download&install the update and reset SecureBootModel to "Default" in config.plist before the reboot.

I know that this isn't a solution, but I'm writing for who's interested in updating and doesn't find a way to do it without changing the SMBIOS or using the full installer.

**Comment by wangzikang-debug** [comment] 2021-09-05 10:01
是你的问题，我的正常收到B6

**Comment by 82ghost82** [comment] 2021-09-05 10:06
> I can't see that window, maybe because I'm enrolled only in public betas program

Yes, that's because it's public beta and not developer seed.

Here also the system softwareupdated log when trigging the software update with cmd+r

[softwareupdated-log.txt](https://github.com/acidanthera/bugtracker/files/7111381/softwareupdated-log.txt)

**Comment by 82ghost82** [comment] 2021-09-05 10:08
> 是你的问题，我的正常收到B6

useless comment, if the team thought it was a user error they had already closed the issue.
And please, write in a universal language.

**Comment by 82ghost82** [comment] 2021-09-06 19:13
Even worse, I reinstalled beta 4, from which in the past I updated via delta ota and the update doesn't show even there..oc release 0.7.2, iMac19,1, SecureBootModel Disabled or Default.

**Comment by khronokernel** [comment] 2021-09-07 05:36
For those with T2 based SMBIOS, can you please test the below PR with OpenCorePkg 0.7.3:

* https://github.com/acidanthera/FeatureUnlock/pull/2

Follow the directions closely, and verify whether Beta 6 in Software Update installs correctly on your machine in the following scenarios:

* SecureBootModel set to `Disabled`
* SecureBootModel set to `x86legacy`

I have confirmed myself that the update shows on an iMacPro1,1 SMBIOS in Beta 5, however installation needs to be verified. 

**Please note**, this is not a permanent fix, instead a temporary one to give Dhinak, myself and other developers a bit more time to research a proper fix. Ideally we'd like to have T2 model IDs work in Monterey so none of this userspace patching is required.

<img width="1673" alt="Screen Shot 2021-09-06 at 11 20 11 PM" src="https://user-images.githubusercontent.com/48863253/132289272-3f2bd28d-9bff-4d33-b7ed-7b5a6b47be1b.png">

**Comment by 82ghost82** [comment] 2021-09-07 07:42
Thank you very much @khronokernel and to all who contributed and are contributing.

Is this specific for beta 5 --> 6?

Yesterday I tested from beta 4, and I just changed the smbios to imacpro1,1, compiled the kext you indicated, injected, booted with nvram reset and tested.

Nothing, in my case the update doesn't show (SecureBootModel=Disabled/x86legacy)..But my system runs on qemu (as described above), so this could be the difference (?)..
Other than the things I listed in the previous replies I don't think I have to check anything else for the update to show:
- SIP/authenticated root
- sealed volume
- unenroll/enroll again in DeveloperSeed
- nvram reset at each change
- check correct smbios information

**Comment by 82ghost82** [comment] 2021-09-07 10:53
It works for me with imacpro1,1 under qemu!

![Screenshot](https://user-images.githubusercontent.com/18054052/132333075-c5805289-abb9-4d36-b850-e726b98ea7a9.png)

**Comment by khronokernel** [comment] 2021-09-07 18:04
Unfortunately after further research we've found that Pallas has multiple T2 model checks. The above PR only patches the initial T2 model check to report OS updates, afterwards there's an additional check for the actual installation of the delta update.

Where this additional T2 check is completely unknown, further research needed.

<img width="800" alt="Screen Shot 2021-09-06 at 11 41 00 PM" src="https://user-images.githubusercontent.com/48863253/132390093-72322755-b6af-4675-b478-2dfdc212e154.png">

**Comment by 82ghost82** [comment] 2021-09-07 18:39
@khronokernel 
This means that for your Mac Pro smbios you see the update but you're not able to install?
That's different from my case, with iMac Pro 1,1 I was able to get the update to show and installation was fine too both with SecureBootModel Default and Disabled (see above, as I'm constantly edit my message by hand handing with tests); last test I'm doing is patching the VMM flag to XXX for iMac19,1.
If you need further testing I'm available to test all you want (if I'm able :)).

**Comment by wy414012** [comment] 2021-09-09 02:39
- Seeing this interesting test, I participated and used the default security model without any problems. 
- Use SMBIOS: iMac Pro1,1  [my EFI](https://github.com/wy414012/OpenCore-GA-b75)
- OpenCore ver:0.7.3
@khronokernel

**Comment by vit9696** [comment] 2021-09-09 06:11
I suggest to calm down for the time being. Given that VMM updates are obviously broken, I believe Apple is making heavy changes in the subsystem. I would speculate that if this is true, we should be able to observe these changes in 2-3 seeds from now. Even if the issue does not get fixed by itself, it will be much easier for us to investigate a more polished code.

As a workaround you should be able to update by downloading a complete installer with the `Default` Apple Secure Boot model and a non-T2 Mac model. This does sound good enough to me for a beta build. We will return to the issue later this autumn.

**Closed** 2021-09-29 16:07 UTC
Labels: help wanted, project:oc
