### ISSUE TITLE
New macOS 14 beta breaks support for all natively made hackintosh wifi

### ISSUE THREAD

**Issue by wqhqq1** [acidanthera/bugtracker#2292] opened 2023-06-06 23:20 UTC
![image](https://github.com/acidanthera/bugtracker/assets/53130008/12c2e01b-d541-4944-ac62-c1313e6da36d)
with io80211family not loaded at all
![image](https://github.com/acidanthera/bugtracker/assets/53130008/5b97d8bf-d5a4-43c3-a146-c5c6b50bfc8f)

**Comment by PMheart** [comment] 2023-06-07 00:56
Starting at 13.0, all kext executables are removed from /S/L/E, hence this error. However, this is not the cause. Please post on forums for support. Thanks!

Closing as off-topic.

**Closed by PMheart** 2023-06-07 00:56 UTC

**Comment by wqhqq1** [comment] 2023-06-07 02:12
that's not the point 
I mean all Broadcom Wi-Fi just stop working in macOS 14 Sonoma

**Comment by PMheart** [comment] 2023-06-07 09:25
This is due to the removal of IO80211FamilyLegacy; it's not our bug.

**Comment by wqhqq1** [comment] 2023-06-08 00:38
So could airportbcrmfixup help solve that？
---- Replied Message ----
| From | ***@***.***> |
| Date | 06/07/2023 17:26 |
| To | acidanthera/bugtracker ***@***.***> |
| Cc | wqhqq1 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [acidanthera/bugtracker] New macOS 14 beta breaks support for all natively made hackintosh wifi (Issue #2292) |

This is due to the removal of IO80211FamilyLegacy; it's not our bug.
