### ISSUE TITLE
Estimated battery time doesn’t work

### ISSUE THREAD

**Issue by usr-sse2** [acidanthera/bugtracker#559] opened 2019-11-08 08:23 UTC
I do confirm too that with VirtualSMC.kext and SMCBatteryManager.kext I do not get estimated battery time on Activity Monitor > Energy tab
It's always stuck Into calculating time left.

When using FakeSMC.kext + ACPIBatteryManager.kext it shows how much time I can expect from current use case like 08:47 hrs etc.

Note: this is stilll present even when using latest release kexts (2 days ago)

_Originally posted by @Sniki in https://github.com/acidanthera/bugtracker/issues/539#issuecomment-548779053_

**Comment by usr-sse2** [comment] 2019-11-08 08:30
I don't confirm.
I use SMCBatteryManager.kext
![Снимок экрана 2019-11-01 в 16 19 46](https://user-images.githubusercontent.com/17758753/68027471-81eb1400-fcc3-11e9-9146-231d2942f162.png)
 _Originally posted by @Andrey1970AppleLife in https://github.com/acidanthera/bugtracker/issues/539#issuecomment-548783855

**Comment by usr-sse2** [comment] 2019-11-08 20:29
> @chiccheung What do you mean by 'the sound of the power cord access'?

When you plug the adapter to charge the laptop it makes the same sound/tone like when you plug the iPhone to charge or a Macbook.


> @vit9696 No, those commits were for milliwatts problem and can only slightly influence on this.

It is still present and sort of bugged, most of the time it keeps saying calculating for me, but sometimes it gets stuck at 20:00 remaining time until i have to charge it again, switching to fakesmc + acpibatterymanager:
- Time calculation correct.
- When i plug the adapter it makes that charging tone

Note: both my laptops do have dual batteries, can't say anything about others, however dual battery support on macOS is buggy.
I use this to combine both batteries:
https://github.com/RehabMan/OS-X-ACPI-Battery-Driver/blob/master/SSDT-BATC.dsl
With this we combine both batteries into one.
We rename notifiers of BAT0 & BAT1 into BATC.
Refer to the source for more information.

It works fine even with VirtualSMC + SMCBatteryManager.
Battery percentage reporting is correct and everything else, the only problem is just cosmetic for me.
- No time remaining (hours:minutes) in ActivityMonitor
- No charging tone when i connect the adapter.

Those are the current issues that i am aware of.

Question:
Is dual battery support present in SMCBATTERYMANAGER ?

_Originally posted by @Sniki in https://github.com/acidanthera/bugtracker/issues/539#issuecomment-549759651_

**Comment by usr-sse2** [comment] 2019-11-09 13:01
@Sniki
Use this
[SMCBatteryManager.kext.zip](https://github.com/acidanthera/bugtracker/files/3827290/SMCBatteryManager.kext.zip) with `-sbatdbg` boot argument. Run
```bash
log show --last boot --predicate 'sender="Lilu" and eventMessage contains "acpib"'
```
and post the log here. You should get output like this:
```
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) return status 1f
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) design capacity of warning: 3975, design capacity of low: 397
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) return status 1f
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) average time to empty: 129
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) run time to empty: 129
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) battery 0 discharging
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) return status 1f
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) average time to empty: 129
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) run time to empty: 129
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) battery 0 discharging
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) return status 1f
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) average time to empty: 116
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) run time to empty: 105
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) battery 0 discharging
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) return status 1f
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) average time to empty: 110
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) run time to empty: 105
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) battery 0 discharging
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) return status 1f
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) average time to empty: 109
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) run time to empty: 107
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) battery 0 discharging
kernel: (Lilu) SMCBatteryManager:   acpib @ (DBG) return status 1f
```

**Comment by usr-sse2** [comment] 2019-11-11 14:33
From log in #539 I see that estimated time is calculated incorrectly: 218820 minutes is 3647 hours.

**Comment by usr-sse2** [comment] 2019-11-11 18:18
@Sniki and @chiccheung, please tell me the value of `B0AC` SMC key when the system is running on battery power and when the battery is charging (but not yet fully charged).

**Comment by chiccheung** [comment] 2019-11-12 02:59
> @Sniki and @chiccheung, please tell me the value of `B0AC` SMC key when the system is running on battery power and when the battery is charging (but not yet fully charged).
> And also these lines from the log in both cases:
> 
> ```
> acpib @ (DBG) average time to empty: 148
> acpib @ (DBG) run time to empty: 170
> acpib @ (DBG) battery 0 discharging
> ```

Here is my log files.
[the log in both cases.zip](https://github.com/acidanthera/bugtracker/files/3834174/the.log.in.both.cases.zip)
Please tell me how to get the value of B0AC SMC key, Sir

**Comment by usr-sse2** [comment] 2019-11-12 07:02
`smc -r B0AC`
You can find `smc` utility in VirtualSMC release archive.

**Comment by usr-sse2** [comment] 2019-11-14 17:31
@Sniki @chiccheung Here is a version with additional debug logging. Please get a log with `msgbuf=1048576 -sbatdbg` boot arguments using 
```bash
log stream --predicate 'sender="Lilu" and eventMessage contains "SMCBatteryManager"'
```
command when the system is on battery power and Activity Monitor can't show estimated time. The log should include at least 4 minutes.
[SMCBatteryManager.kext.zip](https://github.com/acidanthera/bugtracker/files/3847300/SMCBatteryManager.kext.zip)


Do you have only this issue about 60% or also #559?

**Comment by usr-sse2** [comment] 2019-11-20 17:17
@Sniki It seems like I uploaded wrong kext here. Please try with this: 
[SMCBatteryManager.kext.zip](https://github.com/acidanthera/bugtracker/files/3865275/SMCBatteryManager.kext.zip)

**Comment by Sniki** [comment] 2019-11-21 16:16
> @Sniki It seems like I uploaded wrong kext here. Please try with this:
> [SMCBatteryManager.kext.zip](https://github.com/acidanthera/bugtracker/files/3865275/SMCBatteryManager.kext.zip)

Thanks, i will try it tonight hopefully if i find time for it, i've been busy last week and this week.

**Comment by Sniki** [comment] 2019-12-16 21:20
@usr-sse2 i think it has been resolved, it seems to be reporting ok for now.

I did a NVRAM Reset and a clean install afterwards, for now it seems ok so we can close this.

If in case i notice it not reporting or stuck at calculating i will quickly switch to this kext you uploaded, reboot, get logs with the suggestions while it's stuck under calculating or not reporting and upload results and ask for reopen.

Thanks.

**Comment by usr-sse2** [comment] 2019-12-17 09:45
>@usr-sse2 aside of the charging tone when you plug the adapter, i think it has been resolved, it seems to be reporting ok for now. ...

@Sniki On my laptop the charging tone is played, but to wrong output device (always to headphones even when they are unplugged and not visible in System Preferences)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vit9696** [comment] 2020-02-19 09:54
Closing as assumed to be resolved/not reproducible.

**Closed by vit9696** 2020-02-19 09:54 UTC
Labels: project:vsmc

**Comment by Sniki** [comment] 2020-02-19 10:15
> Closing as assumed to be resolved/not reproducible.

@vit9696 

Yes, as seen on one of my previous comments, it was fixed/solved and didn't occur on any of my laptops anymore

Thanks !
