### ISSUE TITLE
Apple-style input broken in RELEASE builds

### ISSUE THREAD

**Issue by naveenkrdy** [acidanthera/bugtracker#754] opened 2020-03-07 20:04 UTC
Hi !
I am using opencore 0.5.6 RELEASE version and keyboard is not working in opencore menu. but if i use opencore 0.5.6 DEBUG version then the keyboard is working.
So my keyboard was working fine in 0.5.5 RELEASE but doesnt seem to work now in 0.5.6 RELEASE but works fine in 0.5.6 DEBUG.

Any idea's what can be the issue ?

-Thanks !

[config.plist.zip](https://github.com/acidanthera/bugtracker/files/4302446/config.plist.zip)
[opencore-2020-03-07-195355.txt.zip](https://github.com/acidanthera/bugtracker/files/4302447/opencore-2020-03-07-195355.txt.zip)

**Comment by Andrey1970AppleLife** [comment] 2020-03-07 20:52
Use forums for support.

**Comment by naveenkrdy** [comment] 2020-03-07 21:18
@Andrey1970AppleLife @vit9696 
umm ! i think its an actual bug but sure let me try forum .

thanks !

**Comment by vit9696** [comment] 2020-03-07 22:04
@naveenkrdy hardly anything changed there, so I am not positive there is a bug. I see that you use an AMD system, perhaps it is the issue. CC @Download-Fritz

**Comment by XLNCs** [comment] 2020-03-08 03:10
> @naveenkrdy hardly anything changed there, so I am not positive there is a bug. I see that you use an AMD system, perhaps it is the issue. CC @Download-Fritz

@vit9696 
Thanks for reply ! : )

I never had any issues with keyboard since the first release of opencore. Its just the 0.5.6 RELEASE where the keyboard issue occurred for me.

i think that the DEBUG version wont print the cause in log , as i can see keyboard working fine in opencore bootpicker while using DEBUG version

what i want is to get a log on the RELEASE version,  but cant seem to get one as the log file is always empty on RELEASE version with debug enabled in config.plist 
Btw my board is a Aptio IV.
If you have any idea’s that i can try/test. Please let me know.

-Thanks !

**Comment by vit9696** [comment] 2020-03-08 09:01
Not nice.
- Might you have broken settings in the bios? Something like enabled fast boot, enabled csm, enabled legacy usb support, etc?
- Also, not working keyboard, what does it mean? Are you unable to use all keys (arrows, space, enter, esc, pgup/pgdown, etc.) or only some of them? Do they work if you press them longer/more frequently? Does the menu show fine otherwise?
- TimerResolution looks a bit too high to me for APTIO? Try something like 6000 or so.

DEBUG builds are basically RELEASE builds with logging enabled. It is logging that somehow makes input work for you, which makes it strange.

**Comment by naveenkrdy** [comment] 2020-03-08 13:36
i check my bios settings again and everything is set correctly as usual.
Fast Boot = Disabled
CSM = Disabled 
Secure Boot = OtherOS
EHCI Hands Off = Enabled
Legacy USB Support is Enabled i think, will disable it and check out the result.

yes ! can't use any key at all. And also tried pressing them for longer but still no dice.

Will try setting TimerResolution to 6000 and let you know : )

-Thanks !

**Comment by vit9696** [comment] 2020-03-08 14:01
Also, are you sure you use all the binaries from releases page and not something custom compiled?

**Comment by naveenkrdy** [comment] 2020-03-08 14:06
> Also, are you sure you use all the binaries from releases page and not something custom compiled?
100% sure ! using the binary provided in the Release page.

Also i just now tried setting the TimerResolution to 6000 and lower but still didnt work.

One more thing i even used my normal config.plist (i.e debug disabled and everything ) with DEBUG version and keyboard still works just doesn't print debug messages anymore. so i am guessing that the issue is not in the config.plist

**Comment by vit9696** [comment] 2020-03-08 14:08
Hmmm, what if you try setting TakeoffDelay to some reasonably high value? It is in microseconds, so start with something like `10000` and increase maybe up to 1-3 seconds?

**Comment by naveenkrdy** [comment] 2020-03-08 14:23
> Hmmm, what if you try setting TakeoffDelay to some reasonably high value? It is in microseconds, so start with something like `10000` and increase maybe up to 1-3 seconds?

tried that just now but didnt work :/

**Comment by vit9696** [comment] 2020-03-08 14:26
- Just to make it clear, if you set timeout, you will autoboot to the default operating system, correct? I.e. there is no freeze or anything.
- Trying all values for `KeySupportMode` (e.g. `AMI`, `V1`, `V2`) have no effect in release version, but work fine in debug version?

To be honest, I am not positive we can help with this without being able to reproduce the problem.

**Comment by naveenkrdy** [comment] 2020-03-09 12:09
> * Just to make it clear, if you set timeout, you will autoboot to the default operating system, correct? I.e. there is no freeze or anything.
Hi !
I made it to autoboot and it booted fine. 
But i observed one thing is ,whenever i press any key while it is doing its countdown in the background before it proceeds to autoboot to default OS , it freezes and doesnt proceed to autoboot.

> * Trying all values for KeySupportMode (e.g. AMI, V1, V2) have no effect in release version, but work fine in debug version?

Tried all these modes in RELEASE version and didnt work. Will test them in DEBUG version and post the results in a moment.

> To be honest, I am not positive we can help with this without being able to reproduce the problem.

Yes ! i understand. For now until a solution is found i will use the DEBUG version till then.
Thanks for taking look into it. I really appreciate it : )

**Comment by naveenkrdy** [comment] 2020-04-07 00:59
@vit9696 Hi ! hope you are doing great .
Today i updated my Opencore from 0.5.6 DEBUG to 0.5.7 RELEASE version and tested the keyboard but sadly it still didnt work.
But after that i added Opencanopy external boot picker to my Opencore 0.5.7 RELEASE version and my keyboard started working.
so could this give you any idea what could be the issue ?

**Comment by vit9696** [comment] 2020-04-07 08:13
OpenCanopy uses legacy keyboard input, that will change soon. So you will have broken input again. Please remind me, what is your hardware.

I think you have issues with KeyForgetThreshold and KeyMergeThreshold.

**Comment by naveenkrdy** [comment] 2020-04-07 21:04
> OpenCanopy uses legacy keyboard input, that will change soon. So you will have broken input again. Please remind me, what is your hardware.
> 
> I think you have issues with KeyForgetThreshold and KeyMergeThreshold.

sure ! 

Here are my specs :
AMD FX 8320
ASUS M5A97 R2.0 (Aptio IV)
Sapphire RX 580

- Thanks

**Comment by vit9696** [comment] 2020-04-26 03:41
I was able to reproduce some similar issue (I had not working QEMU DuetPkg input in RELEASE builds with OpenCanopy), and it was resolved with https://github.com/acidanthera/OpenCorePkg/commit/525b6a6ada693cf3fe0bd4de3fe38ad393bf463a. Perhaps worth checking.

**Comment by naveenkrdy** [comment] 2020-04-26 12:51
@vit9696 hi !
Tried the opencore RELEASE with latest commit and it didnt work.
if i dont press anything then it auto boots to macos but if i press any key then it gets stuck at boot picker. And if i add back the opencanopy my keyboard works fine.

**Comment by vit9696** [comment] 2020-05-26 20:04
Could you please check if the problem persists with all these builds?

[OpenCore-0.5.9-RELEASE-26d3602.zip](https://github.com/acidanthera/bugtracker/files/4684748/OpenCore-0.5.9-RELEASE-26d3602.zip)
[OpenCore-0.5.9-RELEASE-26d3602-both.zip](https://github.com/acidanthera/bugtracker/files/4684745/OpenCore-0.5.9-RELEASE-26d3602-both.zip)
[OpenCore-0.5.9-RELEASE-26d3602-nopri.zip](https://github.com/acidanthera/bugtracker/files/4684746/OpenCore-0.5.9-RELEASE-26d3602-nopri.zip)
[OpenCore-0.5.9-RELEASE-26d3602-conall.zip](https://github.com/acidanthera/bugtracker/files/4684742/OpenCore-0.5.9-RELEASE-26d3602-conall.zip)

**Comment by naveenkrdy** [comment] 2020-05-27 20:27
> Could you please check if the problem persists with all these builds?
> 
> [OpenCore-0.5.9-RELEASE-26d3602.zip](https://github.com/acidanthera/bugtracker/files/4684748/OpenCore-0.5.9-RELEASE-26d3602.zip)
> [OpenCore-0.5.9-RELEASE-26d3602-both.zip](https://github.com/acidanthera/bugtracker/files/4684745/OpenCore-0.5.9-RELEASE-26d3602-both.zip)
> [OpenCore-0.5.9-RELEASE-26d3602-nopri.zip](https://github.com/acidanthera/bugtracker/files/4684746/OpenCore-0.5.9-RELEASE-26d3602-nopri.zip)
> [OpenCore-0.5.9-RELEASE-26d3602-conall.zip](https://github.com/acidanthera/bugtracker/files/4684742/OpenCore-0.5.9-RELEASE-26d3602-conall.zip)

Hi !
Thanks for the test builds.
Tested all of them one by one, but sadly none of them worked. 
No keyboard at boot picker and if i press any key ,the autoboot gets stuck.

Btw apart from this, i also tried to load opencanopy with the all above builds but it doesnt seems to load and is falling back to Builtin mode for some reason.
(i have made sure that i have picker mode set to External and OpenCanopy.efi is added to drivers list.)

Thanks !

**Comment by vit9696** [comment] 2020-05-28 00:10
I am really clueless what it might be, perhaps, we could try debugging it. Will you be able to test 10+ builds and provide logs tomorrow or so? I should be able to find some time closer to the late afternoon or early evening (Moscow time). If this is possible, make sure that your configuration is up to date with master and we will try something.

**Comment by marianopela** [comment] 2020-05-28 07:56
> As for OpenCanopy, we will want to test it too. Make sure that you have the latest OcBinaryData Resources folder copied to your OC folder.

Same thing here too. 0.5.9 broke OpenCanopy. PS2 keyboard is fine though
Lastest OcBinaryData doesn't solve the problem

Count me in for testing
HP ProDesk 600 G1, i5 4590s

**Comment by vit9696** [comment] 2020-05-28 08:02
Right. Please upload your EFI folder with 0.5.9 master and OpenCanopy, and I will try to get back to you today as well.

**Comment by marianopela** [comment] 2020-05-28 08:17
> Right. Please upload your EFI folder with 0.5.9 master and OpenCanopy, and I will try to get back to you today as well.

Don't hurry, and many thanks
[EFI.zip](https://github.com/acidanthera/bugtracker/files/4694178/EFI.zip)

**Comment by vit9696** [comment] 2020-05-28 08:22
Right, and the DEBUG version works fine, correct?

**Comment by marianopela** [comment] 2020-05-28 08:49
> Right, and the DEBUG version works fine, correct?

Should I enable any particular debug option in the config? I just tried Debug version with the same config I sent you in the previous post (so without any debug option) and it behaves exactly the same way

**Comment by Download-Fritz** [comment] 2020-05-28 08:51
@marianopela Then it obviously does not relate to this bug, please do not post off-topic here. If after you have created and inspected a debug log with a DEBUG build you still believe you are facing a bug, create a separate issue with the EFI folder and log attached.

**Comment by naveenkrdy** [comment] 2020-05-29 04:33
> I am really clueless what it might be, perhaps, we could try debugging it. Will you be able to test 10+ builds and provide logs tomorrow or so? I should be able to find some time closer to the late afternoon or early evening (Moscow time). If this is possible, make sure that your configuration is up to date with master and we will try something.
> 
> As for OpenCanopy, we will want to test it too. Make sure that you have the latest OcBinaryData Resources folder copied to your OC folder.

hi !
sure ! just send me the test builds and i will test it ASAP.
i think OcBinaryData is latest but i will test again and report back.
Thanks !

**Comment by vit9696** [comment] 2020-05-29 10:54
Hmmm, so the keyboard is working in RELEASE OpenCanopy, but not working in RELEASE builtin picker? Both of the OpenCore versions are coming from master? This is very strange, because currently OpenCanopy uses the same input method as OpenCore builtin picker does.

**Comment by naveenkrdy** [comment] 2020-05-30 19:01
> Hmmm, so the keyboard is working in RELEASE OpenCanopy, but not working in RELEASE builtin picker? Both of the OpenCore versions are coming from master? This is very strange, because currently, starting with 0.5.9, OpenCanopy uses the same input method as OpenCore builtin picker does.

@vit9696 yes ! 
here are the summary of my observations :

- keyboard doesnt work with opencore RELEASE + Builtin mode.
- keyboard works with opencore DEBUG + Builtin mode.
- keyboard works with opencore RELEASE + Opencanopy
- keyboard doesnt work in UEFIShell with opencore RELEASE + Opencanopy
- keyboard works in UEFIShell with opencore DEBUG + Opencanopy but if i start typing fast, the keyboard gets stuck.

**Comment by vit9696** [comment] 2020-05-30 19:34
Right, ok, I would like to debug it now. Could you please take this case:

```
keyboard works in UEFIShell with opencore DEBUG + Opencanopy but if i start typing fast, the keyboard gets stuck.
``` 

And enable `Target = 67` debugging? When it gets stuck, reboot the computer and upload the opencore log on your ESP folder. Also, do you have iMessage or something for quicker communication?

**Comment by naveenkrdy** [comment] 2020-05-30 23:15
> Right, ok, I would like to debug it now. Could you please take this case:
> 
> ```
> keyboard works in UEFIShell with opencore DEBUG + Opencanopy but if i start typing fast, the keyboard gets stuck.
> ```
> 
> And enable `Target = 67` debugging? When it gets stuck, reboot the computer and upload the opencore log on your ESP folder. Also, do you have iMessage or something for quicker communication?

@vit9696 ok ! 
using opencore DEBUG + Opencanopy and entered UEFI shell then started typing fast and keyboard got stuck.
here is the log :
[opencore-2020-05-30-230429.txt](https://github.com/acidanthera/bugtracker/files/4706774/opencore-2020-05-30-230429.txt)

then manually rebooted and booted staraight into macos:
here is the log for that just in case:
[opencore-2020-05-30-230517.txt](https://github.com/acidanthera/bugtracker/files/4706779/opencore-2020-05-30-230517.txt)

yea i am on imessage. Should i send you my number through email ?

-Thanks !

**Comment by vit9696** [comment] 2020-05-31 02:20
Unfortunately basically nothing in the logs. Right, please e-mail me at vit9696 on protonmail.

**Closed** 2020-05-31 21:56 UTC
Labels: project:oc
