### ISSUE TITLE
SmcBatteryManager.kext always displays "Fully Charged: No" in System Report. Even when the charge is complete.

### ISSUE THREAD

**Issue by armenio** [acidanthera/bugtracker#961] opened 2020-06-07 03:54 UTC
SmcBatteryManager.kext always displays "Fully Charged: No" in System Report.
Even when the charge is complete. 

I have status working OK, it shows 100% in right top bar battery status.
AC working ok.
I think it is a real bug 

It is possible to check charged status this at ACPI (_BST [0] = 0), according to the charger indicator LED and also at the top bar of the system.

Attached is the boot log with the arguments "liludump=300 -liludbgall -vsmcdbg -sbatdbg".
[boot.log](https://github.com/acidanthera/bugtracker/files/4741355/boot.log)
[bootdbg.log](https://github.com/acidanthera/bugtracker/files/4741357/bootdbg.log)

Also information I collected from ACPI with ACPIDebug.kext
It shows the data returned from _BIF, _BIX and _BST in sequence. Data returned from BAT0 to BATC, data returned from BAT1 to BATC and finally the combined data.
[ACPI_DBG.txt](https://github.com/acidanthera/bugtracker/files/4741360/ACPI_DBG.txt)

It is important to say that I have two batteries combined in one ACPI path. It is also attached.
[SSDT-BATC.dsl.txt](https://github.com/acidanthera/bugtracker/files/4741361/SSDT-BATC.dsl.txt)

The issue persists even without using the SSDT battery combination, only deactivating one of them batteries in the bios setup or via ACPI (_STA = 0). Of course, everything else related to battery works.

**Comment by vit9696** [comment] 2020-06-07 05:44
I do not think it is a bug, rather your battery no longer being able to charge at full capacity. I will not close this before @usr-sse2 looks at it.

**Comment by asgmeonerandom** [comment] 2020-06-07 06:23
im surprised this isn't even locked. you didn't even add any info about your efi, acpi patches, kext, etc.

**Comment by Sniki** [comment] 2020-06-07 14:13
> im surprised this isn't even locked. you didn't even add any info about your hardware, efi, acpi patches, kext, etc.
> there is battery patching on google

Dude, what is wrong with all you evil people across all forums recently ?
He asked for help in a human technical friendly way, if Acidanthera members believe it's a bug they keep and look at it, if it is not they close it, if they need more details, they can ask for that. it is as simple as that. none of them asked for your opinion towards that.

You shouldn't be commenting here in first place if it wasn't for:
- Providing more details about the bug
- Confirming it
- Explaining that it is not related to the the kext and it was something else.

This is not a supreme court.

P.S sorry for bloating the issue but i had to add this as it's becoming an increasing phenomenon recently everywhere.

**Comment by asgmeonerandom** [comment] 2020-06-07 18:16
> > im surprised this isn't even locked. you didn't even add any info about your hardware, efi, acpi patches, kext, etc.
> > there is battery patching on google
> 
> Dude, what is wrong with all you evil people across all forums recently ?
> He asked for help in a human technical friendly way, if Acidanthera members believe it's a bug they keep and look at it, if it is not they close it, if they need more details, they can ask for that. it is as simple as that. none of them asked for your opinion towards that.
> 
> You shouldn't be commenting here in first place if it wasn't for:
> 
> * Providing more details about the bug
> * Confirming it
> * Explaining that it is not related to the the kext and it was something else.
> 
> This is not a supreme court.
> 
> P.S sorry for bloating the issue but i had to add this as it's becoming an increasing phenomenon recently everywhere.

congratz! you bloated the issue, i did ask for info that issue was poor as dirt. But, since you can't read I  am writing again.
and you shouldn't comment here for this useless comment. if you have nothing better to say, don't say.
actually, im not evil that is what members on server did to me and here and on forums! ([Hervé](https://www.insanelymac.com/forum/profile/851564-herv%C3%A9/) on insanelymac 
PS: You are not Acidanthera member so you can't judge.

**Comment by armenio** [comment] 2020-06-07 19:05
look, I'm not entirely sure what you mean by "rather your battery no longer being able to charge at full capacity.".
But this bug always occurs, even when using the two batteries combined or when using only one of them.

Also, the ACPI log with data from "ACPI_DBG.txt" is not in a 100% full charged state. they are only reference that data returned by the batteries are being correctly combined.

also, I see that the reading of the information works correctly, however some data like "model, serial number" that I do a "Concatenate" are also not presented correctly.

The perception I have is that some data is read from ACPI before even executing SSDT-BATC.aml

**Comment by armenio** [comment] 2020-06-07 20:45
Important log:

SMCBatteryManager reporting battery status as full
[battery_full.log](https://github.com/acidanthera/bugtracker/files/4742925/battery_full.log)

**Comment by vit9696** [comment] 2020-06-08 04:37
Right, I believe this is a duplicate of another bug: https://github.com/acidanthera/bugtracker/issues/565. We will probably need to get some time to debug this sooner or later. Please reply in that other issue when we get to it.

**Comment by usr-sse2** [comment] 2020-06-08 15:09
Not a duplicate, completely different. On my laptop current capacity = last full charge capacity = 2531 mA•h, but Fully charged is still No.

**Comment by usr-sse2** [comment] 2020-06-08 15:21
Seems like it's due to some non-implemented keys. Maybe `CHLC`?

**Comment by usr-sse2** [comment] 2020-06-08 15:28
Yes, CHLC should be 2 for a fully charged battery

**Comment by usr-sse2** [comment] 2020-06-08 15:40
Implemented it, but the OS doesn't read it (verified by forgetting to release a lock and not getting a hang)

**Comment by vit9696** [comment] 2020-06-08 17:06
Here is some information regarding how Apple Battery Management works. Hope it helps.

Is the menu bar icon showing the same result? If so, then to get how fully charged state is handled it is easiest to check the battery menu (Battery.menu) and its `PowerSource` class, which builds up the following structure:

```C
struct powerSourceTypeStruct
{
  signed __int64 numberOfSources;
  signed __int64 numberOfSourcesPresent;
  signed __int64 totalNumberOfMinutesLeft;
  signed __int64 totalCurrentCapacity;
  signed __int64 totalMaxCapacity;
  char isPresent;
  char anySourceCalculating;
  char anySourceUnknownMinutesLeft;
  char lastSourceIsFinishingCharge;
  char anySourceIsPluggedIn;
  char anySourceCharging;
  char allSourcesCharged;
  char anySourceInPoorCondition;
  char anySourceInCheckBatteryCondition;
  char anySourceInFairCondition;
  char anySourceInUnknownCondition;
  double percentageRemaining;
};
```


```C
        ++v26->numberOfSources;
        if ( (unsigned __int8)objc_msgSend(PowerSource, "isPresent") )
        {
          ++v26->numberOfSourcesPresent;
          v26->isPresent = 1;
          if ( (unsigned __int8)objc_msgSend(PowerSource, "isInternal") )
          {
            v31 = (double)(int)objc_msgSend(PowerSource, maxCapacitySel);
            v2->_internalBatteryCapacity = v31;
          }
          if ( (unsigned __int8)objc_msgSend(PowerSource, "isPluggedIn") )
            v26->anySourceIsPluggedIn = 1;
          if ( (unsigned __int8)objc_msgSend(PowerSource, "isFinishingCharge") )
            v26->lastSourceIsFinishingCharge = 1;
          if ( (unsigned __int8)objc_msgSend(PowerSource, "isCharging") )
            v26->anySourceCharging = 1;
          if ( !(unsigned __int8)objc_msgSend(PowerSource, "isCharged") )
            v26->allSourcesCharged = 0;
          if ( (unsigned __int8)objc_msgSend(PowerSource, "isInPoorCondition") )
          {
            v26->anySourceInPoorCondition = 1;
          }
          else if ( (unsigned __int8)objc_msgSend(PowerSource, "isInCheckBatteryCondition") )
          {
            v26->anySourceInCheckBatteryCondition = 1;
          }
          else if ( (unsigned __int8)objc_msgSend(PowerSource, "isInFairCondition") )
          {
            v26->anySourceInFairCondition = 1;
          }
          else if ( !(unsigned __int8)objc_msgSend(PowerSource, "isInGoodCondition") )
          {
            v26->anySourceInUnknownCondition = 1;
          }
          v124[0] = 1;
          if ( (unsigned __int8)objc_msgSend(PowerSource, "isCalculatingTime") )
            v26->anySourceCalculating = 1;
          else
            v26->totalNumberOfMinutesLeft += (signed __int64)objc_msgSend(PowerSource, "minutesLeft:", v124);
          if ( !v124[0] )
            v26->anySourceUnknownMinutesLeft = 1;
          v26->totalCurrentCapacity += (signed __int64)objc_msgSend(PowerSource, "currentCapacity");
          v26->totalMaxCapacity += (signed __int64)objc_msgSend(PowerSource, maxCapacitySel);
          objc_msgSend(v30, "addObject:", PowerSource);
          if ( !(unsigned __int8)objc_msgSend(PowerSource, v118) )
          {
            v32 = v2;
            v33 = (id)v2->_largestIdealNameWidth;
            v34 = objc_msgSend(PowerSource, "idealNameWidth");
            if ( v33 < v34 )
              v33 = v34;
            v32->_largestIdealNameWidth = (unsigned __int64)v33;
            v120 = v32->_largestBatteryCapacity;
            v35 = (unsigned int)objc_msgSend(PowerSource, maxCapacitySel);
            v32->_largestBatteryCapacity = fmax((double)v35, v120);
          }
        }
```

The methods like `isCharged` are implemented to directly check AppleSmartBattery values like this:

```C
bool __cdecl -[PowerSource isCharged](PowerSource *self, SEL a2)
{
  id v2; // rax
  id v3; // rax
  void *v4; // r15
  unsigned __int8 isCharged; // bl

  v2 = objc_msgSend(self->_psDescriptionDictionary, "objectForKey:", CFSTR("Is Charged"));
  v3 = objc_retainAutoreleasedReturnValue(v2);
  v4 = v3;
  if ( v3 )
  {
    isCharged = (unsigned __int8)objc_msgSend(v3, "boolValue");
  }
  else if ( ((double (*)(id, SEL, ...))objc_msgSend)(self, "percentRemaining") >= 95.0
         && (unsigned __int8)-[PowerSource isPluggedIn](self, "isPluggedIn") )
  {
    isCharged = (unsigned __int8)-[PowerSource isCharging](self, "isCharging") == 0;
  }
  else
  {
    isCharged = 0;
  }
  objc_release(v4);
  return isCharged;
}
```

```C
double __cdecl -[PowerSource percentRemaining](PowerSource *self, SEL a2)
{
  double percent; // xmm1_8
  double curr; // [rsp+0h] [rbp-20h]

  if ( self->_percentRemainingDetermined )
  {
    percent = self->_percentRemaining;
  }
  else
  {
    if ( -[PowerSource maxCapacity](self, "maxCapacity") )
    {
      curr = (double)(int)-[PowerSource currentCapacity](self, "currentCapacity");
      percent = curr / (double)(int)-[PowerSource maxCapacity](self, "maxCapacity") * 100.0;
    }
    else
    {
      percent = 0.0;
    }
    self->_percentRemaining = percent;
    self->_percentRemainingDetermined = 1;
  }
  return fmin(100.0, percent);
}
```

Others are mostly reading `Current Capacity`, `Max Capacity`, `Power Source State` for `AC Power`, `Is Charging` and others directly. Initially `v26->allSourcesCharged` is set to 1, so then the structure is read like this:

```C
  if ( !a3.allSourcesCharged ) {
      /**/
      return;
  }
  v4 = self->_mybundle;
  if ( a3.numberOfSourcesPresent == 1 )
    v5 = objc_msgSend(v4, "localizedStringForKey:value:table:", CFSTR("BAT_CHARGED"), &stru_115A8, 0LL);
  else
    v5 = objc_msgSend(v4, "localizedStringForKey:value:table:", CFSTR("BATS_CHARGED"), &stru_115A8, 0LL);
```

`Is Charged` is set by `kBBatteryStatusCmd` via SMBus. The rest are handled by pmconfigd plugin in powerd and are opensource: https://opensource.apple.com/source/PowerManagement/PowerManagement-956.80.2/pmconfigd/BatteryTimeRemaining.c.auto.html. See `round charge and capacity down to a % scale`. Note the following comment:

```C
            // We will artificially cap the percentage to 99% while charging
            // Batteries may take 10-20 min beyond 100% of charging to
            // relearn their absolute maximum capacity. Leave cap at 99%
            // to indicate we're not done charging. (4482296, 3285870)
```

**Comment by usr-sse2** [comment] 2020-06-08 20:47
Fixed in master. The problem was wrong size of `B0St` key.

**Closed by usr-sse2** 2020-06-08 20:47 UTC
Labels: project:vsmc

**Comment by armenio** [comment] 2020-06-08 21:33
Thanks @usr-sse2  @vit9696 and all acidanthera's team

**Comment by Sher1ocks** [comment] 2020-06-09 11:40
fixed same issue. thanks alot
