### ISSUE TITLE
Black screen on 10.15.1 beta 2 (19B77a) WEG | DP | RX580 | Polaris

### ISSUE THREAD

**Issue by ppogorze** [acidanthera/bugtracker#523] opened 2019-10-17 21:30 UTC
On 10.15.1 beta 2 (19B77a) there is no signal on DP Polaris GPUs.

**Comment by errorexists** [comment] 2019-10-17 21:30
delete whatevergreen

**Comment by InsanelyHack** [comment] 2019-10-17 21:31
Boot without WEG, works fine for HDMI, not sure DP is working.

**Comment by ppogorze** [comment] 2019-10-17 21:39
> Boot without WEG, works fine for HDMI, not sure DP is working.

HDMI works fine, but DP not.

**Comment by humiaozuzu** [comment] 2019-10-18 02:50
@ppogorze Try add `agdpmod=pikera` to bootarg will fix.

**Comment by ppogorze** [comment] 2019-10-18 06:13
> @ppogorze Try add `agdpmod=pikera` to bootarg will fix.
@humiaozuzu this fixed my issue. I will close this.

**Comment by vit9696** [comment] 2019-10-18 07:37
I will reopen this to let more people see it, and in case more issues are discovered with this approach.
- Can anybody tell me about other combinations, for example, does `agpmod=vit9696 work?`
- Could you replace `/System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext` with that of b1 and report the results?
- Could you replace `/System/Library/Extensions/AppleGraphicsControl.kext` with that of b1 and report the results?

**Comment by ppogorze** [comment] 2019-10-18 10:05
Anybody has these kext from beta1? Where i can get these? I can test it.

**Comment by ppogorze** [comment] 2019-10-18 12:42
@vit9696 i'm gonna have today 5700xt, can i help with testing? and how?

**Comment by errorexists** [comment] 2019-10-18 20:04
just put in the 5700 XT an not using WEG or boot args to have DP an HDMI working but if i use WEG then only HDMI works

**Comment by vandroiy2013** [comment] 2019-10-18 22:19
[https://drive.google.com/file/d/1ezr1u0dJBXuMnhTpQyZXmBCqUVn6UsXT/view](url)

**Comment by luk24** [comment] 2019-10-19 03:09
add agdpmod=pikera does work

**Comment by Matgen84** [comment] 2019-10-19 03:17
> just put in the 5700 XT an not using WEG or boot args to have DP an HDMI working but if i use WEG then only HDMI works

Apple is extending its support of AMD GPUs to macOS Catalina, with the second developer beta for macOS 10.15.1 enabling Radeon RX5700 compatibility with the operating system, possibly as a first step ahead of support for the Mac Pro's Radeon Pro Vega II and Duo cards.

**Comment by ppogorze** [comment] 2019-10-19 07:19
@Matgen84 but we are talking about reference cards, right? what about models with similiar pcb and non reference cooling?

**Comment by InsanelyHack** [comment] 2019-10-19 07:49
The general question is, will support in WEG be added for the new cards? simple yes or no would be fine :)

**Comment by vit9696** [comment] 2019-10-19 11:16
It is not like WEG needs (m)any new changes for Navi, even without them the cards should work as fine as apple made the drivers as of current release. The issue with agdpmod, however, affects pretty much all GPUs, including new ones.

For this we need help to determine, what is the culprit of such a regression. By now we have tested that replacing (just) AppleGraphicsControl.kext from b1 in b2 is not enough, and the change is either more complex or indirect. So, what we need is to have you replace all the kexts one by one from b1 in b2, and tell us which minimal combination makes b2 work without agdpmod=pikera boot argument.

The kexts are uploaded here:
https://github.com/acidanthera/bugtracker/issues/523#issuecomment-543978848

Thanks

**Comment by InsanelyHack** [comment] 2019-10-19 11:21
Navi cards seem to work fine without the need for WEG, just using https://github.com/Pavo-IM/AGPMInjector seems to do the trick, the issue with some RX5700 cards is Port layout, which I suspect something has changed somewhere in one of the kext's and agree it's a process of elimination.

**Comment by cattyhouse** [comment] 2019-10-19 11:45
**AGPMInjector** does nothing, and is useless.

**Comment by v10x** [comment] 2019-10-19 15:38
@cattyhouse Would you mind explaining why?

**Comment by Pavo-IM** [comment] 2019-10-20 03:42
Yeah I would love to know also.

**Comment by cattyhouse** [comment] 2019-10-20 09:38
Because if iGPU is properly injected with a working id, dGPU’s framebuffer is set and plutintype is set, there is nothing needed to be done for AGPM, just use system default.

**Comment by InsanelyHack** [comment] 2019-10-20 09:58
So for Xeon and Processors without iGPU? not everyone has the ability to enable the iGPU

**Comment by cattyhouse** [comment] 2019-10-20 14:36
> So for Xeon and Processors without iGPU? not everyone has the ability to enable the iGPU
> the app has been updated recently with the individual AMD,Nvidia Device ID's

It is up to user to choose correct SMBIOS, e.g. iMacPro1,1.
anyway, this is off topic here. i'm not going to discuss this further, or Vit is gonna close this issue :)

**Comment by vit9696** [comment] 2019-10-23 11:19
Fixed in https://github.com/acidanthera/WhateverGreen/commit/f5c4211b160f00b6b495112ae59cc23cec6a541b.

**Closed by vit9696** 2019-10-23 11:19 UTC
Labels: help wanted, project:green

**Comment by errorexists** [comment] 2019-10-23 17:03
> @Matgen84 but we are talking about reference cards, right? what about models with similiar pcb and non reference cooling?
> 
> Maybe we should have another thread for 5700?

i opened a bug for the 5700 with WEG in clover an was closed 
https://github.com/acidanthera/bugtracker/issues/528
